[8.0] Fix search view for welfare.fund.type adding tree view
OCA/l10n-italy pull request #1464
Opened 2019-09-18 16:32 UTC by sergiocorato

2020-12-09 10:45 UTC, vincenzoterzulli requested changes

2020-12-09 10:45 UTC, vincenzoterzulli commented on l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
> +                    else order.client_order_ref
```suggestion
                if company_id.fatturapa_out_sale_internal_ref:
                    order.name
                else:
                    name = order.client_order_ref or order.name
```

2020-12-09 10:46 UTC, vincenzoterzulli commented on l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
> +                    else order.client_order_ref
Meno pythonico, ma più leggibile

2020-12-09 11:43 UTC, sergiocorato commented on l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
> +                    else order.client_order_ref
Mi risulta che la funzione attuale renda:
- order.name se nell'azienda è flaggato `fatturapa_out_sale_internal_ref` oppure se non c'è `client_order_ref`
- order.client_order_ref nei casi residui
Hai fatto un test?

2020-12-09 11:55 UTC, vincenzoterzulli commented on l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
> +                    else order.client_order_ref
Ciao Sergio, 

> Hai fatto un test?
no, ho solo letto il codice.

> Mi risulta che la funzione attuale renda:
> - order.name se nell'azienda è flaggato fatturapa_out_sale_internal_ref oppure se non c'è client_order_ref
> - order.client_order_ref nei casi residui


Non consideri però il seguente caso: se il campo `client_order_ref` è avvalorato viene usato quello al posto del name, anche se è attiva l'opzione `fatturapa_out_sale_internal_ref` nel company. Praticamente lo scopo del modulo viene meno perché ignora la scelta aziendale.

Forse hai fatto i test senza casi di ordini con il campo `client_order_ref` avvalorato?

2020-12-09 16:27 UTC, sergiocorato commented on l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py
> +                    else order.client_order_ref
![scr](https://user-images.githubusercontent.com/7657311/101657100-c78c1b80-3a43-11eb-99dd-955fc8b840ba.png)

2020-12-10 09:04 UTC, vincenzoterzulli approved these changes

2020-12-11 11:37 UTC, sergiocorato commented
/ocabot merge patch

2021-01-06 11:37 UTC, sergiocorato commented
/ocabot merge patch

2021-01-06 12:47 UTC, merged