change license to AGPL-3
OCA/l10n-italy pull request #1643
Opened 2020-02-18 14:03 UTC by scigghia

Cambio di licenza in AGPL-3 per i moduli di l10n-italy, così come discusso qui https://github.com/OCA/l10n-italy/issues/1383

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-09-10 14:43 UTC, eLBati approved these changes
Direi che è troppo complicato modificare solo i moduli con problemi.
Se nessuno è contrario per me si può procedere così

2020-09-10 14:53 UTC, sergiocorato commented
:+1:

2020-09-10 15:01 UTC, eLBati requested changes
Forse non è così complicato: https://github.com/OCA/l10n-italy/pull/1872

2020-09-10 15:01 UTC, eLBati commented
Chiudiamo in favore della https://github.com/OCA/l10n-italy/pull/1872 ?

2020-09-14 07:08 UTC, eLBati commented
Chiudiamo in favore della #1872

2020-09-14 07:08 UTC, closed without merging