add requirements for pip libraries
OCA/l10n-italy pull request #1856
Opened 2020-08-28 14:55 UTC by scigghia

Descrizione del problema o della funzionalità:

aggiunto file requirements.txt con la lista delle librerie python da installare

Comportamento attuale prima di questa PR:

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-08-28 15:22 UTC, eLBati commented
Queste informazioni si trovano già nei `__manifest__` dei moduli (come per [l10n_it_fiscalcode](https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fiscalcode/__manifest__.py)) o [esplcitate nel setup](https://github.com/OCA/l10n-italy/blob/12.0/setup/l10n_it_fatturapa/setup.py).
Se si installano i moduli con pip, le dipendenze vengono automaticamente installate.

Lo scopo è informare l'utente quando installa i moduli senza pip?

2020-08-29 14:44 UTC, scigghia commented
@eLBati torna utile se il repository viene installato con odoo.sh

2020-10-03 09:39 UTC, sergiocorato requested changes
Così facendo si creerebbe un duplicato, da evitare. Per me è da chiudere.

2020-10-06 06:21 UTC, eLBati commented
Sono d'accordo con @sergiocorato 

Sono modifiche legate al metodo di deploy. I metodi di deploy sono infiniti e non possiamo occuparcene a livello di repository, a meno che non sia uno standard OCA globale

2020-10-09 09:50 UTC, scigghia commented
scusate ma anche i repo OCA usano i files requirements.txt
@eLBati @sergiocorato

2020-10-13 07:35 UTC, eLBati commented
@scigghia non ne sono a conoscenza. Ad esempio quale?

2020-10-13 08:42 UTC, scigghia commented
@eLBati https://github.com/OCA/account-financial-tools/blob/12.0/requirements.txt

2020-10-13 09:11 UTC, sergiocorato commented
Dovrebbe essere rimosso per coerenza, la dipendenza è presente nel modulo. Se noti nel repo l10n-italy, le dipendenze di l10n_it_fatturapa sono nel __manifest__.py, poi corretto con la versione nel setup.

2020-10-19 13:50 UTC, scigghia commented
https://github.com/odoo/odoo/blob/12.0/requirements.txt
https://github.com/OCA/OCB/blob/12.0/requirements.txt

2020-10-19 14:01 UTC, sergiocorato commented
Questi servono perchè il core non si installa da libreria pip ma scaricando il git e poi usando pip in locale.

2020-10-22 06:08 UTC, eLBati commented
> Questi servono perchè il core non si installa da libreria pip ma scaricando il git e poi usando pip in locale

O anche lanciando pip direttamente sul repo odoo:
`pip install -e git+https://github.com/odoo/odoo.git@4f7a314eff2725d7bf03188634eff7af9b82cd0d#egg=odoo`

Ad ogni modo:
https://odoo-community.org/groups/contributors-15/contributors-178239

Quindi direi che questa si può chiudere

2020-10-31 21:46 UTC, closed without merging