[10.0 fix] l10n_it_intrastat_statement: ValueError: External ID not found in the system: web.internal_layout
OCA/l10n-italy pull request #1920
Opened 2020-10-14 14:00 UTC by fredzamoabg

Descrizione del problema o della funzionalità:
issue: https://github.com/OCA/l10n-italy/issues/1897

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-10-15 08:55 UTC, eLBati requested changes
Grazie, puoi fare un unico commit?

2020-10-15 08:55 UTC, eLBati commented on l10n_it_intrastat_statement/__manifest__.py
> +    'version': '10.0.1.0.2',
Non è necessario modificare la versione in quanto verrà poi fatto da @OCA-git-bot

2020-10-22 15:03 UTC, tafaRU approved these changes

2020-10-23 10:04 UTC, tafaRU commented
@eLBati puoi aggiornare la tua review? Così poi mergiamo. Grazie.

2020-10-31 07:24 UTC, eLBati approved these changes
Grazie, se avete testato per me OK

2020-11-02 08:17 UTC, tafaRU commented
/ocabot merge patch

2020-11-02 08:57 UTC, merged