[14.0] Migration: l10n_it_fiscalcode
OCA/l10n-italy pull request #1931
Opened 2020-10-30 15:26 UTC by Borruso

Porting del modulo l10n_it_fiscalcode dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-11-06 07:28 UTC, eLBati requested changes
Bisognerebbe fondere gli ultimi 2 commit

2020-11-20 14:48 UTC, tafaRU requested changes
Grazie per la PR!
Coglierei l'occasione per aggiungere https://github.com/Borruso/l10n-italy/pull/2 per la quale ho chiesto review a @primes2h.

2020-11-27 10:58 UTC, tafaRU approved these changes

2020-11-27 10:58 UTC, tafaRU commented
@eLBati puoi aggiornare la tua review?

2020-11-27 11:03 UTC, eLBati approved these changes
LGTM

2020-11-27 11:04 UTC, tafaRU commented
/ocabot merge patch

2020-11-27 14:18 UTC, tafaRU commented
@primes2h hai suggerimenti su come risolvere https://travis-ci.com/github/OCA/l10n-italy/jobs/449612121#L400? É accettabile se lasciamo solo una lingua?

2020-11-27 15:32 UTC, primes2h requested changes
> @primes2h hai suggerimenti su come risolvere https://travis-ci.com/github/OCA/l10n-italy/jobs/449612121#L400? É accettabile se lasciamo solo una lingua?

Possiamo provare a fregarlo così (o in modo similare), vediamo se funziona.

2020-11-27 15:32 UTC, primes2h commented on l10n_it_fiscalcode/readme/INSTALL.rst
> +Install the Python package: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`_.
```suggestion
Installare il modulo Python per il `codice fiscale <https://pypi.python.org/pypi/codicefiscale>`_.

**English**

Install the `fiscal code <https://pypi.python.org/pypi/codicefiscale>`_ Python package.
```

2020-11-27 15:55 UTC, primes2h requested changes
> @primes2h hai suggerimenti su come risolvere https://travis-ci.com/github/OCA/l10n-italy/jobs/449612121#L400? É accettabile se lasciamo solo una lingua?

Eventualmente ci sarebbe quest'altra soluzione:
https://stackoverflow.com/questions/5464627/how-to-have-same-text-in-two-links-with-restructured-text

Direi "as you like it" :smile:

2020-11-27 15:55 UTC, primes2h commented on l10n_it_fiscalcode/readme/INSTALL.rst
> +Install the Python package: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`_.
```suggestion
Installare il modulo Python: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`__.

**English**

Install the Python package: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`__.
```

2020-11-27 15:59 UTC, tafaRU commented on l10n_it_fiscalcode/readme/INSTALL.rst
> +Install the Python package: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`_.
personalmente preferisco questa soluzione, grazie!

2020-11-30 08:25 UTC, tafaRU commented
@primes2h puoi aggiornare la tua review?

2020-11-30 13:47 UTC, primes2h approved these changes
LGTM :+1:

2020-11-30 14:01 UTC, tafaRU commented
/ocabot merge patch

2020-11-30 15:51 UTC, merged