12.0 fix omit move from missing payback new
OCA/l10n-italy pull request #1933
Opened 2020-11-03 08:46 UTC by matteoopenf

Descrizione del problema o della funzionalità:
Nel caso in cui la fattura sia assoggettata a imposta di bollo e non venga applicata la rivalsa in fattura, Odoo scrive in dare e avere l'importo del bollo all'interno della registrazione.

Comportamento desiderato dopo questa PR:
Viene aggiunto un flag sul prodotto "bollo", modificabile dall'utente, da cui viene definito se tali righe debbano essere o meno omesse nel caso non sia presente la rivalsa in fattura.

porting per issue #1694

2020-11-06 08:06 UTC, eLBati commented
@matteoopenf grazie.
Puoi fare un unico commit?

2020-11-06 08:08 UTC, eLBati requested changes

2020-11-06 08:08 UTC, eLBati commented on l10n_it_account_stamp/views/product_view.xml
> -                        <field name="stamp_apply_min_total_base" attrs="{'invisible': ['|',('auto_compute', '=', False), ('is_stamp', '=', False)], 'required': [('auto_compute', '=', True)]}"/>
Come mai `stamp_apply_min_total_base` scompare?

2020-11-06 11:11 UTC, matteoopenf commented on l10n_it_account_stamp/views/product_view.xml
> -                        <field name="stamp_apply_min_total_base" attrs="{'invisible': ['|',('auto_compute', '=', False), ('is_stamp', '=', False)], 'required': [('auto_compute', '=', True)]}"/>
sistemato

2020-11-06 11:11 UTC, matteoopenf commented
> @matteoopenf grazie.
> Puoi fare un unico commit?

vedo per fare un unico commit

2020-11-06 11:18 UTC, matteoopenf commented
> > @matteoopenf grazie.
> > Puoi fare un unico commit?
> 
> vedo per fare un unico commit

il mio è diventato un unico commit devo risolvere comunque o va bene così essendo che non si crea conflitto?

2020-11-12 16:57 UTC, eLBati commented
In questa PR ci deve essere un solo commit

2021-06-09 09:00 UTC, matteoopenf commented
chiudo questa https://github.com/OCA/l10n-italy/pull/1933 in favore di https://github.com/OCA/l10n-italy/pull/2319

2021-06-09 09:00 UTC, closed without merging