[14.0] Migration: l10n_it_fiscal_payment_term
OCA/l10n-italy pull request #1939
Opened 2020-11-06 11:15 UTC by Borruso

Porting del modulo l10n_it_fiscal_payment_term dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-12-04 11:50 UTC, SimoRubi requested changes
Grazie della PR!
Ho fatto review del codice e provato in locale, mi pare tutto ok.
Ho segnato solo un paio di appunti.

2020-12-04 11:50 UTC, SimoRubi commented on l10n_it_fiscal_payment_term/readme/CONTRIBUTORS.rst
> +* Giuseppe Borruso - Dinamiche Aziendali srl <https://github.com/primes2h>
Credo che qui tu voglia mettere il link al tuo profilo, non quello di Sergio

2020-12-04 11:50 UTC, SimoRubi commented on l10n_it_fiscal_payment_term/__manifest__.py
> +    "name": "Italian Localization - Termini fiscali di pagamento",
Puoi mettere invece `ITA - ...` come da https://www.odoo-italia.org/documentazione/12.0/sviluppo/guidelines.html#titolo-del-modulo?

2020-12-04 16:19 UTC, SimoRubi approved these changes
Grazie!

2021-01-22 11:52 UTC, tafaRU approved these changes
Test e code review :+1:

2021-01-22 11:54 UTC, tafaRU commented
/ocabot merge nobump

2021-01-22 13:27 UTC, merged