[14.0] Migration: l10n_it_fiscal_document_type
OCA/l10n-italy pull request #1942
Opened 2020-11-06 14:52 UTC by fredzamoabg

Porting del modulo l10n_it_fiscal_document_type dalla versione 12.0 alla 14.0
il modulo richiede il porting della dipendenza 'l10n_it_account'

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-11-12 17:04 UTC, eLBati commented
Red CI

2020-12-11 18:53 UTC, TheMule71 commented
> Red CI

Ci abbiamo lavorato io e Giuseppe mentre guardavamo tutte le dipendenza di fattura pa... 
https://github.com/Borruso/l10n-italy/tree/14.0-supermerge
ovviamente non è mergiabile in quel modo, farò un commit separato...

2021-03-12 13:16 UTC, SimoRubi commented
@fredzamoabg puoi dare un occhio se si può mergiare https://github.com/fredzamoabg/l10n-italy/pull/2 ?

2021-03-19 10:58 UTC, tafaRU requested changes
@fredzamoabg ci sono troppi commit:

![image](https://user-images.githubusercontent.com/3512779/111769734-d63b6780-88a9-11eb-80fb-53c388c06878.png)

Puoi squashare assieme almeno tutti quelli [MIG]?
@TheMule71 per te un problema se perdi l'autorship sui tuoi commit? Suggerimenti?

2021-03-19 11:58 UTC, As400it reviewed
Ciao, 
nella xml della form fattura dovremo visualizzare "[TD01] fattura"  e non solo il name . 
così era alla 12.0 ritengo che è comodo x l'utente visualizzare il codice .

2021-03-19 13:48 UTC, eLBati commented
https://github.com/OCA/l10n-italy/pull/2075

2021-03-26 11:15 UTC, fredzamoabg commented
> @fredzamoabg ci sono troppi commit:
> 
> ![image](https://user-images.githubusercontent.com/3512779/111769734-d63b6780-88a9-11eb-80fb-53c388c06878.png)
> 
> Puoi squashare assieme almeno tutti quelli [MIG]?
> @TheMule71 per te un problema se perdi l'autorship sui tuoi commit? Suggerimenti?

@tafaRU puoi ricontrollare?

2021-03-29 10:55 UTC, tafaRU commented
Ok @fredzamoabg ora i commit vanno bene :+1: 
Potresti cogliere l'occasione per includere anche https://github.com/OCA/l10n-italy/pull/2075?

2021-04-02 07:54 UTC, tafaRU commented
@fredzamoabg 
> Potresti cogliere l'occasione per includere anche #2075?

si è deciso di farlo successivamente, l'ho tracciato in https://github.com/OCA/l10n-italy/issues/2072

2021-04-02 10:27 UTC, tafaRU requested changes

2021-04-02 10:27 UTC, tafaRU commented on l10n_it_fiscal_document_type/views/fiscal_document_type_view.xml
> +        <field name="binding_view_types">list,form</field>
è necessaria questa modifica?

2021-04-02 10:27 UTC, tafaRU commented on l10n_it_fiscal_document_type/tests/test_doc_type.py
> +        """Check that document type is updated when updating invoice type."""
la doc string non mi sembra più coerente con quanto viene fatto nel test: puoi modificarla?

2021-04-02 12:50 UTC, TheMule71 commented
> @TheMule71 per te un problema se perdi l'autorship sui tuoi commit? Suggerimenti?
Vai squasha pure... :)

2021-04-09 12:11 UTC, tafaRU approved these changes

2021-04-16 08:15 UTC, tafaRU commented
/ocabot merge nobump

2021-04-16 08:40 UTC, merged

2021-04-16 08:46 UTC, eLBati commented
Direi che mancano https://github.com/OCA/l10n-italy/commit/1a46728b1d4b9328ccceda98fe65c149d7c1c0b8 e https://github.com/OCA/l10n-italy/commit/f4270623698bca68871a8abd0e2785ea901c45f6

2021-04-16 09:58 UTC, tafaRU commented
@eLBati: https://github.com/OCA/l10n-italy/issues/2072 e https://github.com/OCA/l10n-italy/issues/2222