[12.0] Aggiunto livello importazione XML fattura elettronica basato sul riepilogo
OCA/l10n-italy pull request #1944
Opened 2020-11-10 14:47 UTC by labaggio

Descrizione del problema o della funzionalità:

https://github.com/OCA/l10n-italy/issues/1941

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-11-12 17:04 UTC, eLBati requested changes
Grazie!

2020-11-12 17:04 UTC, eLBati commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                product = partner.e_invoice_default_product_id
@labaggio visto che le righe da `product = self.get_line_product(line, partner)` e successive sono uguali sia per `e_invoice_detail_level == '1'`  che `e_invoice_detail_level == '2'`, si riescono a scrivere una sola volta fuori dall'`if`?

2020-11-13 10:21 UTC, labaggio commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                product = partner.e_invoice_default_product_id
fatto.

2020-11-13 11:25 UTC, eLBati approved these changes
Grazie

2020-11-14 09:50 UTC, sergiocorato approved these changes

2020-11-14 09:51 UTC, sergiocorato commented
/ocabot merge patch

2020-11-14 11:02 UTC, merged