[FIX] spazi finali in PECDestinatario
OCA/l10n-italy pull request #1966
Opened 2020-11-27 12:44 UTC by TheMule71

Descrizione del problema o della funzionalità:
Se nell'XML sono presenti spazi in coda all'indirizzo nell'element PECDestinatario, la validazione fallisce (non è un dato valido in base all'XMLSchema)
Comportamento attuale prima di questa PR:
Fallisce l'importazione della fattura
Comportamento desiderato dopo questa PR:
La fattura viene importata.

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-11-27 13:25 UTC, jado95 approved these changes

2020-11-27 13:29 UTC, OpenCode approved these changes

2020-11-27 13:39 UTC, TheMule71 commented
Risolve #1932

2020-11-27 13:41 UTC, primes2h commented
@TheMule71 grazie della PR.
Potresti modificare il titolo mettendo il numero della versione per cortesia?

Es.
[12.0][FIX....

Sarebbe anche da creare la issue per tenere traccia delle altre versioni.
https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

2020-11-27 13:42 UTC, primes2h commented
> Sarebbe anche da creare la issue per tenere traccia delle altre versioni.
> https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

Scusa, non avevo visto che era già stata aperta.

2020-11-28 13:40 UTC, eLBati requested changes
@TheMule71 grazie.
Riesci a fare 2 commit, uno per autore?

2020-11-28 20:07 UTC, TheMule71 commented
Così va bene?

2020-11-30 07:31 UTC, eLBati commented
@TheMule71 il contenuto dei commit va bene. L'autore del secondo dovrebbe essere @jado95 
Lo puoi modificare con `git commit --amend --author="Author Name <email@address.com>"`

Infine i test falliscono.

Grazie

2020-11-30 11:26 UTC, jado95 approved these changes

2020-11-30 13:49 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertTrue(len(invoice.invoice_line_ids) == 2)
Tecnicamente in fattura sono due, ma poi aggiunge una riga per il contributo previdenziale e diventano 3. Lo so perché mi sono debuggato l'import. :)

2020-12-04 06:33 UTC, eLBati approved these changes
Grazie

2020-12-04 06:33 UTC, eLBati commented
/ocabot merge patch

2020-12-04 07:11 UTC, merged

2020-12-30 09:42 UTC, vincenzoterzulli commented on l10n_it_fatturapa/bindings/fatturapa.py
> +        pec.text = pec.text.rstrip()
Ciao!
Dato che non esistono mail con spazi, non sarebbe meglio fare uno strip totale per togliere anche spazi iniziali o intermedi?