[10.0] FE 1.6
OCA/l10n-italy pull request #1986
Opened 2020-12-17 13:48 UTC by SimoRubi

Fattura elettronica 1.6 per v10.

Modifiche fatte a partire da https://github.com/LevelPrime/l10n-italy/tree/10.0-l10n_it_fatturapa-1.6-wt che a sua volta include quanto presente in https://github.com/OCA/l10n-italy/pull/1899.

cc @CiroBoxHub @stevech091

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2020-12-17 13:52 UTC, CiroBoxHub commented
:+1:

2020-12-17 13:54 UTC, CiroBoxHub approved these changes

2020-12-17 14:01 UTC, CiroBoxHub approved these changes

2020-12-17 15:28 UTC, scigghia approved these changes
:+1: @CiroBoxHub @SimoRubi @robyf70
bravi ragazzi

2020-12-18 02:00 UTC, marco-marchiori approved these changes
functional review
testata con import di 
- fattura professionista
- fattura agente
- natura 3.4
- tipo TD24
- sistema emittente
- export ft natura 3.4
Tutti i documenti vengono correttamente importati

Nota1 (possibile miglioramento) il TD da documento non viene riportato in altri dati fattura
Nota2 ritenuta enasarco aggiunta manualmente

2020-12-18 09:08 UTC, tafaRU requested changes
Nella versione 12.0 è presente la cartella migrations:
![image](https://user-images.githubusercontent.com/3512779/102595862-98973900-4118-11eb-87e4-898f41308d92.png)
qui invece no.

Verificare quali sono da includere e da quali PR sono state aggiunte.
L'ultimo in ordine di tempo che è stato aggiunto ad esempio si trova qui: https://github.com/OCA/l10n-italy/pull/1914

2020-12-18 14:08 UTC, CiroBoxHub commented
> Nella versione 12.0 all'interno del modulo **l10n_it_fatturapa_in** è presente la cartella **migrations**:
> ![image](https://user-images.githubusercontent.com/3512779/102595862-98973900-4118-11eb-87e4-898f41308d92.png)
> qui invece no.
> 
> Verificare quali sono gli script da includere e in quali PR sono state aggiunte nella 12.0.
> L'ultimo in ordine di tempo è stato aggiunto da: #1914

@tafaRU posso fare il cherry pick di questo? Secondo te è sufficiente?
https://github.com/OCA/l10n-italy/commit/e15f365e05101acc137946b3c860d7891edc7d8a#diff-58177127198cd6b674eb96da8b4009c2ae27c01966d990115dc8d0f756e74fc8

2020-12-18 14:45 UTC, tafaRU commented
> Secondo te è sufficiente?

@CiroBoxHub non ne ho idea, non ho verificato, infatti scrivevo

> Verificare quali sono gli script da includere

So però che ci sta lavorando @SimoRubi attenderei pertanto una sua risposta prima di procedere.

2020-12-18 15:26 UTC, SimoRubi commented
@tafaRU delle 3 migrazioni presenti in v12:

- 12.0.2.0.0: l'ho provata in locale con un nostro cliente e ottengo fatture con un warning tipo:
  ```
  E-bill contains ImportoRitenuta 0.0 but created invoice has got 260.0
  ```
  Questo perché le righe delle ritenute vengono generate, ma l'importo della ritenuta proveniente dalla FE importata non viene migrato nei loro nuovi campi `amount`.
Attualmente non sto trovando dove in v10 tale importo veniva salvato (in v12 pare fosse `ftpa_withholding_amount` che però non esiste più), anzi pare che in fase di import venisse salvato solo il tipo (rif. https://github.com/OCA/l10n-italy/blob/e30b25e05c8750250fb47eafe1352a63880e3bb7/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1165) ma non l'importo.
Un'idea che ho è copiare l'importo di `account.invoice.withholding_tax_amount` dentro una riga delle ritenute create, ma non credo sia del tutto corretto.
- 12.0.1.18.3: popola il campo `invoices_date` che non esiste, quindi direi che non serve
- 12.0.1.15.0: allinea il campo `ftpa_withholding_amount` con la ritenuta nella fattura Odoo, direi che non serve perché verrà già popolato correttamente dalla migrazione in 12.0.2.0.0

In tutto ciò potrei essermi perso qualche concetto fondamentale sulle ritenute perché le conosco un po' così, se qualcuno ha idee su come andrebbe fatta la migrazione scriva pure qui :)
Forse @sergiocorato che facesti la migrazione in v12 hai qualche idea?

2020-12-21 16:44 UTC, stevech091 approved these changes
Test funzionali ok anche con migrazione dati ritenute d'acconto.

2020-12-22 10:17 UTC, tafaRU commented
@marco-marchiori potresti aggiornare la tua review dopo le ultime modifiche apportate?

2020-12-23 09:50 UTC, tafaRU commented
> * Attualmente non sto trovando dove in v10 tale importo veniva salvato (in v12 pare fosse `ftpa_withholding_amount` che però non esiste più), anzi pare che in fase di import venisse salvato solo il tipo (rif. https://github.com/OCA/l10n-italy/blob/e30b25e05c8750250fb47eafe1352a63880e3bb7/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1165
>   ) ma non l'importo.

@SimoRubi confermo la tua analisi: nella 12.0 veniva gestito anche `ImportoRitenuta` come si evince da https://github.com/OCA/l10n-italy/pull/1873/files#diff-a5effb15a448aa412fb06bb6e1b06cc44f9dc2653f43f339942d28d6ec5a9af3L1223-L1224

> Un'idea che ho è copiare l'importo di account.invoice.withholding_tax_amount dentro una riga delle ritenute create, ma non credo sia del tutto corretto.

Ti riferisci a https://github.com/OCA/l10n-italy/pull/1986/commits/2bc9c6874c4a721091ff20f16cf992a1d3cc3555#diff-16188e939fe351db410e56d1a5b9388829d66b327467a2ab47e1a17677521163L13-R13 giusto?
L'alternativa è non migrare affatto il contenuto di quel campo ma dal momento che @stevech091 ha approvato la modifica assumerei che tale soluzione sia accettabile :+1:

2020-12-23 10:02 UTC, tafaRU approved these changes

2020-12-23 10:26 UTC, robyf70 approved these changes
LGTM

2020-12-23 11:02 UTC, tafaRU commented
Attendo la review aggiornate da parte di @marco-marchiori prima di mergiare così come richiesto in https://github.com/OCA/l10n-italy/pull/1986#issuecomment-749465445.

2020-12-23 12:15 UTC, marco-marchiori approved these changes
Testati gli ultimi cambiamenti. Nessun errore
Fattura avvocato: importata, validata
Fattura agente: importata, validata NB non mi riporta le due ritenute, anche se le rileva
Fattura natura N3.4 importata, validata
Fattura con "sistemaemittente" importata, validata
Fattura con TD24 importata, validata

2020-12-23 14:43 UTC, tafaRU commented
> Fattura agente: importata, validata NB non mi riporta le due ritenute, anche se le rileva

@marco-marchiori sulla `12.0` si ha lo stesso comportamento?

2020-12-28 19:17 UTC, marco-marchiori commented
@tafaRU in effetti ho visto ora lo stesso comportamento nella v12 per la stessa fattura, in caso di fattura agente -con due ritenute- non me le riporta ma devo riprenderle a mano

2020-12-28 20:02 UTC, tafaRU commented
Ok @marco-marchiori grazie, puoi aprire una issue in cui descrivi il problema?

2020-12-28 20:03 UTC, tafaRU commented
/ocabot merge major

2020-12-28 21:25 UTC, merged