[14.0][MIG] l10n_it_causali_pagamento
OCA/l10n-italy pull request #1987
Opened 2020-12-17 19:15 UTC by TheMule71

Migrazione dalla 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-01-15 09:57 UTC, andreampiovesana approved these changes
go

2021-01-15 10:35 UTC, primes2h requested changes
Ciao, grazie della PR.
Ho fatto una revisione al volo, ci sono alcune stringhe che andrebbero in inglese perché compaiono nel .pot.

Inoltre vedi anche:
https://github.com/OCA/l10n-italy/pull/1938#discussion_r531601847

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/views/causali_pagamento_view.xml
> +            <tree string="Causale pagamento">
```suggestion
            <tree string="Payment Reason">
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/views/causali_pagamento_view.xml
> +        <field name="name">Causali pagamento</field>
```suggestion
        <field name="name">Payment Reasons</field>
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/models/causale_pagamento.py
> +    _description = "Causale Pagamento"
```suggestion
    _description = "Payment Reason"
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/views/causali_pagamento_view.xml
> +            <form string="Causale pagamento">
```suggestion
            <form string="Payment Reason">
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/views/causali_pagamento_view.xml
> +        name="Causali pagamento"
```suggestion
        name="Payment Reasons"
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/readme/USAGE.rst
> +E' possibile aggiungere nuovi codici o modificare quelli esistenti.
```suggestion
È possibile aggiungere nuovi codici o modificare quelli esistenti.
```

2021-01-15 10:35 UTC, primes2h commented on l10n_it_causali_pagamento/readme/DESCRIPTION.rst
> +Tabelle delle causali di pagamento da usare ad esempio nelle ritenute d'acconto
```suggestion
Tabelle delle causali di pagamento da usare ,ad esempio, nelle ritenute d'acconto.
```

2021-03-19 09:06 UTC, andreampiovesana approved these changes
test ok

2021-03-19 09:12 UTC, tafaRU commented
@primes2h ok per cambiare il nome del modulo in inglese: quale?

2021-03-19 09:51 UTC, andreampiovesana commented
da:
l10n_it_causali_pagamento
a:
l10n_it_payment_reason
?

2021-03-19 11:28 UTC, primes2h commented
> @primes2h ok per cambiare il nome del modulo in inglese: quale?

Se si vuole mantenere il plurale "causali pagamento" direi `l10n_it_payment_reasons` altrimenti `l10n_it_payment_reason`.

2021-03-19 11:32 UTC, tafaRU commented
> altrimenti `l10n_it_payment_reason`.

io voto questa

2021-03-19 11:35 UTC, OpenCode commented
> > @primes2h ok per cambiare il nome del modulo in inglese: quale?
> 
> Se si vuole mantenere il plurale "causali pagamento" direi `l10n_it_payment_reasons` altrimenti `l10n_it_payment_reason`.

I moduli dovrebbero avere i nomi al singolare. Voto per `l10n_it_payment_reason`.

2021-04-09 07:22 UTC, tafaRU requested changes
In aggiunta: forse le modifiche al renaming del modulo avrebbe avuto senso lasciarle su un commit separato, non pensi?

2021-04-09 07:22 UTC, tafaRU commented on l10n_it_payment_reason/tests/test_causali.py
>      def test_renaming_causali(self):
Questo test può essere eliminato perché era contestuale a `migrations/12.0.1.1.0/post-migrate.py` 
(Rif. https://github.com/OCA/l10n-italy/commit/b258f778f758ea1d3ee0358f52b667e6b344e0f7).

2021-04-09 07:22 UTC, tafaRU commented on l10n_it_payment_reason/migrations/14.0.1.0.0/pre-migrate.py
> +        ],
Penso che serva aggiungere anche `rename_xmlids` (vedi https://github.com/OCA/l10n-italy/pull/1938/commits/0d65b1f7fa23facd9ef52749571a4a18a58f4045#r596671706).

2021-04-09 07:22 UTC, tafaRU commented on l10n_it_payment_reason/models/causale_pagamento.py
>      _name = "causale.pagamento"
Il nome del model non lo modifichiamo?

2021-04-09 07:39 UTC, scigghia commented
è più attraente l10n_it_causali_pagamento

2021-04-09 09:17 UTC, TheMule71 commented on l10n_it_payment_reason/models/causale_pagamento.py
>      _name = "causale.pagamento"
Fatto.

2021-04-09 09:17 UTC, TheMule71 commented on l10n_it_payment_reason/migrations/14.0.1.0.0/pre-migrate.py
> +        ],
Aggiunti xmlid delle viste cambiate.

2021-04-09 09:18 UTC, TheMule71 commented on l10n_it_payment_reason/tests/test_causali.py
>      def test_renaming_causali(self):
Eliminato.

2021-04-09 10:03 UTC, tafaRU requested changes

2021-04-09 10:06 UTC, tafaRU commented
Controlla anche Travis che è :red_circle:

2021-04-09 10:13 UTC, TheMule71 commented
> Controlla anche Travis che è

Adesso è verde.

2021-04-09 10:13 UTC, TheMule71 commented on l10n_it_payment_reason/i18n/it.po
> +# Translation of Odoo Server.
Rimossi.

2021-04-09 11:04 UTC, TheMule71 commented on l10n_it_payment_reason/data/causali_pagamento_data.xml
> +<odoo>
Fatto

2021-04-09 11:04 UTC, TheMule71 commented on l10n_it_payment_reason/models/causale_pagamento.py
> +class CausalePagamento(models.Model):
Fatto.

2021-04-09 11:04 UTC, TheMule71 commented on l10n_it_payment_reason/views/causali_pagamento_view.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Fatto

2021-04-09 11:05 UTC, TheMule71 commented on l10n_it_payment_reason/tests/test_causali.py
> +from odoo.exceptions import ValidationError
Fatto. Anche i nomi delle funzioni.

2021-04-09 11:05 UTC, TheMule71 commented on l10n_it_payment_reason/models/causale_pagamento.py
> +from odoo import _, api, fields, models
Fatto.

2021-04-09 12:08 UTC, tafaRU approved these changes
Grazie @TheMule71! Ricordati di notificare quando hai terminato di risolvere i commenti :wink:

2021-04-09 12:21 UTC, tafaRU commented
@TheMule71 ignora questo messaggio:
~~> Ricordati di notificare quando hai terminato di risolvere i commenti wink~~
Ho visto le notifiche su mail solo dopo!

2021-04-09 13:14 UTC, primes2h commented on l10n_it_payment_reason/i18n/l10n_it_causali_pagamento.pot
> +# Translation of Odoo Server.
> Il nome del file è errato, così come il contenuto del file dove ci sono ancora i riferimenti al vecchio nome. Forse è meglio eliminarlo e farlo rigenerare da Weblate. Che ne pensi?

In generale invece di eliminarlo sarebbe meglio rigenerarlo. 
In questo modo è possibile controllare che sia ok prima del merge.

A parte questo per il resto è ok!

2021-04-12 14:13 UTC, primes2h reviewed
Oltre a [questo](https://github.com/OCA/l10n-italy/pull/1987#discussion_r610616255) mi pare sia rimasta in piedi anche [questa](https://github.com/OCA/l10n-italy/pull/1987#pullrequestreview-632111016) osservazione di @tafaRU.

2021-04-14 08:17 UTC, scigghia approved these changes

2021-04-14 08:40 UTC, andreampiovesana approved these changes
go

2021-04-15 12:41 UTC, TheMule71 commented
> Oltre a [questo](https://github.com/OCA/l10n-italy/pull/1987#discussion_r610616255) mi pare sia rimasta in piedi anche [questa](https://github.com/OCA/l10n-italy/pull/1987#pullrequestreview-632111016) osservazione di @tafaRU.

Ho splittato il commit relativo al rename del modulo (a mano, spero di non essermi perso nulla in giro).

Ho anche generato e aggiunto il .pot.

2021-04-15 13:05 UTC, tafaRU commented
Grazie @TheMule71! Unica cosa: puoi eliminare l'incremento della versione nel commit relativo al rename?
La fissiamo poi in fase di merge.

2021-04-15 13:36 UTC, TheMule71 commented
> Grazie @TheMule71! Unica cosa: puoi eliminare l'incremento della versione nel commit relativo al rename?
> La fissiamo poi in fase di merge.

Francamente, l'ho volutamente aggiunto dopo.

Se fai un commit, deve funzionare (a meno di bug _involontari_), senza dipendere da commit successivi. Non puoi crearlo apposta che non funziona singolarmente senza commit successivi...

Se non bumpi la versione, gli script di migrazione non triggerano.  Finché era un unico commit, non c'era problema. La migrazione triggera passando dalla 12.x alla 14.0.0.0.

Facendo tre commit - tre contando black+isort - il secondo porta il modulo l10n_causali_pagamento alla 14.0.0.0, e funziona, visto che non rinomina il modulo. Ma così, "rompi" il terzo.

Il terzo deve rinominare il modulo e deve anche migrare il database. Senza il bump della versione non lo fa. Hai appena creato due commit interdipendenti (non puoi installare il secondo e basta, devi passare direttamente al terzo, _per design_).

Per come la vedo io un bump della versione deve essere parte del terzo commit, sennò non funzionano singolarmente e non ha senso tenere i commit separati a questo punto.

In altre parole, se fai il checkout di 068f398bc e lanci odoo, lui ti installa il modulo alla 14.0.0.0. Se poi fai il checkout di c5c74d715 e aggiorni, il database non viene correttamente modificato dalla rename, a meno di non portare la versione a 14.0.0.1.  Quando i due commit erano fusi il problema non si poneva ovviamente, perché l'eventuale migrazione veniva necessariamente da un db 12 qualcosa.

Inoltre non ha molto senso bumpare la versione in un commit successivo (quello di merge per es.), primo perché dovresti rinominare la directory sotto migrations con la nuova versione, e - anche se funzionasse - avresti deliberatamente creato un commit (c5c74d715) che dipende da un commit successivo per funzionare correttamente.

Non so se mi sono spiegato bene, al limite sentiamoci, anche domani.

2021-04-16 08:16 UTC, primes2h commented
@TheMule71 
Nel secondo commit è rimasto un riferimento al nuovo nome del modulo. Vedi https://github.com/OCA/l10n-italy/pull/1987/commits/068f398bc5d4614b32102c598966bb7b89f2c871

2021-04-16 08:24 UTC, primes2h commented
> @TheMule71
> Nel secondo commit è rimasto un riferimento al nuovo nome del modulo. Vedi [068f398](https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871)

Scusa, intendevo questo https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871#diff-24846e282d48a6b6e77e88f53c57f2be9168a486b5833b410bd0019c026bcba7

2021-04-16 09:31 UTC, TheMule71 commented
> > @TheMule71
> > Nel secondo commit è rimasto un riferimento al nuovo nome del modulo. Vedi [068f398](https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871)
> 
> Scusa, intendevo questo [068f398#diff-24846e282d48a6b6e77e88f53c57f2be9168a486b5833b410bd0019c026bcba7](https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871#diff-24846e282d48a6b6e77e88f53c57f2be9168a486b5833b410bd0019c026bcba7)

Dovrebbe essere a posto.

2021-04-16 10:37 UTC, tafaRU requested changes

2021-04-16 10:37 UTC, tafaRU commented on l10n_it_payment_reason/migrations/14.0.1.0.1/pre-migrate.py
> +    )
Penso che manchi [rename_tables](https://github.com/OCA/openupgradelib/blob/01cc9a1a8933376dcf6516b9a38030c6d0f16072/openupgradelib/openupgrade.py#L694) in base a quanto indicato [qui](https://github.com/OCA/openupgradelib/blob/01cc9a1a8933376dcf6516b9a38030c6d0f16072/openupgradelib/openupgrade.py#L767-L768).
L'ideale è testarlo così come ci siamo detti in standup:
- installare il modulo versione `14.0.1.0.0`
- aggiungere dei dati
- fare checkout sul commit in cui viene fatto il rename, versione `14.0.1.0.1`
- aggiornare il modulo

2021-04-16 12:15 UTC, primes2h commented
> > > @TheMule71
> > > Nel secondo commit è rimasto un riferimento al nuovo nome del modulo. Vedi [068f398](https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871)
> > 
> > 
> > Scusa, intendevo questo [068f398#diff-24846e282d48a6b6e77e88f53c57f2be9168a486b5833b410bd0019c026bcba7](https://github.com/OCA/l10n-italy/commit/068f398bc5d4614b32102c598966bb7b89f2c871#diff-24846e282d48a6b6e77e88f53c57f2be9168a486b5833b410bd0019c026bcba7)
> 
> Dovrebbe essere a posto.

Ok, grazie!

2021-04-16 12:15 UTC, primes2h approved these changes

2021-05-03 10:08 UTC, tafaRU commented
@TheMule71 see https://github.com/TheMule71/l10n-italy/pull/12

2021-05-05 11:17 UTC, TheMule71 commented
Rebase all'ultima 14.0

2021-05-05 12:28 UTC, tafaRU approved these changes

2021-05-05 12:31 UTC, tafaRU commented
/ocabot merge patch

2021-05-05 13:11 UTC, merged