[14.0][MIG] l10n_it_fatturapa_export_zip
OCA/l10n-italy pull request #2080
Opened 2021-01-29 11:10 UTC by Borruso

Porting del modulo l10n_it_fatturapa_export_zip dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-08-28 20:43 UTC, DinamicheAziendali approved these changes
Test funzionali OK .

2021-08-29 17:13 UTC, marcelofrare approved these changes
Functionally OK for me

2021-09-03 10:31 UTC, tafaRU requested changes

2021-09-03 10:31 UTC, tafaRU commented on l10n_it_fatturapa_export_zip/security/ir.model.access.csv
> +access_wizard_fatturapa_export_manager,access_wizard_fatturapa_export_manager,model_wizard_fatturapa_export,account.group_account_invoice,1,1,1,1
Queste 2 ACL mi sembrano ridondanti a fronte di:

_Access rights are additive, a user’s accesses are the union of the accesses they get through all their groups e.g. given a user who is part of group A granting read and create access and a group B granting update access, the user will have all three of create, read, and update._

(rif. https://www.odoo.com/documentation/14.0/developer/reference/addons/security.html#access-rights)

Inoltre il permesso `perm_unlink` può essere impostato a `0` così come fatto da Odoo in https://github.com/odoo/odoo/commit/65530dfd6a0486f44134917f5cc42a2c30b95762#diff-1091362b90b9a9be15980cbc00427e48d5f2f86574ad10e9ebeb87a7c6a9f6b7

Pertanto inserirei solo:
`access_wizard_fatturapa_export_user,access_wizard_fatturapa_export_user,model_wizard_fatturapa_export,account.group_account_invoice,1,1,1,0`

2021-09-03 10:31 UTC, tafaRU commented on l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> +            # "datas_fname": self.name + ".zip",
puoi eliminare questo commento?

2021-09-03 10:31 UTC, tafaRU commented on l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> +                # zf.writestr(att.datas_fname, base64.b64decode(att.datas))
puoi eliminare questo commento?

2021-09-03 10:31 UTC, tafaRU commented on l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> +            # if not att.datas or not att.datas_fname:
puoi eliminare questo commento?

2021-09-03 10:31 UTC, tafaRU commented on l10n_it_fatturapa_export_zip/wizard/export_fatturapa_view.xml
> -    <act_window
QUesto record perché l'hai eliminato?

2021-09-06 07:51 UTC, Borruso commented on l10n_it_fatturapa_export_zip/wizard/export_fatturapa_view.xml
> -    <act_window
probabilmente sarà un errore fatto durante il porting

2021-09-24 14:26 UTC, tafaRU approved these changes

2021-09-24 14:28 UTC, tafaRU commented
/ocabot merge nobump

2021-09-24 18:46 UTC, merged