[12.0][FIX] l10n_it_fatturapa_sale: field permissions
OCA/l10n-italy pull request #2084
Opened 2021-01-31 18:42 UTC by TheMule71

Added fields groups set to "sales_team.group_sale_salesman" instead of
"account.group_account_user".

Descrizione del problema o della funzionalità:
La creazione di una fattura da ordine di vendita con l10n_it_fatturapa_sale installato fallisce da parte di utenti con permessi di Fatturazione ma non Responsabile Fatturazione. Allineato con permessi simili.

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-02-01 07:14 UTC, sergiocorato approved these changes
LGTM

2021-02-02 08:10 UTC, tafaRU commented
@TheMule71 vedo che la PR è ancora **Draft**: è voluto?

2021-02-02 11:07 UTC, TheMule71 commented
> @TheMule71 vedo che la PR è ancora **Draft**: è voluto?

Sì, trattandosi di permessi preferivo riflettere un attimo sulle implicazioni, magari coinvolgendo Simone per vedere se c'è una ragione specifica.

Non riesco ad immaginare una situazione in cui qualcuno là fuori possa ricevere una brutta sorpresa con questo cambiamento, ma il potenziale c'è, almeno un teoria.

Ogni volta che si rilassano delle restrizioni esiste il potenziale che qualcuno veda qualcosa che non è autorizzato a vedere, con tutte le implicazioni anche legali del caso, il che è una situazione irreversibile. Al contrario ovviamente quando si aumentano le restrizioni al massimo qualcuno non riesce più a fare qualcosa che dovrebbe poter fare, ma quello lo si sistema col revert della patch.

La PR è in draft semplicamente perché io non ho fatto quel tipo di analisi. Non ero nemmeno sicuro al 100% che quello che ho messo sia il gruppo migliore, ho preso quello sembrava il più sensato al momento.

L'ho pubblicata perché ho fatto il deply su un cliente che me la chiesta ma mi sembrava una cosa sensata per tutti.

Quello è l'unico motivo per cui è in Draft. Adesso la promuovo.

2021-02-05 09:13 UTC, eLBati requested changes
Allora li metteri entrambi:
`groups="account.group_account_user,sales_team.group_sale_salesman"`

2022-02-28 16:39 UTC, eLBati approved these changes
Grazie

2022-02-28 16:49 UTC, SimoRubi commented
> Ditemi se è il caso di creare anche la issue o se basta così.

La issue potrebbe essere https://github.com/OCA/l10n-italy/issues/2163?

2022-03-04 08:55 UTC, tafaRU commented
/ocabot merge patch

2022-03-04 09:40 UTC, merged