[12.0][FIX] generazione fattura normale senza rc con posizione fiscale con rc
OCA/l10n-italy pull request #2086
Opened 2021-02-01 10:11 UTC by sergiocorato

Descrizione del problema o della funzionalità: una posizione fiscale non può essere usata per emettere fatture normali e con rc contemporaneamente

Comportamento attuale prima di questa PR: bisogna modificare la pos.fiscale al volo ogni volta

Comportamento desiderato dopo questa PR: la pos. fiscale viene usata correttamente

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-02-01 13:15 UTC, eLBati requested changes

2021-02-01 13:15 UTC, eLBati commented on l10n_it_fatturapa_out_rc/models/account_invoice.py
>          res = super(Invoice, self).generate_self_invoice()
`generate_self_invoice` ritorna sempre `None` quindi come fa a funzionare?
Infatti i test falliscono

2021-02-01 15:52 UTC, sergiocorato commented on l10n_it_fatturapa_out_rc/models/account_invoice.py
>          res = super(Invoice, self).generate_self_invoice()
ho corretto, grazie

2021-02-03 11:39 UTC, sergiocorato commented on l10n_it_fatturapa_out_rc/models/account_invoice.py
>          res = super(Invoice, self).generate_self_invoice()
@eLBati aggiorni review? :pray: :)

2021-02-05 09:28 UTC, eLBati approved these changes
Grazie!

2021-02-08 13:33 UTC, sergiocorato commented
/ocabot merge patch

2021-02-08 14:43 UTC, merged