[12.0][FIX]account_invoice_report_ddt_group: set generic session line name when invoice line has no reference in ddt lines.
OCA/l10n-italy pull request #2109
Opened 2021-02-10 10:13 UTC by SimoneVagile

Descrizione del problema o della funzionalità:
See [https://github.com/OCA/l10n-italy/issues/2108](https://github.com/OCA/l10n-italy/issues/2108)
Raggruppamento righe fattura per ddt, con righe senza riferimenti a ddt (es: spese trasporto).

Comportamento attuale prima di questa PR:
La riga di sezione ha il campo Prodotto vuoto.

Comportamento desiderato dopo questa PR:
La riga di sezione viene creata con un nome generico ("No TD").

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-02-13 08:27 UTC, eLBati requested changes

2021-02-13 08:27 UTC, eLBati commented on account_invoice_report_ddt_group/models/account_invoice.py
> +                'name': ddt or 'No TD',
Sarebbe da rendere traducibile

2021-02-15 15:30 UTC, fredzamoabg approved these changes

2021-05-27 09:34 UTC, tafaRU commented
@eLBati puoi aggiornare la tua review?
@SimoneVagile puoi verificare perché Runbot è rosso? Visto che è passato molto tempo fai rebase su `12.0`. Grazie.

2021-05-28 13:22 UTC, eLBati approved these changes
Grazie

2021-05-31 12:51 UTC, tafaRU commented
@SimoneVagile https://github.com/OCA/l10n-italy/pull/2109#issuecomment-849487920

2021-05-31 13:54 UTC, SimoneVagile commented
> @SimoneVagile [#2109 (comment)](https://github.com/OCA/l10n-italy/pull/2109#issuecomment-849487920)

Ok fatto

2021-06-01 07:51 UTC, tafaRU commented
/ocabot merge patch

2021-06-01 09:09 UTC, merged