Close issue #2111
OCA/l10n-italy pull request #2117
Opened 2021-02-17 09:26 UTC by c-amara

Descrizione del problema o della funzionalità:
Fattura Differita TD24 come tipo di documento della fattura elettronica quando si crea fattura da DDT

Comportamento attuale prima di questa PR:
Veniva assegnato come tipo di documento TD01 Fattura

Comportamento desiderato dopo questa PR:
Viene assegnato come tipo di documento TD24 Fattura Differita

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-02-17 21:02 UTC, eLBati requested changes
Grazie delle modifiche.

Travis inoltre si lamenta di
```
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:1:1: F401 'odoo.fields' imported but unused
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:3:1: E302 expected 2 blank lines, found 1
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:5:1: W293 blank line contains whitespace
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:9:1: W293 blank line contains whitespace
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:12:1: W293 blank line contains whitespace
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:15:1: W293 blank line contains whitespace
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:16:27: W292 no newline at end of file
```

Ci sarebbe anche da correggere il test
```
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: FAIL: test_e_invoice_ddt (odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt.TestInvoiceDDT)
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: Traceback (most recent call last):
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: `   File "/home/travis/build/OCA/l10n-italy/setup/l10n_it_fatturapa_out_ddt/odoo/addons/l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py", line 96, in test_e_invoice_ddt
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: `     module_name='l10n_it_fatturapa_out_ddt'
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: `   File "/home/travis/build/OCA/l10n-italy/setup/l10n_it_fatturapa_out/odoo/addons/l10n_it_fatturapa_out/tests/fatturapa_common.py", line 127, in check_content
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: `     self.assertEqual(etree.tostring(test_fatt), etree.tostring(xml))
2021-02-17 11:31:30,232 8132 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt: ` AssertionError: b'<ns[1555 chars]to>TD01</TipoDocumento><Divisa>USD</Divisa><Da[1166 chars]ica>' != b'<ns[1555 chars]to>TD24</TipoDocumento><Divisa>USD</Divisa><Da[1166 chars]ica>'
```

Infine un dubbio funzionale: qualunque fattura generata da DDT è sempre una fattura differita?

2021-02-18 09:46 UTC, c-amara commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        for inv in invs_obj:
Intendi al posto del `for`?
Io credo che il `for` sia necessario in quanto, se non ho capito male, si possono creare anche più fatture da diversi ddt a più partner. Se così `inv_obj` conterrà più fatture da modificare.

2021-02-18 09:52 UTC, c-amara commented
Per quanto riguarda il test non ho ben capito cosa vuole Travis... che mi sembra oltretutto troppo pignolo

2021-02-18 10:06 UTC, c-amara commented
Invece per quanto riguarda l'emissione di fattura differita per tutti i DDT mi sembra sia cosi:

[https://www.tbgstudio.it/documents/FATTURA%20IMMEDIATA%20E%20DIFFERITA.pdf](url)
[https://www.fiscoetasse.com/rassegna-stampa/28208-fatture-differite-2020-guida-ai-codici-td24-e-td25-.html](url)

2021-02-18 19:16 UTC, c-amara commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        invs_obj = self.env['account.invoice'].search([('id', 'in', invoice_sup)])
Ho testato quello che avevo detto per riguardo al ciclo `for` in effetti creando più fatture da più DDT con diversi partner ci sono più fatture da modificare e sempre se non ho capito male `browse` restituisce una sola fattura. 
Ovviamente attendo conferma

2021-02-18 19:19 UTC, eLBati commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        invs_obj = self.env['account.invoice'].search([('id', 'in', invoice_sup)])
browse ritorna un recordset: https://github.com/odoo/odoo/blob/f05a1587e44cd7b27d1764b66e32878ff6b1673e/odoo/models.py#L4726

2021-02-18 19:22 UTC, eLBati commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        for inv in invs_obj:
Il for ci vuole. Intendevo però che conviene eseguirlo solo se `len(doc_type_obj) == 1` perchè la ricerca `self.env['fiscal.document.type'].search([('code', '=', 'TD24')])` potrebbe in teoria ritornare 0 o N risultati

2021-02-18 19:24 UTC, eLBati commented
La cosa più grave di cui si lamenta travis è `b'<ns[1555 chars]to>TD01</TipoDocumento><Divisa>USD</Divisa><Da[1166 chars]ica>' != b'<ns[1555 chars]to>TD24</TipoDocumento><Divisa>USD</Divisa><Da[1166 chars]ica>'` perchè ora giustamente nell'XML c'è `TD24` invece che `TD01`

2021-02-19 11:08 UTC, c-amara commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        for inv in invs_obj:
l' `if` l'ho messo però non capisco perché dovrebbe ritornare 0 o N se document fiscal type ha un solo tipo di documento TD24.

2021-02-19 11:09 UTC, c-amara commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        invs_obj = self.env['account.invoice'].search([('id', 'in', invoice_sup)])
Fatto

2021-02-19 11:10 UTC, c-amara commented
E ma quindi sul test è tutto normale non devo fare nulla? Il risultato diverso è quello che ci si aspetta?

2021-02-19 14:08 UTC, eLBati commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        for inv in invs_obj:
Perchè non ci sono vincoli che impediscano all'utente di eilminare il tipo documento o di crearne altri

2021-02-19 14:09 UTC, eLBati commented
Il test sta fallendo perchè nell'XML del test c'è TD01 invece di TD24 (visto che prima di questa modifica veniva prodotto un XML con TD01)

2021-02-19 15:51 UTC, c-amara commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        for inv in invs_obj:
Ok  non ci avevo pensato... passo e chiudo

2021-02-19 15:52 UTC, c-amara commented
Quindi modifico l'xml di test e risolvo?

2021-02-21 08:29 UTC, eLBati commented
@c-amara LGTM grazie

Riesci a fare un unico commit con `git rebase -i` e `fixup`?

2021-02-22 08:26 UTC, c-amara commented
@eLBati ok provo...

2021-02-22 18:04 UTC, c-amara commented
Ciao @eLBati Spero di non aver fatto pasticci... visto che non riuscivo a fare il fixup dei commit ho eliminato tutto e inviato da capo il commit completo che ora però non vedo nella scheda "Commit" di questa pagina.
Il nuovo Commit però mi appare nel log di git. 
Attendo consigli anche questa volta.

2021-02-24 14:04 UTC, eLBati commented
Nel branch `c-amara:12.0-fix-issue2111` sono finiti dei commit che non dovrebbero esserci.

Mi confermi che tutte le modifiche che vuoi proporre si trovano del commit 6cc4212bebce681ee100e665889666b5f8947443 ?

Se sì, (assumendo che `origin` sia `https://github.com/OCA/l10n-italy.git` e `c-amara` sia `git@github.com:c-amara/l10n-italy.git`, puoi verificare con `git remote -v`) puoi sovrascrivere il branch con
```
git checkout origin/12.0
git branch -d 12.0-fix-issue2111
git checkout -b 12.0-fix-issue2111
git cherry-pick 6cc4212bebce681ee100e665889666b5f8947443
git push -uf c-amara
```

2021-02-24 17:56 UTC, c-amara commented
Si, solo una info: essendoci non miei commit (e non so perché) mi chiedeva di risolvere dei conflitti sul file `fiscal_epos_print/__manifest__.py` che consisteva con il cambiamento della versione. 
Cosa che ho fatto ma solo per togliere quel fastidioso avviso. 
Ripristino il manifest di fiscal_epos_print alla versione precedente prima di eseguire i comandi richiesti? E ovviamente invio un nuovo commit?

2021-02-24 17:59 UTC, c-amara commented
p.s. questo è il risultato di:
```
 git remote -v
origin  git@github.com:c-amara/l10n-italy.git (fetch)
origin  git@github.com:c-amara/l10n-italy.git (push)
```

2021-02-24 19:45 UTC, eLBati commented
Allora ti consiglio di rifare il repo locale con `git clone https://github.com/OCA/l10n-italy.git` e poi aggiungere il tuo remoto con `git remote add c-amara git@github.com:c-amara/l10n-italy.git`.
Aggiorni tutto con `git fetch --all` e infine esegui https://github.com/OCA/l10n-italy/pull/2117#issuecomment-785097834

2021-02-26 16:42 UTC, eLBati approved these changes
Grazie

2021-02-26 18:07 UTC, c-amara commented
Grazie a te per i consigli

2021-02-27 09:31 UTC, GSLabIt commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        if len(doc_type_obj) == 1:
non sarebbe meglio aggiungere `limit=1 `nella search?

2021-03-01 15:20 UTC, eLBati commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
> +        if len(doc_type_obj) == 1:
Anche

2021-03-01 16:51 UTC, GSLabIt commented on l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
>          if len(doc_type_obj) == 1:
```suggestion
        if doc_type_obj:
```

2021-03-02 10:27 UTC, c-amara commented
Buongiorno, visto che ancora non entro in confidenza con GitHub, qualcuno mi fa sapere che succede? E cosa c'è ancora da fare?
Le modifiche richieste sono state fatte.
Attendo notizie.

2021-03-02 10:37 UTC, GSLabIt approved these changes

2021-03-02 10:38 UTC, GSLabIt commented
> Buongiorno, visto che ancora non entro in confidenza con GitHub, qualcuno mi fa sapere che succede? E cosa c'è ancora da fare?
> Le modifiche richieste sono state fatte.
> Attendo notizie.

Travis è rosso: 
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py:11:89: E501 line too long (96 > 88 characters)

2021-03-02 10:50 UTC, c-amara commented
Che Travis fosse rosso lo avevo notato ma non avevo capito quale fosse il problema. Grazie

2021-03-02 18:54 UTC, c-amara commented
Ce ne è ancora codecov/project rosso.. devo fare altro o si ignora?

2021-03-04 11:16 UTC, eLBati commented
@c-amara codecov rosso non è un problema: dice la percentuale totale di copertura dei test automatici è scesa di 0.01%
`codecov/patch` è più importante: dice che le modifiche fatte sono coperte dai test.

Ora però ci sono 6 commit invece di uno.
Per il futuro: per modificare un commit fatto in precendeza usa `git commit --amend`

Ora, assumendo che origin sia `https://github.com/OCA/l10n-italy.git`:
```
git checkout 12.0-fix-issue2111
git fetch origin
git rebase -i origin/12.0
```
metti `fixup` a tutti i commit tranne il primo, salvi e:
```
git push -f
```

2021-03-04 13:16 UTC, eLBati commented
C'era anche questo https://github.com/OCA/l10n-italy/pull/2117#pullrequestreview-600123296 da valutare

2021-03-04 16:25 UTC, c-amara commented
ok @eLBati  incrociamo le dita e grazie come sempre.

2021-03-08 07:14 UTC, eLBati commented
/ocabot merge minor

2021-03-08 08:32 UTC, merged