[14.0] Migration: l10n_it_ricevute_bancarie
OCA/l10n-italy pull request #2138
Opened 2021-02-26 13:12 UTC by Borruso

Porting del modulo l10n_it_ricevute_bancarie dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-05-05 15:57 UTC, TheMule71 commented on l10n_it_ricevute_bancarie/models/riba_config.py
> +        default=lambda self: self.env["res.company"]._company_default_get(
metodo deprecato
https://github.com/odoo/odoo/blob/8f6e2fa1096f57ace6c84ae6083ab77ee37a69a1/odoo/addons/base/models/res_company.py#L186

2021-05-05 15:58 UTC, TheMule71 commented on l10n_it_ricevute_bancarie/models/riba.py
> +        default=lambda self: self.env["res.company"]._company_default_get(
metodo deprecato
https://github.com/odoo/odoo/blob/8f6e2fa1096f57ace6c84ae6083ab77ee37a69a1/odoo/addons/base/models/res_company.py#L186

2021-05-07 08:16 UTC, tafaRU commented
@primes2h esiste un nome in inglese per tradurre le "nostre" ricevute bancarie?

2021-05-07 08:18 UTC, dcorio commented
Ho visto che è stato tradotto con C/O nel modulo, che penso stia per Cash Order.
Stando a questo thread, Cash Order è l'equivalente del vaglia però:
https://forum.wordreference.com/threads/ri-ba-ricevuta-bancaria.690273/

2021-05-07 08:21 UTC, scigghia commented
> @primes2h esiste un nome in inglese per tradurre le "nostre" ricevute bancarie?

Scusate ma è necessario tradurre in inglese anche i moduli puramente "italiani" ? 
Non vuole essere una critica, ma tra le altre cose io dedicherei le energie al completamento del porting e poi valuterei anche questo aspetto "estetico"

2021-05-07 08:30 UTC, tafaRU commented
> Scusate ma è necessario tradurre in inglese anche i moduli puramente "italiani" ?

É un dubbio che ci siamo posti nella standup, per questo scrivevo "nostre"!

2021-05-07 08:31 UTC, primes2h commented
> Ho visto che è stato tradotto con C/O nel modulo, che penso stia per Cash Order.

Si, qui era stata fatta la revisione completa ed erano stati anche corretti alcuni altri termini.
https://github.com/tafaRU/l10n-italy/pull/8

> Stando a questo thread, Cash Order è l'equivalente del vaglia però:
> https://forum.wordreference.com/threads/ri-ba-ricevuta-bancaria.690273/

Lì dicono che il "money order" corrisponde al vaglia, non il "cash order".

La traduzione più diffusa è proprio "cash order":
https://it.bab.la/dizionario/italiano-inglese/ricevuta-bancaria
https://dizionari.repubblica.it/Italiano-Inglese/R/ricevuta.html

2021-05-07 08:32 UTC, marco-marchiori commented
> @primes2h esiste un nome in inglese per tradurre le "nostre" ricevute bancarie?

Tempo (molto) fa, quando le studiai rilevammo che avevano peculiarità che non c'erano in altri sistemi, mi pare ci fossero cose analoghe, ma non equivalenti, solo in Spagna o Francia.
La traduzione con C/O mi sembra fuorviante e fa perdere un sacco di tempo.
Se c'è qualcuno che ci può dare aggiornamenti (non superficiali) sul punto meglio.
Se no terrei ricevute bancarie.

2021-05-07 08:33 UTC, scigghia commented
Allora secondo me la scelta più saggia è quella di lasciare il modulo com'è a livello di traduzione e dedicare energie alla migrazione ;)

2021-05-07 08:40 UTC, primes2h commented
> > @primes2h esiste un nome in inglese per tradurre le "nostre" ricevute bancarie?
> 
> Scusate ma è necessario tradurre in inglese anche i moduli puramente "italiani" ?

Tecnicamente una ricevuta bancaria sarebbe un cash order elettronico.
Se il modulo fosse in un repository OCA generico, concordo con te che si potrebbe porre il problema deila specificità di alcuni aspetti della nostra ricevuta bancaria.
Considera però che il modulo si trova in l10n-italy, quindi va da se che con l10n_it_cash_order ci si riferisce a un cash order con alcune specificità italiane.

2021-05-07 08:45 UTC, scigghia commented
@primes2h cerco di essere diretto, attualmente data la situazione attuale dello stato della migrazione alla 14.0, ritengo che dedicare energie a questo aspetto (puramente estetico, a mio parere) sia uno spreco.

Poi a livello generale io continuo a mantenere le mie riserve sulla utilità di tradurre i moduli italiani in inglese, ma questo è un altro discorso.

Quello che interessa ora è lo stato della migrazione da un punto di vista funzionale e funzionante

2021-05-07 08:52 UTC, marco-marchiori commented
> > > @primes2h esiste un nome in inglese per tradurre le "nostre" ricevute bancarie?
> > 
> > 
> > Scusate ma è necessario tradurre in inglese anche i moduli puramente "italiani" ?
> 
> Tecnicamente una ricevuta bancaria sarebbe un cash order elettronico.
> Se il modulo fosse in un repository OCA generico, concordo con te che si potrebbe porre il problema deila specificità di alcuni aspetti della nostra ricevuta bancaria.
> Considera però che il modulo si trova in l10n-italy, quindi va da se che con l10n_it_cash_order ci si riferisce a un cash order con alcune specificità italiane.

"Tecnicamente" in base a quale definizione di "Cash Order"?
La ricevuta bancaria è documentale.
Qualcuno ha approfondito come sono stati tradotti in inglese gli altri corrispondenti?
Se volete procedere con l'aggiornamento e discutere la traduzione in separata sede mettete la separata sede.
Ma a mio parere questa traduzione è sbagliata e fa perdere tempo a tutti.

2021-05-07 09:07 UTC, dcorio commented
Avere il nome del modulo in inglese è abbastanza utile siccome ci sono società estere con filiali italiane per le quali devono gestire la localizzazione.
Che riba si dica o meno cash order penso faccia poca differenze siccome è probabile che non esiste una corrispondenza precisa in altri paesi.

Per me l10n_it_cash_order proposto da @primes2h va bene

2021-05-07 09:09 UTC, marco-marchiori commented
> Avere il nome del modulo in inglese è abbastanza utile siccome ci sono società estere con filiali italiane per le quali devono gestire la localizzazione.
> Che riba si dica o meno cash order penso faccia poca differenze siccome è probabile che non esiste una corrispondenza precisa in altri paesi.
> 
> Per me l10n_it_cash_order proposto da @primes2h va bene

Quindi un nome sbagliato in inglese aiuta chi parla inglese a capire di cosa si tratta? :-)

2021-05-07 09:18 UTC, primes2h commented
> @primes2h cerco di essere diretto, attualmente data la situazione attuale dello stato della migrazione alla 14.0, ritengo che dedicare energie a questo aspetto (puramente estetico, a mio parere) sia uno spreco.
> 
> Poi a livello generale io continuo a mantenere le mie riserve sulla utilità di tradurre i moduli italiani in inglese, ma questo è un altro discorso.
> 
> Quello che interessa ora è lo stato della migrazione da un punto di vista funzionale e funzionante

Attenzione che io ho solo risposto a domanda specifica. Fate quello che ritenete opportuno, ci mancherebbe. :-)

P.s: non concordo sul fatto che è una questione puramente estetica visto che non è un software solo "italiano", ma nasce internazionale. E la cosa, in questi tipi di software, viene sempre gestita.
Giusto per portare l'esempio di SAP, loro utilizzano addirittura un altro termine:
https://help.sap.com/saphelp_46c/helpdata/en/01/a9cb2f455711d182b40000e829fbfe/frameset.htm

Ma, ribadisco, fate pure quello che volete. :-)

Se decidete di usare RiBa anche nelle stringhe inglesi ricordatevi però di uniformarle tutte, attualmente c'è un mix di inglese/italiano dovuto a PR successive a quella iniziale della 12.0.

2021-05-07 09:20 UTC, marco-marchiori commented
> > @primes2h cerco di essere diretto, attualmente data la situazione attuale dello stato della migrazione alla 14.0, ritengo che dedicare energie a questo aspetto (puramente estetico, a mio parere) sia uno spreco.
> > Poi a livello generale io continuo a mantenere le mie riserve sulla utilità di tradurre i moduli italiani in inglese, ma questo è un altro discorso.
> > Quello che interessa ora è lo stato della migrazione da un punto di vista funzionale e funzionante
> 
> Attenzione che io ho solo risposto a domanda specifica. Fate quello che ritenete opportuno, ci mancherebbe. :-)
> 
> P.s: non concordo sul fatto che è una questione puramente estetica visto che non è un software solo "italiano", ma nasce internazionale. E la cosa, in questi tipi di software, viene sempre gestita.
> Giusto per portare l'esempio di SAP, loro utilizzano addirittura un altro termine:
> https://help.sap.com/saphelp_46c/helpdata/en/01/a9cb2f455711d182b40000e829fbfe/frameset.htm
> 
> Ma, ribadisco, fate pure quello che volete. :-)
> 
> Se decidete di usare RiBa anche nelle stringhe inglesi ricordatevi però di uniformarle tutte, attualmente c'è un mix di inglese/italiano dovuto a PR successive a quella iniziale della 12.0.

Per una volta si potrebbe anche copiare da SAP, no?

2021-05-07 09:22 UTC, TheMule71 commented
Anche per me va bene l10n_it_cash_order.

> Quindi un nome sbagliato in inglese aiuta chi parla inglese a capire di cosa si tratta? :-)

Quello che interessa è aiutare i tecnici (informatici) che devono manutenere installazioni e eventualmente guardare il codice. Molti di loro probabilmente il tecnicismo di cos'è una Ri.Ba. rispetto ad un "cash order" non lo sanno/non li rigurda. Il nome tecnico del modulo serve per i tecnici (informatici).

Al livello di documentazione (visibile agli utenti) sono invece d'accordo. Se dobbiamo usare una terminologia deve essere la più corretta possibile.

2021-05-07 09:22 UTC, primes2h commented
> > Avere il nome del modulo in inglese è abbastanza utile siccome ci sono società estere con filiali italiane per le quali devono gestire la localizzazione.
> > Che riba si dica o meno cash order penso faccia poca differenze siccome è probabile che non esiste una corrispondenza precisa in altri paesi.
> > Per me l10n_it_cash_order proposto da @primes2h va bene
> 
> Quindi un nome sbagliato in inglese aiuta chi parla inglese a capire di cosa si tratta? :-)

Non troverai mai il termine perfetto. Cash order ha un significato un po' più generico di quello che è la ricevuta bancaria, ma per uno straniero il fatto che si trovi nel repository italiano fa capire che è un cash order (o come lo vuoi chiamare) con alcune specificità italiane. Se fosse un cash order generico si troverebbe in un altro repo OCA.

2021-05-07 09:30 UTC, TheMule71 commented
Se "bank bill" fosse più generico, e coprisse le Ri.Ba. andrebbe bene ugualmente. L'importante è usare un nome inglese che gli anglofoni capiscano, ed evitare l'italiano.

_Caso particolare è "FatturaPA" che di fatto è nome proprio, anche sul sito dell'AdE non viene tradotto._

2021-05-07 09:30 UTC, primes2h commented
> > > @primes2h cerco di essere diretto, attualmente data la situazione attuale dello stato della migrazione alla 14.0, ritengo che dedicare energie a questo aspetto (puramente estetico, a mio parere) sia uno spreco.
> > > Poi a livello generale io continuo a mantenere le mie riserve sulla utilità di tradurre i moduli italiani in inglese, ma questo è un altro discorso.
> > > Quello che interessa ora è lo stato della migrazione da un punto di vista funzionale e funzionante
> > 
> > 
> > Attenzione che io ho solo risposto a domanda specifica. Fate quello che ritenete opportuno, ci mancherebbe. :-)
> > P.s: non concordo sul fatto che è una questione puramente estetica visto che non è un software solo "italiano", ma nasce internazionale. E la cosa, in questi tipi di software, viene sempre gestita.
> > Giusto per portare l'esempio di SAP, loro utilizzano addirittura un altro termine:
> > https://help.sap.com/saphelp_46c/helpdata/en/01/a9cb2f455711d182b40000e829fbfe/frameset.htm
> > Ma, ribadisco, fate pure quello che volete. :-)
> > Se decidete di usare RiBa anche nelle stringhe inglesi ricordatevi però di uniformarle tutte, attualmente c'è un mix di inglese/italiano dovuto a PR successive a quella iniziale della 12.0.
> 
> Per una volta si potrebbe anche copiare da SAP, no?

Moltissime cose che ci sono in Odoo sono copiate da SAP, quindi non sarebbe una novità.

Da notare però che i termini usati da SAP (o da Dynamics o da altri) non è sempre detto che siano adeguati perché risentono dell'influenza linguistica del paese di provenienza (Germania, Stati Uniti ecc.).
Nel caso specifico hanno usato "Biill of Exchange" che in italiano significa "cambiale tratta":
 https://www.wordreference.com/enit/bill%20of%20exchange

2021-05-07 09:34 UTC, primes2h commented
> _Caso particolare è "FatturaPA" che di fatto è nome proprio, anche sul sito dell'AdE non viene tradotto._



> > > > @primes2h cerco di essere diretto, attualmente data la situazione attuale dello stato della migrazione alla 14.0, ritengo che dedicare energie a questo aspetto (puramente estetico, a mio parere) sia uno spreco.
> > > > Poi a livello generale io continuo a mantenere le mie riserve sulla utilità di tradurre i moduli italiani in inglese, ma questo è un altro discorso.
> > > > Quello che interessa ora è lo stato della migrazione da un punto di vista funzionale e funzionante
> > > 
> > > 
> > > Attenzione che io ho solo risposto a domanda specifica. Fate quello che ritenete opportuno, ci mancherebbe. :-)
> > > P.s: non concordo sul fatto che è una questione puramente estetica visto che non è un software solo "italiano", ma nasce internazionale. E la cosa, in questi tipi di software, viene sempre gestita.
> > > Giusto per portare l'esempio di SAP, loro utilizzano addirittura un altro termine:
> > > https://help.sap.com/saphelp_46c/helpdata/en/01/a9cb2f455711d182b40000e829fbfe/frameset.htm
> > > Ma, ribadisco, fate pure quello che volete. :-)
> > > Se decidete di usare RiBa anche nelle stringhe inglesi ricordatevi però di uniformarle tutte, attualmente c'è un mix di inglese/italiano dovuto a PR successive a quella iniziale della 12.0.
> > 
> > 
> > Per una volta si potrebbe anche copiare da SAP, no?
> 
> Moltissime cose che ci sono in Odoo sono copiate da SAP, quindi non sarebbe una novità.
> 
> Da notare però che i termini usati da SAP (o da Dynamics o da altri) non è sempre detto che siano adeguati perché risentono dell'influenza linguistica del paese di provenienza (Germania, Stati Uniti ecc.).
> Nel caso specifico hanno usato "Biill of Exchange" che in italiano significa "cambiale tratta":
> https://www.wordreference.com/enit/bill%20of%20exchange

Aggiungo che anche "Bank Bill" non è molto gnerico, è il vaglia cambiario:
https://www.wordreference.com/enit/bank%20bill

2021-05-07 09:38 UTC, primes2h commented
> _Caso particolare è "FatturaPA" che di fatto è nome proprio, anche sul sito dell'AdE non viene tradotto._

Concordo.

2021-05-07 09:44 UTC, marco-marchiori commented
> Se "bank bill" fosse più generico, e coprisse le Ri.Ba. andrebbe bene ugualmente. L'importante è usare un nome inglese che gli anglofoni capiscano, ed evitare l'italiano.
> 
> _Caso particolare è "FatturaPA" che di fatto è nome proprio, anche sul sito dell'AdE non viene tradotto._

Anch'io ho questa sensazione e concordo sul criterio di generalità.
Preferisco poi -al limite- riba ad una traduzione errata.
Per arrivare alla conclusione razionale bisogna perdere quei quarti d'ora che servono a confrontare i significati dei vari termini e delle varie opzioni.

2021-05-07 09:45 UTC, scigghia commented
Non riesco a farmi comprendere.
Io vedo che stiamo dedicando la mattinata a decidere come tradurre in inglese qualcosa, quando potremmo dedicare questo tempo a far funzionare qualcos'altro.
Questo per me è un fattore estetico e non è funzionale "alla causa".
Magari si può tornare più avanti sulla questione specifica della traduzione.

2021-05-07 09:47 UTC, dcorio commented
> Non riesco a farmi comprendere.
> Io vedo che stiamo dedicando la mattinata a decidere come tradurre in inglese qualcosa, quando potremmo dedicare questo tempo a far funzionare qualcos'altro.
> Questo per me è un fattore estetico e non è funzionale "alla causa".
> Magari si può tornare più avanti sulla questione specifica della traduzione.

o "adesso" o su odoo 16

2021-05-07 09:51 UTC, dcorio commented
@scigghia PS: a proposito, servirebbe qualcuno in grado di fare review funzionale del modulo :)

2021-05-07 09:53 UTC, scigghia commented
> > Non riesco a farmi comprendere.
> > Io vedo che stiamo dedicando la mattinata a decidere come tradurre in inglese qualcosa, quando potremmo dedicare questo tempo a far funzionare qualcos'altro.
> > Questo per me è un fattore estetico e non è funzionale "alla causa".
> > Magari si può tornare più avanti sulla questione specifica della traduzione.
> 
> o "adesso" o su odoo 16

io punterei a completare la migrazione, dato che attualmente c'è molta differenza in account con la versione precedente,  poi su odoo > 14 si vedrà

2021-05-07 09:53 UTC, scigghia commented
> @scigghia PS: a proposito, servirebbe qualcuno in grado di fare review funzionale del modulo :)

arriva arriva

2021-05-07 09:58 UTC, primes2h commented
> Per arrivare alla conclusione razionale bisogna perdere quei quarti d'ora che servono a confrontare i significati dei vari termini e delle varie opzioni.

Quei quarti d'ora di approfondimento li ho persi già all'epoca della PR della 12.0 proprio per confrontare le varie alternative e le due opzioni migliori imho erano "cash order" e "collection order". Tra le due quella volta avevo proposto la prima perché era la traduzione più diffusa.
Se qualcun altro ha tempo di fare ulteriori verifiche ben vengano (io ho già dato :-) ), è sempre costruttivo confrontarsi. 

Ribadisco che non c'è problema da parte mia, alla fine decidete pure come preferite dando priorità alle cose che ritenete più opportune.

2021-05-07 11:28 UTC, marco-marchiori commented
> > Per arrivare alla conclusione razionale bisogna perdere quei quarti d'ora che servono a confrontare i significati dei vari termini e delle varie opzioni.
> 
> Quei quarti d'ora di approfondimento li ho persi già all'epoca della PR della 12.0 proprio per confrontare le varie alternative e le due opzioni migliori imho erano "cash order" e "collection order". Tra le due quella volta avevo proposto la prima perché era la traduzione più diffusa.
> Se qualcun altro ha tempo di fare ulteriori verifiche ben vengano (io ho già dato :-) ), è sempre costruttivo confrontarsi.
> 
> Ribadisco che non c'è problema da parte mia, alla fine decidete pure come preferite dando priorità alle cose che ritenete più opportune.

Massimo rispetto per il tempo che ci hai perso e ci perdono tutti.
Ora la questione è diversa, anzi sono due:
- il merito della traduzione, che a mio parere va affrontato come ho proposto
- la priorità della traduzione (io non la vedo così insignificante).
Se non ce la facciamo, pazienza.

2021-05-07 14:06 UTC, primes2h commented
> > Non troverai mai il termine perfetto. Cash order ha un significato un po' più generico di quello che è la ricevuta bancaria, ma per uno straniero il fatto che si trovi nel repository italiano fa capire che è un cash order (o come lo vuoi chiamare) con alcune specificità italiane. Se fosse un cash order generico si troverebbe in un altro repo OCA.
> 
> Per arrivare ad una conclusione razionale dobbiamo confrontare una definizione di Cash Order ed una di riba per capire quanto corrispondono.
> Per questo te l'ho chiesta: temo che non quaglino, ma magari quagliano.

Ricordo che la definizione era presente anche nel dizionario "Economics & Business" Inglese-Italiano di Fernando Picchi.

2021-05-07 14:10 UTC, TheMule71 commented
> per il resto è usabile

Per te avrebbe senso mettere lo stato in alfa e mergiarlo (salvo altre questioni)?

2021-05-09 21:16 UTC, primes2h commented
> > Per arrivare ad una conclusione razionale dobbiamo confrontare una definizione di Cash Order ed una di riba per capire quanto corrispondono.
> > Per questo te l'ho chiesta: temo che non quaglino, ma magari quagliano.
> 
> Ricordo che la definizione era presente anche nel dizionario "Economics & Business" Inglese-Italiano di Fernando Picchi.

Confermo, è presente anche nell'edizione aggiornata dello stesso dizionario, edito della Hoepli (prima era Zanichelli).
Come traduzione indica "cash order" e C/O come abbreviazione.

2021-05-21 08:33 UTC, eLBati commented
Secondo me come nome tecnico  conviene tenere  `l10n_it_ricevute_bancarie` a questo punto

2021-06-11 13:59 UTC, fredzamoabg requested changes
quoto https://github.com/OCA/l10n-italy/pull/2138#commitcomment-51730920, in oltre mancano gli script di migrazione per i campi di account.invoice ed account.invoice.line

2021-07-19 15:18 UTC, TheMule71 commented
Segnalo #2219

2021-09-17 11:23 UTC, Borruso commented
PR da includere:

- #2025 
- #2035 
- #2064 
- #2081 
- #2088 
- #2119 
- #2204 
- #2219

2021-09-26 20:38 UTC, TheMule71 requested changes

2021-09-26 20:38 UTC, TheMule71 commented on l10n_it_ricevute_bancarie/models/riba.py
> +            settlement_move.action_post()
move_line_credit.move_id è lo stesso di settlement_move, per cui la 507 e la 513 fanno la action_post() della stessa move, e la seconda dovrebbe fallire male.

Per me tiene la prima e basta, posti e poi riconcilii.

2021-10-01 08:05 UTC, TheMule71 commented
> PR da includere:
> 
> * [[12.0][IMP][l10n_it_ricevute_bancarie] Flag per escludere un partner dalle … #2025](https://github.com/OCA/l10n-italy/pull/2025)
> * [[12.0][FIX] ricevute bancarie ASCII instead UTF-8 #2035](https://github.com/OCA/l10n-italy/pull/2035)
> * [[12.0][IMP] l10n_it_ricevute_bancarie, manage multiple bank in partner #2064](https://github.com/OCA/l10n-italy/pull/2064)
> * [[12.0][IMP] post-migrate script to set bank on invoice #2081](https://github.com/OCA/l10n-italy/pull/2081)
> * [[12.0][IMP] l'onchange non dovrebbe cambiare una banca valida già impostata #2088](https://github.com/OCA/l10n-italy/pull/2088)
> * [[12.0] [UPD][l10n_it_ricevute_bancarie] Aggiunta la possibilità di scegliere… #2119](https://github.com/OCA/l10n-italy/pull/2119)
> * [[12.0][IMP] created invoice directly with riba bank #2204](https://github.com/OCA/l10n-italy/pull/2204)
> * [[12.0][FIX] add riba partner bank to out_refund for compensated riba #2219](https://github.com/OCA/l10n-italy/pull/2219)

Anche #2445

2021-11-12 08:55 UTC, Borruso commented
> quoto [#2138 (comment)](https://github.com/OCA/l10n-italy/pull/2138#commitcomment-51730920), in oltre mancano gli script di migrazione per i campi di account.invoice ed account.invoice.line

gli script di migrazione sono stati aggiunti potresti provarle

2021-11-12 09:00 UTC, TheMule71 approved these changes
LGTM

2021-11-12 13:35 UTC, AntonioMariaVigliotti commented
Per la traduzione La società PriceWaterHouseCooper dichiara:
![image](https://user-images.githubusercontent.com/46092005/141475564-bd21c381-f49f-4102-b0ff-1e2a2939d944.png)

2021-11-12 16:22 UTC, AntonioMariaVigliotti commented
Test RIBA

Flusso di test:
- Creata fattura con RiBa (OK)
- Creata configurazione RiBa (OK con warning traduzione)
- Generata distinta (OK con warning traduzione)
- Distinta accettata: fattura pagata su conto di portafoglio (OK)
- Distinta accreditata: registrazione contabile con costo (OK)
- Pagata RiBA: stato distinta pagato (OK)

1. Mancano alcune traduzioni
	1.a Fatturazione > Configurazione > Pagamaneti > Configurazione RiBa
		1.a - Modalità di emissione
	1.b Fatturazione > RiBa > Emissione
		1.b - Azione > Issue C/O
	1.c Fatturazione > RiBa > Distinta
		1.b - Paid

Per me il modulo è OK
+1

2021-11-12 16:33 UTC, AntonioMariaVigliotti approved these changes
Ci sono traduzioni da completare.
So che è stato già discusso, lo dico solo come ide personale ma il termine inglese c/o Cash Order mi suona strano; avete verificato il termine "Bank Receipt"?

2021-11-12 18:45 UTC, TheMule71 commented on l10n_it_ricevute_bancarie/readme/ROADMAP.rst
> +Il modulo è stato migrato, ma i test non sono stati provati.
Gli script di migrazione, non i test. :)  Non vogliamo mica offendere github, che poi smette di fare i test :)

2021-11-15 08:07 UTC, Borruso commented on l10n_it_ricevute_bancarie/readme/ROADMAP.rst
> +Il modulo è stato migrato, ma i test non sono stati provati.
mi dispiace non era mia intenzione. ;)

2021-11-15 09:01 UTC, TheMule71 commented
> Ci sono traduzioni da completare. So che è stato già discusso, lo dico solo come ide personale ma il termine inglese c/o Cash Order mi suona strano; avete verificato il termine "Bank Receipt"?

Sì, come puoi leggere qui sopra nei commenti, c'è stata ampia discussione sulle traduzioni.  I dizionari riportano bank receipt come generica ricevuta che ti danno in banca per qualunque operazione tu faccia, molto diverso da una RiBa, che è una forma di pagamento.   Basta fare una ricerca su google, in alcuni casi il significato è opposto: https://help.brightpearl.com/hc/en-us/articles/211128806-Bank-receipts-and-deposits qui dice:

> The bank receipt process can be used for money you receive in that does not relate to a sale or customer account.
> ...
> Money received relating to sales should have a sales order/invoice for a customer. These receipts should be processed through the customer financials or orders module and not as a bank receipt

è l'opposto di quello che intendiamo noi per Ri.Ba, che invece sono legate alla fatture.

2021-11-15 10:11 UTC, AntonioMariaVigliotti commented
Grazie per la risposta.
MI rendo conto che è qualcosa che non esiste all'estero e quindi non 
"esattamente traducibile"

Antonio M. Vigliotti

Mobile (+39) 342.8740910
<https://www.facebook.com/antonio.m.vigliotti><https://www.linkedin.com/in/antonio-m-vigliotti-7b3b592b/><https://twitter.com/AntonioMaria59> 




Il 15/11/21 10:01, Marco Colombo ha scritto:
>
>     Ci sono traduzioni da completare. So che è stato già discusso, lo
>     dico solo come ide personale ma il termine inglese c/o Cash Order
>     mi suona strano; avete verificato il termine "Bank Receipt"?
>
> Sì, come puoi leggere qui sopra nei commenti, c'è stata ampia 
> discussione sulle traduzioni. I dizionari riportano bank receipt come 
> generica ricevuta che ti danno in banca per qualunque operazione tu 
> faccia, molto diverso da una RiBa, che è una forma di pagamento. Basta 
> fare una ricerca su google, in alcuni casi il significato è opposto: 
> https://help.brightpearl.com/hc/en-us/articles/211128806-Bank-receipts-and-deposits 
> qui dice:
>
>     The bank receipt process can be used for money you receive in that
>     does not relate to a sale or customer account.
>     ...
>     Money received relating to sales should have a sales order/invoice
>     for a customer. These receipts should be processed through the
>     customer financials or orders module and not as a bank receipt
>
> è l'opposto di quello che intendiamo noi per Ri.Ba, che invece sono 
> legate alla fatture.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/OCA/l10n-italy/pull/2138#issuecomment-968672277>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AK7U5ZIFORIYA4RFP5S2W6LUMDD6NANCNFSM4YINQJOQ>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> 
> or Android 
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>
>

2021-11-19 10:49 UTC, TheMule71 commented
/ocabot merge nobump

2021-11-19 10:52 UTC, TheMule71 commented
/ocabot merge nobump

2021-11-19 11:16 UTC, merged

2021-11-26 09:40 UTC, elvise commented
> PR da includere:
> 
> * [[12.0][IMP][l10n_it_ricevute_bancarie] Flag per escludere un partner dalle … #2025](https://github.com/OCA/l10n-italy/pull/2025)
> * [[12.0][FIX] ricevute bancarie ASCII instead UTF-8 #2035](https://github.com/OCA/l10n-italy/pull/2035)
> * [[12.0][IMP] l10n_it_ricevute_bancarie, manage multiple bank in partner #2064](https://github.com/OCA/l10n-italy/pull/2064)
> * [[12.0][IMP] post-migrate script to set bank on invoice #2081](https://github.com/OCA/l10n-italy/pull/2081)
> * [[12.0][IMP] l'onchange non dovrebbe cambiare una banca valida già impostata #2088](https://github.com/OCA/l10n-italy/pull/2088)
> * [[12.0] [UPD][l10n_it_ricevute_bancarie] Aggiunta la possibilità di scegliere… #2119](https://github.com/OCA/l10n-italy/pull/2119)
> * [[12.0][IMP] created invoice directly with riba bank #2204](https://github.com/OCA/l10n-italy/pull/2204)
> * [[12.0][FIX] add riba partner bank to out_refund for compensated riba #2219](https://github.com/OCA/l10n-italy/pull/2219)

@Borruso @TheMule71 la #2064 e la #2081 sono ancora da portare ?

2021-11-26 09:41 UTC, Borruso commented
> @Borruso @TheMule71 la #2064 e la #2081 sono ancora da portare ?

Sì

2023-07-06 12:48 UTC, aleuffre commented
Mi sembra che la PR #2119 non sia stata portata, Apro MR.