[ADD] Aggiunto modulo l10n_it_ricevute_bancarie_for_enterprise
OCA/l10n-italy pull request #2139
Opened 2021-02-26 13:22 UTC by Borruso

Porting del modulo l10n_it_ricevute_bancarie_for_enterprise dalla versione 12.0 alla 14.0
Poiché il modulo ha come dipendenza l10n_it_ricevute_bancarie per provarlo alla 14 bisogna installare la PR 2138

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-02-27 06:48 UTC, eLBati commented on l10n_it_ricevute_bancarie_for_enterprise/__manifest__.py
> +    "installable": True,
maintainers?

2021-02-27 06:49 UTC, eLBati commented
> Porting del modulo l10n_it_ricevute_bancarie_for_enterprise dalla versione 12.0

Sulla 12 non mi pare ci sia.

Come nome, ci sono altri casi simili in OCA per eventualmente uniformarci?

2021-04-30 07:44 UTC, dcorio commented
Propongo di eliminare quel "_for_" dal nome, così da uniformarci ai moduli enterprise

2021-11-19 11:11 UTC, OpenCode approved these changes

2021-11-23 08:52 UTC, scigghia approved these changes
:+1:

2021-11-26 10:42 UTC, SimoRubi requested changes
Riporto quanto detto stamattina in chiamata.
Questa PR non è mergiabile perché dipende dal modulo `account_accountant` che è enterprise, però il problema descritto va in qualche modo risolto.

In generale bisogna fare in modo che il modulo `account_accountant` sposti anche questo menu.
Visto che il modulo sposta i menu in modo _statico_ semplicemente cambiando il parent dei menu che conosce (https://github.com/odoo/enterprise/blob/693ea0e9f35738a09465f0b628f6678ca8f4e601/account_accountant/data/account_accountant_data.xml#L10-L28), secondo me l'unica soluzione è mettere il menu delle RiBa sotto uno dei menù esistenti e verrà così spostato automaticamente.

Può comunque valere la pena indagare se ci sono altre soluzioni.

2022-02-04 17:35 UTC, closed without merging