[14.0][MIG] l10n_it_ateco: Migration to 14.0
OCA/l10n-italy pull request #2153
Opened 2021-03-05 14:38 UTC by Borruso

Porting del modulo l10n_it_ateco dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-03-05 18:28 UTC, andreampiovesana approved these changes
go

2021-03-08 07:19 UTC, eLBati approved these changes
LGTM

2021-03-19 13:21 UTC, tafaRU requested changes
Puoi verificare come mai tra le varie build non figurano quelle di Travis?

2021-04-09 10:53 UTC, tafaRU commented
Sostituita da https://github.com/OCA/l10n-italy/pull/2210

2021-04-09 10:53 UTC, closed without merging