12.0 mig l10n it vat registries cash basis
OCA/l10n-italy pull request #2155
Opened 2021-03-05 15:29 UTC by SilvioGregorini

La migrazione si basa sulla versione del modulo presente in #768 

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-03-25 11:58 UTC, scigghia approved these changes

2021-03-30 12:30 UTC, eLBati requested changes
Grazie.
Idealmente, per una storia pulita, dovresti separare l'ultimo commit in
questo https://github.com/OCA/l10n-italy/pull/768/commits/bb6ab23c825051637bcae37e419ccb686ab4a356
+
il commit di porting alla 12

2021-03-30 12:30 UTC, eLBati commented on l10n_it_vat_registries_cash_basis/__manifest__.py
> +    'website': 'https://github.com/OCA/l10n-italy/tree/11.0/',
`12.0` oppure https://github.com/OCA/l10n-italy

2021-03-30 13:11 UTC, SilvioGregorini commented
> Grazie.
> Idealmente, per una storia pulita, dovresti separare l'ultimo commit in
> questo [bb6ab23](https://github.com/OCA/l10n-italy/commit/bb6ab23c825051637bcae37e419ccb686ab4a356)
> +
> il commit di porting alla 12

Ok, lo avevo omesso perché il commit non rientra nella history del repo, è solo in una PR non ancora mergiata.
Rimedio asap.

2023-11-07 08:44 UTC, patrickt-oforce commented
> Grazie. Idealmente, per una storia pulita, dovresti separare l'ultimo commit in questo [bb6ab23](https://github.com/OCA/l10n-italy/commit/bb6ab23c825051637bcae37e419ccb686ab4a356) + il commit di porting alla 12

@eLBati c'è ancora necessità di questa operazione, in #3488?

2024-05-26 12:27 UTC, closed without merging