[14.0][MIG] l10n_it_pec: Migration to 14.0
OCA/l10n-italy pull request #2156
Opened 2021-03-05 15:43 UTC by Borruso

Porting del modulo l10n_it_pec dalla versione 12.0 alla 14.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-03-05 18:29 UTC, andreampiovesana approved these changes
go

2021-03-19 13:14 UTC, tafaRU requested changes
Testato su runbot :+1: 
Oltre al commento puoi verificare come mai tra le varie build non figurano quelle di Travis?

![image](https://user-images.githubusercontent.com/3512779/111785801-57e8c080-88bd-11eb-9919-702b7c2e2c35.png)

2021-03-19 13:14 UTC, tafaRU commented on l10n_it_pec/views/partner_view.xml
> +            <!-- Use of xpath is mandatory due to a change in email field structure
Questo commento penso si possa togliere.

2021-04-02 07:32 UTC, tafaRU commented
@Borruso il problema descritto in https://github.com/OCA/l10n-italy/pull/2156#pullrequestreview-616378408 permane. Puoi verificare?

2021-04-09 10:24 UTC, tafaRU approved these changes

2021-04-09 10:24 UTC, tafaRU commented
/ocabot merge nobump

2021-04-09 10:43 UTC, merged