[12.0] FIX l10n_it_account_stamp when auto_compute_stamp is False
OCA/l10n-italy pull request #2164
Opened 2021-03-10 16:43 UTC by eLBati

Descrizione del problema o della funzionalità:

solo nel caso di applicazione del bollo con il metodo manuale: validando la fattura, il bollo viene rimosso

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-03-11 11:12 UTC, labaggio commented
@eLBati  
La provo subito, ma ho già visto che mi piace la soluzione ;)

2021-03-11 15:49 UTC, labaggio commented
@primes2h non volevo richiederti la review, ho cliccato per sbaglio.. ora non so come toglierti -_-'

2021-03-11 15:54 UTC, OpenCode commented
> @primes2h non volevo richiederti la review, ho cliccato per sbaglio.. ora non so come toglierti -_-'

Tolto

2021-03-11 16:37 UTC, labaggio approved these changes

2021-03-11 16:43 UTC, primes2h commented
> @primes2h non volevo richiederti la review, ho cliccato per sbaglio.. ora non so come toglierti -_-'

Ma figurati, la review la faccio volentieri :-)

2021-03-11 17:00 UTC, primes2h requested changes
Fatto test funzionale.
Ora il bollo resta correttamente selezionato dopo il salvataggio, però viene aggiunto a prescindere dalla soglia e dal tipo di imposta selezionata, campi che sono visibili nel prodotto dopo https://github.com/OCA/l10n-italy/pull/1977.

2021-03-11 19:48 UTC, eLBati commented
> però viene aggiunto a prescindere dalla soglia e dal tipo di imposta selezionata

Non capisco: a cosa serve la modalità manuale se poi è comunque il sistema a decidere se applicare il bollo?
Nella modalità manuale dovrebbe essere l'utente a decidere se applicarlo o meno. Altrimenti usa la modalità automatica.

2021-03-12 08:55 UTC, primes2h commented
> > però viene aggiunto a prescindere dalla soglia e dal tipo di imposta selezionata
> 
> Non capisco: a cosa serve la modalità manuale se poi è comunque il sistema a decidere se applicare il bollo?
> Nella modalità manuale dovrebbe essere l'utente a decidere se applicarlo o meno. Altrimenti usa la modalità automatica.

La #1977 era stata aperta a seguito di una discussione in chat sviluppo, se non ricordo male l'idea era di considerare l'azione manuale come un modo per dare agli utenti una sorta di controllo sull'azione di aggiunta o rimozione, mantenendo però le verifiche di applicabilità. 
Se si vuole tornare a una semplice aggiunta manuale senza i controlli è meglio allora nascondere di nuovo i campi con un revert del commit.

@andreampiovesana @alepit @marcelofrare  @As400it 


P.S.: per me è indifferente, noi usiamo la modalità automatica. :-P

2021-03-12 09:31 UTC, marcelofrare commented
> > però viene aggiunto a prescindere dalla soglia e dal tipo di imposta selezionata
> 
> Non capisco: a cosa serve la modalità manuale se poi è comunque il sistema a decidere se applicare il bollo?
> Nella modalità manuale dovrebbe essere l'utente a decidere se applicarlo o meno. Altrimenti usa la modalità automatica.

Da quanto mi risulta è stata aggiunta l'opzione manuale perché in automatico non sempre funzionava, quindi per consentire all'utente di intervenire e risolvere la situazione al volo.
Mi sono informato e non ci sono casi in cui sia necessario applicare il bollo al di fuori dei casi previsti dalla legge.

2021-03-12 09:33 UTC, marcelofrare commented
> > > però viene aggiunto a prescindere dalla soglia e dal tipo di imposta selezionata
> > 
> > 
> > Non capisco: a cosa serve la modalità manuale se poi è comunque il sistema a decidere se applicare il bollo?
> > Nella modalità manuale dovrebbe essere l'utente a decidere se applicarlo o meno. Altrimenti usa la modalità automatica.
> 
> La #1977 era stata aperta a seguito di una discussione in chat sviluppo, se non ricordo male l'idea era di considerare l'azione manuale come un modo per dare agli utenti una sorta di controllo sull'azione di aggiunta o rimozione, mantenendo però le verifiche di applicabilità.
> Se si vuole tornare a una semplice aggiunta manuale senza i controlli è meglio allora nascondere di nuovo i campi con un revert del commit.
> 
> @andreampiovesana @alepit @marcelofrare @As400it
> 
> P.S.: per me è indifferente, noi usiamo la modalità automatica. :-P

Concordo, l'automatismo deve essere il nostro obbiettivo.

2021-03-12 20:22 UTC, eLBati commented
Io uso solo quella automatica, quindi per me la manuale si può anche togliere (soprattutto se era stata messa perchè l'automatica sbagliava: in quel caso era da correggere l'automatica)

2021-03-23 17:09 UTC, primes2h commented
> Mi sono informato e non ci sono casi in cui sia necessario applicare il bollo al di fuori dei casi previsti dalla legge.

Ok, quindi l'automatismo si potrebbe eventualmente lasciare anche per la modalità manuale.

> La #1977 era stata aperta a seguito di una discussione in chat sviluppo, se non ricordo male l'idea era di considerare l'azione manuale come un modo per dare agli utenti una sorta di controllo sull'azione di aggiunta o rimozione, mantenendo però le verifiche di applicabilità.

@andreampiovesana ricordavo giusto?

2021-03-24 10:36 UTC, eLBati commented
https://discord.com/channels/753902328494424064/753902328494424070/824209693534715920

2021-03-24 14:44 UTC, eLBati commented
> Ok, quindi l'automatismo si potrebbe eventualmente lasciare anche per la modalità manuale

Me ne sfugge l'utilità

2021-03-25 13:31 UTC, primes2h commented
> > Ok, quindi l'automatismo si potrebbe eventualmente lasciare anche per la modalità manuale
> 
> Me ne sfugge l'utilità

Della modalità manuale sfugge anche a me :wink:
Comunque come dicevo qui per me va bene lasciare così.
https://discord.com/channels/753902328494424064/753902328494424070/824342636084461609
Se chi è interessato non si interessa perché dovrei farlo io :sweat_smile: (mi sarei anche risparmiato volentieri lavoro inutile).

2021-03-25 13:32 UTC, primes2h approved these changes
LGTM

2021-03-25 13:33 UTC, primes2h commented
/ocabot merge patch

2021-03-25 14:57 UTC, merged