[10.0][l10n_it_central_journal] Fix proper page subtotals
OCA/l10n-italy pull request #2217
Opened 2021-04-12 14:29 UTC by robyf70

Descrizione del problema o della funzionalità:

Implementa la stampa del libro giornale come da normativa di legge.

A causa del sistema di stampa del ``qweb`` per l'header ed il footer risulta un pò difficoltoso ottenere il risultato con il supporto standard di odoo. La PR utilizza un'approccio per certi versi "brutale" perchè approccia il problama non utilizzando header e footer ma  decidendo a priori quante righe per pagina è possibile stampare e quindi utilizzando la prima e ultima riga per riportare i progressivi e totali di pagina

Comportamento attuale prima di questa PR:

La stampa del libro giornale non rispetta le caratteristiche necessarie di legge che prevedono i riporti ad inizio anno/progressivi ed i totali a fine pagina.

Comportamento desiderato dopo questa PR:

Implementare una vera e propria stampa del libro giornale così come richiesto dalla normativa odierna,

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-04-16 09:08 UTC, sergiocorato commented
Ero arrivato ad una soluzione simile qui 8) : https://github.com/sergiocorato/efatto/tree/8.0/l10n_it_central_journal_ext verifico se c'è qualcosa di buono.

2021-04-16 10:53 UTC, sergiocorato commented
@robyf70 ho caricato una PR in draft solo per confronto, vuoi vedere se ti è comoda? Non è fatta decentemente ;)

2021-04-22 13:17 UTC, sergiocorato commented on l10n_it_central_journal/wizard/print_giornale.py
> +        if self.last_def_date_print == self.daterange.date_end:
presumo:
```suggestion
            if self.last_def_date_print == self.daterange.date_end:
```

2021-04-22 16:19 UTC, robyf70 commented
@sergiocorato Ho una serie di modifiche per risolvere anche il problema di del numero di pagina, più tardi committo tutto e rivediamo la PR

2021-04-22 16:36 UTC, sergiocorato reviewed
@robyf70 ti segnalo intanto che ho caricato una PR a partire da questa sulla 12.0 #2231 , attendo per coordinarci

2021-04-22 20:35 UTC, robyf70 commented
> @robyf70 ti segnalo intanto che ho caricato una PR a partire da questa sulla 12.0 #2231 , attendo per coordinarci

@sergiocorato Hai rifatto la PR sul mio ultimo push? Quest'ultimo push risolve alcune cose come la numerazione pagina che ora riprende dall'ultima stampa in definitiva, la possibilita' di usare un solo ``date range`` per cumulare le stampe definitive in sequenza, oppure in alternativa/contemporaneamente permettere al ``date range`` di collegarlo e recuperare i parametri dell'ultima stampa definiva da un range precedente.

2021-04-26 09:25 UTC, sergiocorato commented
@robyf70 Puoi correggere i vari errori sul travis?

2021-05-06 10:27 UTC, robyf70 commented
> @robyf70 Puoi correggere i vari errori sul travis?

@sergiocorato Ho pushato un fix sulla numerazione delle pagine, che andava a cambiare la numerazione in altri documenti come le fatture. Come finisce il build correggo anche gli errori su travis

2021-05-08 07:53 UTC, robyf70 commented
@sergiocorato Ora Travis è verde

2021-06-17 16:09 UTC, sergiocorato requested changes
Segnalo alcune note

2021-06-17 16:09 UTC, sergiocorato commented on l10n_it_central_journal/views/report_account_central_journal.xml
> +                    <script>
La modifica che fai qui vuol dire che il metodo inserito in `l10n_it_account` non funziona?

2024-01-21 12:27 UTC, closed without merging