[14.0][MIG] l10n_it_intrastat
OCA/l10n-italy pull request #2228
Opened 2021-04-22 12:36 UTC by SimoRubi

Migrazione da https://github.com/OCA/l10n-italy/tree/8d6bb2847a9c3f80e632935cb7d80e69f028876d/l10n_it_intrastat

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-04-30 06:36 UTC, fredzamoabg requested changes

2021-04-30 06:36 UTC, fredzamoabg commented on l10n_it_intrastat/models/account.py
> +            country_payment_id = self.invoice_id.partner_id.country_id
**invoice_id** va sostituito con **move_id**

2021-04-30 10:29 UTC, TheMule71 commented
Ciao,
vedo in giro ancora dei size= nei fields.Char()

2021-05-06 08:09 UTC, SimoRubi commented on l10n_it_intrastat/models/account.py
> +            country_payment_id = self.invoice_id.partner_id.country_id
Grazie, fatto

2021-05-06 08:10 UTC, fredzamoabg approved these changes

2021-05-06 08:16 UTC, SimoRubi commented
> Ciao,
vedo in giro ancora dei size= nei fields.Char()

Sì, a quanto vedo `size` è sempre stato deprecato fin da https://github.com/odoo/odoo/commit/524bb0a52027ec81245750bb5f0a9e5320faf922 ma funziona e non vedo una valida alternativa: si potrebbero aggiungere dei constraint ma mi pare essere moolto più developer-friendly un semplice `size=` nella definizione del campo; i constraint li vedo utili per gestire casi più complessi.
Dici che sono da togliere comunque?

2021-07-19 10:14 UTC, TheMule71 commented
Segnalo #2320

2021-11-12 15:56 UTC, SimoRubi commented on l10n_it_intrastat/models/account.py
> +        res.update({"country_payment_id": country_payment_id.id})
Grazie della review!
Probabilmente è il comportamento desiderato, di sicuro è lo stesso comportamento presente in v12

2021-11-12 15:56 UTC, SimoRubi commented on l10n_it_intrastat/models/account.py
> +        statistic_amount_euro = amount_euro
Volendo si possono cambiare, però dipende dal caso:

- se l'intrastat è una cosa solo europea allora ha senso lasciare `euro` e aggiungere magari un controllo che la `currency` sia effettivamente EUR
- altrimenti per me va bene rinominare campi/variabili in modo da _anonimizzare_ la valuta

Non so però in quale caso siamo

2021-11-12 15:56 UTC, SimoRubi commented on l10n_it_intrastat/models/account.py
> +        return section
Modificato, grazie

2021-11-12 18:14 UTC, TheMule71 commented on l10n_it_intrastat/models/account.py
> +        statistic_amount_euro = amount_euro
Anche se fosse cosa solo europea, quello che dicevo io è che se sono euro con certezza, andrebbe usata quella come currency, al posto di `company_currency` nella _convert().

Esplicito è sempre meglio che implicito, in questo caso chiamiamo la variabile _euro perché implicitamente sappiamo che company_currency è sempre euro. Meglio esplicitare la cosa ed usare effettivamente euro. Stiamo convertendo in euro non nella currency della company.   Se ci venisse anche il più remoto dubbio che ci sia differenza, non dovremmo chiamare la variabile qualcosa_euro perché a quel punto sarebbe super fuorviante dal punto di vista della leggibilità.

2021-11-15 13:40 UTC, SimoRubi commented on l10n_it_intrastat/models/account.py
> +        statistic_amount_euro = amount_euro
Finché non sappiamo quale sia il caso direi che non c'è nulla da modificare e qualunque sia la modifica sarebbe da fare anche in `12.0` perché il codice è lo stesso per questi campi.
Potresti aprire una issue e se ne parlerà lì?

Per quanto riguarda le modifiche riguardanti la migrazione (quindi cambiamenti rispetto a `12.0`), secondo te si può andare avanti?

2021-11-15 13:53 UTC, TheMule71 approved these changes
LGTM

2021-11-15 13:53 UTC, TheMule71 commented on l10n_it_intrastat/models/account.py
> +        statistic_amount_euro = amount_euro
> Per quanto riguarda le modifiche riguardanti la migrazione (quindi cambiamenti rispetto a `12.0`), secondo te si può andare avanti?

Si la cosa è abbastanza estetica in fondo.

2021-11-16 13:00 UTC, TheMule71 commented
/ocabot merge nobump

2021-11-18 11:14 UTC, tafaRU commented
@TheMule71 il tuo merge non è andato a buon fine: puoi riprovare? Considerato che ci sono altri commit dopo quello di merge, non userei l'opzione `nobump` ma almeno `patch`, che ne pensi?

2021-11-18 16:19 UTC, AntonioMariaVigliotti approved these changes
Test superati
Ringrazio lo sviluppatore il lavoro fatto

2021-11-18 16:24 UTC, AntonioMariaVigliotti approved these changes

2021-11-19 09:29 UTC, TheMule71 commented
/ocabot merge nobump

2021-11-19 10:15 UTC, merged

2021-11-19 14:33 UTC, tafaRU commented
/ocabot migration l10n_it_intrastat