[14.0] mig l10n_it_vat_statement_split_payment
OCA/l10n-italy pull request #2246
Opened 2021-04-27 14:36 UTC by eLBati

Depends on https://github.com/OCA/l10n-italy/pull/2230

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-04-29 14:49 UTC, scigghia commented
Questa pull request è stata finanziata dall'Associazione Odoo Italia, mediante gara aggiudicata da TAKOBI
rif https://www.odoo-italia.org/blog/blog-odoo-italia-1/post/verbale-del-consiglio-direttivo-21-04-2021-82

Ringrazio tutti i soci e partner italiani che sostengono, anche con piccoli contributi, l'impegno dell'associazione nel fornire una localizzazione contabile per Odoo, standardizzata e con una elevata copertura funzionale.

https://www.odoo-italia.org/shop

2021-05-04 13:27 UTC, eLBati commented
:green_apple:

2021-05-07 12:44 UTC, tafaRU requested changes
pre-commit fallisce: vedi https://github.com/OCA/l10n-italy/pull/2246/checks?check_run_id=2500618649
Inoltre, puoi uniformare il commit message a quanto indicato su https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch ?
Per il resto LGTM

2021-05-07 14:11 UTC, eLBati commented
> pre-commit fallisce

Verifico

> puoi uniformare il commit message

Ti riferisci a 3b1878db5b4cf9374d2edec1824565ad98415f32 ?

2021-05-07 14:53 UTC, tafaRU commented
> Ti riferisci a [3b1878d](https://github.com/OCA/l10n-italy/commit/3b1878db5b4cf9374d2edec1824565ad98415f32) ?

Intendo che dovresti cambiarlo in `[MIG] l10n_it_vat_statement_split_payment: Migration to 14.0`.

2021-05-09 21:11 UTC, As400it approved these changes
test funzionali

2021-05-10 06:43 UTC, andreampiovesana approved these changes
go

2021-05-21 09:21 UTC, eLBati commented
@tafaRU modificato

2021-05-21 10:26 UTC, tafaRU approved these changes

2021-05-21 10:27 UTC, tafaRU commented
/ocabot merge nobump

2021-05-21 11:10 UTC, merged