[14.0] porting l10n_it_invoices_data_communication
OCA/l10n-italy pull request #2278
Opened 2021-05-10 14:53 UTC by eLBati

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-05-21 08:51 UTC, As400it requested changes
in models/account_invoice riga 69 e 75 dovresti sostituire self.number con self.name . 

se nell'imposta non hai esigibilità iva impostata si rompe. 
Grazie

2021-05-21 10:02 UTC, eLBati commented
> in models/account_invoice riga 69 e 75 dovresti sostituire self.number con self.name .
> 
> se nell'imposta non hai esigibilità iva impostata si rompe.
> Grazie

Grazie, corretto

2021-06-18 15:03 UTC, As400it approved these changes
Approvato

2021-06-25 06:41 UTC, eLBati commented
Riporto qua le segnalazioni
https://github.com/OCA/l10n-italy/pull/2337#issuecomment-865705220
https://github.com/OCA/l10n-italy/pull/2337#issuecomment-865710813
visto che sono relative a questo modulo

2021-06-25 06:43 UTC, eLBati commented
@stevech091 grazie dei feedback https://github.com/OCA/l10n-italy/pull/2278#issuecomment-868263546

Dovrei aver risolto

2021-06-28 07:58 UTC, stevech091 commented
@eLBati gli errori che ti avevo segnalato sono risolti.
Grazie

2021-06-28 10:08 UTC, eLBati commented
> @eLBati gli errori che ti avevo segnalato sono risolti.
> Grazie

La conto come approvazione

/ocabot merge nobump

2021-06-28 10:50 UTC, merged