[FIX] l10n_it_intrastat_statement: wrong year in section 2 / 4
OCA/l10n-italy pull request #2304
Opened 2021-05-31 10:00 UTC by AntonioMariaVigliotti

Descrizione del problema o della funzionalità:
Quando vengono inserite registrazioni manuali di rettifica in sezioni 2 e 4, durante la generazione del file viene sempre impostato l'anno 20 invece dell'anno 21.
Questo dovuto dal taglio dell'anno, che preleva il dato da sinistra (secolo) invece che a destra.
Nel 2020 l'anno ed il secolo erano identici e quindi l'errore (molto subdolo) non si è evidenziato.

Comportamento attuale prima di questa PR:
La dichiarazione intrastat dei clienti italiani che aggiungono le rettifiche è sbagliata con il rischio di multe a causa di un bug software

Comportamento desiderato dopo questa PR:
La dichiarazione viene emessa correttamente.

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-05-31 10:09 UTC, robyf70 requested changes

2021-05-31 10:09 UTC, robyf70 commented on l10n_it_intrastat_statement/__manifest__.py
> +    'version': '12.0.1.2.5',
Non cambiare versione dato che l'OCA bot se ne occupa da solo di farlo

2021-05-31 10:09 UTC, robyf70 commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +    value = str(value or "")[-length:]  # Formatting only sets minimum width
la lunghezza massima la fai partire del fondo piuttosto che prendere i primi length?

2021-05-31 10:23 UTC, SimoRubi requested changes
Grazie della PR!

2021-05-31 10:23 UTC, SimoRubi commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +    value = str(value or "")[-length:]  # Formatting only sets minimum width
Se un valore numerico non sta nella lunghezza prefissata per il campo non credo ci sia un modo 'giusto' di tagliarlo.
Ad esempio, se il valore fosse 123456.78 e la lunghezza fosse 3, nessuna delle opzioni:
- '123'
- '.78'

pare sensata.
Quindi secondo me qui puoi lasciare com'era o sollevare un'eccezione quando la lunghezza di `str(value)` è maggiore di `length`.
Il problema dell'anno (effettivamente davvero subdolo) dovrebbe risolversi con l'altro commento qui sotto.

2021-05-31 10:23 UTC, SimoRubi commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> -        rcd += format_9(str(self.fiscalyear)[2:], 2)
Qui lascerei com'era prima, oppure userei '% 100'

2021-05-31 10:23 UTC, SimoRubi commented on l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
> +        # year = (self.year_id or 0) // 100
Puoi provare semplicemente a sostituire l'operatore // con %?
Penso che questa modifica da sola possa correggere l'errore che hai trovato:
```
>>> year = 2021
>>> year // 100
20
>>> year % 100
21
```

2021-05-31 10:29 UTC, SimoRubi commented
Puoi creare una issue per tracciare l'errore anche nelle altre versioni? Vedi https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue

2021-05-31 10:40 UTC, AntonioMariaVigliotti commented on l10n_it_intrastat_statement/__manifest__.py
> +    'version': '12.0.1.2.5',
Grazie, non sapevo di questa caratteristica

2021-05-31 10:51 UTC, AntonioMariaVigliotti commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +    value = str(value or "")[-length:]  # Formatting only sets minimum width
Vedi sotto

2021-05-31 10:52 UTC, AntonioMariaVigliotti commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +    value = str(value or "")[-length:]  # Formatting only sets minimum width
Ok ripristinato

2021-05-31 10:52 UTC, AntonioMariaVigliotti commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> -        rcd += format_9(str(self.fiscalyear)[2:], 2)
Fatto!

2021-05-31 10:52 UTC, AntonioMariaVigliotti commented on l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
> +        # year = (self.year_id or 0) // 100
Fatto

2021-05-31 10:53 UTC, AntonioMariaVigliotti commented
Appena la PR della 12.0 è a posto, passo alle altre versioni

2021-05-31 11:05 UTC, SimoRubi requested changes
Vedo che c'è ancora una modifica ai permessi del manifest:
![image](https://user-images.githubusercontent.com/32064796/120183855-8ca7bb00-c210-11eb-9d64-d70b62d4dc64.png)

Puoi rimuoverla?

2021-05-31 11:28 UTC, AntonioMariaVigliotti commented
Ceratmente.
Ho una domanda: nella histroy posso inserire la versione 12.0.1.2.5, perchè sto documentando una variazione di una versione che ancora non esiste.
Come fate Voi?

2021-05-31 12:49 UTC, SimoRubi commented
> Ceratmente.
> Ho una domanda: nella histroy posso inserire la versione 12.0.1.2.5, perchè sto documentando una variazione di una versione che ancora non esiste.
> Come fate Voi?

Premettendo che non credo sia necessario segnalare nel manifest questa modifica perché è comunque presente nella storia dei commit del modulo, puoi specificare la versione nel manifest in questa PR.
È vero che il bot _può_ aggiornare la versione in autonomia come ti è stato indicato in https://github.com/OCA/l10n-italy/pull/2304#discussion_r642374796 ma che io sappia non è vietato né crea particolari problemi fare la modifica all'interno della PR, soprattutto se poi ti serve citarla da qualche parte come in questo caso.

Giusto per info, c'è un meccanismo ([towncrier](https://github.com/twisted/towncrier)) per riportare la storia dei commit nel README automaticamente ma che io sappia il nostro repository non è configurato per utilizzarlo, puoi trovare maggiori info in https://github.com/OCA/maintainer-tools/pull/432

2021-05-31 14:14 UTC, AntonioMariaVigliotti commented
> > Ceratmente.
> > Ho una domanda: nella histroy posso inserire la versione 12.0.1.2.5, perchè sto documentando una variazione di una versione che ancora non esiste.
> > Come fate Voi?
> 
> Premettendo che non credo sia necessario segnalare nel manifest questa modifica perché è comunque presente nella storia dei commit del modulo, puoi specificare la versione nel manifest in questa PR.
> È vero che il bot _può_ aggiornare la versione in autonomia come ti è stato indicato in [#2304 (comment)](https://github.com/OCA/l10n-italy/pull/2304#discussion_r642374796) ma che io sappia non è vietato né crea particolari problemi fare la modifica all'interno della PR, soprattutto se poi ti serve citarla da qualche parte come in questo caso.
> 
> Giusto per info, c'è un meccanismo ([towncrier](https://github.com/twisted/towncrier)) per riportare la storia dei commit nel README automaticamente ma che io sappia il nostro repository non è configurato per utilizzarlo, puoi trovare maggiori info in [OCA/maintainer-tools#432](https://github.com/OCA/maintainer-tools/pull/432)

La modifica segnalata in git é visibile solo agli sviluppatori ed é molto tecnica. Solitamente io inserisco la cronologia nel README (come fa OCA) che è già un'informazione utilie e visibile anche utenti meno tecnici. Detto questo, cosa faccio? Elimino il file HISTORY o lo lascio con la versione incerta?

Dimmi qual è la soluzione migliore per la Community italiana che mi adeguo e parto con le altre versioni.

Grazie

2021-05-31 14:51 UTC, SimoRubi commented
> > > Ceratmente.
> > > Ho una domanda: nella histroy posso inserire la versione 12.0.1.2.5, perchè sto documentando una variazione di una versione che ancora non esiste.
> > > Come fate Voi?
> > 
> > 
> > Premettendo che non credo sia necessario segnalare nel manifest questa modifica perché è comunque presente nella storia dei commit del modulo, puoi specificare la versione nel manifest in questa PR.
> > È vero che il bot _può_ aggiornare la versione in autonomia come ti è stato indicato in [#2304 (comment)](https://github.com/OCA/l10n-italy/pull/2304#discussion_r642374796) ma che io sappia non è vietato né crea particolari problemi fare la modifica all'interno della PR, soprattutto se poi ti serve citarla da qualche parte come in questo caso.
> > Giusto per info, c'è un meccanismo ([towncrier](https://github.com/twisted/towncrier)) per riportare la storia dei commit nel README automaticamente ma che io sappia il nostro repository non è configurato per utilizzarlo, puoi trovare maggiori info in [OCA/maintainer-tools#432](https://github.com/OCA/maintainer-tools/pull/432)
> 
> La modifica segnalata in git é visibile solo agli sviluppatori ed é molto tecnica. Solitamente io inserisco la cronologia nel README (come fa OCA) che è già un'informazione utilie e visibile anche utenti meno tecnici. Detto questo, cosa faccio? Elimino il file HISTORY o lo lascio con la versione incerta?
> 
> Dimmi qual è la soluzione migliore per la Community italiana che mi adeguo e parto con le altre versioni.
> 
> Grazie

Se vuoi segnalare nel README che la fix è presente da una certa versione, secondo me devi anche mettere la nuova versione nel manifest per coerenza (perché in effetti la versione `1.2.4` ha anche sottoversioni di sviluppo senza fix); altrimenti togli il file HISTORY.

Comunque l'unica modifica che ho chiesto è https://github.com/OCA/l10n-italy/pull/2304#pullrequestreview-672204655 e aggiungo che tutte le modifiche dovrebbero stare in un unico commit (ho visto ora che sono duplicati).

2021-05-31 18:41 UTC, AntonioMariaVigliotti commented
Rimosso HISTORY e rimosso i nomi dei colleghi che hanno lavorato alla risoluzione di altri bug e implementazioni.
Saranno oggetto di prossime PR
Se approvate questa inizio il lavoro sulle altre versioni

2021-06-01 07:09 UTC, SimoRubi requested changes
Riesci a includere tutto in un solo commit?
Attualmente ce ne sono 3 tutti con lo stesso messaggio

2021-06-01 12:42 UTC, zeroincombenze commented
Volentieri ma non so come fare. Sai darmi qualche dritta?

2021-06-01 13:06 UTC, SimoRubi commented
> Volentieri ma non so come fare. Sai darmi qualche dritta?

1. Riscrivi la storia dei tuoi commit eseguendo `git rebase -i 6cd14269eb34d08b310ac37eda9a8a4957f823e6^`
2. Nell'editor che si apre, segni il secondo e il terzo commit con **fixup** invece di **pick**: questo fa sì che le modifche si concentrino tutte nel primo commit
3. Esegui `git log` per controllare che ci sia un solo tuo commit, seguito dagli altri commit di `12.0`
4. Push forzato per sovrascrivere la storia dei commit anche in github: `git push -f`

2021-06-01 16:09 UTC, AntonioMariaVigliotti commented
E' stato piuttosto complicato ma alla fine c'è l'ho fatta! Ora dovrebbe esserci una sola commit.
Simone, grazie mille per la pazienza e l'assistenza.
Spero di poter ricambiare con i miei contributi.
Resto in attesa della conferma (spero) definitiva.

2021-06-01 16:35 UTC, sergiocorato commented
È rimasta una modifica non pertinente su ` l10n_it_withholding_tax/i18n/it.po`, poi il resto direi ok.

2021-06-01 16:42 UTC, AntonioMariaVigliotti commented
Come è possibile il conflitto con withholding tax? Non capisco, non ho toccato quel modulo

2021-06-01 16:45 UTC, AntonioMariaVigliotti commented
Credo di aver capito, c'è stato un aggiornamento delle repository OCA. Con il fetch/merge sembra risolto
Sergio puoi dare un'occhiata, per favore?
Così mi dici se devo fare qualche azione correttiva
Grazie

2021-06-01 21:29 UTC, sergiocorato approved these changes
Grazie

2021-06-03 14:35 UTC, eLBati commented
Mi pare ci sia un problema con i commit: dovrebbe essere uno e dovrebbe avere un messaggio significativo per questa modifica

2021-06-03 14:48 UTC, zeroincombenze commented
Ciao Lorenzo,
riesci ad essere più preciso e darmi qualche dritta?

2021-06-10 14:51 UTC, eLBati commented
Assumendo che tu abbia un repository locale `l10n-italy` dove `origin` è `OCA/l10n-italy` e `AntonioMariaVigliotti` è `AntonioMariaVigliotti/l10n-italy`
(se non ci fosse:
```
git remote add AntonioMariaVigliotti git@github.com:AntonioMariaVigliotti/l10n-italy.git
```
) e il branch `12.0` è collegato a `origin/12.0`, puoi innanzitutto aggiornare il codice:
```
git checkout 12.0
git pull
git fetch AntonioMariaVigliotti
```
Poi ti sposti sul tuo branch remoto e crei un branch dedicato (usare come nome branch sempre 12.0 impedisce di lavorare bene sui branch locali)
```
git checkout AntonioMariaVigliotti/12.0
git checkout -b intrastat-fix
```
lanci quindi rebase
```
git rebase -i origin/12.0
```
Vedrai che i commit di merge non verranno proposti.
Nel rebase interattivo dovrai sostituire `pick` con `reword` per modificare il messaggio di commit, visto che "Update translation files" è sbagliato.

A questo punto hai 2 strade: sovrascrivere `AntonioMariaVigliotti/12.0` con
```
git push -f AntonioMariaVigliotti 12.0
```
Strada che sconsiglio.

Meglio: carichi sul tuo remoto il branch `intrastat-fix` con
```
git push -u AntonioMariaVigliotti intrastat-fix
```
e apri una nuova PR usando il nuovo branch

2021-06-11 04:48 UTC, AntonioMariaVigliotti commented
Fatto!
Grazie Lorenzo

Antonio M. Vigliotti

Mobile (+39) 342.8740910
<https://www.facebook.com/antonio.m.vigliotti><https://www.linkedin.com/in/antonio-m-vigliotti-7b3b592b/><https://twitter.com/AntonioMaria59> 




Il 10/06/21 16:52, Lorenzo Battistini ha scritto:
> |git push -u AntonioMariaVigliotti intrastat-fix|

2021-06-11 07:26 UTC, TheMule71 commented
> git checkout AntonioMariaVigliotti/12.0
> git checkout -b intrastat-fix

Solo come curiosità, si può fare con un unico comando:

git checkout AntonioMariaVigliotti/12.0 -b intrastat-fix

2021-06-11 07:31 UTC, sergiocorato requested changes
Correggo la review in attesa che ci sia un unico commit (mi devo mettere un post-it sul pc di guardare i commit...)

2021-06-11 12:29 UTC, AntonioMariaVigliotti commented
Chiudo questa PR perché sostituita da
https://github.com/OCA/l10n-italy/pull/2326

2021-06-11 12:29 UTC, closed without merging