[FIX][l10n_it_account_stamp] Fixed method 'action_move_create' to avo…
OCA/l10n-italy pull request #2319
Opened 2021-06-09 08:59 UTC by matteoopenf

Descrizione del problema o della funzionalità:
Nel caso in cui la fattura sia assoggettata a imposta di bollo e non venga applicata la rivalsa in fattura, Odoo scrive in dare e avere l'importo del bollo all'interno della registrazione.

Comportamento desiderato dopo questa PR:
Viene aggiunto un flag sul prodotto "bollo", modificabile dall'utente, da cui viene definito se tali righe debbano essere o meno omesse nel caso non sia presente la rivalsa in fattura.

porting per issue #1694

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-06-09 10:05 UTC, sergiocorato commented
Grazie, se correggi travis poi per me è ok

2021-06-09 10:23 UTC, matteoopenf commented
@sergiocorato  fatto

2021-06-09 12:20 UTC, matteoopenf commented
@sergiocorato direi che ci siamo esatto?

2021-06-10 07:21 UTC, tafaRU approved these changes

2021-06-10 08:26 UTC, alessandrocamilli approved these changes

2021-06-10 08:26 UTC, matteoopenf commented
@tafaRU  per caso è possibile mergiare?

2021-06-10 10:47 UTC, tafaRU commented
> @tafaRU per caso è possibile mergiare?

attendiamo prima la conferma di @sergiocorato

2021-06-10 15:22 UTC, eLBati commented
> Nel caso in cui la fattura sia assoggettata a imposta di bollo e non venga applicata la rivalsa in fattura, Odoo scrive in dare e avere l'importo del bollo all'interno della registrazione

Come mai questo sarebbe sbagliato?
La registrazione serve per rilevare i debiti per bolli da versare, indipendentemente da se te lo fai pagare dal cliente

2021-06-10 15:29 UTC, matteoopenf commented
> > Nel caso in cui la fattura sia assoggettata a imposta di bollo e non venga applicata la rivalsa in fattura, Odoo scrive in dare e avere l'importo del bollo all'interno della registrazione
> 
> Come mai questo sarebbe sbagliato?
> La registrazione serve per rilevare i debiti per bolli da versare, indipendentemente da se te lo fai pagare dal cliente

@alessandrocamilli

2021-06-11 07:43 UTC, sergiocorato commented
Facendo una verifica vedo che il bollo se addebitato genera questa scrittura:
![Screenshot(188)](https://user-images.githubusercontent.com/7657311/121649610-06ee0000-ca99-11eb-9a95-02efa856f4c0.png)
mentre in caso contrario questa:
![Screenshot(187)](https://user-images.githubusercontent.com/7657311/121649611-081f2d00-ca99-11eb-92e3-2456c60922a4.png)
Il tutto avendo configurato nel bollo questi conti (il costo nei costi e il debito nei ricavi):
![Screenshot(189)](https://user-images.githubusercontent.com/7657311/121649817-3a308f00-ca99-11eb-9af5-2435274678f9.png)
Direi che il problema è solo relativo alla configurazione sul bollo?

2021-06-11 08:19 UTC, matteoopenf commented
> Facendo una verifica vedo che il bollo se addebitato genera questa scrittura:
> ![Screenshot(188)](https://user-images.githubusercontent.com/7657311/121649610-06ee0000-ca99-11eb-9a95-02efa856f4c0.png)
> mentre in caso contrario questa:
> ![Screenshot(187)](https://user-images.githubusercontent.com/7657311/121649611-081f2d00-ca99-11eb-92e3-2456c60922a4.png)
> Il tutto avendo configurato nel bollo questi conti (il costo nei costi e il debito nei ricavi):
> ![Screenshot(189)](https://user-images.githubusercontent.com/7657311/121649817-3a308f00-ca99-11eb-9af5-2435274678f9.png)
> Forse il problema è solo relativo alla configurazione sul bollo?

si è tutto relativo alla configurazione dei due conti aspetto @alessandrocamilli  camilli che ne sa di più

2021-06-17 15:33 UTC, sergiocorato requested changes
blocco il merge in attesa di verifica

2024-05-26 12:27 UTC, closed without merging