[14.0][FIX] l10n_it_fatturapa_in: Fixed singleton error on field computation
OCA/l10n-italy pull request #2355
Opened 2021-07-02 16:59 UTC by TheMule71

Taking over #2350

Fixes: https://github.com/OCA/l10n-italy/issues/2349

diff from #2350 (due to pre-commit formatting)

```diff --git a/l10n_it_fatturapa_in/models/account.py b/l10n_it_fatturapa_in/models/account.py
index 998191db7..7f7dafc99 100644
--- a/l10n_it_fatturapa_in/models/account.py
+++ b/l10n_it_fatturapa_in/models/account.py
@@ -247,10 +247,12 @@ class AccountInvoice(models.Model):
             bill.e_invoice_validation_message = ",\n".join(error_messages) + "."
             other_account_moves -= bill
 
-        other_account_moves.write({
-            'e_invoice_validation_error': False,
-            'e_invoice_validation_message': False,
-        })
+        other_account_moves.write(
+            {
+                "e_invoice_validation_error": False,
+                "e_invoice_validation_message": False,
+            }
+        )
 
     def name_get(self):
         result = super(AccountInvoice, self).name_get()
```

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-07-12 15:07 UTC, SimoRubi requested changes

2021-07-12 15:07 UTC, SimoRubi commented on l10n_it_fatturapa_in/models/account.py
> -        self.e_invoice_validation_message = False
Da https://github.com/odoo/odoo/commit/9920f20e4c7753bc17bea71dea3a90f7de687196 è possibile assegnare un valore ad un campo per più record, quindi per risolvere il problema credo sia sufficente rimuovere `self.ensure_one`, puoi provare?

2021-07-19 07:07 UTC, tafaRU approved these changes

2021-07-19 08:37 UTC, TheMule71 commented on l10n_it_fatturapa_in/models/account.py
> -        self.e_invoice_validation_message = False
Funziona. Ho anche aggiunto un piccolo test, provato prima e dopo la patch.

2021-07-19 08:44 UTC, SimoRubi commented on l10n_it_fatturapa_in/models/account.py
> -        self.e_invoice_validation_message = False
Grazie, puoi dare un nome più significativo al test e/o aggiungere una docstring?
`test_2349_fix` non fa capire cosa dovrebbe testare.

2021-07-23 10:45 UTC, tafaRU commented
@SimoRubi puoi controllare se ora è ok?

2021-07-23 11:02 UTC, SimoRubi approved these changes
Revisione del codice, per me è ok

2021-07-23 11:13 UTC, tafaRU commented
/ocabot merge patch

2021-07-23 11:59 UTC, merged