[12.0][IMP] l10n_it_account_stamp: Usabilità per il bollo in fattura
OCA/l10n-italy pull request #2448
Opened 2021-10-04 10:05 UTC by SimoRubi

Risolve https://github.com/OCA/l10n-italy/issues/2447 per `12.0`

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-10-06 04:57 UTC, eLBati requested changes
https://github.com/OCA/l10n-italy/issues/2447#issuecomment-935454114

2021-10-06 07:28 UTC, SimoRubi commented
> [#2447 (comment)](https://github.com/OCA/l10n-italy/issues/2447#issuecomment-935454114)

Grazie della review!
Quindi i vari messaggi sono da togliere/modificare?
Vorrei fare in modo che l'utente riesca a capire cosa sta succedendo al bollo e far vedere solo l'immagine com'è prima di queste modifiche non aiuta molto.

2021-10-07 13:14 UTC, SimoRubi commented
> > Quindi i vari messaggi sono da togliere/modificare?
> 
> Quali messaggi?

I messaggi che introduco nel form della fattura con questa PR:
- > Stamp line can only be added in draft state
- > Stamp line added

In pratica dalla tua review non mi è chiaro cosa vorresti che modificassi in questa PR.

> Per sicurezza: è chiaro che aver applicato il bollo in fattura è una cosa diversa da averlo inserito come riga da far pagare al cliente?

Mi è chiaro quello che fa il codice del modulo:
- se la riga in fattura non è presente, vengono comunque generate le registrazioni contabili sui conti configurati nel bollo.
- altrimenti il bollo viene addebitato al cliente

Questa PR dovrebbe servire a chiarire quando la riga è stata aggiunta in fattura.
Quando è aggiunta viene visualizzato il messaggio:
> Stamp line added

vicino all'immagine del bollo.

2021-10-08 09:10 UTC, marco-marchiori commented
Sì alla fine mi sembra tutto sommato una buona soluzione far capire all'utente che vede la fattura che per inserire il bollo la deve portare in bozza.
Per alcuni utenti vedere semplicemente l'icona del bollo può far presupporre che ci sia (pensando al doc cartaceo), la fattura uscirebbe senza e l'accertamento da parte dell'agenzia è praticamente certo.

2021-10-20 08:54 UTC, marco-marchiori commented
@primes2h 
sì esatto, giusta osservazione, quando nella fattura cartacea vedevi la marca avevi già pagato il bollo (e ti potevi rivalere oppure no).
Quindi, se il sisema settato con il calcolo automatico e correttamente configurato aggiunge sempre la riga bollo allora il problema riguarda l'espressione utilizzata nel bottone: se clicco il bottone riaddebito il bollo al cliente, va cambiata l'espressione.
In ogni caso il pulsante visibile e correttamente disposto evita errori e fraintendimenti.

2021-11-22 15:12 UTC, SimoRubi commented
@OCA/local-italy-maintainers si può mergiare o devo fare qualche altra modifica?

2021-11-22 15:18 UTC, OpenCode commented
/ocabot merge minor

2021-11-22 16:47 UTC, merged