[14.0][FIX] l10n_it_delivery_note: select wizard fails to get picking state after core updates
OCA/l10n-italy pull request #2484
Opened 2021-10-29 14:00 UTC by fredzamoabg

le modifiche apportate al metodo `_compute_state` (https://github.com/odoo/odoo/commit/dca7119f6fe4f9e66c3ecc58f204420e2ad805cd#diff-79cbc763115661182c02285c07320098510f5686700359ddee67443b4893dc30) da parte del core portano ad un fallimento nel tentativo di assegnare un delivery note esistente ad un picking in stato 'done'.
in pratica:
![image](https://user-images.githubusercontent.com/70569899/139447274-f0442454-1a28-4e72-976d-e3dc7c4df009.png)

questo accade perchè il dato ('state') non risulta in cache.

questa PR per forzare l'inserimento in cache di tale dato evitando quindi la chiamata al metodo `_compute_state`

2021-11-22 16:26 UTC, stevech091 approved these changes
Functional test OK

2021-11-23 13:22 UTC, SimoRubi requested changes
Grazie della PR!
Ho provato la modifica e permette di selezionare un delivery note esistente, tuttavia nella lista dei picking alcuni picking risultano in stato **Draft** mentre invece sono completati, puoi verificare?
Riporto il video appena fatto in runbot (http://3517657-2484-24cb5a.runbot2-2.odoo-community.org/web#action=307&model=stock.picking&view_type=list&cids=1&menu_id=187):

https://user-images.githubusercontent.com/32064796/143030811-718a55ca-b248-4deb-822d-367a53aa0797.mp4
Nel video si vede che i picking **WH/OUT/00019** e **WH/OUT/00020** sono **Done** ma nel popup di selezione del delivery note risultano in stato **Draft**, puoi verificare?

Non è chiaro che questo pezzo di XML (mostrare un campo in una tree nascosta) esista per correggere un bug, riesci ad aggiungere un test che verifichi l'utilità di questa modifica?
Per chiarirlo potresti aggiungere una nota per giustificare, almeno a parole, la modifica.

Avendo un test ci mettiamo al sicuro da almeno un paio di possibilità nel caso la modifica venga rimossa in futuro:
- se il test fallisce allora la modifica risulta effettivamente necessaria
- se il test passa allora il codice del core è stato corretto e la modifica non è più necessaria

In pratica il test assicura che il problema non tornerà a presentarsi in futuro.

2021-11-23 14:09 UTC, fredzamoabg commented
> Grazie della PR! Ho provato la modifica e permette di selezionare un delivery note esistente, tuttavia nella lista dei picking alcuni picking risultano in stato **Draft** mentre invece sono completati, puoi verificare? Riporto il video appena fatto in runbot (http://3517657-2484-24cb5a.runbot2-2.odoo-community.org/web#action=307&model=stock.picking&view_type=list&cids=1&menu_id=187):
> 
> https://user-images.githubusercontent.com/32064796/143030811-718a55ca-b248-4deb-822d-367a53aa0797.mp4 Nel video si vede che i picking **WH/OUT/00019** e **WH/OUT/00020** sono **Done** ma nel popup di selezione del delivery note risultano in stato **Draft**, puoi verificare?
> 
> Non è chiaro che questo pezzo di XML (mostrare un campo in una tree nascosta) esista per correggere un bug, riesci ad aggiungere un test che verifichi l'utilità di questa modifica? Per chiarirlo potresti aggiungere una nota per giustificare, almeno a parole, la modifica.
> 
> Avendo un test ci mettiamo al sicuro da almeno un paio di possibilità nel caso la modifica venga rimossa in futuro:
> 
> * se il test fallisce allora la modifica risulta effettivamente necessaria
> * se il test passa allora il codice del core è stato corretto e la modifica non è più necessaria
> 
> In pratica il test assicura che il problema non tornerà a presentarsi in futuro.

@SimoRubi per quanto riguarda l'errore che hai riscontrato non penso dipenda da questa modifica comunque verifico. per il discorso dei test ok vedo cosa posso fare.
grazie

2021-11-25 10:14 UTC, fredzamoabg commented
@SimoRubi ho provato ad aggiungere un test che cercasse di riprodurre il problema (escludendo le modifiche alla view introdotte in questa PR) ma non ci sono riuscito.
ho inserito invece un commento che potrebbe venire utile ai posteri.

per il problema che hai riscontrato circa lo stato dei picking nel form come ti ho scritto precedentemente non è un problema relativo a questa PR (il campo è pure un altro `picking_ids`); ho provato cmq a capire come venirne a capo... purtroppo senza successo. A riguardo ti chiederei eventualmente di aprire una issue se lo ritieni necessario.

2021-11-25 12:05 UTC, SimoRubi requested changes
> @SimoRubi ho provato ad aggiungere un test che cercasse di riprodurre il problema (escludendo le modifiche alla view introdotte in questa PR) ma non ci sono riuscito. ho inserito invece un commento che potrebbe venire utile ai posteri.

Peccato per il test, comunque 👍🏻 

> per il problema che hai riscontrato circa lo stato dei picking nel form come ti ho scritto precedentemente non è un problema relativo a questa PR (il campo è pure un altro `picking_ids`); ho provato cmq a capire come venirne a capo... purtroppo senza successo. A riguardo ti chiederei eventualmente di aprire una issue se lo ritieni necessario.

Con il codice di `14.0` non riesco ad aprire il wizard di selezione di un delivery note esistente quindi non mi è possibile verificare che il problema esista anche senza queste modifiche.

L'unica verifica che ho potuto fare è in `12.0` dove è possibile aprire il wizard e gli stati dei trasferimenti sono corretti:
![image](https://user-images.githubusercontent.com/32064796/143437248-159206da-eeac-4624-bd14-a806200bc6f6.png)
puoi aggiungerlo alla issue di tracciamento come descritto in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue?
La issue è sempre da creare insieme alla PR soprattutto se il problema può riguardare diverse versioni come in questo caso.

Quando sarà possibile replicare l'errore anche senza queste modifiche allora potrai riportarlo in un'altra issue/PR dedicata; fino ad allora, per quanto improbabile, ai fatti il problema sembra essere causato da queste modifiche.

2021-11-25 12:27 UTC, fredzamoabg commented
> > @SimoRubi ho provato ad aggiungere un test che cercasse di riprodurre il problema (escludendo le modifiche alla view introdotte in questa PR) ma non ci sono riuscito. ho inserito invece un commento che potrebbe venire utile ai posteri.
> 
> Peccato per il test, comunque 👍🏻
> 
> > per il problema che hai riscontrato circa lo stato dei picking nel form come ti ho scritto precedentemente non è un problema relativo a questa PR (il campo è pure un altro `picking_ids`); ho provato cmq a capire come venirne a capo... purtroppo senza successo. A riguardo ti chiederei eventualmente di aprire una issue se lo ritieni necessario.
> 
> Con il codice di `14.0` non riesco ad aprire il wizard di selezione di un delivery note esistente quindi non mi è possibile verificare che il problema esista anche senza queste modifiche.
> 
> L'unica verifica che ho potuto fare è in `12.0` dove è possibile aprire il wizard e gli stati dei trasferimenti sono corretti: ![image](https://user-images.githubusercontent.com/32064796/143437248-159206da-eeac-4624-bd14-a806200bc6f6.png) puoi aggiungerlo alla issue di tracciamento come descritto in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue? La issue è sempre da creare insieme alla PR soprattutto se il problema può riguardare diverse versioni come in questo caso.
> 
> Quando sarà possibile replicare l'errore anche senza queste modifiche allora potrai riportarlo in un'altra issue/PR dedicata; fino ad allora, per quanto improbabile, ai fatti il problema sembra essere causato da queste modifiche.

il problema che avevi evidenziato inizialmente si verifica selezionando il DN mentre nell'immagine non sembra tu l'abbia fatto.

2021-11-25 12:52 UTC, fredzamoabg commented
ok il problema è sempre dovuto alla chiamata al metodo **_compute_state** di stock.picking. quindi il problema non è dovuto alle modifiche in questa PR ma chiaramente lo evidenzia fisto che il form non si apriva proprio...

2021-11-26 11:31 UTC, fredzamoabg commented
come concordato ho nascosto la colonna nel wizard.
nota: non l'ho cancellata per:

![image](https://user-images.githubusercontent.com/70569899/143574512-c133b6d3-472e-4301-a4a1-bd22475867d6.png)

2021-11-26 14:57 UTC, SimoRubi approved these changes
Provata in locale (runbot sta ancora girando) e revisione del codice, per me è ok

2021-11-30 09:06 UTC, fredzamoabg commented
il core ha mergiato la PR che risolve il problema del metodo `_compute_state` (questo il commit https://github.com/odoo/odoo/commit/86315761dc154e55dd464a6945eea4ac178fb602). questa PR non è più necessaria.

2021-11-30 09:17 UTC, tafaRU commented
grazie @fredzamoabg per l'aggiornamento, allora chiudi pure.

2021-11-30 09:28 UTC, closed without merging