[FIX] l10n_it_split_payment: fix unbalanced lines
OCA/l10n-italy pull request #2515
Opened 2021-11-16 13:44 UTC by Borruso

2021-11-17 09:52 UTC, SimoRubi reviewed
Grazie della PR!
Vorrei provarla ma non so come riprodurre l'errore, puoi aggiungere in descrizione almeno gli step per riprodurre il problema?
Se poi riesci sarebbe bene anche aggiungere un test per evitare regressioni in futuro.

In base a https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo poi servirebbe anche una issue di tracciamento per portare l'eventuale correzioni alle altre versinoi supportate.

2021-11-19 09:59 UTC, Borruso commented
> Grazie della PR! Vorrei provarla ma non so come riprodurre l'errore, puoi aggiungere in descrizione almeno gli step per riprodurre il problema? Se poi riesci sarebbe bene anche aggiungere un test per evitare regressioni in futuro.
> 
> In base a https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo poi servirebbe anche una issue di tracciamento per portare l'eventuale correzioni alle altre versinoi supportate.

Aggiunto test

2021-11-22 10:02 UTC, SimoRubi requested changes
Grazie degli step e del test!
> In base a https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo poi servirebbe anche una issue di tracciamento per portare l'eventuale correzioni alle altre versinoi supportate.

Aggiungo che per poter vedere le righe contabili devo confermare la fattura e per poter aggiungere la seconda riga devo prima riportarla in bozza.
Una volta fatto ciò in runbot ottengo l'errore:
![image](https://user-images.githubusercontent.com/32064796/142840732-cab1b35c-494d-413f-99f2-4f90f7aad2ae.png)
che suppongo sia quello che vuoi correggere.

Ho provato nel runbot generato dalla tua PR ma non riesco ad aggiungere la seconda riga perché continua a togliermela da sotto il mouse, qui sotto il video che parte dalla fattura con lo split payment già confermata e riportata in bozza:
https://user-images.githubusercontent.com/32064796/142841062-ba6eaa50-5ffc-4953-be2e-4fa00b4d1fb1.mp4

Puoi verificare?

2022-07-13 08:07 UTC, SirTakobi requested changes
Aspettavo a fare review perché i test falliscono, ma tanto vale scriverlo direttamente :smile:
Puoi correggere i test?

2022-07-13 08:22 UTC, Borruso commented
> Aspettavo a fare review perché i test falliscono, ma tanto vale scriverlo direttamente smile Puoi correggere i test?

falliscono i test di fatturapa_out_sp

2022-07-18 10:39 UTC, tafaRU commented
/ocabot rebase

2022-07-19 09:06 UTC, tafaRU commented
@Borruso FYI sto lavorando su questa.

2022-07-20 10:57 UTC, tafaRU requested changes
Per quanto riguarda i problemi sollevati nei test, debuggando ho scoperto che:

- https://github.com/OCA/l10n-italy/runs/7387629100?check_suite_focus=true#step:8:751 si dovrebbe risolvere con un rebase su `14.0` in modo da includere https://github.com/OCA/l10n-italy/pull/2821
- https://github.com/OCA/l10n-italy/runs/7387629100?check_suite_focus=true#step:8:903 lo puoi risolvere così come ho fatto in https://github.com/tafaRU/l10n-italy/commit/804a9777901f5e40beda229b812e6cfa5a322d07
Ti avrei fatto una PR ma il tuo fork non è visibile 
![image](https://user-images.githubusercontent.com/3512779/179964282-58b44424-eef6-4cfe-b354-e8cb2c4749a2.png)

Provando la tua PR su runboat ho trovato un problema:
![Peek 2022-07-20 12-38](https://user-images.githubusercontent.com/3512779/179964568-955cbe00-5346-4532-a53b-efa1b1eb663e.gif)

Nota, se può essere d'aiuto: il problema specifico si risolve sostituendo in questi due punti [(primo](https://github.com/Borruso/l10n-italy/blob/48e61b9983fcb7d38a21302237c679783b4f0dd3/l10n_it_split_payment/models/account.py#L135) e [secondo](https://github.com/Borruso/l10n-italy/blob/48e61b9983fcb7d38a21302237c679783b4f0dd3/l10n_it_split_payment/models/account.py#L150)) il metodo `write` con `update`. Così facendo però si introduce di nuovo l'effetto collaterale della scomparsa delle Invoice Lines.

-edit-
Se la fattura viene salvata le Invoice Lines ricompaiono.

2022-07-20 10:57 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                if not move.is_sale_document():
Lascerei `if move.is_purchase_document()` così com'è attualmente.

2022-07-20 10:57 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp.price_unit,
Qui e più sotto rimetterei `line_sp[0]` così come già discusso in https://github.com/OCA/l10n-italy/pull/1959#discussion_r602127514 Cosa ne pensi?

2022-07-22 10:01 UTC, tafaRU commented
/ocabot rebase

2022-07-22 10:21 UTC, matteoopenf commented
abbiamo testato su runboat e sembra funzionare e non crea più lo sbilanciamento, credo quindi solo i test vado sistemati, appena si riesce anche con i test riproviamo e approvo

2022-07-22 10:40 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                if not move.is_sale_document():
Vedi https://github.com/Borruso/l10n-italy/pull/11/commits/89bc3f3bdaa0f4e22954f8b8ec620497e4741f07

2022-07-22 10:40 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp.price_unit,
Vedi https://github.com/Borruso/l10n-italy/pull/11/commits/89bc3f3bdaa0f4e22954f8b8ec620497e4741f07

2022-07-22 10:42 UTC, tafaRU commented
> abbiamo testato su runboat e sembra funzionare e non crea più lo sbilanciamento, credo quindi solo i test vado sistemati, appena si riesce anche con i test riproviamo e approvo

stiamo lavorandoci, vedi https://github.com/Borruso/l10n-italy/pull/11

2022-07-22 13:04 UTC, tafaRU approved these changes

2022-07-22 13:06 UTC, matteoopenf approved these changes

2022-07-22 15:18 UTC, tafaRU requested changes

2022-07-22 15:18 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp = line_sp.with_context(check_move_validity=False)
Mi sono accorto solo ora che questa riga e la 150 introducono una duplicazione di codice: sarebbe meglio fare l'assegnazione una sola volta dopo la 120. Puoi provvedere?
Poi per il resto LGTM.

2022-07-26 14:10 UTC, michelerusti approved these changes

2022-07-27 08:09 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp = line_sp.with_context(check_move_validity=False)
@Borruso ho visto https://github.com/OCA/l10n-italy/compare/51cd055201da954fdac4d63812faacfa928de946..71d5008c2323a44518695bf08789ff8ba8c458d0 ma non mi sembra ancora corretto. Nel mio precedente commento intendevo che `line_sp[0].with_context(check_move_validity=False)` può essere assegnata una sola volta.

2022-08-05 11:57 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp[0].write(write_off_line_vals)
In questo punto userei direttamente: `line_sp.write(write_off_line_vals)` considerato che `line_sp = line_sp[0].with_context(check_move_validity=False)`. Puoi apportare la modifica? Poi ci dovremmo essere :+1: 
Grazie!

2022-08-05 11:58 UTC, tafaRU commented on l10n_it_split_payment/models/account.py
> +                line_sp = line_sp.with_context(check_move_validity=False)
@Borruso vedi https://github.com/OCA/l10n-italy/pull/2515#pullrequestreview-1063255541

2022-08-24 09:55 UTC, tafaRU requested changes
@Borruso nei vari force-pushed che hai fatto hai alterato il contenuto del commit https://github.com/OCA/l10n-italy/pull/2515/commits/0c55bf680c9b6fb3dbf79412bb2d2d6647acb818 che ora è privo di senso.
Hai pertanto due possibilità:

1. riportarlo simile a com'era in https://github.com/Borruso/l10n-italy/pull/11/commits/6b03b4d7602bba66419c37682348c528fb0aedae
2. schiacchiarlo con il tuo precedente (https://github.com/OCA/l10n-italy/pull/2515/commits/288a7300a7390e3d9cc09309ab1c30711bd8e1e6)

Per me va bene anche la seconda, next time però fai più attenzione :wink: 
Grazie.

2022-08-24 13:49 UTC, tafaRU approved these changes
Grazie!

2022-08-24 13:52 UTC, tafaRU commented
/ocabot merge patch

2022-08-24 14:09 UTC, merged