imp for issue 2540 and 2072
OCA/l10n-italy pull request #2541
Opened 2021-12-05 09:25 UTC by scigghia

ref #2072 #2540

2021-12-07 09:01 UTC, matteoopenf approved these changes

2021-12-07 13:46 UTC, sergiocorato requested changes
Essendo un port di una modifica fatta da altri, va cherry-picckato il vecchio commit in modo da mantenere il riferimento all'autore originale.

2021-12-08 08:54 UTC, scigghia commented
@sergiocorato dovrei fare cherry pick su questo commit giusto ?

https://github.com/OCA/l10n-italy/pull/2075/commits/1a46728b1d4b9328ccceda98fe65c149d7c1c0b8

2021-12-08 14:15 UTC, sergiocorato commented
> @sergiocorato dovrei fare cherry pick su questo commit giusto ?
> 
> [1a46728](https://github.com/OCA/l10n-italy/commit/1a46728b1d4b9328ccceda98fe65c149d7c1c0b8)

Sì

2021-12-09 10:47 UTC, CiroBoxHub approved these changes

2021-12-09 14:08 UTC, robyf70 approved these changes
LGTM

2021-12-09 14:23 UTC, scigghia commented
/ocabot merge

2021-12-09 14:24 UTC, scigghia commented
/ocabot merge nobump

2021-12-09 14:25 UTC, OpenCode commented
/ocabot merge nobump

2021-12-09 14:35 UTC, sergiocorato approved these changes

2021-12-09 14:51 UTC, merged