[14.0][FIX] l10n_it_fatturapa_in: show if a file contains self invoices
OCA/l10n-italy pull request #2553
Opened 2021-12-10 10:25 UTC by TheMule71

Self invoices should not be re-imported with SdI sends them back.

Fix for #2552

2021-12-10 14:51 UTC, TheMule71 commented
ping @As400it 
hai modo di vedere se la logica va bene? Nel filtro di default, un file XML che contiene delle autofatture non viene fatto vedere. Per adesso visualizzo il flag, anche se sto pensando di toglierlo (nella pratica, l'utente - causa filtro - vedrà sempre e solo il flag non selezionato).

2021-12-16 09:24 UTC, eLBati requested changes
Grazie, riesci ad aggiungere un test?

2021-12-16 10:28 UTC, TheMule71 commented
> Grazie, riesci ad aggiungere un test?

Cosa suggerisci di testare? Il modulo sostanzialmente cambia il filtro di default nella vista.
Forse si potrebbe verificare se il flag `.is_self_invoice` viene correttamente settato in fase di import.

2021-12-16 14:38 UTC, eLBati commented
> Forse si potrebbe verificare se il flag .is_self_invoice viene correttamente settato in fase di import

Esatto, testare cosa succede quando si riceve un XML di quel tipo

2022-01-14 14:16 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Non avendone a portata di mano, ne ho inventato uno

2022-01-14 14:18 UTC, TheMule71 commented
> > Forse si potrebbe verificare se il flag .is_self_invoice viene correttamente settato in fase di import
> 
> Esatto, testare cosa succede quando si riceve un XML di quel tipo

Fatto

2022-01-14 14:20 UTC, tafaRU approved these changes

2022-01-19 11:28 UTC, tafaRU commented
@eLBati puoi aggiornare la tua review?

2022-01-28 09:58 UTC, eLBati requested changes

2022-01-28 09:58 UTC, eLBati commented on l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Per questo file SDI ritorna

```


IT02780790107_11008.xml | 00475 | Per il valore indicato nell’elemento  2.1.1.1 <TipoDocumento> deve essere presente l’elemento 1.4.1.1  <IdFiscaleIVA> del cessionario/committente (i tipi documento TD16,  TD17, TD18, TD19, TD20, TD22 e TD23  prevedono obbligatoriamente la  presenza della partita IVA del cessionario/committente)
```

2022-01-28 17:16 UTC, TheMule71 commented
@eLBati 
dici che con questa modifica lo SdI è più contento?
```
diff --git a/l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml b/l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
index 929ee8d87..a7f408127 100644
--- a/l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
+++ b/l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
@@ -31,7 +31,10 @@
     </CedentePrestatore>
     <CessionarioCommittente>
       <DatiAnagrafici>
-        <CodiceFiscale>03533590174</CodiceFiscale>
+        <IdFiscaleIVA>
+          <IdPaese>IT</IdPaese>
+          <IdCodice>03533590174</IdCodice>
+        </IdFiscaleIVA>
         <Anagrafica>
           <Denominazione>BETA GAMMA</Denominazione>
         </Anagrafica>
```

2022-02-03 15:52 UTC, eLBati approved these changes
LGTM

2022-02-03 16:21 UTC, tafaRU commented
/ocabot merge minor

2022-02-03 16:50 UTC, merged