[14.0][FIX] l10n_it_withholding_tax: set wt amount residual in invoice payment wizard
OCA/l10n-italy pull request #2572
Opened 2021-12-29 10:01 UTC by Borruso

Descrizione del problema o della funzionalità:
#1695 

Co-authored-by: alessandrocamilli <alessandrocamilli@openforce.it>
--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2021-12-29 10:03 UTC, Borruso commented
#2430

2022-02-11 14:37 UTC, TheMule71 requested changes

2022-02-11 14:37 UTC, TheMule71 commented on l10n_it_withholding_tax/models/account.py
> +        if amount_net_pay_residual:
ha senso `float_is_zero`?

2022-03-09 13:21 UTC, tafaRU commented on l10n_it_withholding_tax/models/account.py
> +        if amount_net_pay_residual:
@Borruso potresti rispondere a questo commento? Grazie.

2022-03-09 16:14 UTC, Borruso commented on l10n_it_withholding_tax/models/account.py
> +        if amount_net_pay_residual:
credo che potrebbe andare

2022-04-01 06:43 UTC, zeroincombenze approved these changes
Test effettuato sia con pagamento totale che parziale.

+1

2022-07-28 09:45 UTC, matteoopenf commented
per caso verrà mergiata?

2022-11-28 17:47 UTC, matteoopenf commented
per caso verrà mergiata?

2023-03-03 10:50 UTC, matteoopenf commented
@OCA/local-italy-developers  per caso è possibile mergiare?

2023-03-03 13:27 UTC, tafaRU commented
@TheMule71 potresti aggiornare la tua review?

2023-03-21 09:42 UTC, matteoopenf commented
@TheMule71  perfavore, quando puoi dai un'occhiata?

2023-03-23 11:17 UTC, eLBati commented
@matteoopenf sei hai testato e revisionato, puoi mettere l'approvazione?

2023-03-23 11:17 UTC, matteoopenf approved these changes
la usiamo da molto in produzione

2023-04-14 15:33 UTC, matteoopenf commented
@eLBati  @TheMule71  ci sono novità?

2023-05-03 17:04 UTC, eLBati commented
Per me si può procedere. @TheMule71 per te?

2023-05-18 06:56 UTC, matteoopenf commented
@TheMule71 possiamo procedere al merge?

2023-05-19 07:39 UTC, TheMule71 approved these changes
LGTM

2023-05-19 07:40 UTC, TheMule71 commented
/ocabot merge patch

2023-05-19 08:47 UTC, scigghia approved these changes
LGTM

2023-05-19 10:07 UTC, merged