[FIX] l10n_it_withholding_tax: reconcile payments after reset invoice to draft
OCA/l10n-italy pull request #2673
Opened 2022-02-21 10:23 UTC by Borruso

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-04-01 06:56 UTC, zeroincombenze approved these changes
Con questa branch non ho riscontrato il problema che invece avevo rilevato con la review #2572

2022-05-13 13:14 UTC, tafaRU commented
@Borruso puoi gestire i conflitti?

2022-08-22 07:51 UTC, francescapenso approved these changes

2022-08-25 07:47 UTC, are-agilebg approved these changes

2022-08-26 08:12 UTC, francescapenso commented
merge?

2022-09-14 15:56 UTC, SirTakobi requested changes
Grazie della PR!
Ho fatto diverse prove (in locale perché la PR non ha runboat) e c'è qualcosa che non mi torna, qui sotto i passi che ho fatto:

1. Creo una fattura fornitore da 10 + 2,2 con ritenuta del 10% e la confermo, i totali della fattura sono:
    ![image](https://user-images.githubusercontent.com/101628000/190199989-f95090fe-f4c5-487b-9e6e-98708140eb9c.png)
3. Creo un pagamento da 11,2 (nel popup lascio Differenza di pagamento = Tieni aperta) e la fattura risulta correttamente pagata.
4. Porto in bozza e riconfermo, agganciando i debiti in sospeso creati dal pagamento precedente
5. I totali della fattura ora sono
    ![image](https://user-images.githubusercontent.com/101628000/190200965-45c09ae4-6ac1-4db6-b47f-be7e1ef5d4bc.png)

Come mai ci sono dei pagamenti extra? È normale che l'importo dovuto sia negativo?

Ho provato gli stessi passi in runboat e in effetti il comportamento è simile: i totali alla fine sono 
![image](https://user-images.githubusercontent.com/101628000/190201966-69f1d557-1738-473f-8e09-9ec9a703cf59.png)
In pratica in runboat vengono generati 3 pagamenti da 1€ per le ritenute, mentre in questa PR vengono generati 4 pagamenti: uno da 1€, uno da 0,99€ e due da 0,9€.
Puoi verificare?

2023-11-08 13:43 UTC, matteoopenf commented
@Borruso  hai chiuso in favore di altro o solo chiuso?

2023-11-10 21:40 UTC, francescapenso commented
è da fare review?

2024-02-23 10:28 UTC, francesco-ooops commented
@Borruso ci sono differenze rispetto alla soluzione per v16 mergiata in https://github.com/OCA/l10n-italy/pull/3707 ?

2024-02-26 09:14 UTC, Borruso commented
> @Borruso ci sono differenze rispetto alla soluzione per v16 mergiata in #3707 ?

non ci sono differenze

2024-02-26 09:40 UTC, francesco-ooops commented
@eLBati si può mergiare anche questa dunque?

2024-02-26 10:32 UTC, merged