[12.0][IMP] intrastat 2022
OCA/l10n-italy pull request #2686
Opened 2022-02-25 08:52 UTC by sergiocorato

Descrizione del problema o della funzionalità:

Comportamento attuale prima di questa PR:

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-02-25 08:57 UTC, eLBati commented
Sostituisce quindi la https://github.com/OCA/l10n-italy/pull/2664 ?

2022-02-25 09:00 UTC, sergiocorato commented
> Sostituisce quindi la #2664 ?

No, in base a quello che si è detto in chat la #2664 va avanti per la parte base (non statement). Ho solo caricato il codice proposto da Antonio, più o meno ripulito, ma poi Antonio mi pare dicesse che lo farà mettere in ordine dal loro sviluppatore.

2022-02-25 09:30 UTC, eLBati commented
Noto che questa PR attualmente è uguale alla https://github.com/OCA/l10n-italy/pull/2664

In chiamata si diceva comunque di fare una unica PR con le modifiche basilari, per entrambi i moduli, per supportare il nuovo formato

2022-02-25 13:41 UTC, eLBati requested changes

2022-02-25 13:41 UTC, eLBati commented on l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
> +        if self.statement_id.exclude_optional_column_sect_1_3:
Il campo `exclude_optional_column_sect_1_3` non esiste

2022-02-25 13:45 UTC, eLBati commented
@zeroincombenze riesci a dare un'occhiata a queste modifiche e dirci cosa ci sarebbe da fare per poter fare il merge?
Grazie

2022-02-28 15:37 UTC, eLBati requested changes

2022-02-28 15:39 UTC, eLBati commented
Propongo intanto queste modifiche https://github.com/sergiocorato/l10n-italy/pull/2

2022-02-28 15:56 UTC, sergiocorato commented on l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
> +                _("Missing payment method on 'Purchases - Section 4'"))
Da quanto leggo nelle specifiche, non sembrano campi sempre obbligatori. Non pare comunque una modifica legata alle nuove regole per il 2022, se è una modifica pre-esistente è meglio spostarla su una PR separata.

2022-02-28 15:56 UTC, sergiocorato commented on l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
> +                _("Missing payment method on 'Sales - Section 4'"))
Da quanto leggo nelle specifiche, non sembrano campi sempre obbligatori. Non pare comunque una modifica legata alle nuove regole per il 2022, se è una modifica pre-esistente è meglio spostarla su una PR separata.

2022-02-28 15:56 UTC, sergiocorato commented
> Propongo intanto queste modifiche [sergiocorato#2](https://github.com/sergiocorato/l10n-italy/pull/2)

Le applico

2022-03-01 11:29 UTC, eLBati commented
Anche https://github.com/sergiocorato/l10n-italy/pull/3

2022-03-03 17:49 UTC, zeroincombenze commented
Ciao,
scusatemi ma questa settimana non sono riuscito a fornire risposte.
Ora gli do un'occhiata

2022-03-07 08:31 UTC, eLBati commented
https://github.com/OCA/l10n-italy/pull/2690#issuecomment-1060325106

2022-03-07 08:42 UTC, zeroincombenze commented
eLBati, stai lavorando su l10n_it_intrastat_statement o posso proseguire io?

2022-03-07 08:48 UTC, eLBati commented
@zeroincombenze prosegui pure grazie

2022-03-07 11:25 UTC, eLBati commented
Aperto anche https://github.com/sergiocorato/l10n-italy/pull/5

2022-03-07 13:28 UTC, eLBati commented
@zeroincombenze puoi dare un'occhiata ai test automatici?

2022-03-07 18:00 UTC, zeroincombenze commented
Cosa c'è che non va?

2022-03-12 10:00 UTC, eLBati approved these changes
Penso che intanto si possa procedere con questa

2022-03-12 10:33 UTC, zeroincombenze commented
Ottimo. Grazie

2022-03-16 13:40 UTC, eLBati commented
/ocabot merge minor

2022-03-18 08:37 UTC, eLBati commented
/ocabot merge minor

2022-03-18 09:58 UTC, merged