[12.0][FIX] l10n_it_fatturapa_in, skip registered invoice in _compute_xml_data
OCA/l10n-italy pull request #2705
Opened 2022-03-17 15:33 UTC by GSLabIt

Descrizione del problema o della funzionalità:

Comportamento attuale prima di questa PR:

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-03-18 07:43 UTC, tafaRU approved these changes

2022-03-18 07:45 UTC, tafaRU requested changes
Revisione del codice :+1: 
Occorre però sistemare Travis.

2022-03-18 09:09 UTC, GSLabIt commented
> Revisione del codice 👍
> Occorre però sistemare Travis.

Certo, ma non credo dipendano da questa pr ..per scrupolo in locale ho eliminato il codice e l'errore lo prendo uguale ..

2022-03-18 09:36 UTC, GSLabIt commented
Ho fatto delle prove su runbot e ci sono delle differenze  nell'import con dati minimi:
<img width="1268" alt="Schermata 2022-03-18 alle 10 20 56" src="https://user-images.githubusercontent.com/11652845/158977831-35677dbe-8c39-44f1-8ad5-1fa99218855c.png">

stesso import con il massimo dei dettagli:

<img width="1275" alt="Schermata 2022-03-18 alle 10 21 42" src="https://user-images.githubusercontent.com/11652845/158977894-6cacb79b-f2b1-4206-81e1-f51731e7463e.png">

Nel primo caso non ci sono neppure i totali, è corretto?

Ho provato anche un altro import e su dati minimali inserisce una riga fattura:

dettagli max: 
<img width="1278" alt="Schermata 2022-03-18 alle 10 28 42" src="https://user-images.githubusercontent.com/11652845/158978103-9d852289-888c-4782-96fc-67ba1963e6e1.png">

dettagli min:

<img width="1275" alt="Schermata 2022-03-18 alle 10 29 16" src="https://user-images.githubusercontent.com/11652845/158978126-e86ad62a-bc7f-4652-8dbb-91a0defd22f6.png">

@tafaRU @sergiocorato @eLBati @TheMule71 qualcuno ha idea del problema? perché non pare dipendere da questa pr.

2022-03-18 10:47 UTC, sergiocorato commented
> Ho fatto delle prove su runbot e ci sono delle differenze nell'import con dati minimi: <img alt="Schermata 2022-03-18 alle 10 20 56" width="1268" src="https://user-images.githubusercontent.com/11652845/158977831-35677dbe-8c39-44f1-8ad5-1fa99218855c.png">
> 
> stesso import con il massimo dei dettagli:
> 
> <img alt="Schermata 2022-03-18 alle 10 21 42" width="1275" src="https://user-images.githubusercontent.com/11652845/158977894-6cacb79b-f2b1-4206-81e1-f51731e7463e.png">
> 
> Nel primo caso non ci sono neppure i totali, è corretto?
> 
> Ho provato anche un altro import e su dati minimali inserisce una riga fattura:
> 
> dettagli max: <img alt="Schermata 2022-03-18 alle 10 28 42" width="1278" src="https://user-images.githubusercontent.com/11652845/158978103-9d852289-888c-4782-96fc-67ba1963e6e1.png">
> 
> dettagli min:
> 
> <img alt="Schermata 2022-03-18 alle 10 29 16" width="1275" src="https://user-images.githubusercontent.com/11652845/158978126-e86ad62a-bc7f-4652-8dbb-91a0defd22f6.png">
> 
> @tafaRU @sergiocorato @eLBati @TheMule71 qualcuno ha idea del problema? perché non pare dipendere da questa pr ma più dall'import con dati minimi.

Hai fatto una prova in locale per vedere se non dà errori senza questa PR?

2022-03-18 10:48 UTC, GSLabIt commented
@sergiocorato si provato, tirato via il codice, stessi errori.

2022-03-18 11:17 UTC, tafaRU commented
@GSLabIt la ultima build su `12.0` https://app.travis-ci.com/github/OCA/l10n-italy/builds/247365802 é :green_circle: 
Hai provato in locale a riprodurre cosa fa Travis?

1. [Creating instance](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L822)
2. [Testing](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L1925)

2022-03-18 11:19 UTC, GSLabIt commented
> @GSLabIt la ultima build su `12.0` https://app.travis-ci.com/github/OCA/l10n-italy/builds/247365802 è 🟢 Hai provato in locale a riprodurre cosa fa Travis?
> 
> 1. [Creating instance](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L822)
> 2. [Testing](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L1925)

Si ho provato a togliere il codice ed eseguire i test e mi da lo stesso errore. Ora faccio un'ulteriore test sul branch 12.0 e vedo.

2022-03-18 11:57 UTC, GSLabIt commented
> @GSLabIt la ultima build su `12.0` https://app.travis-ci.com/github/OCA/l10n-italy/builds/247365802 è 🟢 Hai provato in locale a riprodurre cosa fa Travis?
> 
> 1. [Creating instance](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L822)
> 2. [Testing](https://app.travis-ci.com/github/OCA/l10n-italy/jobs/563727939#L1925)

Credo di aver risolto, per un qualche motivo, che io non ho capito, non gli piace avere dei valori di default prima che vada a leggere il file ..ho risolto con un `else` 😬

2022-03-18 13:50 UTC, GSLabIt commented
@sergiocorato @tafaRU finalmente travis verde.. se/quando avete 2 minuti.. review e merge?

2022-03-18 13:54 UTC, sergiocorato approved these changes

2022-03-18 16:32 UTC, tafaRU approved these changes

2022-03-20 17:37 UTC, sergiocorato commented
/ocabot merge patch

2022-03-20 19:05 UTC, merged

2022-04-04 04:59 UTC, eLBati commented
Ma quindi se `_compute_xml_data` venisse eseguito su un XML importato, i campi `xml_supplier_id` etc verrebbero svuotati?
Rendendo praticamente inutil il metodo `recompute_xml_fields`?

2022-04-04 05:36 UTC, eLBati commented
Anche
https://github.com/OCA/l10n-italy/issues/2699#issuecomment-1065867986
e
https://github.com/OCA/l10n-italy/issues/2716#issuecomment-1085540760

2022-04-04 07:11 UTC, GSLabIt commented
> Ma quindi se `_compute_xml_data` venisse eseguito su un XML importato, i campi `xml_supplier_id` etc verrebbero svuotati?
> 

Si, in quel caso sarebbero svuotati. Purtroppo ho finito le idee, se vuoi provare a fare un fix, welcome! L'unica cosa che mi vienevib mente è di nascondere il pulsante x ricalcolare i dati se la fattura è registrata. 

I suggerimenti di @TheMule71 purtropo non hanno portato ad alcuna soluziome, perché importando lo stesso fibe manualmente funziona correttamente. Il problema si verifica solo al''update del modulo.

2022-04-05 10:36 UTC, TheMule71 commented
> I suggerimenti di @TheMule71 purtropo non hanno portato ad alcuna soluziome, perché importando lo stesso file manualmente funziona correttamente. Il problema si verifica solo al''update del modulo.

Io non ho molto tempo di guardarci in settimana. Ma il dato è molto interessante. È un errore di parsing XML (da lxml) sull'url del namespace se non ho visto male, che contiene uno spazio.

Quiindi succede una cosa strana, l'XML viene sistemato internamente in un caso e non nell'altro. La cosa può avere senso, se la fix avviene in fase di caricamento, ma è stata introdotta di recente.

Magari invece in passato si usava un parser più lassista.

Comunque la cosa giusta è fare una migration che corregge gli XML salvati su db, oppure introdurre la logica che permetta a _compute_xml_data() di fare il parsing corretto.


Hai modo di verificare che l'allegato presente nel DB la cui migrazione fallisce e l'allegato presente nel DB dopo aver caricato a mano l'XML siano diversi?

2022-04-06 08:07 UTC, eLBati commented
Ho comunque fatto https://github.com/OCA/l10n-italy/pull/2748