[14.0 mig l10n it pos fatturapa
OCA/l10n-italy pull request #2739
Opened 2022-03-30 16:56 UTC by robyf70

2022-04-13 08:02 UTC, robyf70 commented
@eLBati @francesco-ooops Potete fare un review anche se ho visto che fallisce a causa di ``ERROR: TestReverseCharge.test_intra_EU_zero_total``

2022-04-13 08:29 UTC, francesco-ooops commented
@robyf70 crea nuovo cliente > abilita e-fattura > mancano i controlli CF/P.IVA e indirizzo al salvataggio

2022-04-13 08:48 UTC, robyf70 commented
> @robyf70 crea nuovo cliente > abilita e-fattura > mancano i controlli CF/P.IVA e indirizzo al salvataggio

Non ho capito che tipo di controlli intendi. Che sia valorizzato CF o P.IVA?

2022-04-13 09:03 UTC, francesco-ooops commented
> > @robyf70 crea nuovo cliente > abilita e-fattura > mancano i controlli CF/P.IVA e indirizzo al salvataggio
> 
> Non ho capito che tipo di controlli intendi. Che sia valorizzato CF o P.IVA?

esatto, stessa cosa per per indirizzo, come avviene sulla 12 e come avviene nel modello del contatto

2022-04-13 09:08 UTC, robyf70 commented
> > > @robyf70 crea nuovo cliente > abilita e-fattura > mancano i controlli CF/P.IVA e indirizzo al salvataggio
> > 
> > 
> > Non ho capito che tipo di controlli intendi. Che sia valorizzato CF o P.IVA?
> 
> esatto, stessa cosa per per indirizzo, come avviene sulla 12 e come avviene nel modello del contatto

Ho controllato la 12, ma nel codice non c'è questo tipo di controllo

2022-04-13 10:05 UTC, robyf70 commented
Tra l'altro pensavo di aggiungere il check di validazione della partita iva

2022-04-13 13:50 UTC, francesco-ooops commented
@robyf70 da quale modulo viene la funzione di validazione delle P.IVA? ho notato che è attiva anche se il flag "Verifica delle partite IVA con il servizio europeo VIES" è disattivato

2022-04-13 13:54 UTC, robyf70 commented
quello ``VIES`` è un'estensione dello standard.

2022-04-20 08:34 UTC, francesco-ooops requested changes
questa PR sulla sx, v.12 sulla dx: https://recordit.co/nsI10CjCDl

creo nuovo cliente > abilito e-fattura > salvo

in v.12, se non c'è P.IVA o CF, ricevo messaggio di errore
in questa PR no

2022-04-26 10:21 UTC, francesco-ooops commented
@robyf70 riesci a metterci le mani a breve?

2022-04-26 10:39 UTC, robyf70 commented
> @robyf70 riesci a metterci le mani a breve?

ho una modifica che fà il controllo della partita iva direttamente da JS, vedo se nel pomeriggio riesco a rifare i tutti i check

2022-04-26 11:39 UTC, TheMule71 commented
> > Ho controllato la 12, ma nel codice non c'è questo tipo di controllo
> 
> Quello che posso testare è che se creo un contatto e abilito il flag fattura elettronica nel modello contatti devo inserire CF/P.IVA e indirizzo, mentre nel POS questo vincolo non c'è: https://recordit.co/fnp8TcFxet

Credo che il codice sia questo:
https://github.com/OCA/l10n-italy/blob/4c0218b51ff288a8932f25b6d21eba19069f74c2/l10n_it_fatturapa/models/partner.py#L127-L134

2022-05-19 15:43 UTC, francesco-ooops commented
@robyf70 ok per te se portiamo avanti il lavoro fatto fin qui?

2022-05-19 15:45 UTC, robyf70 commented
> @robyf70 ok per te se portiamo avanti il lavoro fatto fin qui?

Per me ok

2023-07-14 09:21 UTC, francesco-ooops commented
@OCA/local-italy-maintainers si può chiudere

2023-07-14 10:58 UTC, tafaRU commented
Chiudo in favore di https://github.com/OCA/l10n-italy/pull/3482

2023-07-14 10:58 UTC, closed without merging