[REF] l10n_it_central_journal: new printing method
OCA/l10n-italy pull request #2754
Opened 2022-04-08 16:12 UTC by Borruso

2022-04-13 20:37 UTC, andreampiovesana commented
perchè non usate xlsxwriter?
modulo OCA con risultato equivalente?

2022-04-14 07:02 UTC, matteoopenf commented
> perchè non usate xlsxwriter? modulo OCA con risultato equivalente?

credo perchè reportlab è in Odoo standard. Però aspettiamo la sua risposta

2022-04-15 07:10 UTC, Borruso commented
> perchè non usate xlsxwriter? modulo OCA con risultato equivalente?

si potrebbe optare come soluzione, ma per essere lineari con quello che c'è ora ho optato alla generazione di un PDF

2022-04-20 08:26 UTC, GSLabIt commented
@Borruso si riesce ad aggiungere un'opzione per la stampa delle fatture raggruppate per conto? quello che nella 12.0 veniva fatto con [account_invoice_group_line](https://github.com/OCA/account-invoicing/tree/12.0/account_group_invoice_line) ma ora `account.invoice` non esiste più e raggruppare su `account.move` non mi pare possibile.

2022-04-22 08:01 UTC, As400it commented
> @Borruso si riesce ad aggiungere un'opzione per la stampa delle fatture raggruppate per conto? quello che nella 12.0 veniva fatto con [account_invoice_group_line](https://github.com/OCA/account-invoicing/tree/12.0/account_group_invoice_line) ma ora `account.invoice` non esiste più e raggruppare su `account.move` non mi pare possibile.

Ciao per la V12.0 c'è il modulo che raggruppa le scritture contabili . Comunque, come da call del venerdi mattina,  aggiungiamo un' opzione per raggruppare o meno per conto.

2022-04-22 08:21 UTC, GSLabIt commented
> 
> 
> 
> > @Borruso si riesce ad aggiungere un'opzione per la stampa delle fatture raggruppate per conto? quello che nella 12.0 veniva fatto con [account_invoice_group_line](https://github.com/OCA/account-invoicing/tree/12.0/account_group_invoice_line) ma ora `account.invoice` non esiste più e raggruppare su `account.move` non mi pare possibile.
> 
> Ciao per la V12.0 c'è il modulo che raggruppa le scritture contabili . Comunque, come da call del venerdi mattina,  aggiungiamo un' opzione per raggruppare o meno per conto.  

Si, purtroppo per la 14 il modulo non è stato portato perché non esiste più `account.invoice`. L'opzione per raggruppare andrebbe benissimo.

2022-05-27 08:03 UTC, stevech091 approved these changes
Function review ok

2022-05-27 08:15 UTC, Borruso commented
> Si, purtroppo per la 14 il modulo non è stato portato perché non esiste più `account.invoice`. L'opzione per raggruppare andrebbe benissimo.

Potresti provare la PR @GSLabIt

2022-05-27 15:27 UTC, GSLabIt commented
> > Si, purtroppo per la 14 il modulo non è stato portato perché non esiste più `account.invoice`. L'opzione per raggruppare andrebbe benissimo.
> 
> Potresti provare la PR @GSLabIt

Sembrerebbe ok.

2022-05-28 13:26 UTC, elvise approved these changes
@Borruso @GSLabIt 
Perfetto!

2022-06-07 10:32 UTC, stefano-ooops approved these changes
TEST EFFETTUATI OK

2022-07-08 16:05 UTC, TheMule71 requested changes

2022-07-29 15:36 UTC, elvise commented
@TheMule71 merge ?

2022-08-11 12:18 UTC, elvise commented
@TheMule71 vorremo portare questo modulo alla 14, credi che sia pronto per il merge ?

2022-08-24 17:09 UTC, francesco-ooops commented on l10n_it_central_journal/wizard/print_giornale.py
> +        return move_name
@Borruso questa richiesta è stata applicata?

2022-08-26 06:58 UTC, TheMule71 commented
L'avevamo guardato insieme a @Borruso, c'erano cosette da cambiare, poi da allora non ci siamo più riincrociati. Appena riusciamo a guardarlo di nuovo, aggiorno lo stato, sia per il merge in 12 che per il porting verso 14.

2022-08-26 14:06 UTC, TheMule71 approved these changes
LGTM

2022-09-02 07:27 UTC, As400it approved these changes
Go 

test funzionali  OK .

2022-09-05 10:59 UTC, francesco-ooops commented
@OCA/local-italy-maintainers si può mergiare?

2022-09-05 12:32 UTC, tafaRU commented
@Borruso questa si può chiudere in favore di https://github.com/OCA/l10n-italy/pull/2927?

2022-09-06 09:48 UTC, TheMule71 commented
Per chiarire: la #2927 nasce perché questa modifica un modulo funzionante in 12.0, alterandone il comportamento, senza possbilità per l'utente di tornare alla vecchia stampa stile q-web, pre PR.  Al di là dell'estetica diversa, e di potenziali comportamenti diversi, c'è da considerare che qualsiasi customizzazione locale del qweb verrebbe invalidata in modo irreversibile e senza un migration path - se non quello di passare a reportlab anche per la customizzazione.

La #2927 è lo stesso codice spostato in un modulo a parte, in modo che chi vuole tenere le vecchie stampe lo possa fare. Per la 14 manterremo i due moduli per la 16 si vedrà.

2022-09-12 10:47 UTC, francesco-ooops commented
@TheMule71 a seguito di https://github.com/OCA/l10n-italy/pull/2927#issuecomment-1239186121 , c'è ancora lavoro da fare in questa PR o è mergiabile così com'è?

2022-09-16 08:41 UTC, TheMule71 commented
Chiudo in favore di #2927.

2023-08-25 09:00 UTC, closed without merging