[FIX] - fix tax_exigibility
OCA/l10n-italy pull request #2799
Opened 2022-05-13 12:52 UTC by AlessandroSkab

Ci siamo accorti che se provo a generare il report della Liquidazione IVA con periodo fiscale avente un'imposta che ha delle imposte figlie con a loro volta il campo vat_statement_account_id impostato, viene fuori un errore a causa della mancanza di account_id all'interno del modello account.tax.
Con il passaggio alla versione 13.0 il campo account_id di account.tax è stato rimosso. Seguendo le linee guida dettate dalla migrazione alla versione 13.0 di OCA/OpenUpgrade abbiamo risolto il problema facendo il controllo, precedente fatto su account_id, sul campo tax_exigibility.  

Documentazione seguita:
https://github.com/OCA/OpenUpgrade/blob/420ac0f79fa0cc216500d73df60741b4618a304b/addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt#L455-L461

2022-05-13 13:15 UTC, valeriobelcastro approved these changes

2022-05-17 13:14 UTC, tafaRU requested changes

2022-05-17 13:14 UTC, tafaRU commented on l10n_it_account/models/account_tax.py
> +                if child.tax_exigibility == "on_invoice":
Sulla base di come `account_id` è stato migrato in OpenUpgrade (rif. [link](https://github.com/OCA/OpenUpgrade/blob/420ac0f79fa0cc216500d73df60741b4618a304b/addons/account/migrations/13.0.1.1/openupgrade_analysis_work.txt#L455-L461)) ritengo che per rendere il controllo più conforme all’originale sia opportuno controllare:

`if account_ids` dove:

```
            account_ids = (
                child.mapped("invoice_repartition_line_ids.account_id")
                | child.mapped("refund_repartition_line_ids.account_id")
            ).ids

Cosa ne pensi?

2022-06-13 10:14 UTC, tafaRU commented on l10n_it_account/models/account_tax.py
> +                if child.tax_exigibility == "on_invoice":
@AlessandroSkab hai visto https://github.com/OCA/l10n-italy/pull/2799#discussion_r874799014 ?

2022-09-12 12:54 UTC, tafaRU commented
Chiudo a favore si https://github.com/OCA/l10n-italy/pull/2931

2022-09-12 12:54 UTC, closed without merging