[14.0] [fix] l10n_it_reverse_charge, rc flag in move line
OCA/l10n-italy pull request #2813
Opened 2022-05-24 10:29 UTC by GSLabIt

fix https://github.com/OCA/l10n-italy/issues/2812

2022-06-06 15:22 UTC, stefano-ooops approved these changes
test funzionale ok!

2022-06-29 09:52 UTC, TheMule71 requested changes

2022-06-29 09:52 UTC, TheMule71 commented on l10n_it_reverse_charge/models/account_move.py
> +                line.rc = bool(line.move_id.fiscal_position_id.rc_type_id)
Non succede, ma tecnicamente dipende anche da `move_id.move_type`, attraverso la `.is_purchase_document()`.

Dipende anche dal valore di `move_id.fiscal_position_id.rc_type_id`

2022-06-29 09:53 UTC, TheMule71 requested changes

2022-06-29 09:53 UTC, TheMule71 commented on l10n_it_fatturapa_in_rc/models/account_invoice.py
> +    @api.depends("move_id", "move_id.fiscal_position_id", "tax_ids")
Vd. commento precendente.

2022-09-08 17:08 UTC, GSLabIt commented on l10n_it_reverse_charge/models/account_move.py
> +                line.rc = bool(line.move_id.fiscal_position_id.rc_type_id)
ok, grazie

2022-09-08 17:09 UTC, GSLabIt commented on l10n_it_fatturapa_in_rc/models/account_invoice.py
> +    @api.depends("move_id", "move_id.fiscal_position_id", "tax_ids")
ok, grazie

2022-09-09 07:36 UTC, vincenzoterzulli commented
@TheMule71 hai visto la issue #2870 e quanto fatto su v8?

2022-10-05 10:02 UTC, elvise commented
@TheMule71 possiamo mergiare ?

2022-10-10 16:58 UTC, elvise commented
@TheMule71 gentle remind :)

2022-10-11 11:15 UTC, TheMule71 requested changes

2022-10-11 11:15 UTC, TheMule71 commented on l10n_it_reverse_charge/models/account_move.py
> +    rc = fields.Boolean("RC", compute="_compute_rc_flag", store=True, readonly=False)
La _compute dovrebbe assegnare sempre un valore a tutte le istanze, essendo stored dovrebbe bastare un default qui.

> Check that all "compute" methods of non-stored computed fields assign a value in any case to the field, even if it is a falsy one. Or if they are stored, at least they have an initialization value (a default for example). You can use the expression self.<field> = ... at the beginning of the compute for pre-assigning a value to all records.

2022-10-14 08:29 UTC, GSLabIt commented on l10n_it_reverse_charge/models/account_move.py
> +    rc = fields.Boolean("RC", compute="_compute_rc_flag", store=True, readonly=False)
fatto

2022-10-14 09:21 UTC, TheMule71 reviewed
LGTM

(oops)

2022-10-14 09:27 UTC, TheMule71 approved these changes
LGTM

2022-10-14 09:28 UTC, TheMule71 commented
/ocabot merge patch

2022-10-14 09:38 UTC, merged