[14.0][FIX] l10n_it_instrastat, account move: fix subject to intrastat on partner change
OCA/l10n-italy pull request #2835
Opened 2022-06-15 15:19 UTC by GSLabIt

2022-09-08 16:45 UTC, matteoopenf commented on l10n_it_intrastat/models/purchase_order.py
> +class SaleOrder(models.Model):
credo che qua volevi scrivere PurchaseOrder

2022-09-08 16:47 UTC, GSLabIt commented on l10n_it_intrastat/models/purchase_order.py
> +class SaleOrder(models.Model):
si, grazie. Modifico

2022-10-05 10:08 UTC, francesco-ooops commented
@matteoopenf puoi ri-testare?

2022-10-05 10:18 UTC, matteoopenf commented
> @matteoopenf puoi ri-testare?

non conosco il contesto puoi dirmelo?

avevo solo fatto un commento per un banale errore.
Posso approvare solo a livello di review non so cosa testare esattamente

2022-10-05 10:50 UTC, TheMule71 commented
La parte purchase order in realtà non c'entra col titolo, giusto?

Mi chiedo se vada fixata in quel punto, stai creando la fattura da po, la fiscal position è specificata e prevede l'intrastat, dovrebbe essere la create della fattura a gestire la cosa, non chi la chiama. Mi sfugge qualcosa?

2022-10-05 12:57 UTC, GSLabIt commented
> La parte purchase order in realtà non c'entra col titolo, giusto?
> 
> Mi chiedo se vada fixata in quel punto, stai creando la fattura da po, la fiscal position è specificata e prevede l'intrastat, dovrebbe essere la create della fattura a gestire la cosa, non chi la chiama. Mi sfugge qualcosa?

No, è stato aggiunto successivamente. 

Va fixata allo stesso modo di:

https://github.com/OCA/l10n-italy/blob/c88ab7620f2c7eb539bb9eaae1763358d09ae5d3/l10n_it_intrastat/models/sale_order.py#L7-L15

2022-10-05 13:17 UTC, matteoopenf commented
> > La parte purchase order in realtà non c'entra col titolo, giusto?
> > Mi chiedo se vada fixata in quel punto, stai creando la fattura da po, la fiscal position è specificata e prevede l'intrastat, dovrebbe essere la create della fattura a gestire la cosa, non chi la chiama. Mi sfugge qualcosa?
> 
> No, è stato aggiunto successivamente.
> 
> Va fixata allo stesso modo di:
> 
> https://github.com/OCA/l10n-italy/blob/c88ab7620f2c7eb539bb9eaae1763358d09ae5d3/l10n_it_intrastat/models/sale_order.py#L7-L15

scusa ma dove hai linkato lo fa nel sale.order e tu lo hai fatto nel purchase.order o sbaglio a capire il senso?

2022-10-05 13:18 UTC, GSLabIt commented
> > > La parte purchase order in realtà non c'entra col titolo, giusto?
> > > Mi chiedo se vada fixata in quel punto, stai creando la fattura da po, la fiscal position è specificata e prevede l'intrastat, dovrebbe essere la create della fattura a gestire la cosa, non chi la chiama. Mi sfugge qualcosa?
> > 
> > 
> > No, è stato aggiunto successivamente.
> > Va fixata allo stesso modo di:
> > https://github.com/OCA/l10n-italy/blob/c88ab7620f2c7eb539bb9eaae1763358d09ae5d3/l10n_it_intrastat/models/sale_order.py#L7-L15
> 
> scusa ma dove hai linkato lo fa nel sale.order e tu lo hai fatto nel purchase.order o sbaglio a capire il senso?

Esatto, il `purchase.order` ha lo stesso problema del `sale.order`

2022-10-05 13:22 UTC, matteoopenf commented
> > > > La parte purchase order in realtà non c'entra col titolo, giusto?
> > > > Mi chiedo se vada fixata in quel punto, stai creando la fattura da po, la fiscal position è specificata e prevede l'intrastat, dovrebbe essere la create della fattura a gestire la cosa, non chi la chiama. Mi sfugge qualcosa?
> > > 
> > > 
> > > No, è stato aggiunto successivamente.
> > > Va fixata allo stesso modo di:
> > > https://github.com/OCA/l10n-italy/blob/c88ab7620f2c7eb539bb9eaae1763358d09ae5d3/l10n_it_intrastat/models/sale_order.py#L7-L15
> > 
> > 
> > scusa ma dove hai linkato lo fa nel sale.order e tu lo hai fatto nel purchase.order o sbaglio a capire il senso?
> 
> Esatto, il `purchase.order` ha lo stesso problema del `sale.order`

allora si ha senso

2022-10-06 06:51 UTC, stefano-ooops approved these changes

2022-10-06 07:28 UTC, TheMule71 commented
> Esatto, il `purchase.order` ha lo stesso problema del `sale.order`

Appunto, la mia domanda era esattamente quella: ha senso che siano i chiamanti a fixare il problema?  non avrebbe più senso che fosse la `create()` della fattura a farlo?

Chiunque stia creando una fattura ha quel problema. Se la fiscal position prevede intrastat, deve estrarla e passarla nei valori. 

Per me ha poco senso, la `create()` della fattura dovrebbe implementare quella logica. Sale order e purchase order sono solo due dei modelli che possono creare una fattura. Ok, coprono la stragrande maggioranza dei casi, ma non vedo controindicazioni a spostare quella logica nella `create()` eliminandola dalle `_prepare_invoice()`.

2022-10-13 08:19 UTC, TheMule71 commented
Per me la domanda è un altra: ha senso crearte una fattura con fiscal_position col flag instrastat == True ma la fattura è intrastat = False di default?

Da quello che vedo:
https://github.com/OCA/l10n-italy/blob/29dbd9fdb507cdcbecf64e301251791291222e9b/l10n_it_intrastat/models/account.py#L275-L279
https://github.com/OCA/l10n-italy/blob/29dbd9fdb507cdcbecf64e301251791291222e9b/l10n_it_intrastat/models/account.py#L289-L291
per me no.

Creando una fattura in bozza, `intrastat` viene copiata da quella della fiscal_position. Siccome è un `on_change`, la cosa non succede quando la creazione avviene da codice, e per me questo è un bug della `create()`.   Se tra i `values` non viene passata esplicitamente la chiave `intrastat` la dovrebbe copiare da `fiscal_position_id.intrastat`, per implementare la stessa logica.

Quello della `sale_order.py` è un workaround ad un bug che in realtà è nella `create()` di `account.move`. Per me il codice andrebbe tolto da `sale_order.py` e spostato nella create di `account.move`, invece di duplicarlo in `purchase.order`.

2022-10-14 10:29 UTC, GSLabIt commented
> Per me la domanda è un altra: ha senso crearte una fattura con fiscal_position col flag instrastat == True ma la fattura è intrastat = False di default?
> 
> Da quello che vedo:
> 
> https://github.com/OCA/l10n-italy/blob/29dbd9fdb507cdcbecf64e301251791291222e9b/l10n_it_intrastat/models/account.py#L275-L279
> 
> 
> https://github.com/OCA/l10n-italy/blob/29dbd9fdb507cdcbecf64e301251791291222e9b/l10n_it_intrastat/models/account.py#L289-L291
> 
> 
> per me no.
> Creando una fattura in bozza, `intrastat` viene copiata da quella della fiscal_position. Siccome è un `on_change`, la cosa non succede quando la creazione avviene da codice, e per me questo è un bug della `create()`. Se tra i `values` non viene passata esplicitamente la chiave `intrastat` la dovrebbe copiare da `fiscal_position_id.intrastat`, per implementare la stessa logica.
> 
> Quello della `sale_order.py` è un workaround ad un bug che in realtà è nella `create()` di `account.move`. Per me il codice andrebbe tolto da `sale_order.py` e spostato nella create di `account.move`, invece di duplicarlo in `purchase.order`.

@TheMule71 vedi se può andar bene

2022-10-14 14:50 UTC, GSLabIt commented on l10n_it_intrastat/models/account.py
> +        vals_list = values if isinstance(values, list) else [values]
grazie x la dritta, mi era sfuggito 🙆🏻‍♂️

2022-10-14 16:26 UTC, GSLabIt commented on l10n_it_intrastat/models/account.py
> +        vals_list = values if isinstance(values, list) else [values]
@TheMule71 a questo punto si potrebbero anche eliminare i test per sale e purchase, evitando di averli come dipendenze. Cosa ne pensi?

2022-10-19 14:30 UTC, francesco-ooops commented
@TheMule71 buona per il merge?

2022-10-20 07:03 UTC, stefano-ooops reviewed
ho effettuato nuovi test ma ancora la creazione della fattura da acquisti non porta il flag RC, allego video[
](https://recordit.co/MYEpjxs82u)

2022-10-20 07:17 UTC, GSLabIt commented
> ho effettuato nuovi test ma ancora la creazione della fattura da acquisti non porta il flag RC, allego video

Questa è una pr per il flag `intrastat` non per il flag `RC`

2022-10-20 07:28 UTC, stefano-ooops commented
> > ho effettuato nuovi test ma ancora la creazione della fattura da acquisti non porta il flag RC, allego video
> 
> Questa è una pr per il flag `intrastat` non per il flag `RC`

ok.

2022-10-20 15:36 UTC, TheMule71 commented on l10n_it_intrastat/models/account.py
> +        vals_list = values if isinstance(values, list) else [values]
> @TheMule71 a questo punto si potrebbero anche eliminare i test per sale e purchase, evitando di averli come dipendenze. Cosa ne pensi?

Direi di si se le dipendenze ci sono solo per i test.

2022-10-21 08:23 UTC, GSLabIt commented on l10n_it_intrastat/models/account.py
> +        vals_list = values if isinstance(values, list) else [values]
> > @TheMule71 a questo punto si potrebbero anche eliminare i test per sale e purchase, evitando di averli come dipendenze. Cosa ne pensi?
> 
> Direi di si se le dipendenze ci sono solo per i test.

fatto

2022-10-25 08:55 UTC, francesco-ooops commented
@TheMule71 quando puoi :)

2022-10-25 09:23 UTC, TheMule71 approved these changes
LGTM

2022-10-31 15:32 UTC, francesco-ooops commented
@OCA/local-italy-maintainers buona per il merge?

2022-11-02 09:28 UTC, tafaRU requested changes
Potresti aggiungere un test o modificarne uno esistente per coprire il nuovo codice introdotto?
Per il resto LGTM.

2022-11-07 09:51 UTC, GSLabIt commented
> Potresti aggiungere un test o modificarne uno esistente per coprire il nuovo codice introdotto?
> Per il resto LGTM.

Aggiunto, vedi se va bene

2022-11-07 13:17 UTC, tafaRU approved these changes

2022-11-07 13:18 UTC, tafaRU commented
/ocabot merge minor

2022-11-07 13:38 UTC, merged