[FIX] l10n_it_invoices_data_communication 10.0: Fix missing argument error in comunicazione.dati.iva compute_values
OCA/l10n-italy pull request #2879
Opened 2022-07-21 13:23 UTC by TheClaud99

Descrizione del problema o della funzionalità:
In l10n_it_invoices_data_communication per odoo 10.0, viene lanciato un missing argument error quando si prova a a chiamare la funziona compute_values in comunicazione.dati.iva

Comportamento attuale prima di questa PR:
In l10n_it_invoices_data_communication per odoo 10.0, viene lanciato un missing argument error quando si prova a a chiamare la funziona compute_values in comunicazione.dati.iva

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-08-05 08:38 UTC, TheMule71 approved these changes
LGTM

2022-08-05 08:39 UTC, SirTakobi commented
Grazie della PR!
Puoi controllare come mai Travis fallisce? Credo che la riga che hai modificato sia troppo lunga

2022-08-05 09:14 UTC, TheMule71 requested changes

2022-08-05 09:14 UTC, TheMule71 commented on l10n_it_invoices_data_communication/models/communication.py
> +            encode_for_export(partner.street and partner.street.encode('utf8') or '', 60),
In effetti questa riga è troppo lunga.

2022-09-26 23:48 UTC, TheMule71 commented
Per cortesia, squasha i commit in uno solo.

2022-10-09 17:35 UTC, TheMule71 approved these changes
LGTM

2024-06-02 12:28 UTC, closed without merging