[FIX] Ricevere fatture elettroniche in base64 via PEC
OCA/l10n-italy pull request #2916
Opened 2022-08-25 09:18 UTC by SirTakobi

Risolve https://github.com/OCA/l10n-italy/issues/2915 per `12.0`.

2022-08-26 04:34 UTC, eLBati commented
Quindi in pratica in 3fb298fb15e6c274c692300c276c885a9e0ebd9f ci eravamo dimenticati di portare `decoded = base64.b64decode(attachment.datas)`?

2022-08-26 12:27 UTC, SirTakobi commented
> Quindi in pratica in [3fb298f](https://github.com/OCA/l10n-italy/commit/3fb298fb15e6c274c692300c276c885a9e0ebd9f) ci eravamo dimenticati di portare `decoded = base64.b64decode(attachment.datas)`?

Sì, forse perché veniva usato solo nel caso in cui l'allegato è uno `zip`

2022-08-27 06:19 UTC, eLBati requested changes
Chiuderei questa in favore di https://github.com/OCA/l10n-italy/pull/2919

2022-08-29 06:49 UTC, SirTakobi commented
> Chiuderei questa in favore di #2919

https://github.com/OCA/l10n-italy/pull/2919#pullrequestreview-1088138975

2023-02-01 05:41 UTC, eLBati approved these changes
Grazie

2023-02-27 16:25 UTC, primes2h approved these changes
Ciao, grazie per la PR.
La patch funziona correttamente, appena provata su un caso reale.

2023-02-27 16:57 UTC, merged