[12.0] FIX receive_fe in case of base64 files coming from SDI
OCA/l10n-italy pull request #2919
Opened 2022-08-27 06:18 UTC by eLBati

Without this change, every SDI file would be doubly encoded in base64.

file_name_content_dict must be base64-encoded, as described in its documentation.
Next methods must handle the "real" content, in order to process ZIP files also.

2022-08-27 10:15 UTC, TheMule71 requested changes

2022-08-27 10:15 UTC, TheMule71 commented on l10n_it_sdi_channel/models/sdi.py
> +                base64.decodebytes(file_content),
Domanda: ha senso fare in modo che sia il chiamante del metodo `receive_fe` a fare la decode?

In fondo, `sdi_channel` è generico come modulo, e a priori non tutti i canali necessariamente prevedono base64.  L'idea di avere un canale che scarica le fatture e - prima di passarle alla `receive_fe` - sia costretto a encodarle base64 la trovo convoluta.

La `receive_fe()` dovrebbe accettare dei file XML, oltre che a degli zip, e immagino che anche i metadati siano testo... - i chiamanti passano dati binari, o zipfile, o `bytes` adatti al parsing diretto XML (ossia potenzialmente adatti per `xml.etree.ElementTree.fromstring()` - salvo errori di sintassi ovviamente). 

A proposito, poco sopra, riga 115, io invece di testare se il filename termina per .zip, che fa molto PC DOS,  farei una `try:` direttamente prima della `with Zipfile.zipfile(...)`, che fa molto python, o perlomeno userei la `zipfile.is_zipfile()`, che guarda il magic, se vogliamo mantenere l'`if`.

2022-08-29 06:48 UTC, SirTakobi requested changes

2022-08-29 06:48 UTC, SirTakobi commented on l10n_it_sdi_channel/models/sdi.py
> +                base64.decodebytes(file_content),
Concordo con https://github.com/OCA/l10n-italy/pull/2919#pullrequestreview-1087666584: questo metodo dovrebbe riceve i file pronti per essere processati, non qualcosa di già codificato.

> file_name_content_dict must be base64-encoded, as described in receive_fe documentation.

Allora ci sarebbe da correggere la sua documentazione, l'ho aggiunto in https://github.com/OCA/l10n-italy/pull/2916.

2022-12-15 15:26 UTC, eLBati commented
Quindi questa sarebbe da chiudere in favore di https://github.com/OCA/l10n-italy/pull/2916 giusto?

2023-01-19 11:56 UTC, SirTakobi commented
> Quindi questa sarebbe da chiudere in favore di #2916 giusto?

Per me sì

2023-02-01 05:40 UTC, closed without merging