[IMP][l10n_it_ricevute_bancarie] refactor action_post method
OCA/l10n-italy pull request #2922
Opened 2022-08-30 13:34 UTC by patrickt-oforce

Refactor action_post method, splitting part of due costs line calculation into helpers, to allow method extension and override

2022-09-09 13:30 UTC, tafaRU requested changes
Puoi verificare perché le due build **tests** faliscono?

2022-11-04 16:42 UTC, patrickt-oforce commented
@tafaRU ho rimesso mano a questa PR, avevo cannato la chiamata a un metodo; ma il precommit qui fallisce mentre in locale no; prima difare il push ho aggiornato il branch e fatto un rebase in modo da avere tutto aggiornato. Hai dei suggerimenti?

2022-11-05 10:37 UTC, patrickt-oforce commented
@tafaRU @OCA/local-italy-maintainers Sto cercando di comprendere perché falliscono i test; c'è un db particolare che viene usato negli ambienti di test?
Perché in locale alcuni dati come `base.res_partner_3` usato come ref nel metodo setUp di riba_common per impostare il partner nel mio db 14.0 non esiste

2022-11-05 13:44 UTC, TheMule71 commented
> @tafaRU @OCA/local-italy-maintainers Sto cercando di comprendere perché falliscono i test; c'è un db particolare che viene usato negli ambienti di test? Perché in locale alcuni dati come `base.res_partner_3` usato come ref nel metodo setUp di riba_common per impostare il partner nel mio db 14.0 non esiste

Si trova qui:
https://github.com/odoo/odoo/blob/f3d2e5170a6c30fc7f2134660c89d60b487220a1/odoo/addons/base/data/res_partner_demo.xml#L73-L86
se nel tuo db non esiste, i dati demo non sono stati caricati correttamente.

2022-11-07 09:41 UTC, patrickt-oforce commented
> > @tafaRU @OCA/local-italy-maintainers Sto cercando di comprendere perché falliscono i test; c'è un db particolare che viene usato negli ambienti di test? Perché in locale alcuni dati come `base.res_partner_3` usato come ref nel metodo setUp di riba_common per impostare il partner nel mio db 14.0 non esiste
> 
> Si trova qui: https://github.com/odoo/odoo/blob/f3d2e5170a6c30fc7f2134660c89d60b487220a1/odoo/addons/base/data/res_partner_demo.xml#L73-L86 se nel tuo db non esiste, i dati demo non sono stati caricati correttamente.

Grazie mille per la risposta; stavo usando una copia di un db reale. RIcontrollerò il tutto partendo con un db demo

2022-11-07 11:21 UTC, tafaRU commented
@patrickt-oforce 

> ma il precommit qui fallisce mentre in locale no

dovrai fare rebase non appena verrà mergiata https://github.com/OCA/l10n-italy/pull/3005

2022-11-07 11:27 UTC, patrickt-oforce commented
> @patrickt-oforce
> 
> > ma il precommit qui fallisce mentre in locale no
> 
> dovrai fare rebase non appena verrà mergiata #3005

Vedendo il log di precommit; non so se #3005 risolve; sembra un problema legato agli import fatti da PyLint che sulla 3.11 si rompono

2022-11-07 11:28 UTC, matteoopenf commented
> > @patrickt-oforce
> > > ma il precommit qui fallisce mentre in locale no
> > 
> > 
> > dovrai fare rebase non appena verrà mergiata #3005
> 
> Vedendo il log di precommit; non so se #3005 risolve; sembra un problema legato agli import fatti da PyLint che sulla 3.11 si rompono

Su discord di OCA canale Accouting dicevano questo:
![image](https://user-images.githubusercontent.com/43987335/200299486-51d2cded-d9bc-4375-9894-135f3edd4aef.png)

2024-10-01 08:47 UTC, matteoopenf commented
@francesco-ooops  posso avere un rebase qui perfavore?

2024-10-01 08:53 UTC, francesco-ooops commented
/ocabot rebase

2024-10-01 09:08 UTC, matteoopenf commented
> /ocabot rebase

Grazie Mille

2025-03-16 12:35 UTC, closed without merging