[14.0][FIX] -  l10n it intrastat statement: weight can be 0
OCA/l10n-italy pull request #2981
Opened 2022-10-24 10:06 UTC by michelerusti

Corregge #2980  per 14.0

2022-10-25 13:50 UTC, are-agilebg approved these changes

2022-11-17 10:38 UTC, michelerusti commented
Pensate sia possibile portare avanti questa PR? 
Se fossero necessarie modifiche resto a disposizione

2022-12-01 16:16 UTC, eLBati requested changes
Le traduzioni vanno modificate solo tramite translation.odoo-community.org

2023-02-08 16:41 UTC, michelerusti commented
> Le traduzioni vanno modificate solo tramite translation.odoo-community.org

Ho rimosso la modifica e fatto richiesta per accedere alle traduzioni!
Fammi sapere se può andar bene così

2023-04-04 09:38 UTC, michelerusti commented
@eLBati Non va bene qualcosa ancora o possiamo risolvere la richiesta?

2023-04-07 06:42 UTC, eLBati approved these changes
LGTM

2023-04-07 12:14 UTC, tafaRU commented
/ocabot merge minor

2023-04-07 12:46 UTC, merged