[16.0] [MIG] l10n_it_vat_payability
OCA/l10n-italy pull request #2989
Opened 2022-11-02 02:03 UTC by TheMule71

2022-11-08 14:35 UTC, primes2h commented
/ocabot migration l10n_it_vat_payability

2022-11-10 15:33 UTC, warp10 approved these changes
LGTM

2022-11-10 15:50 UTC, tafaRU requested changes

2022-11-10 15:50 UTC, tafaRU commented on l10n_it_vat_payability/__manifest__.py
> +    "pre_init_hook": "rename_old_italian_module",
Si può eliminare, non serve più.

2022-11-10 15:50 UTC, tafaRU commented on l10n_it_vat_payability/__manifest__.py
> +    "external_dependencies": {
Anche questo si può eliminare.

2022-11-10 16:21 UTC, tafaRU approved these changes

2022-11-10 16:26 UTC, merged