[16.0] [MIG] l10n_it_account
OCA/l10n-italy pull request #2990
Opened 2022-11-02 02:18 UTC by TheMule71

2022-11-02 08:03 UTC, SirTakobi commented
@TheMule71 puoi includere PR aperte modificando il _test-requirements.txt_ invece di fare https://github.com/OCA/l10n-italy/pull/2990/commits/0b083a0a1bebf67d2d1ab1333582071a5490a343.
Se le includi nel _test-requirements.txt_ è automaticamente impossibile mergiare questa PR per sbaglio perché fa fallire il check **Detect unreleased dependencies**

2022-11-02 18:11 UTC, TheMule71 commented
> @TheMule71 puoi includere PR aperte modificando il _test-requirements.txt_ invece di fare [0b083a0](https://github.com/OCA/l10n-italy/commit/0b083a0a1bebf67d2d1ab1333582071a5490a343). Se le includi nel _test-requirements.txt_ è automaticamente impossibile mergiare questa PR per sbaglio perché fa fallire il check **Detect unreleased dependencies**

Ottimo, grazie. Le altre PR (le nostre) mi preoccupano già di meno, i commit sparirebbero comunque se fossero identici, causerebbero conflict se fossero diversi.

2022-11-03 17:20 UTC, TheMule71 commented
> Anche per le nostre PR, è comunque meglio usare i requirements per non rischiare di mergiare diverse PR insieme e per non dover fare continui rebase quando cambia _l'altra_ PR

Ho inziato a farlo da fatturapa_out (esclusa) in poi.  Il fatto è che così devo riesumare il supermerge (cosa che volevo evitare), perché non sono testabili fuori da github senza fare il merge a mano.

2022-11-08 14:34 UTC, primes2h commented
/ocabot migration l10n_it_account

2022-11-10 14:52 UTC, SirTakobi requested changes
Grazie della PR!
In https://github.com/TheMule71/l10n-italy/pull/31 ho fatto le modifiche di cui abbiamo parlato e anche qualcos'altro, che ne pensi?

2022-11-10 15:56 UTC, SirTakobi approved these changes

2022-11-11 08:59 UTC, SirTakobi requested changes
@TheMule71 mi sembra si siano perse le modifiche di https://github.com/TheMule71/l10n-italy/pull/31 nel rebase

2022-11-11 14:02 UTC, SirTakobi approved these changes

2022-11-11 15:32 UTC, tafaRU requested changes
Review tecnica basata su https://github.com/TheMule71/l10n-italy/compare/TheMule71:l10n-italy:5b6aed0650616352588f5c2aaf707ca0dd37e92c~5...TheMule71:l10n-italy:5b6aed0650616352588f5c2aaf707ca0dd37e92c

`account_tax_balance` è stato mergiata: puoi togliere la PR da https://github.com/TheMule71/l10n-italy/blob/16.0-mig-l10n_it_account/test-requirements.txt?

2022-11-11 15:32 UTC, tafaRU commented on l10n_it_account/readme/DESCRIPTION.rst
> +Notice: the migratiob script hasn't been tested.
s/migrationb/migration :wink:

2022-11-11 15:50 UTC, tafaRU approved these changes

2022-11-11 16:06 UTC, eLBati commented
/ocabot merge nobump

2022-11-11 16:13 UTC, merged