[16.0] [MIG] l10n_it_fatturapa_in
OCA/l10n-italy pull request #3000
Opened 2022-11-03 00:37 UTC by TheMule71

2022-11-03 23:45 UTC, TheMule71 commented
Alcuni test vengono skippati, perché provocano errori DB che impediscono l'esecuzione di test successivi.

2022-12-08 01:23 UTC, TheMule71 commented
Promemoria: https://github.com/OCA/l10n-italy/pull/3004

2022-12-30 21:11 UTC, TheMule71 commented
Include #3111 per far passare i test. Ovviamente, andrebbe mergiata prima quella.

2023-01-26 07:31 UTC, andreampiovesana requested changes
provato con ultimo aggiornamento e funziona

2023-01-31 12:57 UTC, francescapenso commented
Ho fatto un po di test di importazione di fatture elettroniche tutti con successo. 
Per ora ho provato fatture con iva normali, fatture con esenzioni iva, forfettari e ritenuta d'acconto. Tutte funzionanti

2023-02-01 14:59 UTC, andreampiovesana commented
merge?

2023-02-01 21:09 UTC, TheMule71 commented
> merge?
Serve review tecnica.

2023-02-20 09:04 UTC, TonyMasciI approved these changes

2023-02-21 20:42 UTC, TheMule71 commented on l10n_it_fatturapa_in/views/account_view.xml
> +            </field -->
Nice catch.
Ribalto la domanda ai funzionali, in particolare @andreampiovesana . Ricordi il perché è stata commentata? Immagino ci fosse un motivo ma non ricordo quale.

2023-02-21 23:21 UTC, andreampiovesana commented
Vorrei aggiungere la ricerca della costo della contropartita per fornitore, oltre che per il prodotto:
![image](https://user-images.githubusercontent.com/13952131/220481139-17f50982-1862-45a2-8c03-40d3d33f7cfa.png)

2023-02-27 22:08 UTC, marco-marchiori approved these changes
Provato oggi l'import di alcune fatture XML in ambiente runboat
http://oca-l10n-italy-16-0-pr3000-f3da2a372433.runboat.odoo-community.org/
le fatture si importano e si caricano correttamente.
Marco

2023-02-27 22:24 UTC, andreampiovesana approved these changes
merge

2023-03-02 14:40 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                        "tax_ids": [(6, 0, [invoice_line_tax_id])],
Ci pensa https://github.com/odoo/odoo/blob/245804aabb5cd8b3a84b2a4836b188ec9fb144e1/addons/account/models/account_move_line.py#L433 
che se vedi mette 'product' anche per delle semplici entry.

Per il 'rounding', provato, ma questo codice si aspetta una sola riga https://github.com/odoo/odoo/blob/245804aabb5cd8b3a84b2a4836b188ec9fb144e1/addons/account/models/account_move.py#L1175-L1177

e  questo zappa tutte le righe 'rounding' senza troppe domande: https://github.com/odoo/odoo/blob/245804aabb5cd8b3a84b2a4836b188ec9fb144e1/addons/account/models/account_move.py#L1861-L1867

2023-03-05 19:38 UTC, TheMule71 commented on l10n_it_fatturapa_in/__manifest__.py
> +# Copyright 2015 AgileBG SAGL <http://www.agilebg.com>
> Manca [6736c3b](https://github.com/OCA/l10n-italy/commit/6736c3b9b077fade96edec96afd1bcd9cac5acef), se non vuoi aggiungerlo qui va almeno segnato in #3013 che la `16.0` potrebbe essere affetta.

Non mi pare affetta. https://github.com/TheMule71/l10n-italy/blob/2e1eb0e1dbd13c6a57bef08cdcb58826680c1368/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1082
È possibile sia stata corretta all'epoca semplicemente vedendo la issue.

> 
> Manca [765364d](https://github.com/OCA/l10n-italy/commit/765364dedb1011c1448bdfa1b61ce3ef18a1b6e1) aggiunto solo quanche giorno fa alla `14.0`; se non vuoi aggiungerlo qui va almeno segnato in #2869 che la `16.0` potrebbe essere affetta.

Segnata nella issue. La PR riguarda + moduli, non ha senso includerla nella migrazione di `l10n_it_fatturapa_in`, meglio fare il porting della PR una volta mergiata `l10n_it_fatturapa_in` (e anche `l10n_it_fatturapa_in_rc`).

> 
> Puoi separare le modifiche automatiche di pre-commit dalle altre modifiche necessarie per la migrazione come descritto in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch?

Il commit `pre-commit stuff` è vuoto, probabilmente è sparito cancellato da un rebase -i.   Per essere più preciso (ho appena provato a rifare la prima parte della migrazione) contiene solo questo file `setup/l10n_it_fatturapa_in/setup.py`, che però è già presente nei commit precendenti (della 14).  La prima volta non trova il file in quanto `git format-patch --keep-subject --stdout origin/16.0..origin/14.0 -- $module ` non selezione la directory `setup` (quindi non include quel file anche se presente nei commit).

Per uniformità ho inserito un commit (con `--allow-empty`), che però appunto è vuoto.

Nel commit di migrazione ci sono un sacco di modifiche per far contento il pre-commit, ma che non vengono applicate automaticamente. Io avevo proposto di creare un secondo commit ('more pre-commit stuff') per separarle dalla migrazione vera e propria ma la proposta è stata cassata.

2023-03-05 19:43 UTC, TheMule71 commented on l10n_it_fatturapa_in/models/account.py
> +        return ret
In effetti non lo è. Non c'è return nell'originale.

2023-03-05 19:59 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/fatturapa_common.py
> +    def setUpClass(cls):
Beh in parte è dovuto dallo spostamento di codice dal `setUp()` di `TestFatturaPAXMLValidation` (che fa sì che venga sempre eseguito per ogni test, e non ha senso rieseguire quelle istruzioni).  Questa è una parte che ha creato effettivamente problemi, ma oggettivamente si potrebbe backportare alla 14, dove però non crea gli stessi problemi.

Tutto il resto, deriva da fatto che tra 14 e 16 un sacco di oggetti vengono controllati per coerenza di company, e prima non era così.

Un sacco di test della 14 funzionano implicitamente usando oggetti (per oggetti intento robe tipo conti, tasse, pos. fiscale e robe del genere) che in realtà appartengano alla company di default e non la company usata per i test. Nella 14 non è un problema.

Nella 16 sì, quindi sebbene *esteticamente* si potrebbe backportare gran parte delle modiche, nella 14 non servono, mentre nella 16 sono necessarie a causa dei combiamenti avvenuti, per cui fanno parte della migrazione. 

Poi, proprio volendo possiamo spezzare la funzione ma una funzione di setup fa quello di mestiere, creare tutta una serie di oggetti necessari successivamente per i test. Non è particolarmente complessa dal punto di vista logico, è solo una lunga sequenza di `create()`.   In molti casi vengono duplicati oggetti già esistenti perché non sono altro che quelli che nella 14 vengono implicitamente usati.

2023-03-05 20:07 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertFalse(vat_partner_exists())
Vd commento in testa al test. Il `test_53_xml_import` si potrebbe anche rimuovere, il partner non viene creato nella 16 (la vat invalida viene intercettata prima). Se il comportamento cambia tra 14 e 16, è una modifica legata alla migrazione. Non è una modifica da backportare alla 14, e non serve un commit separato.

L'unica cosa discutibile è se rimuovere il test completamente o no.

2023-03-05 20:17 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> -        supplier = self.env["res.partner"].search(
Non ricordo come falliva il test sinceramente. Il problema era comunque debuggare.

In generale, non è carino che un test dipenda dall'esecuzione di un test precedente per funzionare.  Non lo si può lanciare isolatamente.

Questa modifica potrebbe aver senso portarla all'indietro, ma siamo sempre nell'ambito dell'estetica - i test nella 14 sono comunque verdi, quello che non si può fare è invocarli separatamente da command line.

Ma è un problema genericamente diffuso in tutti i nostri test... semplicemente fatturapa_in ne ha mediamente più degli altri moduli, e tende a succedere più spesso.

La issue per il refactoring dei test c'è, ma ovviamente non è una priorità.

Di questo modifica forse si potrebbe anche fare un revert (ammesso che un test precedente crei effettivamente quel partner), ma non vedo che ci guadagnamo a farlo, sinceramente.

2023-03-05 20:31 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                    ("company_id", "=", self.env.company.id),
Si ma così non si può vedere imposte di + company? (`company_ids`). La rule non è abbastanza selettiva.

Se stai importando una fattura nella company A non ha senso che tu possa "vedere" imposte della company B anche se hai accesso ad entrambe al livello di company_ids.  Devi limitare la ricerca alla company corrente. Nella 16 non puoi usare tasse della company B nelle fatture della company A.

Anche qui, nella 14 apparentemente non dava problemi, e trovata una tassa con quella Natura di esenzione e imposta a zero di fatto conta solo la label (anche a livello contabile non c'è differenza). Ovvio che sapendolo uno potrebbe crearsi un problema andando nella company B e modificando la tassa, ma non è esattamente uno scenario plausible.

Nella 16, senza quella condizione extra nella search, l'import fallisce senza che l'utente possa farci nulla, se non "togliersi" da tutte le company tranne una e rifare l'import.

2023-03-05 22:58 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +            retLine["tax_ids"] = [fields.Command.clear()]
Non prenderla al 100% perché sono passati mesi, ma mi [pare di ricordare che a causa delle modifiche `onchange` -> `compute` (https://github.com/odoo/odoo/commit/d8d47f9ff8554f4b39487fd2f13c153c7d6f958d) di fatto adesso creando oggetti da codice (senza `Form` ovviamente) ti trovi molte più cose pre-popolate e tra queste le tasse di default.

Essendo una cosa della 16, non è da backportare.

2023-03-05 23:18 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> -            .sudo()
Non so esattamente, prima serviva? La modifica fa parte del porting, nella 16 non esiste proprio `xmlid_to_object`, come da indicazioni l'ho rimpiazzata con `env.ref` vd. https://github.com/odoo/odoo/commit/d8d47f9ff8554f4b39487fd2f13c153c7d6f958d

Passo la palla a chi ha fatto i test funzionali, avete fatto prove da utente "normale" oltre che da admin? Se sì, allora il `sudo()` evidentemente non serve (almeno, sulla 16).

2023-03-05 23:34 UTC, TheMule71 commented on l10n_it_fatturapa_in/i18n/it.po
> +# Translation of Odoo Server.
Sono traduzioni successive alla creazione della PR.
 
Devo cherry-pickare tutti i commit di traduzione sulla 14 per `l10n_it_fatturapa_in` dal 3/11/2022 ad oggi? (ping @primes2h)
Non mi è mai capitato di doverle includere in una migration credevo ci pensasse weblate ad aggiornare le traduzione dopo il merge.

2023-03-05 23:44 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertEqual(invoice.amount_tax, 3.75)
Vd. https://github.com/OCA/l10n-italy/pull/3000#discussion_r1125750643

Nella 16 c'è una tassa di default, del 15% (25 * 0.15 = 3.75) che nella 14 non c'è.  Il senso della assert è che comunque non sia 3.89 (ossia tassa del 15.55% come da XML), perché l'aliquota manca nel DB.

Nella 14 non viene messa nessuna tassa di default per cui è 0, nella 16 ti trovi la tassa del 15% per cui è 3.75.

È un cambiamento del comportamento di una create() di una fattura tra 14 e 16. Fa parte del porting e non va backportato.

2023-03-06 00:38 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        invoice.e_invoice_force_validation = True  # XXX perché serve nella 16?
Questa è effettivamente una cosa da rivedere.

'Computed amount untaxed 34.32 is different from summary data 34.67' questo è il problema.

Ma oggettivamente se si conta l'arrotondamento l'imponibile è effettivamente 34.32 e non 34.67.
E siccome noi aggiungiamo una riga alla fattura, viene (nella 16) calcolata tra imponibile.

La domanda è come risolvere e/o come mai sulla 14 non succede.

2023-03-06 09:27 UTC, marcelofrare approved these changes
LGTM functional

2023-03-07 09:33 UTC, primes2h commented on l10n_it_fatturapa_in/i18n/it.po
> +# Translation of Odoo Server.
> Grazie per la review!
> 
> Sono traduzioni successive alla creazione della PR.
> 
> Devo cherry-pickare tutti i commit di traduzione sulla 14 per `l10n_it_fatturapa_in` dal 3/11/2022 ad oggi? (ping @primes2h) Non mi è mai capitato di doverle includere in una migration credevo ci pensasse weblate ad aggiornare le traduzione dopo il merge.

Weblate rigenera il .pot e i vari .po ma mi pare che non traduca automaticamente le stringhe come fa Transifex (e questo è un bene). 
Al massimo, in caso di aggiornamenti intra-versione, le popola con stringhe simili provenienti da traduzioni precedenti segnandondole come da modificare.

In caso di migrazione l'ideale sarebbe sempre tenere aggiornata la PR con cherry pick di aggiunte/correzioni intervenute nel frattempo, come si fa in certi casi con eventuali patch/fix al codice di cui è stato fatto il merge.
In generale, se la cosa non viene gestita nella PR sarà necessario farlo successivamente in weblate o con PR apposite (a seconda del caso).

2023-03-07 09:43 UTC, francesco-ooops commented on l10n_it_fatturapa_in/i18n/it.po
> +# Translation of Odoo Server.
@primes2h se le traduzioni sono già in memoria weblate dalla versione precedente è una questione di pochi minuti aggiungerle alla nuova versione con la funzione "Automatic suggestions". C'è solo da ricordarsi di sistemare la traduzione qualche ora dopo il merge

2023-03-07 09:55 UTC, primes2h commented on l10n_it_fatturapa_in/i18n/it.po
> +# Translation of Odoo Server.
> @primes2h se le traduzioni sono già in memoria weblate dalla versione precedente è una questione di pochi minuti aggiungerle alla nuova versione con la funzione "Automatic suggestions". C'è solo da ricordarsi di sistemare la traduzione qualche ora dopo il merge

Si si, certo! Anche una PR con una patch per il codice si sta poco a fare successivamente con un cherry pick. Era solo per fare un parallelo tra le due situazioni.

2023-03-08 09:15 UTC, TheMule71 commented
> LGTM functional

Grazie per la review, Marcelo. Per caso hai visto https://github.com/OCA/l10n-italy/pull/3000#discussion_r1125753976? hai provato da utente non admin?

2023-03-08 21:05 UTC, marcelofrare commented
> > LGTM functional
> 
> Grazie per la review, Marcelo. Per caso hai visto [#3000 (comment)](https://github.com/OCA/l10n-italy/pull/3000#discussion_r1125753976)? hai provato da utente non admin?

ho provato da un utente non admin e come vedi **non è possibile operare**.
solo l'utente con l'impostazione ADMINISTRATION → `Settings` ha accesso al menù

Mi pare che questa impostazione non fosse indispensabile nelle versioni precedenti.

![immagine](https://user-images.githubusercontent.com/25057933/223847584-632be483-ed2a-43b2-9890-e6457174cce6.png)

2023-03-10 07:47 UTC, TheMule71 commented
> > > LGTM functional
> > 
> > 
> > Grazie per la review, Marcelo. Per caso hai visto [#3000 (comment)](https://github.com/OCA/l10n-italy/pull/3000#discussion_r1125753976)? hai provato da utente non admin?
> 
> ho provato da un utente non admin e come vedi **non è possibile operare**. solo l'utente con l'impostazione ADMINISTRATION → `Settings` ha accesso al menù
> 
> Mi pare che questa impostazione non fosse indispensabile nelle versioni precedenti.
> 
> ![immagine](https://user-images.githubusercontent.com/25057933/223847584-632be483-ed2a-43b2-9890-e6457174cce6.png)

Ho rimesso il `.sudo()`.

I test andrebbero rivisti in ottica di eseguirli come utente normale, ma non è un refactoring da affrontare come migrazione.

2023-03-13 14:18 UTC, marcelofrare commented
> Ho rimesso il `.sudo()`.

confermo che ora funziona da utente senza permessi di amministrazione. Grazie

2023-03-17 10:09 UTC, TheMule71 commented on l10n_it_fatturapa_in/models/account.py
> +        return ret
Ho scoperto che serve per evitare un warning pre-commit.

2023-03-17 10:21 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> -        self.env.user.lang = "it_IT"
Lasciando la forzatura della lingua ottieni:

```
2023-03-17 10:13:08,267 12625 ERROR o16-mig-fpain odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml: FAIL: TestFatturaPAXMLValidation.test_37_xml_import_dates
Traceback (most recent call last):
  File "/home/marco/src/odoo/16/OCA/l10n-italy/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 711, in test_37_xml_import_dates
    self.assertEqual(invoice.fatturapa_attachment_in_id.invoices_date, "12/18/2014")
AssertionError: '18/12/2014' != '12/18/2014'
- 18/12/2014
+ 12/18/2014
```

perché nella 14 non lo faccia non lo so, ma il test sembra voler il formato americano ma forza la lingua italiana.  Non è ben documentato.

Se il senso del test era "forzo la lingua it ma Odoo (14) la ignora e usa comunque in formato data americano e a ma va bene così", beh andrebbe scritto a caratteri cubitali.  E anche perché.

Togliendo la forzatura, l'import del file funziona.

Sottolineo che nel file il formato è diverso da entrambi, è ISO e non ambiguo: `<Data>2014-12-18</Data>`

2023-03-17 10:22 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        # self.env.user.lang = "it_IT"
Idem come sopra:
```
2023-03-17 10:22:13,095 12811 ERROR o16-mig-fpain odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml: FAIL: TestFatturaPAXMLValidation.test_38_xml_import_dates
Traceback (most recent call last):
  File "/home/marco/src/odoo/16/OCA/l10n-italy/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 723, in test_38_xml_import_dates
    self.assertEqual(
AssertionError: '18/12/2014 20/12/2014' != '12/18/2014 12/20/2014'
- 18/12/2014 20/12/2014
+ 12/18/2014 12/20/2014
```

2023-03-17 10:34 UTC, TheMule71 commented on l10n_it_fatturapa_in/views/account_view.xml
>                      name="efatt_rounding"
Ripristinato.

2023-03-17 10:36 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        invoice.e_invoice_force_validation = True  # XXX perché serve nella 16?
Ho eliminato la riga per far fallire il test.

2023-03-17 10:42 UTC, TheMule71 commented on l10n_it_fatturapa_in/views/account_view.xml
>                      name="efatt_rounding"
Come non detto, mo' lo ritolgo:
```
odoo.tools.convert.ParseError: while parsing /home/marco/src/odoo/16/OCA/l10n-italy/l10n_it_fatturapa_in/views/account_view.xml:170
Error while validating view near:

                    <button name="button_cancel_posted_moves" string="Request EDI Cancellation" type="object" groups="account.group_account_invoice" attrs="{'invisible' : [('edi_show_cancel_button', '=', False)]}"/>
                    <button name="button_abandon_cancel_posted_posted_moves" string="Call off EDI Cancellation" type="object" groups="account.group_account_invoice" attrs="{'invisible' : [('edi_show_abandon_cancel_button', '=', False)]}"/>
                        <button name="button_cancel" string="Cancel" type="object" groups="account.group_account_invoice" data-hotkey="w" attrs="{'invisible' : ['|', '|', ('id', '=', False), ('state', '!=', 'draft'),('move_type', '==', 'entry')]}"/>
                        <button name="button_draft" string="Reset to Draft" type="object" groups="account.group_account_invoice" attrs="{'invisible' : [('show_reset_to_draft_button', '=', False)]}" data-hotkey="q"/>
                        <!-- Set as Checked -->

Field "efatt_rounding" does not exist in model "account.move.line"
```

In effetti è un campo della fattura, non della riga.

2023-03-17 11:04 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +            elif company.arrotondamenti_tax_id:
Falliscono i test `test_08_xml_import` e `test_09_xml_import`.
```
Traceback (most recent call last):
  File "/home/marco/src/odoo/16/OCA/l10n-italy/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 205, in test_08_xml_import
    self.assertAlmostEqual(invoice.amount_total, 1288.61)
AssertionError: 1267.13 != 1288.61 within 7 places (21.47999999999979 difference)
```

Quello che succede è che applica la tassa di default (sulla 16, non sulla 14) alla riga di sconto.  Per cui,
la somma delle righe è: 1431.792
lo sconto sarebbe (sul totale, vd. XML): 143.1792 (il 10%)
Nella 14, 1431.792 - 143.1792 = 1288.6128
Nella 16, applica allo sconto la tassa del 15%, portandolo a 164.66 e   1431.79 - 164.66 = 1267.13.

Non sapevo se lo sconto sul totale fattura venisse conteggiato come un arrotondamento, mi sembrava sensato applicare la `company.arrotondamenti_tax_id`.  Credo che il test passerebbero anche semplicamente con un CLEAR delle tasse.

In ogni caso non credo sia da backportare as is. 

Comunque separo il commit.

2023-03-17 11:39 UTC, TheMule71 commented
Il test 25 fallisce per il problema arrotondamento:

https://discord.com/channels/753902328494424064/753902328494424070/1082973850167410698

2023-03-24 15:47 UTC, SirTakobi requested changes

2023-03-24 15:47 UTC, SirTakobi commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +            elif company.arrotondamenti_tax_id:
Capito, grazie del chiarimento.
Penso sia meglio eliminare le imposte invece di mettere quella per l'arrotondamento, così abbiamo lo stesso comportamento della `14.0`.

2023-03-24 15:47 UTC, SirTakobi commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                        "tax_ids": [(6, 0, [invoice_line_tax_id])],
Ah ecco, grazie del chiarimento

> Ci pensa https://github.com/odoo/odoo/blob/245804aabb5cd8b3a84b2a4836b188ec9fb144e1/addons/account/models/account_move_line.py#L433 che se vedi mette 'product' anche per delle semplici entry.

penso sarebbe più chiaro impostarlo esplicitamente invece di lasciare implicitamente decidere al default; ma non vedo grossi problemi per ora a lasciarlo così (ci saranno forse quando cambierà il default).

2023-04-06 19:57 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/fatturapa_common.py
> +    def setUpClass(cls):
Fatto.

2023-04-06 20:06 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertEqual(invoice.amount_tax, 3.75)
L'assert è una cosa in più, non fa parte della logica del test.  Potremmo anche rimuoverla. È solo per completezza che viene verificato il valore di `amount_tax`. 

Quello che il test deve verificare è altro.  Per come la vedo io è cambiato un comportamento di default del core. Non ha senso downgradare un comportamento (per es. forzando la rimozione della tassa di default.

Soprattutto tenendo conto che di fatto nella 14 era un bug più che altro, la tassa c'era ma non veniva applicata (a meno di usare la classe `Form` o chiamare direttamente l'`onchange`).  È un cosa che a logica avrebbe dovuto già fare il test nella 14 (ma che non essendo importante ai fini del test, non è necessario correggere).

2023-04-07 09:29 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertEqual(invoice.amount_tax, 3.75)
Ok, modificato il comportamento dell'import. Ora se non trova la tassa, forza nessuna tassa.

2023-04-07 09:30 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> -        self.env.user.lang = "it_IT"
Fatto.

2023-04-07 09:31 UTC, TheMule71 commented on l10n_it_fatturapa_in/views/account_view.xml
>                      name="efatt_rounding"
Fatto. Da vedere se è posizionato correttamente.

2023-04-07 09:48 UTC, TheMule71 commented on l10n_it_fatturapa_in/views/account_view.xml
>                      name="efatt_rounding"
Controllato sembra OK.

2023-04-07 09:49 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +            elif company.arrotondamenti_tax_id:
Fatto.

2023-04-07 10:03 UTC, TheMule71 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                    ("company_id", "=", self.env.company.id),
Considera che in fase di creazione:
https://github.com/TheMule71/l10n-italy/blob/a9cfaa598ae9a9f537a15db8dbc42f1cb93fb3b2/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1064
viene `presa self.env.company`

Successivamente, ci possono essere medoti/funzioni chiamati senza il contesto della fattura, come ad es. `get_account_taxes`
https://github.com/TheMule71/l10n-italy/blob/a9cfaa598ae9a9f537a15db8dbc42f1cb93fb3b2/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L445-L449
che si vanno a prendere la company ancora da `self.env.company` (invece di `invoice.company_id` come fanno quei metodi che hanno il contesto della fattura).

`get_account_taxes` cerca una tassa per aliquota e (se zero) per natura, da applicare alla fattura ovviamente. Siccome la 16 adesso controlla che la company sia coerente, la `company_id` della tassa deve essere la stessa della fattura.

Ho reso più evidente la company scelta (prima nel codice si andava a prendere più volte `self.env.company`, adesso viene settata all'inizio della funzione (come era già) e viene sempre usata quella.

2023-04-07 13:13 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        self.assertFalse(vat_partner_exists())
Ho ripristinato il test originale. La compute che creava il partner non viene invocata della `create()`. Semplicemente accedendo ad uno di campi calcolati (in lettura), scatena il tutto.

2023-04-07 13:22 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> -        supplier = self.env["res.partner"].search(
Ho ripristinato il test originale.

2023-04-07 13:25 UTC, TheMule71 commented on l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
> +        invoice.e_invoice_force_validation = True  # XXX perché serve nella 16?
vd. https://github.com/OCA/l10n-italy/pull/3000#issuecomment-1473704150

2023-04-07 13:30 UTC, TheMule71 commented
@SirTakobi dovrei aver rivisto tutto.

2023-04-13 13:00 UTC, SirTakobi approved these changes
Grazie mille delle modifiche,
ho solo verificato la storia dei commit e fatto revisione del codice.

Ho messo ancora qualche commento per le questioni in sospeso ma per me non c'è più nulla di bloccante per il merge.

2023-04-14 08:39 UTC, merged