[16.0][MIG] l10n_it_appointment_code
OCA/l10n-italy pull request #3001
Opened 2022-11-03 08:21 UTC by Borruso

Migration l10n_it_appointment_code from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-11-08 14:30 UTC, primes2h commented
/ocabot migration l10n_it_appointment_code

2022-11-10 16:11 UTC, SirTakobi requested changes
Grazie della PR!
Puoi squashare i commit amministrativi come indicato in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#tasks-to-do-in-the-migration?
Ho trovato un problema di visualizzazione, per correggere ti ho proposto https://github.com/Borruso/l10n-italy/pull/12, puoi vedere se va bene ed eventualmente mergiarla?

2022-11-14 13:24 UTC, tafaRU requested changes
In aggiunta, puoi schiacciare i tre commits seguenti in uno solo? I due amministrativi con il primo.
![image](https://user-images.githubusercontent.com/3512779/201671136-257f634f-29ab-4807-9642-891788378d51.png)

Per il resto LGTM, l'ho anche testato su runboat :+1:

2022-11-14 13:24 UTC, tafaRU commented on l10n_it_appointment_code/i18n/it.po
> +# 	* l10n_it_central_journal_reportlabappointment_code
penso trattasi di un refuso: puoi verificare?

2022-11-14 13:26 UTC, Borruso commented on l10n_it_appointment_code/i18n/it.po
> +# 	* l10n_it_central_journal_reportlabappointment_code
sisi correggo subito

2022-11-14 14:11 UTC, tafaRU commented on l10n_it_appointment_code/i18n/it.po
> +# 	* l10n_it_central_journal_reportlabappointment_code
rimane da risolvere https://github.com/OCA/l10n-italy/pull/3001#pullrequestreview-1179088507 Grazie

2022-11-15 08:07 UTC, tafaRU approved these changes

2022-11-15 08:07 UTC, tafaRU commented
@SirTakobi potresti aggiornare la tua review?

2022-11-18 09:23 UTC, warp10 approved these changes
Tested, LGTM.

2022-11-24 15:16 UTC, SirTakobi approved these changes
Revisione dei commit, del codice e provato in runboat, per me è ok

2022-11-25 08:04 UTC, tafaRU commented
/ocabot merge nobump

2022-11-25 08:11 UTC, merged