[16.0][MIG] l10n_it_central_journal_reportlab
OCA/l10n-italy pull request #3002
Opened 2022-11-04 09:46 UTC by Borruso

Migration l10n_it_central_journal_reportlab from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-11-08 14:28 UTC, primes2h commented
/ocabot migration l10n_it_central_journal_reportlab

2022-11-11 10:44 UTC, TonyMasciI reviewed
Aprirò una ISSUE per la V14

2022-11-11 10:44 UTC, TonyMasciI commented on l10n_it_central_journal_reportlab/wizard/print_giornale.py
> +                lines_data.append([[row, date, move, account, name, debit, credit]])
c'è un motivo per cui sono stati fatti due if in cascata quando si potrebbe eseguire questo codice?

Da questo:

```
            if line["debit"] > 0:
                debit = Paragraph(formatLang(self.env, line["debit"]), style_number)
                credit = Paragraph(formatLang(self.env, 0), style_number)
                list_balance.append((line["debit"], 0))
                lines_data.append([[row, date, move, account, name, debit, credit]])
            if line["credit"] > 0:
                debit = Paragraph(formatLang(self.env, 0), style_number)
                credit = Paragraph(formatLang(self.env, line["credit"]), style_number)
                list_balance.append((0, line["credit"]))
                lines_data.append([[row, date, move, account, name, debit, credit]])
```

a questo:
```
            debit = Paragraph(formatLang(self.env, line["debit"]), style_number)
            credit = Paragraph(formatLang(self.env, line["credit"]), style_number)
            list_balance.append((line["credit"], line["credit"]))
            lines_data.append([[row, date, move, account, name, debit, credit]])
```

2022-11-11 10:44 UTC, TonyMasciI commented on l10n_it_central_journal_reportlab/wizard/print_giornale.py
> +            self.year_footer = fields.Date.to_date(self.date_move_line_from_view).year
Non ha senso modificare questo pezzo di codice:

`            self.year_footer = fields.Date.to_date(self.date_move_line_from_view).year
`

con:


`            self.l10n_it_year_footer = self.l10n_it_date_move_line_from_view.year
`

2023-09-07 07:46 UTC, Borruso commented
@TonyMasciI per le varie modifiche suggerite `Aprirò una ISSUE per la V14`, suggerisco di applicarle dopo la migrazione dato che queste modifiche dovranno essere per v14 e v16

Bisognerebbe creare poi una issue di tracciamento

2023-09-07 07:52 UTC, TonyMasciI approved these changes

2023-09-07 07:58 UTC, tafaRU requested changes
Il resto LGTM :+1:

2023-09-07 07:58 UTC, tafaRU commented on l10n_it_central_journal_reportlab/wizard/print_giornale.xml
> +                    <field name="daterange_id" domain="[('company_id', '!=', False)]" />
Puoi aggiungere un commento spiegando la ragione per cui è stato aggiunto questo domain? (Mi ricordo che se ne era parlato in call). Grazie.

2023-09-07 09:10 UTC, tafaRU approved these changes

2023-09-07 09:39 UTC, marcelofrare approved these changes
LGTM functional

2023-09-07 10:12 UTC, marcelofrare commented
Nota a margine:
il readme è piuttosto limitato.
Sarebbe da aggiungere l'indicazione che il file PDF generato dal modulo lo si trova in fondo alla form.
Inoltre, servirebbe spiegare la differenza tra STAMPA e STAMPA DEFINITIVA

2023-09-07 10:55 UTC, tafaRU commented
@marcelofrare in merito a https://github.com/OCA/l10n-italy/pull/3002#issuecomment-1709885254 abbiamo aperto https://github.com/OCA/l10n-italy/issues/3562

2023-09-07 10:58 UTC, tafaRU requested changes
@Borruso puoi schiacciare [669bf8022d1934fa3a4942fece3847432a943f99](https://github.com/OCA/l10n-italy/pull/3002/commits/669bf8022d1934fa3a4942fece3847432a943f99) con il precedente?

2023-09-07 12:50 UTC, tafaRU approved these changes

2023-09-07 13:04 UTC, tafaRU commented
/ocabot merge nobump

2023-09-07 13:04 UTC, tafaRU commented
/ocabot merge nobump

2023-09-07 13:17 UTC, merged