[14.0] [FIX] XML "show preview" not translatable
OCA/l10n-italy pull request #3004
Opened 2022-11-04 22:51 UTC by primes2h

![immagine](https://user-images.githubusercontent.com/227940/200085960-6b2efa8d-df5a-45d5-a174-5d0befb7bda7.png)

2022-11-06 20:39 UTC, primes2h commented
Il pre-commit :red_circle: non dipende da questa PR.

2022-11-06 20:47 UTC, marcelofrare approved these changes

2022-11-07 13:42 UTC, primes2h commented
Pre-commit ora è :green_circle:

2022-11-09 13:33 UTC, tafaRU requested changes
Grazie della PR!
Per evitare duplicazioni di codice potresti definire il metodo `ftpa_preview` nel modulo `l10n_it_fatturapa` analogamente a quanto fatto per `ftpa_preview_link`?
https://github.com/OCA/l10n-italy/blob/8dee28fe07dff9d6d260ae46e0be4a7c413f6a8c/l10n_it_fatturapa/models/ir_attachment.py#L34

2022-11-21 08:11 UTC, primes2h commented
> Grazie della PR! Per evitare duplicazioni di codice potresti definire il metodo `ftpa_preview` nel modulo `l10n_it_fatturapa` analogamente a quanto fatto per `ftpa_preview_link`?
> 

Fatto.

2022-11-21 08:27 UTC, tafaRU commented
Grazie @primes2h. Un'ultima cosa: puoi _splittare_ i commit in due? Uno per ogni modulo coinvolto. Grazie.

2022-11-21 09:31 UTC, primes2h commented
@tafaRU 

Fatto!

2022-11-21 10:01 UTC, tafaRU approved these changes
Ti avevo erroneamente indicato:
> Uno per ogni modulo coinvolto

In questo caso specifico va bene come hai fatto ora tu:

![image](https://user-images.githubusercontent.com/3512779/203019781-9a8ed530-0969-40d4-a121-02b922f9f0b9.png)

infatti il primo dei due è corretto che contenga anche le modifiche a `l10n_it_fatturapa`  , spezzarli ulteriormente avrebbe infatti comportato l'aggiunta di un commit in cui il modulo non era funzionante.

L'ho anche testata su runboat :+1:

2022-11-21 10:06 UTC, primes2h commented
> Ti avevo erroneamente indicato:
> 
> > Uno per ogni modulo coinvolto
> 
> In questo caso specifico va bene come hai fatto ora tu:
> 
> ![image](https://user-images.githubusercontent.com/3512779/203019781-9a8ed530-0969-40d4-a121-02b922f9f0b9.png)
> 
> infatti il primo dei due è corretto che contenga anche le modifiche a `l10n_it_fatturapa` , spezzarli ulteriormente avrebbe infatti comportato l'aggiunta di un commit in cui il modulo non era funzionante.

Infatti mi sembrava l'unico modo per gestire correttamente la cosa.
Grazie!

2022-11-21 13:00 UTC, primes2h commented
/ocabot merge patch

2022-11-21 13:01 UTC, TheMule71 commented
Allora, la butto lì... 
visto che il metodo è statico, non so se chiamerei il parametro `self`, piuttosto `record` (esattamente come per i metodi di classe si preferisce `cls` invece di `self`).  E una mera questione di leggibilità.

E di conseguenza, i miei sensi di ragno mi dicono che forse un `ensure_one()` da qualche parte ci va, perché credo che  sia un recordset e da qualche parte (magari prima di chiamare il metodo statico) bisogna assicurarsi che la lunghezza sia 1 (altrimenti chiamerei la variabile `records` o `rset`).

2022-11-21 13:02 UTC, TheMule71 commented
Too late... :)

2022-11-21 13:22 UTC, merged