[FIX][l10n_it_fatturapa_in] Fix amount_total_signed sign
OCA/l10n-italy pull request #3042
Opened 2022-11-16 10:17 UTC by lorenzoallegrucci

2023-02-09 11:08 UTC, matteoopenf approved these changes

2023-02-09 12:24 UTC, TheMule71 commented
Servirebbe un test. Se un errore del genere non risulta, significa che nessuno dei 50 e passa test di fatturapa_in è mai andato a controllare l'importo totale...

2023-02-09 12:26 UTC, matteoopenf commented
> Servirebbe un test. Se un errore del genere non risulta, significa che nessuno dei 50 e passa test di fatturapa_in è mai andato a controllare l'importo totale...

Noi ci siamo accorti guardando sulla tree delle fatture fornitori.
Puoi fare un check sulla tree delle fatture fornitori delle tue istanze?

2023-02-09 12:37 UTC, TheMule71 requested changes

2023-02-09 12:37 UTC, TheMule71 commented on l10n_it_fatturapa_in/models/account.py
> +                sign = inv.move_type in ["in_refund", "out_refund"] and 1 or -1
Io francamente andrei meglio a rivedere la logica del metodo in super(). In particolare:
https://github.com/odoo/odoo/blob/14c985af526602a88666714e716283650521e537/addons/account/models/account_move.py#L848-L857

Prima cosa andrebbe usato `move.direction_sign` invece di cercare di calcolarlo noi.

Seconda cosa, di tutti campi che la `_compute_amount` riempie, vanno valutati quali cambiano. Può essere anche che in effetti non siano solo `amount_total` e `amount_total_signed`, ma anche `amount_total_in_currency_signed` da aggiornare.

Però dal codice `amount_total` è la somma delle `line.amount_currency` di ciascuna linea (valore in valuta della fattura) col `move.direction_sign`.  Invece `amount_total_signed` è la somma delle `line.balance` (valore nella valuta della company), col segno invertito per tutto ciò che non è una "entry" (è il nostro caso). E `amount_total_in_currency_signed` è ulteriormente diverso.

In più se effettivamente `amount_total_signed` è nella currency locale, l'arrotondamento andrebbe convertito prima di sommarlo.

2024-03-31 12:25 UTC, closed without merging

2026-05-18 12:46 UTC, patrickt-oforce commented
@TheMule71 che tu sappia, poi questa PR è stata rifatta con un'altra logica usando i tuoi suggerimenti?