[16.0][MIG] l10n_it_vat_registries
OCA/l10n-italy pull request #3080
Opened 2022-12-02 13:29 UTC by Borruso

Migration l10n_it_vat_registries from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2022-12-02 13:35 UTC, tafaRU commented
/ocabot migration l10n_it_vat_registries

2022-12-15 17:10 UTC, TonyMasciI requested changes
Revisione Tecnica:
- Installazione OK
- Test unitari OK

2023-01-13 10:33 UTC, marco-marchiori approved these changes
Cambia il layout, molto chiaro
Functional test OK

2023-02-27 08:04 UTC, andreampiovesana commented
Gli importi sono allineati a sx, li sposterei a dx, se visualizzo su browser si vedono box altrimenti su libreoffice o altri visualizatori pdf non si vedono, allego screenshot:

![image](https://user-images.githubusercontent.com/13952131/221507235-b01a608c-509c-4ace-a139-921b792092d2.png)

2023-06-09 15:35 UTC, andreampiovesana commented
> Gli importi sono allineati a sx, li sposterei a dx, se visualizzo su browser si vedono box altrimenti su libreoffice o altri visualizatori pdf non si vedono, allego screenshot:
> 
> ![image](https://user-images.githubusercontent.com/13952131/221507235-b01a608c-509c-4ace-a139-921b792092d2.png)

questo è ok?

2023-07-07 14:21 UTC, marcelofrare approved these changes
LGTM! grazie Giuseppe!

2023-07-07 14:22 UTC, andreampiovesana approved these changes
LGTM

2023-07-11 07:06 UTC, scigghia approved these changes
:+1:

2023-07-12 06:47 UTC, andreampiovesana commented
@TonyMasciI approvi?

2023-07-14 05:16 UTC, eLBati requested changes

2023-07-14 05:16 UTC, eLBati commented on l10n_it_vat_registries/models/vat_registry.py
> +            elif move_line.account_id.account_type == "liability_non_current":
Non dovrebbe essere `liability_payable`?

2023-07-14 05:16 UTC, eLBati commented on l10n_it_vat_registries/views/account_view.xml
> +                    name="cee_type"
Chissà se questo campo è effettivamente ancora usato da qualcuno. Si potrebbe fare un sondaggio ed eventualmente rimuoverlo.
Lo scrivo solo come appunto, non bloccante per la PR

2023-07-27 19:36 UTC, MaurizioPellegrinet approved these changes
LGTM

2023-08-25 14:43 UTC, gbtechnology commented
C'è qualche altra cosa che è bloccante per la PR?

2023-08-25 15:03 UTC, tafaRU commented
@eLBati puoi aggiornare la tua review?

2023-09-05 14:48 UTC, SirAionTech requested changes
Grazie della PR!
Potresti modificare la storia dei commit come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?

2023-09-07 06:54 UTC, andreampiovesana commented
merge @eLBati ?

2023-09-07 08:06 UTC, michelerusti commented
prendo in carico la PR

2023-09-07 10:21 UTC, Borruso commented on l10n_it_vat_registries/tests/test_registry.py
> +        invoice._onchange_quick_edit_line_ids()
vero però le poche funzioni rimaste in onchange senza non scattano

2023-09-07 10:23 UTC, Borruso commented on l10n_it_vat_registries/i18n/it.po
inclusi

2023-09-07 10:46 UTC, MarcoCalcagni approved these changes
Ok . test funzionali ok anche con le varie richieste fatte.

2023-09-07 10:50 UTC, newneo47 approved these changes
ok test

2023-09-07 11:18 UTC, SirAionTech requested changes

2023-09-07 11:18 UTC, SirAionTech commented on l10n_it_vat_registries/tests/test_registry.py
> +        invoice._onchange_quick_edit_line_ids()
> vero però le poche funzioni rimaste in onchange senza non scattano

Se serve eseguire tutti gli `onchange` allora è necessario creare la fattura con `Form`

2023-09-07 13:36 UTC, SirAionTech commented
Prendo in carico per fare le modifiche mancanti

2023-09-07 14:08 UTC, Borruso commented on l10n_it_vat_registries/tests/test_registry.py
> +        invoice._onchange_quick_edit_line_ids()
utilizzato `Form`

2023-09-07 14:12 UTC, SirAionTech commented on l10n_it_vat_registries/tests/test_registry.py
> +        invoice._onchange_quick_edit_line_ids()
> utilizzato `Form`

Non serve più grazie, ho rifatto direttamente la PR

2023-09-07 14:42 UTC, SirAionTech requested changes
Sostituita da https://github.com/OCA/l10n-italy/pull/3564

2023-09-07 15:33 UTC, closed without merging