[FIX][l10n_it_fatturapa_out_rc] fix currency problem in reverse charg…
OCA/l10n-italy pull request #3096
Opened 2022-12-22 11:07 UTC by matteoopenf

…e invoice

2022-12-26 10:39 UTC, TheMule71 requested changes

2022-12-26 10:39 UTC, TheMule71 commented on l10n_it_fatturapa_out/data/invoice_it_template.xml
> +                                t-esc="format_monetary(tax_data['ImponibileImporto'], euro)"
Questo toglie la conversione a tutte le fatture, non solo rc. Infatti spacca https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py#L697

2022-12-26 10:39 UTC, TheMule71 commented on l10n_it_fatturapa_out_rc/views/invoice_it_template.xml
> +                t-esc="format_monetary(fpa_to_eur(get_sign(record) * tax_data['Imposta'], record), currency)"
Se arrivati a questo punto tax_data['ImponibileImporto'] è già in euro e tax_data['Imposta'] è ancora in altra valuta, il problema direi che è altrove.

Qui a livello di template o si convertono entrambi o nessuno dei due. Convertire uno solo non ha molto senso, IMHO.

2022-12-26 10:59 UTC, matteoopenf commented
Di quale metodo potrei fare l’override per capire il colpevole? Ci ho girato molto da novembre, ma non ho trovato molto Matteo ***@***.*** Il giorno 26 dic 2022, alle ore 11:39, Marco Colombo ***@***.***> ha scritto:﻿
@TheMule71 requested changes on this pull request.



In l10n_it_fatturapa_out/data/invoice_it_template.xml:
> @@ -602,7 +602,7 @@ e 'line' per riga di fattura (a seconda del livello in cui sono chiamati)
                               <!--                <SpeseAccessorie t-esc=""/>-->
                               <!--                <Arrotondamento t-esc=""/>-->
                               <ImponibileImporto
-                                t-esc="format_monetary(fpa_to_eur(tax_data['ImponibileImporto'], record), euro)"
+                                t-esc="format_monetary(tax_data['ImponibileImporto'], euro)"

Questo toglie la conversione a tutte le fatture, non solo rc. Infatti spacca https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py#L697



In l10n_it_fatturapa_out_rc/views/invoice_it_template.xml:
> +                t-esc="format_monetary(get_sign(record) * tax_data['ImponibileImporto'], currency)"
             />
             </xpath>
             <xpath expr="//DatiRiepilogo/Imposta" position="replace">
+<!--                <Imposta-->
+<!--                t-esc="format_monetary(get_sign(record) * tax_data['Imposta'], currency)"-->
+<!--            />-->
                 <Imposta
-                t-esc="format_monetary(get_sign(record) * tax_data['Imposta'], currency)"
+                t-esc="format_monetary(fpa_to_eur(get_sign(record) * tax_data['Imposta'], record), currency)"

Se arrivati a questo punto tax_data['ImponibileImporto'] è già in euro e tax_data['Imposta'] è ancora in altra valuta, il problema direi che è altrove.
Qui a livello di template o si convertono entrambi o nessuno dei due. Convertire uno solo non ha molto senso, IMHO.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano

2022-12-26 11:03 UTC, matteoopenf commented
Altrimenti potrei provare a convertirli ove occorre dove genera il dizionario e qui sul template togliere la conversione.
Non so se possibile, ho buttato lì una soluzione.

2022-12-26 21:37 UTC, TheMule71 commented
Per me va mantenuta questa logica:
https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/data/invoice_it_template.xml#L231-L236

Ossia tutto in valuta estera in `account.move` e poi si convertono gli importi nel template.

Il modulo `l10n_fatturapa_out_rc` potrebbe anche fare l'override di:
https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L118
e cambiare il segno dove serve, invece di alterare il template.

2022-12-27 08:17 UTC, matteoopenf commented
> Per me va mantenuta questa logica:
> 
> https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/data/invoice_it_template.xml#L231-L236
> 
> Ossia tutto in valuta estera in `account.move` e poi si convertono gli importi nel template.
> 
> Il modulo `l10n_fatturapa_out_rc` potrebbe anche fare l'override di:
> 
> https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L118
> 
> 
> e cambiare il segno dove serve, invece di alterare il template.

ma il problema non è tanto il segno, ma proprio il valore che si ottiene da quel metodo che è già in valuta

2022-12-30 11:32 UTC, matteoopenf commented
> Per me va mantenuta questa logica:
> 
> https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/data/invoice_it_template.xml#L231-L236
> 
> Ossia tutto in valuta estera in `account.move` e poi si convertono gli importi nel template.
> 
> Il modulo `l10n_fatturapa_out_rc` potrebbe anche fare l'override di:
> 
> https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L118
> 
> 
> e cambiare il segno dove serve, invece di alterare il template.

ciao, ci sto ancora ragionando, ma se il valore arriva già convertito, che senso ha l'override?

2023-01-01 22:56 UTC, TheMule71 commented
> ciao, ci sto ancora ragionando, ma se il valore arriva già convertito, che senso ha l'override?

Il fatto è che non dovrebbe arrivare convertito.  Mettiamola così, se fosse già in euro e tutto il resto della fattura fosse in dollari, che succede quando la stampi?   Per me i valori devono essere tutti in dollari a livello di `account.move`.
Poi vengono convertiti da fatturapa_out dove serve.

2023-01-01 23:26 UTC, matteoopenf commented
> > ciao, ci sto ancora ragionando, ma se il valore arriva già convertito, che senso ha l'override?
> 
> 
> 
> Il fatto è che non dovrebbe arrivare convertito.  Mettiamola così, se fosse già in euro e tutto il resto della fattura fosse in dollari, che succede quando la stampi?   Per me i valori devono essere tutti in dollari a livello di `account.move`.
> 
> Poi vengono convertiti da fatturapa_out dove serve.

Scusa, ma sbaglio o sembra che sia proprio Odoo a convertire parzialmente i dati? Quindi è una sorta di bug di Odoo?

2023-11-20 09:13 UTC, matteoopenf commented on l10n_it_fatturapa_out/data/invoice_it_template.xml
> +                                t-esc="format_monetary(tax_data['ImponibileImporto'], euro)"
quindi dovrei cambiare il test?

2023-11-20 09:19 UTC, matteoopenf commented on l10n_it_fatturapa_out/data/invoice_it_template.xml
> +                                t-esc="format_monetary(tax_data['ImponibileImporto'], euro)"
puoi darmi un hint su come migliorare il test e portare a compimento la PR?
https://github.com/OCA/l10n-italy/blob/6aabdd6c271e11bfe1195e83892d235d4f1c3c13/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py#L741 potrebbe essere che non devo forzare la divisa qui?
Grazie mille

2023-11-29 13:46 UTC, matteoopenf commented on l10n_it_fatturapa_out/data/invoice_it_template.xml
> +                                t-esc="format_monetary(tax_data['ImponibileImporto'], euro)"
ho scoperto dopo varie prove che e' vero che questo test fallisce, ma che l'xml, che si testa e' a sua volta non valido, aggiorno la Issue tra poco

2023-11-29 13:58 UTC, francesco-ooops commented
@matteoopenf da chiudere?

2023-11-29 14:01 UTC, matteoopenf commented
> @matteoopenf da chiudere?

Sto arrivando su tutto quanto come sono apro la nuova chiudo questa.
Come già detto il test 15 è errato e entro sera conto di dettagliare la cosa

2023-12-01 16:12 UTC, closed without merging