[12.0] FIX reconcile_supplier_invoice setting currency to avoid redundant exchange_diff_move when not needed
OCA/l10n-italy pull request #3183
Opened 2023-02-21 20:07 UTC by eLBati

2023-03-05 13:08 UTC, eLBati commented on l10n_it_reverse_charge/models/account_invoice.py
> +            'currency_id': self.currency_id.id,
Grazie, modificato

2023-03-23 14:33 UTC, SirTakobi requested changes
Grazie della PR!
Per facilitare la tracciatura delle correzioni/migliorie sulle varie versioni, puoi aprire una issue aggiungendo la descrizione, tramite use case, del problema? (parafrasando https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue)

Hai modo di aggiungere un test?

Puoi adattare il messaggio del commit a https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? Ad esempio: ci sarebbe da menzionare il nome del modulo modificato e la prima riga andrebbe accorciata (puoi mettere tutti i dettagli nelle righe successive).

2023-11-17 15:56 UTC, odooNextev commented
@eLBati può essere che c'è anche nella 16?
Stiamo facendo dei test per migrare la nostra istanza da 14 e nella creazione di un'autofattura compare una differenza di cambio non necessaria che nella 14 non compariva.

![image](https://github.com/OCA/l10n-italy/assets/93990941/9700c672-c949-4a60-81f4-15c1b32f361c)

2024-01-18 11:06 UTC, eLBati commented
> può essere che c'è anche nella 16?

@odooNextev sì: https://github.com/OCA/l10n-italy/pull/3864

2024-01-19 08:59 UTC, TheMule71 requested changes

2024-01-19 08:59 UTC, TheMule71 commented on l10n_it_reverse_charge/models/account_invoice.py
> +            'currency_id': self.currency_id.id,
Da fare lo stesso su `rc_credit_line_vals()`?

2024-06-30 12:30 UTC, closed without merging