[ADD] l10n_it_fatturapa_out_fd
OCA/l10n-italy pull request #3186
Opened 2023-02-22 17:14 UTC by SirTakobi

Risolve #3185

2023-02-24 10:01 UTC, eLBati requested changes
SDI dice
"Per la fattura: INV/2020/0001 del 2020-01-01 - Per il valore indicato nell'elemento 2.1.1.1 <TipoDocumento> il cedente/prestatore non può essere uguale al cessionario/committente"
@SirTakobi puoi modificare l'XML?
Grazie

2023-02-24 11:48 UTC, SirTakobi commented
Grazie della review!
Puoi verificare se ora va meglio?

2023-02-24 17:11 UTC, eLBati approved these changes
Grazie

2023-03-13 13:10 UTC, eLBati requested changes

2023-03-13 13:10 UTC, eLBati commented on l10n_it_fatturapa_out_fd/wizards/wizard_export_fatturapa.py
> +                    Percentuale='%.2f' % float_round(discount_fixed, 8),
Qua penso ci vada `Importo`

2023-03-13 13:10 UTC, eLBati commented on l10n_it_fatturapa_out_fd/tests/data/IT06363391001_00001.xml
> +                <PrezzoUnitario>100.00000</PrezzoUnitario>
Userei un prezzo diverso, in base al quale non si abbia `PrezzoTotale` = 80 sia con `Percentuale` che `Importo`

2023-03-14 09:15 UTC, SirTakobi commented on l10n_it_fatturapa_out_fd/wizards/wizard_export_fatturapa.py
> +                    Percentuale='%.2f' % float_round(discount_fixed, 8),
Giusto, ho corretto, puoi verificare se ora va meglio?

2023-03-14 09:52 UTC, eLBati approved these changes
Grazie

2024-01-16 11:36 UTC, primes2h commented
/ocabot rebase

2024-01-29 11:12 UTC, primes2h approved these changes
LGTM

Grazie!

Fix per test rosso https://github.com/OCA/l10n-italy/pull/3909

2024-01-29 13:45 UTC, primes2h commented
/ocabot rebase

2024-01-29 14:06 UTC, primes2h commented
/ocabot merge nobump

2024-01-29 14:31 UTC, merged