[16.0][MIG] l10n_it_fatturapa_pec
OCA/l10n-italy pull request #3190
Opened 2023-02-24 09:18 UTC by Borruso

2023-02-24 11:04 UTC, tafaRU commented
/ocabot migration l10n_it_fatturapa_pec

2023-07-21 11:50 UTC, TheMule71 approved these changes
LGTM

2023-09-07 07:59 UTC, marcelofrare approved these changes
LGTM

2023-09-07 08:41 UTC, eLBati requested changes
Sulla 14 sono state rilasciate queste modifiche https://github.com/OCA/l10n-italy/pull/3118 che quindi sarebbero da includere in questo modulo, verificando che anche gli altri moduli coinvolti siano aggiornati

2023-09-07 08:52 UTC, eLBati commented
La PR https://github.com/OCA/l10n-italy/pull/3118 modifica altri moduli che sono già merged su 14.0, quindi conviene fare il merge di questa e poi portare la https://github.com/OCA/l10n-italy/pull/3118 alla 16

2023-09-07 08:57 UTC, eLBati approved these changes

2023-09-07 08:57 UTC, eLBati commented
/ocabot merge nobump

2023-09-07 09:12 UTC, merged