[14.0][mig]l10n italy sale commission riba
OCA/l10n-italy pull request #3230
Opened 2023-03-23 16:20 UTC by odooNextev

2023-03-24 07:43 UTC, odooNextev commented
@tafaRU sapresti dirci come poter risolvere questo problema?
https://github.com/OCA/l10n-italy/actions/runs/4502926903/jobs/7925438831?pr=3230#step:6:5
Fondamentalmente il problema è che il nostro modulo dipende da `l10n_it_ricevute_bancarie` che è in stato alpha, però non dovrebbe aver raggiunto uno stato superiore visto che è stato pubblicato da un po'?
Perdonami se sto sbagliando qualcosa, ma non conosco bene gli stati e la loro assegnazione

2023-03-24 08:29 UTC, tafaRU commented
> @tafaRU sapresti dirci come poter risolvere questo problema?

Abbiamo tre strade che elenco in ordine di mia preferenza:
1. promuovere `l10n_it_ricevute_bancarie` a `Beta`
2. impostare esplicitamente `in `l10n_it_sale_commission_riba` la chiave development_status`  a `Alpha`
3. disabilitare il controllo a livello di repository sfruttando https://github.com/OCA/oca-addons-repo-template/blob/3a63f6cc9d6825b4d5ce74c85754659de3fcca0b/copier.yml#L134

Per portare avanti il punto 1 devi creare una PR in cui semplicemente cambi il valore della la chiave `development_status`. Per ulteriori info al riguardo puoi fare riferimento a https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_development_status.rst

2023-03-24 13:17 UTC, odooNextev commented
@primes2h abbiamo modificato il nome del modulo come avevi richiesto per la v14.0, tra poco faccio anche la v12.0

2023-03-30 09:08 UTC, GSLabIt commented on l10n_it_riba_sale_commission/i18n/it.po
> +#: model:ir.model.fields,field_description:l10n_it_riba_sale_commission .field_account_invoice__no_commission
c'è uno spazio di troppo, verifica anche il resto del file perché si ripete.

2023-04-03 13:52 UTC, stefano-ooops approved these changes
testato ok

2023-04-04 14:10 UTC, GSLabIt commented on l10n_it_riba_sale_commission/README.rst
> +Richiede almeno la versione 3.3.1 del modulo ``sale_commission``
l'ultima versione è la `14.0.1.5.2`, typo?

2023-04-04 14:10 UTC, GSLabIt commented on l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
> +E' possibile inserire aggiungere "Senza commissioni" ad una fattura, in modo
typo

2023-04-04 14:10 UTC, GSLabIt commented on l10n_it_riba_sale_commission/views/invoice_no_commission.xml
> +        <field name="name">invoice.no.commission.form</field>
meglio aggiungere il nome del modello `account.move.invoice.no.commission.form`

2023-04-04 14:10 UTC, GSLabIt commented on l10n_it_riba_sale_commission/wizard/wizard_riba_commissions_settle.py
> +                riba_mv_line = self.env["riba.distinta.move.line"].search(
si potrebbe già applicare il filtro alla super, tipo : 
```
agent_lines = super()._get_agent_lines(agent, date_to_agent) \
.filtered(lambda al: not al.invoice_id.no_commission) \
.filtered(lambda r: r.invoice_payment_term_id.riba)

for line in agent_lines:
    riba_mv_line = self.env["riba.distinta.move.line"].search(
    ...

2023-04-11 12:06 UTC, francesco-ooops approved these changes
dopo queste dovremmo essere a posto

2023-04-11 12:06 UTC, francesco-ooops commented on l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
> +E' possibile inserire aggiungere "Senza commissioni" ad una fattura, in modo
@odooNextev scusate la pedanteria, se potete rimuovere uno tra "inserire" e "aggiungere" e sostituire "commissioni" con "provvigioni"

2023-04-11 12:06 UTC, francesco-ooops commented on l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
> +Il modulo permette di integrare il pagamento riba con le commissioni agenti.
sostituire "commissioni" con "provvigioni"

2023-04-14 08:14 UTC, francesco-ooops commented
@OCA/local-italy-maintainers possiamo mergiare?

2023-04-14 08:18 UTC, primes2h commented
@francesco-ooops in giornata vedo di dargli un'occhiata.

2023-04-17 16:12 UTC, primes2h requested changes
Qualche suggerimento e correzione della parte documentale secondo le linee guida.

2023-04-21 07:49 UTC, francesco-ooops commented
@odooNextev riuscite a fixare?

2023-04-21 14:06 UTC, primes2h requested changes

2023-04-21 14:06 UTC, primes2h commented on l10n_it_riba_sale_commission/i18n/it.po
> +msgstr "Wizard per creare la liquidazione delle commissioni nelle fatture"
_commissions_ → _provvigioni_
_Wizard_ in genere si traduce con _Procedura guidata_. 
Se dalla stringa è chiaro il contesto è sufficiente _Procedura_, anche in caso di frasi che diventerebbero troppo lunghe.



```suggestion
msgstr "Procedura per la liquidazione delle provvigioni nelle fatture"
```

2023-04-26 08:18 UTC, francesco-ooops commented
@primes2h tutto ok ora?

2023-04-26 15:18 UTC, primes2h requested changes

2023-04-27 13:06 UTC, primes2h commented
@odooNextev per richiedere di nuovo la revisione della PR dopo una modifica, invece di un messaggio ti conviene fare così:

![immagine](https://user-images.githubusercontent.com/227940/234869337-167e1a2d-2f71-40c0-abba-db5a27386288.png)

Dopo il clic sul simbolo, cerca la persona alla quale vuoi richiedere la revisione.

P.S.: visto il commento che aveva fatto qui https://github.com/OCA/l10n-italy/pull/3204#discussion_r1137216037 e le modifiche conseguenti, ti conviene chiedere una nuova revisione anche a @tafaRU.

2023-04-28 08:07 UTC, tafaRU approved these changes

2023-04-28 08:07 UTC, tafaRU commented
/ocabot merge nobump

2023-04-28 08:17 UTC, SirTakobi commented
> @odooNextev per richiedere di nuovo la revisione della PR dopo una modifica, invece di un messaggio ti conviene fare così:
> 
> ![immagine](https://user-images.githubusercontent.com/227940/234869337-167e1a2d-2f71-40c0-abba-db5a27386288.png)
> 
> Dopo il clic sul simbolo, cerca la persona alla quale vuoi richiedere la revisione (o aggiornare una esistente).

I normali contributor non vedono il :gear: ma possono solo richiedere la review di chi è già tra i reviewer: 
![image](https://user-images.githubusercontent.com/101628000/235093936-d70769e8-93d8-48f7-9dca-02f6850a7712.png)

2023-04-28 08:39 UTC, merged

2023-05-03 09:03 UTC, primes2h commented
> > @odooNextev per richiedere di nuovo la revisione della PR dopo una modifica, invece di un messaggio ti conviene fare così:
> > ![immagine](https://user-images.githubusercontent.com/227940/234869337-167e1a2d-2f71-40c0-abba-db5a27386288.png)
> > Dopo il clic sul simbolo, cerca la persona alla quale vuoi richiedere la revisione (o aggiornare una esistente).
> 
> I normali contributor non vedono il gear ma possono solo richiedere la review di chi è già tra i reviewer: ![image](https://user-images.githubusercontent.com/101628000/235093936-d70769e8-93d8-48f7-9dca-02f6850a7712.png)


:+1: 
Hai ragione, grazie per l'osservazione.