[14.0][ADD] SEPA credit transfer for Italy
OCA/l10n-italy pull request #3254
Opened 2023-04-04 14:44 UTC by caiuka

Riprende la [#3215](https://github.com/OCA/l10n-italy/pull/3215) chiusa per errore, ed implementa quindi la [#3203](https://github.com/OCA/l10n-italy/issues/3203).

Segue lo stesso funzionamento del modulo di bank-payment, basta scegliere il pain indicato per l'Italia.

Utilizza la libreria Fintech, per esportare un file XML 100% compliant con le banche italiane.

2023-04-04 14:48 UTC, matteoopenf commented
puoi fixare quello che ti avevo detto nell'altra pr?

2023-04-06 09:39 UTC, francesco-ooops commented
@matteoopenf dipendenza aggiunta, review? :)

2023-04-06 10:43 UTC, matteoopenf approved these changes

2023-04-06 10:43 UTC, matteoopenf commented
> @matteoopenf dipendenza aggiunta, review? :)

done

2023-04-11 13:22 UTC, francesco-ooops commented
@OCA/local-italy-maintainers qualche idea del perchè aggiungere la versione minima della libreria fintech non venga accettato dal precommit? 

Grazie!

2023-04-11 14:59 UTC, SirTakobi commented
> @SirTakobi Perché continua a dare errore?

Andava lasciato nel `requirements.txt`, come sta indicando il log di pre-commit:
```
diff --git a/requirements.txt b/requirements.txt
index fe9f55f..a3e73d7 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -2,6 +2,7 @@
 asn1crypto
 codicefiscale
 elementpath
+fintech>=7.2.10
 openupgradelib
 unidecode
 xlrd
``` 
(da https://github.com/OCA/l10n-italy/actions/runs/4668774101/jobs/8266295256?pr=3254#step:7:53)

L'hook `setuptools-odoo-get-requirements` genera il file `requirements.txt` in base a quello che trova nei manifest e nei setup dei moduli, e controlla che coincida con il file `requirements.txt`.
Se ci sono delle differenze, fallisce e stampa il diff.

2023-04-11 15:08 UTC, caiuka commented
> Andava lasciato nel `requirements.txt`, come sta indicando il log di pre-commit:
> 
> ```

Ti ringrazio molto, ti devo una birra alla prima occasione!

2023-04-14 08:24 UTC, GSLabIt requested changes

2023-04-14 08:24 UTC, GSLabIt commented on l10n_it_account_banking_sepa_credit_transfer/__manifest__.py
> +    "external_dependencies": {"python": ["fintech"]},
```suggestion
    "external_dependencies": {"python": ["fintech>=7.2.10"]},
```

2023-04-21 10:17 UTC, stefano-ooops approved these changes
ok funziona

2023-04-21 10:56 UTC, GSLabIt commented on l10n_it_account_banking_sepa_credit_transfer/models/account_payment_line.py
> +            record.line_sequence = line_sequence
come la vedi una cosa del genere?

```
        for _id, record in enumerate(self.order_id.payment_line_ids):
            record.sequence = _id + 1
```

2023-04-24 09:40 UTC, caiuka commented on l10n_it_account_banking_sepa_credit_transfer/models/account_payment_line.py
> +            record.line_sequence = line_sequence
La vedo benissimo! 👍 
Grazie 😀

2023-04-24 11:24 UTC, GSLabIt approved these changes

2023-04-27 08:28 UTC, francesco-ooops commented
@OCA/local-italy-maintainers ci sono diverse PR aperte che aggiungono repo al file oca_dependencies, e questo non permette di gitaggregarle correttamente. 

Si può procedere ad un merge rapido?

Grazie!

2023-04-28 08:18 UTC, tafaRU commented
> @OCA/local-italy-maintainers ci sono diverse PR aperte che aggiungono repo al file oca_dependencies, e questo non permette di gitaggregarle correttamente.

Il file `oca_dependencies.txt` per i repository che hanno GitHub Actions come CI non serve più. Le dipendenze appartenenti ad altri repository vengono risolti in automatico, vedi:

* https://github.com/OCA/l10n-italy/actions/runs/4784820794/jobs/8506783815?pr=3254#step:4:17
* https://github.com/OCA/l10n-italy/actions/runs/4784820794/jobs/8506783815?pr=3254#step:4:20

2023-04-28 14:13 UTC, francesco-ooops commented
@tafaRU dobbiamo rimuovere il file oca_dependencies a seguito di #3296 ?

2023-04-28 14:30 UTC, tafaRU commented
> @tafaRU dobbiamo rimuovere il file oca_dependencies a seguito di #3296 ?

sì grazie

2023-04-28 14:39 UTC, francesco-ooops commented
@caiuka puoi procedere?

2023-05-01 08:10 UTC, caiuka commented
@matteoopenf @SirTakobi @GSLabIt Review? 🙏

2023-05-01 08:46 UTC, matteoopenf approved these changes

2023-05-02 14:13 UTC, GSLabIt commented
/ocabot rebase

2023-05-02 14:15 UTC, GSLabIt commented
@caiuka puoi fare rebase?

2023-05-03 09:05 UTC, primes2h commented
/ocabot rebase

2023-05-04 09:59 UTC, francesco-ooops commented
@As400it questo può tornare utile? :)

2023-05-08 09:31 UTC, SirTakobi commented
> > @primes2h The rebase process failed, because command `git push --force berim-it tmp-pr-3254:14.0-l10n_it_account_banking_sepa_credit_transfer` failed with output:
> > ```
> > remote: Permission to berim-it/l10n-italy.git denied to OCA-git-bot.
> > fatal: unable to access 'https://github.com/berim-it/l10n-italy/': The requested URL returned error: 403
> > ```
> 
> vedo che questo problema compare in molte pr non solo su questa

Credo possa dipendere dal check 
![image](https://user-images.githubusercontent.com/101628000/236789286-db84b0cb-ad8d-47d9-a191-7b1b4b72e80a.png)

@caiuka puoi verificare se è abilitato in questa PR?

2023-05-08 10:07 UTC, matteoopenf commented
> > > @primes2h The rebase process failed, because command `git push --force berim-it tmp-pr-3254:14.0-l10n_it_account_banking_sepa_credit_transfer` failed with output:
> 
> > > ```
> 
> > > remote: Permission to berim-it/l10n-italy.git denied to OCA-git-bot.
> 
> > > fatal: unable to access 'https://github.com/berim-it/l10n-italy/': The requested URL returned error: 403
> 
> > > ```
> 
> > 
> 
> > vedo che questo problema compare in molte pr non solo su questa
> 
> 
> 
> Credo possa dipendere dal check 
> 
> ![image](https://user-images.githubusercontent.com/101628000/236789286-db84b0cb-ad8d-47d9-a191-7b1b4b72e80a.png)
> 
> 
> 
> @caiuka puoi verificare se è abilitato in questa PR?

Ho letto questo post https://github.com/community/community/discussions/24618#discussioncomment-5821143 non è che come alcuni mesi fa GitHub ha cambiato qualcosa e quindi ora il comando non va per quello?

2023-05-08 10:17 UTC, SirTakobi commented
> Ho letto questo post https://github.com/orgs/community/discussions/24618#discussioncomment-5821143 non è che come alcuni mesi fa GitHub ha cambiato qualcosa e quindi ora il comando non va per quello?

Ho letto solo il post linkato e si riferisce a un deploy del 5-6 Maggio, mentre qui l'errore (https://github.com/OCA/l10n-italy/pull/3254#issuecomment-1532684963) è del 3 Maggio quindi non credo possa influire.

2023-05-08 12:05 UTC, SirTakobi commented
:man_shrugging: forse lo puoi vedere con l'utente proprietario del branch https://github.com/berim-it/l10n-italy/tree/14.0-l10n_it_account_banking_sepa_credit_transfer?
Io di solito uso branch del mio utente nelle PR per questo pensavo fosse l'autore a poter vedere il check

2023-05-08 12:24 UTC, primes2h commented
> > > Ma non riesco a trovare dove abilitare, potresti indicarmi?
> > 
> Incredibilmente non sembra esserci
> 
> ![image](https://user-images.githubusercontent.com/1492435/236809127-6d87c9ab-b4cd-4180-8519-cf3fbc932776.png)

Prova a verifcare se riesci a vederlo da PC.

2023-05-10 09:18 UTC, caiuka commented
> > > > Ma non riesco a trovare dove abilitare, potresti indicarmi?
> > 
> > 
> > Incredibilmente non sembra esserci
> > ![image](https://user-images.githubusercontent.com/1492435/236809127-6d87c9ab-b4cd-4180-8519-cf3fbc932776.png)
> 
> Prova a verifcare se riesci a vederlo da PC.

Niente, anche da PC.
L'utente è quello di creazione del fork e della PR.
Ho cercato più o meno ovunque quella impostazione.

2023-05-10 15:38 UTC, francesco-ooops commented
@caiuka ok per te se la chiudiamo e portiamo avanti in #3301 ?

2023-05-10 16:06 UTC, closed without merging

2023-05-26 14:04 UTC, gbtechnology commented
Salve a tutti.
@caiuka per caso la PR è stata chiusa per sbaglio?

Ad ogni modo un try except lo metterei in generate_payment_file: ho fatto diversi test e si rompe in alcuni punti dove mancano info necessarie. Prendi ad esempio name=self.company_partner_bank_id.acc_holder_name a linea 67: acc_holder_name non mi pare sia un parametro obblicatorio nell'account bancario quindi se manca si rompe. Idem in debtor.set_originator_id(cuc=cuc) quando nel controllo il cuc viene rilevato come non corretto.

Per una persona tecnica i messaggi di errori sono sufficienti a capire cosa manca/cosa è sbagliato, ma forse gestire il tutto con delle exception che rimandano a uno UserError potrebbe essere un'idea.

2023-05-26 14:13 UTC, gbtechnology commented
Ah grazie @caiuka mi era sfuggito :+1: