[MIG] l10n_it_pos_fatturapa: Migration to 14.0
OCA/l10n-italy pull request #3315
Opened 2023-05-19 09:31 UTC by caiuka

Migrazione del modulo dalla v12 alla v14

2023-05-25 16:24 UTC, OpenCode commented
> possiamo aggiungere a #1905 ?

Fatto

2023-05-29 08:27 UTC, GSLabIt commented on l10n_it_pos_fatturapa/static/src/js/ClientDetailsEdit.js
> +            }
non mi pare sia strettamente necessario

2023-05-30 08:35 UTC, francesco-ooops commented
@robyf70 quando hai un momento ;)

2023-06-06 14:46 UTC, robyf70 requested changes
Il resto LGTM

2023-06-06 14:46 UTC, robyf70 commented on l10n_it_pos_fatturapa/static/src/js/ClientDetailsEdit.js
> +            }
Non necessario

2023-06-06 15:40 UTC, iw3hxn commented on l10n_it_pos_fatturapa/models/res_partner.py
> +            electronic_invoice_subjected = bool(
no, ritorna un None

2023-06-09 10:22 UTC, francesco-ooops commented
@robyf70 @GSLabIt ok ora?

2023-06-14 08:05 UTC, francesco-ooops commented
@caiuka rebase

2023-06-29 06:45 UTC, closed without merging