[IMP] Nuovo modulo per corretta fatturazione KIT da DDT
OCA/l10n-italy pull request #3320
Opened 2023-05-22 09:45 UTC by SirTakobi

Forward port di https://github.com/OCA/l10n-italy/pull/1337 a `12.0`.
Migrazione di https://github.com/OCA/l10n-italy/pull/1336 a `12.0`.
Implementa https://github.com/OCA/l10n-italy/issues/1335 per `12.0`.

2023-05-22 10:34 UTC, eLBati requested changes

2023-05-22 10:34 UTC, eLBati commented on l10n_it_ddt_mrp_kit/__manifest__.py
> +    ],
Penso convenga aggiungere `auto_install` altrimenti la fatturazione dei kit non funziona proprio

2023-05-22 13:02 UTC, SirTakobi commented on l10n_it_ddt_mrp_kit/__manifest__.py
> +    ],
:+1:

2023-05-22 13:03 UTC, SirTakobi commented on l10n_it_ddt_mrp_kit/tests/test_td_invoice_kit.py
> +        self.assertCountEqual(
Grazie della review!
Ero preoccupato per l'ordine dei prodotti, ma ho fatto una piccola modifica in modo che non sia un problema.
Puoi controllare se ora va meglio?

2023-05-22 13:16 UTC, eLBati approved these changes
Grazie

2023-07-09 16:18 UTC, mrcast approved these changes
Functional test, ok!

2023-07-17 05:42 UTC, eLBati commented
/ocabot merge nobump

2023-07-17 06:53 UTC, merged