[16.0][MIG] l10n_it_intrastat_statement
OCA/l10n-italy pull request #3327
Opened 2023-05-25 07:37 UTC by Borruso

Migration l10n_it_intrastat_statement from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-05-25 07:41 UTC, tafaRU commented
/ocabot migration l10n_it_intrastat_statement

2023-09-08 08:40 UTC, TheMule71 commented
Pura curiosità, vedo https://github.com/Borruso/l10n-italy/blob/c5e310ae4fd0da8e941ed7ba6558bb3bce55755e/l10n_it_intrastat_statement/report/report_intrastat_mod1.xml#L7
che usano `web.internal_layout`, c'entra qualcosa con `l10n_it_account.internal_layout` e sarebbe meglio usare quello o non c'entra nulla?

2023-09-08 13:15 UTC, Borruso commented
> Pura curiosità, vedo https://github.com/Borruso/l10n-italy/blob/c5e310ae4fd0da8e941ed7ba6558bb3bce55755e/l10n_it_intrastat_statement/report/report_intrastat_mod1.xml#L7 che usano `web.internal_layout`, c'entra qualcosa con `l10n_it_account.internal_layout` e sarebbe meglio usare quello o non c'entra nulla?

in realtà non ti so dire c'è la stessa cosa in v14

2023-09-29 10:56 UTC, SirAionTech requested changes
I test sono :x:, puoi verificare?

2023-09-29 12:54 UTC, Borruso commented
> I test sono ❌, puoi verificare?

fatto rabase test rossi per dipendenza

2023-09-30 15:02 UTC, primes2h commented
@Borruso
ci sarebbe da aggiungere qeusto commit https://github.com/OCA/l10n-italy/pull/3543/commits/b92edb226952d6a391465d29d162f7380d0bda4c

2023-09-30 15:10 UTC, Borruso commented
> @Borruso ci sarebbe da aggiungere qeusto commit [b92edb2](https://github.com/OCA/l10n-italy/commit/b92edb226952d6a391465d29d162f7380d0bda4c)

@primes2h ecco a te https://github.com/OCA/l10n-italy/pull/3622

2023-10-02 09:51 UTC, primes2h commented
> > @Borruso ci sarebbe da aggiungere qeusto commit [b92edb2](https://github.com/OCA/l10n-italy/commit/b92edb226952d6a391465d29d162f7380d0bda4c)
> 
> @primes2h ecco a te #3622 appena si mergia qui faccio un rebase

Grazie!

2023-10-02 13:23 UTC, SirAionTech requested changes
Grazie della PR!
Manca qualche commit di `14.0`, tipo https://github.com/OCA/l10n-italy/commit/e7c3c5efae04c7f7ef2958b72fe3c5a987933b0d, li potresti aggiungere?

Ci sono traduzioni consecutive dello stesso traduttore, ad esempio 
![image](https://github.com/OCA/l10n-italy/assets/143788994/fbbc2aea-1666-4f77-af74-3de051fb64a0)
, le potresti schiacciare come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate?

2023-10-02 13:23 UTC, SirAionTech commented on l10n_it_intrastat_statement/wizard/export_file.py
> +            view_id = False
È possibile evitare di cercare più volte lo stesso riferimento esterno? Va bene che sono nella cache ma è comunque un'operazione che si può evitare.
Penso che questo sia più vicino al codice del modulo prima della migrazione, cosa ne pensi?
```suggestion
        view = self.env.ref(
            "l10n_it_intrastat_statement.wizard_account_intrastat_export_file"
        )
        view_id = view.id
```

2023-10-03 06:21 UTC, Borruso commented on l10n_it_intrastat_statement/wizard/export_file.py
> +            view_id = False
fatto

2023-10-03 06:21 UTC, Borruso commented
> Grazie della PR! Manca qualche commit di `14.0`, tipo [e7c3c5e](https://github.com/OCA/l10n-italy/commit/e7c3c5efae04c7f7ef2958b72fe3c5a987933b0d), li potresti aggiungere?
> 
> Ci sono traduzioni consecutive dello stesso traduttore, ad esempio ![image](https://user-images.githubusercontent.com/143788994/271977600-fbbc2aea-1666-4f77-af74-3de051fb64a0.png) , le potresti schiacciare come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate?

fatto

2023-10-03 09:43 UTC, SirAionTech commented
> > Grazie della PR! Manca qualche commit di `14.0`, tipo [e7c3c5e](https://github.com/OCA/l10n-italy/commit/e7c3c5efae04c7f7ef2958b72fe3c5a987933b0d), li potresti aggiungere?
> > Ci sono traduzioni consecutive dello stesso traduttore, ad esempio ![image](https://user-images.githubusercontent.com/143788994/271977600-fbbc2aea-1666-4f77-af74-3de051fb64a0.png) , le potresti schiacciare come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate?
> 
> fatto

Grazie, quando hai finito con le modifiche ricorda per favore di chiedermi di aggiornare la revisione in 
![image](https://github.com/OCA/l10n-italy/assets/143788994/ac624128-103c-44cd-a0aa-76342b4fb34d)

2023-10-05 14:07 UTC, SirAionTech approved these changes

2023-10-05 20:12 UTC, andreampiovesana approved these changes
LGTM - functional test ok

2023-10-05 20:13 UTC, MaurizioPellegrinet approved these changes
LGTM

2023-10-06 07:17 UTC, tafaRU approved these changes

2023-10-06 07:17 UTC, tafaRU commented
/ocabot merge nobump

2023-10-06 07:43 UTC, merged