16.0 mig l10n it fiscalcode sale
OCA/l10n-italy pull request #3342
Opened 2023-05-30 12:57 UTC by odooNextev

2023-05-30 12:58 UTC, tafaRU commented
/ocabot migration l10n_it_fiscalcode_sale

2023-07-06 17:01 UTC, tafaRU commented
@odooNextev non vedo il commit `... pre-commit stuff`: puoi verificare?

2023-07-07 06:34 UTC, odooNextev commented
> @odooNextev non vedo il commit `... pre-commit stuff`: puoi verificare?

Pensavo servisse solo per le operazioni preliminari e poi alla fine si squasha tutto in uno di migrazione "[MIG] nome modulo"
Se devo rimetterlo devo resettare e rifare

2023-07-07 07:12 UTC, tafaRU commented
@odooNextev trattandosi di una migrazione di un modulo occorre seguire le indicazioni contenute in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

2023-07-07 13:38 UTC, odooNextev commented
@tafaRU adesso ricordo...
Tecnicamente il commit "[[MIG] l10n_it_fiscalcode_sale: Migration to 16.0](https://github.com/OCA/l10n-italy/pull/3342/commits/dbf1d83ab0d8f2034df339944beee8619813bbfa)" sarebbe  `... pre-commit stuff`, ma a cui ho cambiato il nome con `reword` perchè altrimenti avrei dovuto fare un commit vuoto per "[MIG] $module: Migration to 16.0".
L'unica modifica di cui il modulo necessità per funzionare sulla 16 è quella della version nel manifest che è obbligatoria per fare un commit con precommit attivato.

Faccio il reword per ripristinare il nome e poi un commit vuoto con "[MIG] $module: Migration to 16.0"?

2023-07-07 14:59 UTC, tafaRU commented
> perchè altrimenti avrei dovuto fare un commit vuoto per "[MIG] $module: Migration to 16.0".

il  cambio della versione non è sufficiente?

2023-07-07 15:01 UTC, odooNextev commented
> > perchè altrimenti avrei dovuto fare un commit vuoto per "[MIG] $module: Migration to 16.0".
> 
> il cambio della versione non è sufficiente?

Precommit mi obbliga a farlo nel "suo" commit `pre-commit stuff` perchè fallisce altrimenti con la versione non giusta quindi dopo non abbiamo più niente da modificare

2023-07-07 15:04 UTC, tafaRU commented
> Precommit mi obbliga a farlo nel "suo" commit `pre-commit stuff` perchè fallisce altrimenti con la versione non giusta quindi dopo non abbiamo più niente da modificare

Ok ma se adesso sposti il cambio di versione, dovrebbe andare a posto, no?

2023-07-07 15:29 UTC, odooNextev commented
> > Precommit mi obbliga a farlo nel "suo" commit `pre-commit stuff` perchè fallisce altrimenti con la versione non giusta quindi dopo non abbiamo più niente da modificare
> 
> Ok ma se adesso sposti il cambio di versione, dovrebbe andare a posto, no?

Ho capito dove sbagliavo... non mettevo `--no-verify` nel commit di pre-commit...
Adesso però smanettendo sul branch mi ha cancellato i commit di Lorenzo della v12...

2023-07-07 15:52 UTC, MarcoCalcagni approved these changes
Ok test funzionali

2023-07-07 15:53 UTC, MarcoCalcagni commented
@tafaRU @TheMule71 @eLBati  
mergiabile

2023-07-07 19:29 UTC, odooNextev commented
No Marco non può essere mergiata perché mi si è cancellata l’history delle versioni precedenti.Lunedì la rifaccio in poco tempo.Il giorno 7 lug 2023, alle ore 17:53, 'Marco Calcagni' via Odoo ***@***.***> ha scritto:﻿
@tafaRU @TheMule71 @eLBati
mergiabile

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-10 07:58 UTC, tafaRU requested changes
Rimane un'ultima cosa da fare: schiacciare i commit amministrativi.

![image](https://github.com/OCA/l10n-italy/assets/3512779/a850d184-b206-4bab-9f00-9f9763143e5e)

I blocchi evidenziati con il riquadro rosso li puoi schiacciare con il commit precedente.

**Hint**: utilizzare i *tip* presenti in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

Grazie!

2023-07-10 08:58 UTC, closed without merging