[16.0][FIX] - account_vat_period_end_statement - wrong trees proportions
OCA/l10n-italy pull request #3380
Opened 2023-06-14 06:34 UTC by michelerusti

Fixes #3231 e #3375 per la 16.0

2023-06-14 07:12 UTC, tafaRU commented
@andreampiovesana @maxgrassi potete testarla e fare una review?

2023-06-14 08:18 UTC, maxgrassi commented
Testata, allego screen di come risulta ora in visualizzazione:

<img width="1435" alt="liquidazione-iva" src="https://github.com/OCA/l10n-italy/assets/18476727/773e872d-5b76-4634-9bdd-0e475539868e">

2023-06-14 08:27 UTC, tafaRU commented
grazie @maxgrassi, per favore aggiungi la tua review, non solo un commento.

![image](https://github.com/OCA/l10n-italy/assets/3512779/f0933240-2120-4838-abfa-d534e3059fa3)

2023-06-14 16:42 UTC, andreampiovesana approved these changes
LGTM

2023-06-15 07:49 UTC, MaurizioPellegrinet commented
Mi risulta ancora questa vista ...
![photo1686778730](https://github.com/OCA/l10n-italy/assets/130933959/e77e16fd-840b-4a21-b602-2a7b3bf53f55)

2023-06-15 08:09 UTC, tafaRU requested changes
@michelerusti puoi verificare l'ultima segnalazione?

Anche a me provando su runboat risulta così:

![image](https://github.com/OCA/l10n-italy/assets/3512779/45e508a5-66c9-45ac-9d3b-0771a7b2cc33)

2023-06-15 18:10 UTC, michelerusti commented
> @michelerusti puoi verificare l'ultima segnalazione?
> 
> Anche a me provando su runboat risulta così:
> 
> ![image](https://user-images.githubusercontent.com/3512779/246039646-45e508a5-66c9-45ac-9d3b-0771a7b2cc33.png)

@tafaRU il problema sta in come odoo si aspetta di fromattare le form
In questo caso, mette[ una regola CSS](https://github.com/odoo/odoo/blob/9ee022362a098359c78fd1cdb53287dab4d5b298/addons/web/static/src/views/form/form_controller.scss#L475-L477C33) che va a spaccare in due colonne la grid forzando quella di sinistra a 150px

**Se** volessimo continuare ad avere le due `<tree>` di fianco, dobbiamo forzare il parametro a, ad esempio:
`grid-template-columns: fit-content(150px) 1fr;`
Ma dovrei sovrascrivere la regola nel foglio di stile di questo modulo

In alternativa potremmo metterle una sopra l'altra cambiando solo la vista.


Quale pensi sia l'opzione migliore?

2023-06-16 13:59 UTC, andreampiovesana commented
![immagine](https://github.com/OCA/l10n-italy/assets/13952131/75360049-56d9-47e8-b3df-f74f4b8ba608)

2023-06-16 14:05 UTC, michelerusti commented
> ![immagine](https://user-images.githubusercontent.com/13952131/246437755-75360049-56d9-47e8-b3df-f74f4b8ba608.png) io toglierei col= e colspan=

Nel runboat ora le tree sono larghe uguali, non come nella tua immagine

Se togliessimo `col=` e `colspan=`  si rompono tutte e due le tree
![image](https://github.com/OCA/l10n-italy/assets/102949020/b3e849c9-953c-4fb2-a4e4-6b804e4e6e95)

Mi sto perdendo qualcosa?

2023-06-16 17:34 UTC, MaurizioPellegrinet approved these changes
LGTM

2023-06-16 18:13 UTC, maxgrassi commented
Per me è OK. Grazie @michelerusti

2023-06-19 14:06 UTC, tafaRU approved these changes
@michelerusti grazie della PR :+1: 
Come detto in call: apri una issue per indagare il `css`  pregresso.
Grazie.

2023-06-19 14:23 UTC, merged