[16.0] [MIG] l10n_it_fatturapa_out_sp
OCA/l10n-italy pull request #3392
Opened 2023-06-19 07:13 UTC by Borruso

Migration l10n_it_fatturapa_out_sp from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-06-20 06:49 UTC, tafaRU commented
/ocabot migration l10n_it_fatturapa_out_sp

2023-07-06 08:23 UTC, tafaRU commented
@Borruso aggiungere in tests requirements la dipendenza a `split payment. Grazie.

2023-07-06 10:06 UTC, Borruso commented
> @Borruso aggiungere in tests requirements la dipendenza a `split payment. Grazie.

test ok

2023-07-06 19:13 UTC, andreampiovesana approved these changes
LGTM

2023-09-06 14:25 UTC, SirAionTech requested changes
Grazie della PR!
Potresti modificare la storia dei commit come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?

2023-10-02 07:51 UTC, SirAionTech commented
https://github.com/OCA/l10n-italy/pull/3387 è stata mergiata, puoi eliminare l'ultimo commit e fare rebase

2023-10-03 09:09 UTC, SirAionTech approved these changes
Grazie della PR!
Ho fatto revisione della storia dei commit e del codice, per me è ok

2023-10-05 12:52 UTC, OpenCode commented
/ocabot merge nobump

2023-10-05 13:40 UTC, closed without merging