[16.0][FIX] Remove unused css classes
OCA/l10n-italy pull request #3402
Opened 2023-06-22 13:37 UTC by michelerusti

2023-06-22 14:07 UTC, tafaRU requested changes
Coglierei l'occasione per rinominare il file in `account_vat_period_end_statement.css`. Grazie.

2023-06-23 07:08 UTC, michelerusti commented on account_vat_period_end_statement/__manifest__.py
> +            "account_vat_period_end_statement/static/src/css/*.css",
La stringa veniva molto lunga con il nuovo nome, ho guardato negli altri repo di l10n-italy ed ho visto che fa così anche su [l10n_it_account](https://github.com/OCA/l10n-italy/blob/e1cd1fb6596d7080152d6406111c5d2f716c348c/l10n_it_account/__manifest__.py#L35)

Se pensi sia meglio mettere il nome fisso fammi sapere ma penso che nella cartella `/css/` ci debbano essere solo i file css

2023-06-23 07:21 UTC, tafaRU commented on account_vat_period_end_statement/__manifest__.py
> +            "account_vat_period_end_statement/static/src/css/*.css",
Grazie del chiarimento! Può andare bene così :+1:

2023-06-23 07:21 UTC, tafaRU approved these changes

2023-09-20 14:36 UTC, michelerusti commented
@tafaRU questa possiamo portarla avanti o ci sono da fare altre verifiche?

2023-11-22 14:43 UTC, michelerusti commented
@tafaRU che ne pensi?

2023-11-22 14:48 UTC, tafaRU commented
/ocabot merge patch

2023-11-22 14:58 UTC, merged