[14.0] l10n_it_fatturapa_ou: Add validation to company phone number
OCA/l10n-italy pull request #3451
Opened 2023-07-07 08:35 UTC by salvorapi

Fix issue #2405

Add validation to company phone number with library phonenumbers

2023-07-07 12:42 UTC, aleuffre approved these changes
Code review, LGTM

2023-07-07 13:36 UTC, salvorapi commented
> Code review, LGTM

Ho fatto la rebase dal branch della 14.0 per fare andare i test.

2023-07-07 13:37 UTC, aleuffre approved these changes

2023-07-07 13:38 UTC, aleuffre commented
> > Code review, LGTM
> 
> Ho fatto la rebase dal branch della 14.0 per fare andare i test.

Stavo per dire che mi sembrava uguale a prima :D

2023-07-07 14:34 UTC, tafaRU commented
> per fare andare i test.

purtroppo sono ancora :red_circle:

2023-07-07 14:47 UTC, salvorapi commented
> > per fare andare i test.
> 
> purtroppo sono ancora 🔴

Lo so  :tired_face: appena ripushato...

2023-07-07 15:38 UTC, salvorapi commented
> > per fare andare i test.
> 
> purtroppo sono ancora 🔴

@tafaRU :white_check_mark:

2023-07-07 15:43 UTC, aleuffre approved these changes

2023-07-14 08:33 UTC, salvorapi commented
up

2023-07-14 08:46 UTC, aleuffre approved these changes

2024-01-29 11:25 UTC, francesco-ooops commented
@salvorapi se puoi aggiungere un po' di test coverage a questa e fai ripartire il runboat facciamo review

2024-02-11 17:25 UTC, salvorapi commented
> @salvorapi se puoi aggiungere un po' di test coverage a questa e fai ripartire il runboat facciamo review

Ciao, ho aggiunto i test e rifatto la commit. Mi sono permesso di aggiungermi tra i CONTRIBUTORS 😊

Salvo.

2024-07-22 07:59 UTC, francesco-ooops commented
/ocabot rebase

2024-07-22 08:06 UTC, francesco-ooops commented
@salvorapi puoi fare rebase?

2024-07-22 12:35 UTC, salvorapi commented
> @salvorapi puoi fare rebase?

Fatto. 

Ho sistemato anche il file dei tests `test_fatturapa_xml_validation.py` rispettando la sequenza dei test (io ho aggiunto il 19, 20 e 21).

Salvo.

2024-07-24 12:19 UTC, MaurizioPellegrinet approved these changes
LGTM

2024-08-07 10:36 UTC, francesco-ooops commented
@OCA/local-italy-maintainers si può mergiare?

2024-08-09 08:13 UTC, francesco-ooops commented
ping

2024-08-09 08:20 UTC, tafaRU requested changes

2024-08-09 08:20 UTC, tafaRU commented on l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
> +        self.check_content(xml_content, "IT03297040366_00020.xml")
come mai il nome della file non è coerente con il nome del test?

2024-08-09 08:20 UTC, tafaRU commented on l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
> +        self.check_content(xml_content, "IT03297040366_00021.xml")
come sopra

2024-08-09 08:20 UTC, tafaRU commented on l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
> +        self.check_content(xml_content, "IT03297040366_00022.xml")
come sopra

2025-01-17 14:15 UTC, tafaRU commented
@salvorapi hai modo di risolvere gli ultimi commenti? Fammi sapere nel caso non ti fossero chiari grazie.

2025-01-18 16:06 UTC, salvorapi commented
> @salvorapi hai modo di risolvere gli ultimi commenti? Fammi sapere nel caso non ti fossero chiari grazie.

risolto.

Il 00019.xml stava più giù nel test **test_trasmittente_xml_export**

Ho fatto fix sui test che ho aggiunto io così sono allineati.

2025-01-20 07:54 UTC, tafaRU approved these changes

2025-01-24 08:41 UTC, eLBati commented
/ocabot merge patch

2025-01-24 08:58 UTC, merged