[FIX] l10n_it_fatturapa_in: rimosso abs dall'importo imponibile https…
OCA/l10n-italy pull request #3462
Opened 2023-07-07 10:35 UTC by TonyMasciI

…://github.com/OCA/l10n-italy/issues/2959

2023-12-07 11:34 UTC, SirAionTech requested changes
Grazie della PR!
È la stessa modifica di https://github.com/OCA/l10n-italy/commit/5cad119780c1dc81f9c088f2be8f9972bf97f579, puoi mantenere l'autore originale?

2023-12-13 15:51 UTC, andreampiovesana commented
merge please

2023-12-13 15:56 UTC, francesco-ooops commented
> merge please

penso dovresti chiedere a @TonyMasciI di fixarla come richiesto e poi approvarla :)

2024-01-17 14:07 UTC, andreampiovesana approved these changes
@TonyMasciI fai quanto richiesto?

2024-01-23 13:50 UTC, TonyMasciI commented
> Grazie della PR! È la stessa modifica di [5cad119](https://github.com/OCA/l10n-italy/commit/5cad119780c1dc81f9c088f2be8f9972bf97f579), puoi mantenere l'autore originale?

ciao @SirAionTech mi puoi dare una mano su come posso fare questa operazione? grazie!

2024-01-24 08:30 UTC, SirAionTech commented
> > Grazie della PR! È la stessa modifica di [5cad119](https://github.com/OCA/l10n-italy/commit/5cad119780c1dc81f9c088f2be8f9972bf97f579), puoi mantenere l'autore originale?
> 
> ciao @SirAionTech mi puoi dare una mano su come posso fare questa operazione? grazie!

Puoi usare `cherry-pick` per copiare autore e contenuto di un commit, vedi https://git-scm.com/docs/git-cherry-pick.

2024-06-30 16:36 UTC, sergiocorato commented
@TonyMasciI pensi di proseguire con questa PR?
Per fare cherry-pick Simone ti ha lasciato il link alle istruzioni, nel tuo caso puoi fare un reset --hard origin/16.0 del branch saydigital:16.0-fix-l10n_it_fatturapa_in-2959 , poi fare il cherry-pick, infine fare un push -f

2024-12-22 12:33 UTC, closed without merging