16.0 mig l10n it withholding tax payment
OCA/l10n-italy pull request #3507
Opened 2023-07-28 08:54 UTC by odooNextev

2023-08-03 19:01 UTC, MaurizioPellegrinet approved these changes
LGTM

2023-08-04 06:46 UTC, andreampiovesana approved these changes
LGTM

2023-08-04 08:00 UTC, SirTakobi requested changes
Grazie della PR!
Potresti rimuovere i commit dei bot come descritto in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate?

Ci sono anche due commit di migrazione e manca il commit con le modifiche di `pre-commit`, puoi aiutarti con https://github.com/OCA/odoo-module-migrator

2023-08-04 10:09 UTC, odooNextev commented
Ma intendi rimuovere tutti quelli fatti dai bot o squashare quelli uguali in un unico come dice la guida? quindi per esempio questi: 3e7ad46c67ffc37d70c906b02e6093a68c0dcf09 con bb89a2b02735367b6f5c728709e2cf6ae866f285

2023-08-04 10:13 UTC, SirTakobi commented
> Ma intendi rimuovere tutti quelli fatti dai bot o squashare quelli uguali in un unico come dice la guida? quindi per esempio questi: [3e7ad46](https://github.com/OCA/l10n-italy/commit/3e7ad46c67ffc37d70c906b02e6093a68c0dcf09) con [bb89a2b](https://github.com/OCA/l10n-italy/commit/bb89a2b02735367b6f5c728709e2cf6ae866f285)

Va benissimo se fai come dice la guida

2023-09-07 15:15 UTC, SirAionTech requested changes
La revisione https://github.com/OCA/l10n-italy/pull/3507#pullrequestreview-1562378935 non è risolta, ad esempio c'è ancora il commit 94f98b806bf0a749fc090714505758e00eae62d3.

2023-09-07 15:50 UTC, tafaRU requested changes
I commit di pre-commit e di migrazione sono da rivedere, sono mescolati. 
Inoltre ci sono da schiacciare i commit amministrativi. Grazie!

2023-09-08 09:36 UTC, tafaRU commented
@odooNextev i test falliscono, vedi https://github.com/OCA/l10n-italy/actions/runs/6119460806/job/16609428469?pr=3507#step:8:443

2023-09-08 10:53 UTC, andreampiovesana commented
@odooNextev bisogna sistemare i dati di test x multicompany
![image](https://github.com/OCA/l10n-italy/assets/13952131/2202ffe5-0e1e-4c5e-97b5-ba8fdf053364)

2023-09-08 11:04 UTC, SirAionTech requested changes
C'è ancora il commit 122790b8fb9a063dce1439fc047530931a30c81d di @oca-transbot.
Sono stati rimossi commit  che non andavano rimossi:
- a5681a16c42a93ccff53af6f0d5fe42a9d240cee
- b1847a0321a9a7393db26557d084a815289060e9

Mancano i commit:
- dcc884bf58f43ab1e8078086a9d89a5a6717f0d5 (che andrebbe schiacciato perché è di un bot)
- a57ebf9cbd22a7cc0942a2cb7631e5c3c56ebd1e

2023-09-08 13:27 UTC, SirAionTech commented
> @tafaRU e @SirTakobi adesso potete fare review?

Se i test falliscono al PR non si può mergiare quindi è inutile fare review

2023-09-22 08:45 UTC, andreampiovesana commented
come possiamo sbloccare la situazione?

2023-09-22 12:56 UTC, odooNextev commented
I test sono passati, come posso recuperare i commits che dovevano rimanere?

2023-10-05 09:26 UTC, SirAionTech requested changes
> I test sono passati, come posso recuperare i commits che dovevano rimanere?

Rifai il processo di migrazione.
Visto che siamo nel code sprint ho tempo di portarla avanti quindi la prendo in carico per correggere i punti aperti.

2023-10-05 13:56 UTC, closed without merging