[IMP][14.0] l10n_it_intrastat: add some missing instrastat codes
OCA/l10n-italy pull request #3543
Opened 2023-08-28 12:30 UTC by PicchiSeba

Aggiunta di alcune categorie mancanti ai codici intrastat

2023-08-28 14:20 UTC, PicchiSeba commented
@francesco-ooops in [questa PR](https://github.com/OCA/l10n-italy/pull/3518#issuecomment-1668242016) mi era stato detto di non inserire direttamente le traduzioni

2023-08-28 14:37 UTC, francesco-ooops commented
ok, allora l'importante è ricordarsi di inserirle dopo il merge su weblate (avevo fatto un lavoraccio per inserire tutte quelle presenti al momento e sono termini con una traduzione specifica)

2023-08-29 06:50 UTC, PicchiSeba commented
Per i termini specifici ho sotto mano la gazzetta dell'EU dove sono riportati i termini esatti, ricopierò da lì

2023-09-25 10:26 UTC, PicchiSeba commented
@OCA/local-italy-maintainers

sono anche già pronto con la traduzione ufficiale

2023-09-25 14:35 UTC, primes2h commented
> Per i termini specifici ho sotto mano la gazzetta dell'EU dove sono riportati i termini esatti, ricopierò da lì

È in versione digitale o cartacea?

Se hai modo di recuperare un link alla documentazione sarebbe ottimo, potremmo aggiungerlo al glossario specifico.
https://www.odoo-italia.org/documentazione/14.0/traduzioni/glossari/intrastat.html

2023-09-25 14:42 UTC, PicchiSeba commented
> > Per i termini specifici ho sotto mano la gazzetta dell'EU dove sono riportati i termini esatti, ricopierò da lì
> 
> È in versione digitale o cartacea?
> 
> Se hai modo di recuperare un link alla documentazione sarebbe ottimo, potremmo aggiungerlo al glossario specifico. https://www.odoo-italia.org/documentazione/14.0/traduzioni/glossari/intrastat.html

Sono in formato digitale.

Mi riferisco ai documenti presenti in [questa pagina](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L:2022:282:TOC) nelle varie lingue, tra cui quelle che interessano a noi (italiano e inglese per l'appunto)

2023-09-25 15:24 UTC, primes2h requested changes

2023-09-25 15:24 UTC, primes2h commented on l10n_it_intrastat/data/report.intrastat.code.csv
> +intrastat_category_2014_73181639,73181639,good,Nuts of stainless steel (excl. blind rivet nuts)
```suggestion
intrastat_category_2014_73181631,73181631,good,"Blind rivet nuts of stainless steel"
intrastat_category_2014_73181639,73181639,good,"Nuts of stainless steel (excl. blind rivet nuts)"
```

2023-09-25 15:33 UTC, primes2h commented
> > > Per i termini specifici ho sotto mano la gazzetta dell'EU dove sono riportati i termini esatti, ricopierò da lì
> > 
> > 
> > È in versione digitale o cartacea?
> > Se hai modo di recuperare un link alla documentazione sarebbe ottimo, potremmo aggiungerlo al glossario specifico. https://www.odoo-italia.org/documentazione/14.0/traduzioni/glossari/intrastat.html
> 
> Sono in formato digitale.
> 
> Mi riferisco ai documenti presenti in [questa pagina](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L:2022:282:TOC) nelle varie lingue, tra cui quelle che interessano a noi (italiano e inglese per l'appunto)

Grazie, appena riesco vedo di aggiungere i riferimenti nel glossario.

2023-09-25 16:02 UTC, primes2h approved these changes
LGTM

Grazie!

2023-09-25 16:05 UTC, primes2h commented
Ah, visto ora. C'è un piccolo typo nel testo del commit, anche se non è bloccante.

`instrastat → intrastat`

2023-09-26 06:53 UTC, PicchiSeba commented
> Ah, visto ora. C'è un piccolo typo nel testo del commit, anche se non è bloccante.
> 
> `instrastat → intrastat`

Corretto ora

2023-09-26 07:37 UTC, primes2h commented
/ocabot merge patch

2023-09-29 15:24 UTC, PicchiSeba commented
è successo qualcosa durante il merge? vedo che è stato creato un branch ma poi più niente

2023-09-30 14:25 UTC, primes2h commented
/ocabot merge patch

2023-09-30 14:58 UTC, merged