[FIX][ l10n_it_split_payment] fix unbal
OCA/l10n-italy pull request #3548
Opened 2023-08-31 09:50 UTC by matteoopenf

2023-08-31 13:57 UTC, patrickt-oforce approved these changes

2023-08-31 14:07 UTC, lorenzoallegrucci approved these changes

2023-08-31 14:09 UTC, amosdisabatino approved these changes

2023-09-08 09:20 UTC, andreampiovesana commented
merge?

2024-01-04 08:18 UTC, SirAionTech requested changes
Ho provato e già senza queste modifiche non trovo problemi, vedi  https://github.com/OCA/l10n-italy/issues/3546#issuecomment-1875631635.

2024-01-04 08:29 UTC, matteoopenf commented
> Ho provato e già senza queste modifiche non trovo problemi, vedi [#3546 (comment)](https://github.com/OCA/l10n-italy/issues/3546#issuecomment-1875631635).

noi per ora l'errore lo abbiamo e altre modifiche a questo modulo non sono entrate da quando lo abbiamo riscontrato.

Appena posso ci torno sopra, per me la pr resta valida

2024-01-26 08:54 UTC, theandryx commented
Nella versione 16 crea la stessa problematica.
Al primo salvataggio bilancia correttamente.
Dopo aver salvato la fattura con split payment e provando ad aggiungere una nuova riga ( o toglierne una già esistente ) al salvataggio non riesce più a bilanciarla causando l'impossibilità di editare le fatture.

Controllando i commit sembrerebbe quasi che i fix applicati alla v14 non siano stati poi riportati nella v16

2024-07-21 12:31 UTC, closed without merging