[14.0] [FIX] Contact field on picking always visible
OCA/l10n-italy pull request #3600
Opened 2023-09-21 15:04 UTC by odooNextev

Come segnalato nella issue, il campo `contact` dei picking viene nascosto se il trasferimento è di tipo interno o consegna, ma viene richiesto quando se ne valida uno creato manualmente (inventory > transfers > create).
https://github.com/OCA/l10n-italy/issues/3597

Per cominciare propongo di lasciarlo sempre visibile, ma si può discutere anche di soluzioni alternative.

2023-09-21 15:10 UTC, andreampiovesana approved these changes
LGTM

2024-06-10 07:13 UTC, odooNextev commented
@francesco-ooops dobbiamo lasciare andare questo fix?

2024-08-03 13:50 UTC, MaurizioPellegrinet commented
È possibile riattivare runboat?

2024-08-05 07:57 UTC, MaurizioPellegrinet approved these changes
Funzionale: OK

2024-10-04 08:17 UTC, sergiocorato commented
@odooNextev ci sono diversi errori nei test, puoi correggerli?

2024-10-04 08:18 UTC, sergiocorato requested changes
Test non funzionanti

2025-03-16 12:35 UTC, closed without merging