[14.0] FIX l10n_it_financial_statements_report: use landscape format for PDF
OCA/l10n-italy pull request #3601
Opened 2023-09-22 08:11 UTC by eLBati

Senza queste modifiche, il PDF ignora il formato impostato nel report e usa quello verticale

2023-09-22 10:10 UTC, GSLabIt approved these changes

2023-09-26 08:37 UTC, elvise requested changes
Passando da view e print si ottiene ancora la stampa in verticale

Steps:
1 View
![IMG_0975](https://github.com/OCA/l10n-italy/assets/5269577/890ef9ef-b40e-43ea-8f99-bf3241f79ac5)

2 Print
![IMG_0978](https://github.com/OCA/l10n-italy/assets/5269577/20f08b86-50d5-42de-b5ce-8c05fffd6661)


3 PDF in verticale 
[Financial Statements Report HTML 2.pdf](https://github.com/OCA/l10n-italy/files/12725135/Financial.Statements.Report.HTML.2.pdf)

Risultato atteso:
Stampa in orizzontale

2023-09-27 13:46 UTC, stefano-ooops approved these changes
ok funzionale

2023-09-27 15:49 UTC, francesco-ooops commented
@eLBati riesci a sistemare?

2023-09-30 12:20 UTC, eLBati commented
@elvise @francesco-ooops modificato, grazie

2023-10-13 14:06 UTC, elvise approved these changes
LGTM

2023-10-13 14:08 UTC, francesco-ooops commented
@eLBati merge?

2023-10-13 14:18 UTC, eLBati commented
/ocabot merge patch

2023-10-13 14:55 UTC, merged