[12.0][IMP] l10n_it_account_stamp remove stamp tax line when no more applicable
OCA/l10n-italy pull request #3666
Opened 2023-10-16 07:32 UTC by sergiocorato

Descrizione del problema o della funzionalità:

Comportamento attuale prima di questa PR:

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-10-16 09:13 UTC, SirAionTech requested changes
Grazie della PR!
Puoi aprire una issue per tracciare questa modifica anche nelle altre versioni come descritto in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue?

2023-10-16 09:13 UTC, SirAionTech commented on l10n_it_account_stamp/models/invoice.py
> +                        line.unlink()
Puoi verificare come mai questa riga non risulta essere coperta dai test?
![image](https://github.com/OCA/l10n-italy/assets/143788994/82f50eb1-107b-4449-8564-823c72de63a0)

Visto che giustamente hai aggiunto un test, mi aspettavo che questa riga venisse eseguita

2023-10-16 09:55 UTC, sergiocorato commented on l10n_it_account_stamp/models/invoice.py
> +                        line.unlink()
Pensavo fosse già stato addebitato il bollo, ho corretto, grazie.

2024-01-29 14:22 UTC, primes2h commented
/ocabot rebase

2024-01-29 14:37 UTC, primes2h approved these changes
LGTM

Grazie!

2024-08-11 12:31 UTC, closed without merging