[FIX] fixed xml on downpayment invoice
OCA/l10n-italy pull request #3678
Opened 2023-10-23 10:48 UTC by Marcoapu

2024-02-15 09:51 UTC, SirAionTech requested changes
Grazie della PR!
Puoi schiacciare tutti i commit in uno solo? Nota che il commit risultante dovrebbe seguire https://github.com/OCA/odoo-community.org/blob/8afdb5a5ebfd3314e2fc836c9b9f644468ee044e/website/Contribution/CONTRIBUTING.rst#L1114.

Puoi aggiungere un test? Così si evitano regressioni

2024-06-11 20:39 UTC, DigitalAutomations approved these changes
functional

2024-06-11 20:42 UTC, francescapenso approved these changes
funzionale

2024-06-12 06:29 UTC, MaurizioPellegrinet commented
Runboat non disponibile al momento, è possibile testarla?

2024-06-12 06:52 UTC, primes2h commented
/ocabot rebase

2024-06-12 07:40 UTC, primes2h commented
> Runboat non disponibile al momento, è possibile testarla?

Runboat pronto per i test. :-)

2024-06-12 09:23 UTC, MaurizioPellegrinet approved these changes
Test funzionale OK

2024-06-12 10:36 UTC, francesco-ooops commented
> Grazie della PR! Puoi schiacciare tutti i commit in uno solo? Nota che il commit risultante dovrebbe seguire https://github.com/OCA/odoo-community.org/blob/8afdb5a5ebfd3314e2fc836c9b9f644468ee044e/website/Contribution/CONTRIBUTING.rst#L1114.
> 
> Puoi aggiungere un test? Così si evitano regressioni

@Marcoapu puoi verificare queste richieste?

2024-08-01 17:07 UTC, matteoopenf commented
e' possibile un rebase? cosi parte runboat?

2024-08-02 07:00 UTC, SirAionTech commented
/ocabot rebase

2024-08-02 08:31 UTC, matteoopenf commented
> /ocabot rebase

grazie Mille

2024-08-02 10:08 UTC, matteoopenf commented on l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
> +                    tax_amount = abs(tax_id.balance)
manca un caso da gestire se sia credit che debit sono uguali zero, l'esempio sarebbe quello di una fattura a zero, altrimenti ci si trova con tax_amount non valorizzato, aggiungo intanto il caso nella mia pr per 14.0

2024-09-24 10:56 UTC, matteoopenf commented
sto riprovando questa pr, con un cliente che ha problemi con gli anticipi e sembra non funzionare.
Qualcun altro per caso ha fatto dei test?
Sembra che sia l'imposta che l'imponibile importo vengano errati,

2024-10-04 08:24 UTC, francesco-ooops commented
Mergiata in https://github.com/OCA/l10n-italy/pull/4381

2024-10-04 08:24 UTC, closed without merging