[16.0] [FIX] l10n_fatturapa_in: add migration to remove view inheritance
OCA/l10n-italy pull request #3694
Opened 2023-11-02 11:01 UTC by odooNextev

E' necessario aggiungere questo script per migrare correttamente il modulo dalla v14 alla v16.
Infatti senza rimuovere preventivamente l'ereditarietà dalla vista `view_fatturapa_in_attachment_form`, questa verrebbe considerata  come un'estensione anche nella v16 ed andrebbe in errore.

2023-11-02 11:07 UTC, SirAionTech approved these changes
Grazie della PR!
Ho solo fatto revisione del codice e per me è ok

2023-11-02 11:13 UTC, odooNextev commented
Perchè fallisce ancora il precommit?
Mi sembrava fossero state mergiate le PR relative

2023-11-02 11:14 UTC, aleuffre commented
> Perchè fallisce ancora il precommit? Mi sembrava fossero state mergiate le PR relative

Solo su v14. Nessuno ha ancora preso su il task per v16

https://github.com/OCA/l10n-italy/pull/3686

2024-01-09 09:24 UTC, Guidomadormo approved these changes
It works!

2024-01-17 18:22 UTC, mde-spring approved these changes
Works fine for me also!

2024-01-19 09:39 UTC, SirAionTech requested changes
> L'`inherit` è aggiunto nella 14.0 dal #3118
> 
> Il merge è successivo alla migrazione dei vari moduli coinvolti alla 16.
> 
> Secondo me, la soluzione è portare la PR alla 16, non disfare parzialmente sul DB 14 in uno script di migrazione le cose aggiunte dalla #3118.

Capito, lo puoi aggiungere come review della PR?

Ne abbiamo parlato poco fa in chiamata ed effettivamente mi hai convinto che sarebbe meglio fare così, aggiungo che esiste la #3785 per portare le modifiche di #3118 e altre.

2024-01-19 09:48 UTC, TheMule71 requested changes

2024-01-19 09:48 UTC, TheMule71 commented on l10n_it_fatturapa_in/migrations/16.0.1.0.0/pre-migrate.py
> +    view = env.ref("l10n_it_fatturapa_in.view_fatturapa_in_attachment_form")
Io piuttosto mergerei https://github.com/OCA/l10n-italy/pull/3785 e in generale allinerei i sorgenti della 14 alla 16 quando sono più recenti, invece di disfare le aggiunte con script di migrazione.

2024-03-13 08:19 UTC, closed without merging