[16.0] [FIX] nolabel view
OCA/l10n-italy pull request #3699
Opened 2023-11-03 10:16 UTC by Borruso

Fix incorrect display of fields with the `nolabel` attribute

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-11-03 11:28 UTC, MarcoCalcagni approved these changes
OK LGTM

2023-11-03 11:30 UTC, matteoopenf approved these changes
vedi per il pre-commit per il resto LGTM

2023-11-03 12:26 UTC, Borruso commented
> vedi per il pre-commit per il resto LGTM

errore tecnico in OCA

2023-11-17 08:49 UTC, tafaRU commented
> errore tecnico in OCA

è stato corretto: fai `rebase`!

2023-11-23 07:47 UTC, tafaRU commented
@Borruso grazie della PR!
Per rendere più semplice la review sarebbe utile avere degli screenshot prima e dopo le modifiche. Hai mica modo di aggiungerli nella descrizione della PR?

2023-11-23 11:39 UTC, andreampiovesana approved these changes
Merge?

2023-12-13 08:04 UTC, Borruso commented
> @Borruso grazie della PR! Per rendere più semplice la review sarebbe utile avere degli screenshot prima e dopo le modifiche. Hai mica modo di aggiungerli nella descrizione della PR?

fatto

2023-12-13 16:33 UTC, marcelofrare approved these changes
lgtm on runboat

2023-12-19 16:53 UTC, francesco-ooops commented
@Borruso solo 16 giusto?

2023-12-19 17:08 UTC, Borruso commented
> @Borruso solo 16 giusto?

sisi

2024-01-09 14:23 UTC, francesco-ooops commented
@OCA/local-italy-maintainers si può mergiare?

2024-01-09 15:58 UTC, primes2h requested changes

2024-01-09 15:58 UTC, primes2h commented on l10n_it_fatturapa_sale/views/sale_order_views.xml
> +                    <field name="related_documents" nolabel="1" />
Come mai qui la stringa "Related Documents" è stata tolta e non è stata messa in `separator` come (ad es.) [qui](https://github.com/OCA/l10n-italy/pull/3699/files#diff-0d6e3045af0140c933caf9b651726880e7fcc975d491c8db37e0bde0bf486646R443)?

2024-01-26 15:50 UTC, primes2h commented on l10n_it_fatturapa_sale/views/sale_order_views.xml
> +                    <field name="related_documents" nolabel="1" />
> posso inserirlo ma visivamente mi sembrava più idoneo alla form

In effetti è più carino così e non toglie informazioni visto che la stringa è presente anche nel nome della scheda.

Anzi, sarebbe carino farlo anche per la 14.0, se ti avanza tempo. :wink: 

Vedi:
![immagine](https://github.com/OCA/l10n-italy/assets/227940/333cdbb7-4dc8-423d-b700-64e4539bb413)
![immagine](https://github.com/OCA/l10n-italy/assets/227940/15a97692-2e92-4645-b67d-f8acbec8e38a)

2024-01-26 15:50 UTC, primes2h approved these changes
Grazie.

2024-01-26 15:51 UTC, primes2h commented
/ocabot merge patch

2024-01-26 16:26 UTC, primes2h commented
/ocabot merge patch

2024-01-26 17:15 UTC, merged