[16.0][IMP] l10n_it_fatturapa_out: not generate empty Causale
OCA/l10n-italy pull request #3700
Opened 2023-11-03 10:28 UTC by Borruso

No generate empty Causale in xml

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-11-03 11:27 UTC, MarcoCalcagni approved these changes
LGTM

2023-11-17 08:51 UTC, tafaRU commented
/ocabot rebase

2023-12-19 16:40 UTC, Borruso commented
> @Borruso issue?

ecco a te

2023-12-21 15:38 UTC, tafaRU requested changes
La modifica in se mi  pare :+1: 
Prima di mergiarla potresti cambiare il prefisso del commit message?
Da [IMP] a [FIX] coerentemente con la issue collegata etichetta con https://github.com/OCA/l10n-italy/labels/bug. Grazie!

2023-12-21 15:50 UTC, Borruso commented
> La modifica in se mi pare 👍 Prima di mergiarla potresti cambiare il prefisso del commit message? Da [IMP] a [FIX] coerentemente con la issue collegata etichetta con [ bug](https://github.com/OCA/l10n-italy/labels/bug) . Grazie!

fatto

2023-12-21 15:51 UTC, tafaRU approved these changes

2023-12-21 15:52 UTC, tafaRU commented
/ocabot merge patch

2023-12-21 16:38 UTC, merged