[MIG] l10n_it_fatturapa_out_triple_discount
OCA/l10n-italy pull request #3720
Opened 2023-11-15 15:09 UTC by SirAionTech

Migrazione da https://github.com/OCA/l10n-italy/tree/8937e1406eb42768a820539a0f0d9e5e8f305188/l10n_it_fatturapa_out_triple_discount (`12.0`).

Dipende da:

- [ ] https://github.com/OCA/account-invoicing/pull/1606
  la PR linkata è necessaria perché nell'ambiente dei test viene inserito il modulo **account_invoice_triple_discount** che interferisce con il calcolo degli sconti.

  Ad esempio, senza la PR linkata un test di **l10n_it_fatturapa_in** fallisce:
  ```
  2023-11-15 14:50:06,830 76056 ERROR db-name odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml: FAIL: TestFatturaPAXMLValidation.test_31_xml_import
  Traceback (most recent call last):
    File "/path/to/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 632, in test_31_xml_import
      self.assertEqual(invoice.invoice_line_ids[1].discount, 100)
  AssertionError: 100.00000000000014 != 100
  ```

2023-11-15 17:42 UTC, francesco-ooops commented
@SirAionTech capisco la necessità di fare la migrazione alla versione che interessa, ma dato che stiamo lavorando proprio ora sulla migrazione per la 14 (https://github.com/OCA/l10n-italy/pull/3681) potrebbe essere utile unire le forze per mergiare una delle due versioni e successivamente fare il backporting o fw-porting dell'altra in modo da essere allineati, che ne dici?

soprattutto perchè queste migrazioni hanno fatto uscire fuori magagne su account_triple_discount (e al momento sulla 14 hanno rotto i test di sale_triple_discount, cfr https://github.com/OCA/account-invoicing/pull/1605 ), per cui non proprio una passeggiata di salute 😅

2023-11-16 08:58 UTC, SirAionTech commented
> @SirAionTech capisco la necessità di fare la migrazione alla versione che interessa, ma dato che stiamo lavorando proprio ora sulla migrazione per la 14 (#3681) potrebbe essere utile unire le forze per mergiare una delle due versioni e successivamente fare il backporting o fw-porting dell'altra in modo da essere allineati, che ne dici?
> 
> soprattutto perchè queste migrazioni hanno fatto uscire fuori magagne su account_triple_discount (e al momento sulla 14 hanno rotto i test di sale_triple_discount, cfr [OCA/account-invoicing#1605](https://github.com/OCA/account-invoicing/pull/1605) ), per cui non proprio una passeggiata di salute 😅

Certo, ho fatto https://github.com/OCA/l10n-italy/pull/3681#pullrequestreview-1733781767 per evidenziare cosa secondo me non va bene in quella migrazione.

2023-11-16 09:20 UTC, francesco-ooops commented
@SirAionTech molto apprezzato <3

Se la tua PR è in stato più avanzato e sono presenti i test possiamo anche concentrarci su questa e fare il backporting, basta che il tutto sia celere ecco 😅

2023-11-27 15:39 UTC, SirAionTech commented on l10n_it_fatturapa_out_triple_discount/tests/fatturapa_common.py
> +        ).id
Servono ad avere un'azienda che produca lo stesso file presente nei test.
Ad esempio viene impostato il regime fiscale a RF01 perché deve essere lo stesso di https://github.com/OCA/l10n-italy/pull/3720/files#diff-b4442d0a23dcdee7b95d10e0baed8c8266eaac33d66499c6cd97f11266027b04R29.

2023-11-27 16:12 UTC, eLBati commented on l10n_it_fatturapa_out_triple_discount/tests/fatturapa_common.py
> +        ).id
Per modificare il meno possibile il file di test esistente?
L'importante penso sia avere un XML valido per la parte rilevante per le funzionalità di questo modulo, poi se il resto del file XML contiene i dati che contengono tutti gli altri XML di test , non vedo problemi a modificarlo

2023-11-27 16:18 UTC, matteoopenf commented
Concordo Matteo ***@***.*** Il giorno 27 nov 2023, alle ore 17:12, Lorenzo Battistini ***@***.***> ha scritto:﻿
@eLBati commented on this pull request.



In l10n_it_fatturapa_out_triple_discount/tests/fatturapa_common.py:
> +            {"name": "YourCompany_"}
+        )
+
+        self.env.company.name = "YourCompany"
+        self.env.company.vat = "IT06363391001"
+        self.env.company.fatturapa_art73 = True
+        self.env.company.partner_id.street = "Via Milano, 1"
+        self.env.company.partner_id.city = "Roma"
+        self.env.company.partner_id.state_id = self.env.ref("base.state_us_2").id
+        self.env.company.partner_id.zip = "00100"
+        self.env.company.partner_id.phone = "06543534343"
+        self.env.company.email = ***@***.***"
+        self.env.company.partner_id.country_id = self.env.ref("base.it").id
+        self.env.company.fatturapa_fiscal_position_id = self.env.ref(
+            "l10n_it_fatturapa.fatturapa_RF01"
+        ).id

Per modificare il meno possibile il file di test esistente?
L'importante penso sia avere un XML valido per la parte rilevante per le funzionalità di questo modulo, poi se il resto del file XML contiene i dati che contengono tutti gli altri XML di test , non vedo problemi a modificarlo

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano

2023-11-27 17:03 UTC, SirAionTech commented on l10n_it_fatturapa_out_triple_discount/tests/fatturapa_common.py
> +        ).id
O modifico il setup dei test (come ho fatto), o modifico il file XML: ho preferito modificare il setup dei test per ottenere la stessa fattura elettronica perché penso che il test debba verificare che il modulo possa produrre esattamente quella fattura elettronica.

> se il resto del file XML contiene i dati che contengono tutti gli altri XML di test , non vedo problemi a modificarlo

Tutti gli altri XML di test contengono proprio questi dati: le modifiche fatte qui sono le stesse che furono necessarie per la migrazione a `14.0` di **l10n_it_fatturapa_out**: https://github.com/OCA/l10n-italy/blob/8ae41d3b1f550ca58bdd96e272c524cfd48e336a/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py#L45-L62
in modo che le fatture elettroniche non fossero da cambiare nella migrazione.
Esiste già la issue https://github.com/OCA/l10n-italy/issues/2507 per evitare di ripetere questo setup  ma deve ancora essere risolta.

Quindi pensi sia meglio che modifichi il file della fattura elettronica generato dai test?
Così facendo conterrà dati diversi da tutti gli altri XML di test.

2023-11-27 17:04 UTC, SirAionTech commented
https://github.com/OCA/l10n-italy/pull/3720#discussion_r1406477869

On Mon, 27 Nov 2023 at 17:18, Matteo Mircoli ***@***.***>
wrote:

> Concordo Matteo ***@***.*** Il giorno 27 nov 2023, alle ore 17:12, Lorenzo
> Battistini ***@***.***> ha scritto:﻿
> @eLBati commented on this pull request.
>
>
>
> In l10n_it_fatturapa_out_triple_discount/tests/fatturapa_common.py:
> > + {"name": "YourCompany_"}
> + )
> +
> + self.env.company.name = "YourCompany"
> + self.env.company.vat = "IT06363391001"
> + self.env.company.fatturapa_art73 = True
> + self.env.company.partner_id.street = "Via Milano, 1"
> + self.env.company.partner_id.city = "Roma"
> + self.env.company.partner_id.state_id =
> self.env.ref("base.state_us_2").id
> + self.env.company.partner_id.zip = "00100"
> + self.env.company.partner_id.phone = "06543534343"
> + self.env.company.email = ***@***.***"
> + self.env.company.partner_id.country_id = self.env.ref("base.it").id
> + self.env.company.fatturapa_fiscal_position_id = self.env.ref(
> + "l10n_it_fatturapa.fatturapa_RF01"
> + ).id
>
> Per modificare il meno possibile il file di test esistente?
> L'importante penso sia avere un XML valido per la parte rilevante per le
> funzionalità di questo modulo, poi se il resto del file XML contiene i dati
> che contengono tutti gli altri XML di test , non vedo problemi a
> modificarlo
>
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are
> receiving this because you are subscribed to this thread.Message ID:
> ***@***.***>
>
> Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via
> Tiziano,32 20145 Milano
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/l10n-italy/pull/3720#issuecomment-1828160713>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCJAXQVS4U2XBRQPENZWYU3YGS4MLAVCNFSM6AAAAAA7MUVTZSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRYGE3DANZRGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-28 13:32 UTC, eLBati requested changes

2023-11-28 13:32 UTC, eLBati commented on l10n_it_fatturapa_out_triple_discount/data/invoice_it_template.xml
> +        id="account_invoice_it_dati_bollo"
Qua meglio un `id` tipo `account_invoice_it_triple_discount`

2023-12-07 15:54 UTC, SirAionTech commented
Aggiornamento: la PR analoga per `14.0` https://github.com/OCA/l10n-italy/pull/3743 è stata mergiata

2023-12-07 16:10 UTC, francesco-ooops commented
@OCA/local-italy-maintainers aggiungere a https://github.com/OCA/l10n-italy/issues/2967

2024-06-14 07:25 UTC, OvertakeMattia approved these changes
Testato il modulo e  controllato emissione di una decina di documenti con sconto 1, 2, 3 anche in varie combinazioni di presenza /assenza e funziona correttamente

2024-06-14 13:51 UTC, SirAionTech commented
/ocabot migration l10n_it_fatturapa_out_triple_discount

2024-11-12 09:30 UTC, SirAionTech commented
/ocabot rebase

2025-04-20 12:36 UTC, closed without merging