[12.0] [IMP] l10n_it_fiscalcode: add codicefiscale.isvalid()
OCA/l10n-italy pull request #3724
Opened 2023-11-15 16:09 UTC by odooNextev

https://github.com/OCA/l10n-italy/issues/3719

2024-01-25 11:23 UTC, primes2h commented
/ocabot rebase

2024-01-29 13:44 UTC, primes2h commented
/ocabot rebase

2024-01-29 14:17 UTC, primes2h commented
@odooNextev 
Test :x: su un codice fiscale, sembra che questa PR funzioni a dovere. :-)

2024-02-28 14:14 UTC, odooNextev commented
Abbiamo corretto il test di `l10n_it_fatturapa_in` che impostava sul partner una stringa che non era un CF valido

2024-03-04 09:52 UTC, SirAionTech commented
> @OCA/local-italy-developers si può mergiare?

Serve almeno una revisione.
@primes2h questa https://github.com/OCA/l10n-italy/pull/3724#issuecomment-1914786428 potrebbe essere una revisione?

2024-03-04 09:58 UTC, odooNextev commented
> > @OCA/local-italy-developers si può mergiare?
> 
> Serve almeno una revisione. @primes2h questa [#3724 (comment)](https://github.com/OCA/l10n-italy/pull/3724#issuecomment-1914786428) potrebbe essere una revisione?

Hai ragione, non avevo notato.
Per testarlo basta inserire un codice fiscale non valido non solo come numero di caratteri (quello c'era già senza questa PR), ma anche come formato (lettere dove ci dovrebbero essere numeri o viceversa).

2024-03-04 15:23 UTC, primes2h commented on l10n_it_fiscalcode/model/res_partner.py
>          return True
> Ok, abbiamo aggiunto il messaggio di errore

Grazie, ho fatto due test su runboat:

1) codice < 16 caratteri

![image](https://github.com/OCA/l10n-italy/assets/227940/ce42b86f-c64e-47f3-a1f1-a16d1d553918)

2) codice errato

![image](https://github.com/OCA/l10n-italy/assets/227940/4fd0dae8-3ef7-450f-912d-4fc887168946)

2024-03-04 15:48 UTC, odooNextev commented on l10n_it_fiscalcode/model/res_partner.py
>          return True
Esatto, è quello che ottengo anche io in locale, non va bene?
Per togliere il `None` dovrei usare `UserError` invece che `ValidationError`, ma semanticamente penso sia più corretto usare `ValidationError` anche se aggiunge `None`.

2024-03-04 17:12 UTC, primes2h commented on l10n_it_fiscalcode/model/res_partner.py
>          return True
> Esatto, è quello che ottengo anche io in locale, non va bene? Per togliere il `None` dovrei usare `UserError` invece che `ValidationError`, ma semanticamente penso sia più corretto usare `ValidationError` anche se aggiunge `None`.

Intendevo il doppio messaggio. Ora che i messaggi vengono gestiti all'interno di `check_fiscalcode()` [questo](https://github.com/OCA/l10n-italy/pull/3724/files#diff-9ff0d21220b64095b1c978b0c601b89e8effe23514d3c56cda475c93e8c22ec6R38-R41) non serve più e puoi mettere direttamente `@api.constrains`.
In questo modo risolvi anche il problema `None`.

![image](https://github.com/OCA/l10n-italy/assets/227940/2f101f21-ab6f-4880-9739-4e70f1bd52cf)

2024-03-05 15:08 UTC, primes2h commented
> > @OCA/local-italy-developers si può mergiare?
> 
> Serve almeno una revisione. @primes2h questa [#3724 (comment)](https://github.com/OCA/l10n-italy/pull/3724#issuecomment-1914786428) potrebbe essere una revisione?

Ops, visto ora. :sweat_smile: 
Attendiamo solo https://github.com/OCA/l10n-italy/pull/3724#discussion_r1511502801, poi possiamo procedere con il merge.

2024-03-13 13:43 UTC, odooNextev commented
@primes2h dovremmo aver risolto

2024-03-13 14:26 UTC, primes2h requested changes

2024-03-13 14:26 UTC, primes2h commented on l10n_it_fiscalcode/model/res_partner.py
> +    @api.constrains('fiscalcode')
@api.multi non va eliminato

```suggestion
    @api.multi
    @api.constrains('fiscalcode')
```

2024-03-13 14:43 UTC, odooNextev commented on l10n_it_fiscalcode/model/res_partner.py
> +    @api.constrains('fiscalcode')
Fatto 👍

2024-03-13 14:59 UTC, primes2h commented on l10n_it_fiscalcode/model/res_partner.py
> +    @api.constrains('fiscalcode')
> Fatto 👍

Grazie.

2024-03-13 14:59 UTC, primes2h approved these changes

2024-03-13 15:18 UTC, SirAionTech commented
> @odooNextev Dal test su runboat ho notato un comportamento anomalo. Se parto da un partner di tipo azienda che contiene un CF non corretto e cambio la tipologia in persona fisica, al salvataggio non viene eseguito alcun controllo.
> 
> Ho visto però che il problema era presente anche prima di questa PR, quindi possiamo comunque procedere con il merge.
> 
> È giusto però segnalare la cosa, casomai qualcuno volesse darci un'occhiata.

Puoi aprire una issue (https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue)? Sarà comunque difficile che qualcuno si metta a correggerlo, ma almeno ha più visibilità di un commento in una PR

2024-03-13 15:39 UTC, merged