[16.0][FIX] l10n_it_financial_statements_report: use landscape format for PDF
OCA/l10n-italy pull request #3732
Opened 2023-11-22 09:59 UTC by aleuffre

Cherry pick of https://github.com/OCA/l10n-italy/pull/3601

2023-11-22 11:45 UTC, francesco-ooops commented
cc @eLBati

2023-11-23 11:47 UTC, andreampiovesana approved these changes
LGTM

2023-12-01 09:03 UTC, SirAionTech requested changes
Grazie della PR!
Ho provato e funziona correttamente, ho però qualche dubbio sulle modifiche al codice, puoi verificare?

2023-12-13 11:29 UTC, aleuffre commented on l10n_it_financial_statements_report/report/reports.xml
> +        <field
Ho testato e se rimuovo questo, la stampa poi non viene landscape.

2023-12-13 11:37 UTC, aleuffre commented on l10n_it_financial_statements_report/report/templates/financial_statements_report.xml
> +    <template id="report_pdf">
Io ho fatto cherry-pick com'era. In effetti questa modifica non sembra essere necessaria.

2023-12-13 15:52 UTC, MaurizioPellegrinet approved these changes
LGTM

2024-07-19 11:14 UTC, eLBati approved these changes
Grazie

2024-07-19 12:06 UTC, andreampiovesana approved these changes
LGTM

2024-10-24 14:54 UTC, eLBati commented
/ocabot rebase

2024-10-28 11:56 UTC, aleuffre commented
> /ocabot rebase

Ciao, ho fatto rebase. Purtroppo non avrò tempo di guardare la questione a breve.

2024-10-28 14:13 UTC, francesco-ooops commented on l10n_it_financial_statements_report/report/reports.xml
> +        <field
@SirAionTech dato che è un cherry-pick, se dobbiamo fare modifiche più sostanziali si possono fare in una nuova PR in modo da chiudere questa?

2024-10-28 14:24 UTC, SirAionTech commented on l10n_it_financial_statements_report/report/reports.xml
> +        <field
Secondo me no: se è stata fatta una modifica sbagliata in una versione non andrebbe portata così com'è nelle altre versioni.

Soprattutto se, come in questo caso, verrebbe portata all'ultima versione supportata (al momento diciamo che è ancora `16.0`).

2025-03-12 14:42 UTC, eLBati commented
Questa PR la abbiamo in produzione da tempo. Direi di procedere

2025-04-17 15:57 UTC, eLBati commented
/ocabot merge patch

2025-04-17 17:44 UTC, merged