[14.0] FIX l10n_it_fatturapa_in: importing refund with negative lines
OCA/l10n-italy pull request #3751
Opened 2023-12-01 17:12 UTC by eLBati

Risolve https://github.com/OCA/l10n-italy/issues/2465

Il caso dovrebbe essere coperto dal test https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_in/tests/data/IT01234567890_FPR07.xml , infatti, importando tale file da browser, si ottiene l'errore.

Il test però non fallisce probabilmente perchè la valuta dell'azienda nei test è USD e quella delle fatture è EUR, mentre nell'importazione manuale è tutto EUR.

Ci sarebbe quindi da provare a fare un test dove la valuta dell'azienda è EUR

2023-12-05 09:42 UTC, sergiocorato requested changes
Test su runboat con nota di credito con valori negativi non quadrano le righe contabili:
![Screenshot(296)](https://github.com/OCA/l10n-italy/assets/7657311/89aec607-1d9d-4d01-86f3-a6cabeaeb521)

Test in locale con nota di credito con valori negativi con stesso problema:
![Screenshot(297)](https://github.com/OCA/l10n-italy/assets/7657311/0baf292c-6fe8-44e1-9394-78f5d1bf0823)

Test su runboat con fattura fornitore negativa non quadra (anche se ci fosse l'imposta):
![Screenshot(298)](https://github.com/OCA/l10n-italy/assets/7657311/f554ca18-4705-46fe-a4a9-2657c0359ac2)

Senza questa PR la nota di credito fornitore con importi negativi viene caricata correttamente, non riesco quindi a riprodurre il bug che risolve, non risolve comunque il #2465

2023-12-05 09:52 UTC, sergiocorato commented
Forse non mi è chiaro il risultato che si vuole ottenere, visto che la fattura negativa non è validabile.

2023-12-06 14:36 UTC, eLBati commented
@sergiocorato grazie.
Ho modificato così: https://github.com/OCA/l10n-italy/compare/26336a73f2d6204f1b82031352222dac057e26c6..64f3c7586b6f907426ddf475ab394f2315a3c381
Non ho trovato un metodo che ricalcolasse `amount_currency`

2024-02-26 14:01 UTC, sergiocorato approved these changes

2024-02-26 14:02 UTC, sergiocorato commented
/ocabot merge patch

2024-02-26 14:16 UTC, merged

2024-06-25 09:57 UTC, matteoopenf commented
Buongiorno,

mi sta accadendo a seguito di questa pr.
Che arrivato a questo punto:
![image](https://github.com/OCA/l10n-italy/assets/43987335/3fb79b4b-99b0-4416-8387-e210a314d831)

Che se importo una fattura con il minimo, invoice_line_ids e' vuoto, quindi fallisce il check all'interno del for e quindi un documento td 01 mi diventa una nota di credito.
Cio' non mi accade con il massimo.
Credo che prima del for vada controllato se invoice_line_ids e' valorizzato