[16.0] FIX access error to e-invoices for users who did not create the attachment
OCA/l10n-italy pull request #3827
Opened 2024-01-09 17:11 UTC by eLBati

2024-01-10 13:58 UTC, mrcast approved these changes
Functional test ok!

2024-01-13 11:50 UTC, TheMule71 commented
In generale mi piaceve di più l'idea di creare gli allegati correttamente, e non con `res_id` e `res_model` NULL, anche per https://github.com/odoo/odoo/blob/e8834cb00b82e0bee7f6338aef940037a3e49471/odoo/addons/base/models/ir_attachment.py#L444C1-L444C13
che suggerisce on odoo li considerano dei left-over.

Non vorrei che un giorno qualcuno in odoo / OCA / * pensasse che sia una buona idea rimuovere tutti gli allegati "orfani".

2024-01-17 17:23 UTC, matteoopenf commented
> In generale mi piaceve di più l'idea di creare gli allegati correttamente, e non con `res_id` e `res_model` NULL, anche per https://github.com/odoo/odoo/blob/e8834cb00b82e0bee7f6338aef940037a3e49471/odoo/addons/base/models/ir_attachment.py#L444C1-L444C13 che suggerisce in odoo li considerano dei left-over.
> 
> Non vorrei che un giorno qualcuno in odoo / OCA / * pensasse che sia una buona idea rimuovere tutti gli allegati "orfani".

si in effetti e' pericoloso lasciarli orfani perche' diventerebbero soggeti a eliminazione

2024-01-18 09:28 UTC, eLBati commented
> Non vorrei che un giorno qualcuno in odoo / OCA / * pensasse che sia una buona idea rimuovere tutti gli allegati "orfani".

Questo lo vedo difficile, perchè di `ir.attachment` non collegati a alcun record ce ne sono parecchi (immagini, CSS...)

2024-01-18 09:30 UTC, eLBati commented
> si in effetti e' pericoloso lasciarli orfani perche' diventerebbero soggeti a eliminazione

Non mi risulta, vedi sopra.

Provate a cercare in un DB di produzione, magari con website, attachment dove `res_model` non è valorizzato

2024-02-14 14:45 UTC, SirAionTech requested changes
Grazie della PR!
Come mai il commit non rispetta le linee guida? Vedi https://github.com/OCA/odoo-community.org/blob/8afdb5a5ebfd3314e2fc836c9b9f644468ee044e/website/Contribution/CONTRIBUTING.rst#L1114.

Puoi aggiungere un test? Così si evitano regressioni

2024-02-14 14:45 UTC, SirAionTech commented on l10n_it_fatturapa_in/models/attachment.py
> +        for attachment in self:
Giusto una nota per dire che normalmente nei metodi `api.model` `self` è un recordset vuoto, questo metodo però viene anche chiamato su dei record, ad esempio in https://github.com/odoo/odoo/blob/d752abb24d9b25bb6d10e411961447c8c8e28bba/odoo/addons/base/models/ir_attachment.py#L503

2024-02-14 14:45 UTC, SirAionTech commented on l10n_it_fatturapa_in/models/attachment.py
> +                .search([("ir_attachment_id", "=", attachment.id)])
Cercare all'interno di un loop è molto dispendioso, si può spostare la ricerca fuori dal loop?

2024-02-14 14:45 UTC, SirAionTech commented on l10n_it_fatturapa_out/models/attachment.py
> +    @api.model
Tutto questo è duplicato di quanto sopra, non sono tante righe ma dici che è possibile ridurre la duplicazione del codice?

2024-03-01 15:32 UTC, eLBati commented
> Come mai il commit non rispetta le linee guida?

modificato

2024-03-01 18:52 UTC, eLBati commented
Sposto in https://github.com/OCA/l10n-italy/pull/3785 a causa del refactoring `fatturapa.attachment`

2024-03-01 18:52 UTC, closed without merging

2024-03-04 08:39 UTC, SirAionTech commented
> Sposto in #3785 a causa del refactoring `fatturapa.attachment`

Ok, ma credo abbia più speranze di essere mergiata se resta indipendente.
Come mai il refactoring `fatturapa.attachment` (immagino tu intenda il commit https://github.com/OCA/l10n-italy/pull/3785/commits/3ed6b63ac8d2616e261a6734e9e54facc240d30b di #3785) impone di spostarla in #3785?

2024-03-04 09:36 UTC, eLBati commented
Perchè le 2 PR toccavano gli stessi file e da separate, se mergiate, non funzionavano, vedi ad es `_check_access_ftpa`

2024-03-04 09:50 UTC, SirAionTech commented
> Perchè le 2 PR toccavano gli stessi file e da separate, se mergiate, non funzionavano, vedi ad es `_check_access_ftpa`

Capito grazie, quindi le PR di per sé non hanno problemi: ci sono problemi solo quando cerchi di usarle entrambe