[16.0] FIX l10n_it_reverse_charge avoiding extra "exchange difference" entry
OCA/l10n-italy pull request #3879
Opened 2024-01-22 16:53 UTC by eLBati

Estensione di https://github.com/OCA/l10n-italy/pull/3864

Altrimenti la registrazione che chiude le autofatture sarebbe di questo tipo:

![image](https://github.com/OCA/l10n-italy/assets/1033131/9faf6c13-18d1-4275-b9ea-19dc3fc2df5a)

quindi con una valuta estera ma senza importo.

Questo produce (mentre su v12 no) una registrazione extra di questo tipo:

![image](https://github.com/OCA/l10n-italy/assets/1033131/4577ae9d-fb58-450f-bbd7-6ad17b3f831a)

2024-02-06 11:22 UTC, eLBati commented
/ocabot rebase

2024-02-14 13:10 UTC, SirAionTech requested changes
Grazie della PR!
Puoi aggiungere un test? Così si evitano regressioni

2024-06-28 09:09 UTC, MaurizioPellegrinet commented
Appena disponibile runboat la provo

2024-06-28 10:20 UTC, odooNextev commented on l10n_it_reverse_charge/models/account_move.py
@eLBati la differenza (secondo me) sostanziale tra la mia e la tua PR è nel metodo `compute_rc_amount_tax_main_currency` perchè mi tengo da parte il valore della fattura originale per evitare una conversione di un valore già convertito e quindi possibili errori di arrotondamenti:
https://github.com/OCA/l10n-italy/pull/4238/files#diff-3c6a29bf7c09821dd6605e9b9c729ab09d0c83b13505138134c227b0b202ac2dR184

Per il resto sono molto simili e posso pensare di aggiungere un test

2024-07-19 08:31 UTC, eLBati commented
https://github.com/OCA/l10n-italy/pull/4238#issuecomment-2238655507

2024-10-24 15:52 UTC, eLBati commented
Avendo fatto merge di https://github.com/OCA/l10n-italy/pull/4238 questa si può chiudere giusto @odooNextev ?

2024-10-24 16:01 UTC, francesco-ooops commented
@eLBati dunque confermi che risolve il problema indicato in https://github.com/OCA/l10n-italy/issues/3863 ?

2024-10-25 10:49 UTC, eLBati commented
> @eLBati dunque confermi che #4238 risolve il problema indicato in #3863 ?

sì

2024-10-25 10:51 UTC, francesco-ooops commented
@eLBati allora direi che chiudo dato che questa risolve #3863

2024-10-25 10:51 UTC, closed without merging