[FIX] l10n_it_riba: remove account and journal domain
OCA/l10n-italy pull request #3928
Opened 2024-02-05 16:08 UTC by odooNextev

Questa fix permette di ammettere che sia il conto portafoglio (accettazione) che il conto di accredito (quello che si muove in D) siano dei conti outstanding che riportano la scadenza.
In questo modo anche chi utilizza questo modulo dovrebbe in futuro poter convergere ad odoo standard in modo semplice.

https://discord.com/channels/753902328494424064/753902328494424070/1200197828044140584

2024-02-14 09:18 UTC, SirAionTech approved these changes
Grazie della PR!
Ho fatto solo revisione del codice e per me è ok.
Puoi aprire la issue di tracciamento? Vedi https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue.

@marco-marchiori puoi vedere se è quello che intendevi in https://discord.com/channels/753902328494424064/753902328494424070/1200197828044140584?

2024-05-10 08:24 UTC, andreampiovesana approved these changes
LGTM

2024-05-10 08:48 UTC, odooNextev commented
@OCA/local-italy-maintainers quando riuscite si può mergiare?

2024-05-20 15:25 UTC, andreampiovesana commented
merge?

2024-05-21 07:21 UTC, eLBati requested changes

2024-05-21 07:21 UTC, eLBati commented on l10n_it_riba/readme/CONTRIBUTORS.rst
> +* Nextev Srl <odoo@nextev.it>
Non andrebbe modificato il `CONTRIBUTORS.md`?

2024-05-21 07:28 UTC, odooNextev commented on l10n_it_riba/readme/CONTRIBUTORS.rst
> +* Nextev Srl <odoo@nextev.it>
Hai ragione, comunque per semplicità tolgo il file e lascio la modifica dei contributors per la prossima PR dell'esposizione sempre delle riba

2024-05-22 07:27 UTC, eLBati commented
/ocabot merge patch

2024-05-22 07:58 UTC, merged