[16.0] [FIX] l10n_it_fatturapa_import_zip correctly imports all XML files in zip
OCA/l10n-italy pull request #3959
Opened 2024-02-14 10:53 UTC by rlucia

Corregge https://github.com/OCA/l10n-italy/issues/3958

Con queste modifiche, dopo l'estrazione del contenuto dello zip file:
 - non vengono presi in considerazione tutti i file estratti
 - vengono presi in considerazione solo XML validi
 - vengono presi in considerazione solo file con estensione `.p7m` (in questa fase mi è sembrato un overkill verificarne anche la correttezza formale)
 - viene fatto uno scan di tutti i file anche nelle subdirectory
 - aggiunto logging che informa quali file vengono importati e cosa viene scartato

E' stato modificato il file `xml_import.zip` utilizzato dai test, che ora contiene anche un file non xml e non p7m, ed alcuni xml in una subdirectory.

2024-02-14 11:31 UTC, SirAionTech requested changes
Grazie della PR!
Ho fatto solo revisione del codice.

Puoi aggiungere un test? Così si evitano regressioni.

Puoi verificare come mai falliscono i test esistenti? Finché falliscono la PR non si può mergiare.

Per il messaggio del commit, puoi seguire https://github.com/OCA/odoo-community.org/blob/8afdb5a5ebfd3314e2fc836c9b9f644468ee044e/website/Contribution/CONTRIBUTING.rst#L1114?

2024-02-14 12:08 UTC, SirAionTech commented
> @SirAionTech grazie. Appena ho un attimo verifico le commit messages rules. Nel frattempo comunque edito il commento della PR.
> 
> Btw, il test falliva perché non avevo considerato l'import di file p7m.
> 
> Rifatto anche il file xml_import.zip che contiene un file che dovrebbe essere escluso e spostati alcuni file in subdirectory. Cosi' il test effettivamente verifica il codice modificato.

Perfetto grazie, quando vuoi che aggiorni la revisione puoi richiederlo direttamente in Github seguendo https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review
![image](https://github.com/OCA/l10n-italy/assets/143788994/1655022b-2aec-4fdc-a0d2-58263b9fe544)

2024-02-15 06:50 UTC, rlucia commented on l10n_it_fatturapa_import_zip/models/attachment.py
> +            ET.parse(file_path)
LGTM

2024-02-23 09:26 UTC, TheMule71 approved these changes
LGTM

2024-02-23 09:26 UTC, TheMule71 commented
/ocabot merge patch

2024-02-23 09:48 UTC, merged