[14.0] [FIX] l10n_it_delivery_note: error in sequence name generation
OCA/l10n-italy pull request #4052
Opened 2024-03-14 11:54 UTC by renda-dev

Keep generating name with sequence number until one is available.

This could be useful because if for any weird reason a DN with the next sequence has already been created it would show a validation error.

2024-03-14 15:10 UTC, SicurSam approved these changes

2024-03-15 09:21 UTC, aleuffre requested changes

2024-03-15 09:21 UTC, aleuffre commented on l10n_it_delivery_note/models/stock_delivery_note.py
> +                        break
**issue**: il nome del DN deve essere unico per company, non globalmente. Credo sia opportuno aggiungere `company_id` a questa search.

2024-03-15 09:28 UTC, renda-dev commented on l10n_it_delivery_note/models/stock_delivery_note.py
> +                        break
Pienamente d'accordo, grazie mille!

2024-03-15 09:31 UTC, aleuffre approved these changes
Code review

2024-03-15 09:31 UTC, aleuffre commented
/ocabot merge patch

2024-03-15 10:00 UTC, merged