[16.0] l10n_it_intrastat_statement ricalcola la sequenza dopo la poss…
OCA/l10n-italy pull request #4077
Opened 2024-03-27 16:25 UTC by robyf70

La PR per la v16 di #3904

2024-03-28 09:03 UTC, sergiocorato approved these changes

2024-07-18 10:30 UTC, SirAionTech requested changes
Grazie della PR!
Puoi modificare il messaggio del commit per seguire https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
In particolare:
> Commit messages are in English

Potresti aggiungere un test per verificare che il problema viene risolto? Così si evitano regressioni

2024-11-20 14:26 UTC, MaurizioPellegrinet commented
@SirAionTech @sergiocorato è possibile testarla?

2024-11-20 14:32 UTC, francesco-ooops commented
/ocabot rebase

2024-11-20 14:32 UTC, francesco-ooops commented
@robyf70 puoi fare rebase?

2024-12-11 13:45 UTC, sergiocorato commented
/ocabot rebase

2025-01-17 14:59 UTC, tafaRU commented
Sostituita da https://github.com/OCA/l10n-italy/pull/4558

2025-01-17 14:59 UTC, closed without merging