[16.0] [ADD] l10n_it_withholding_tax_account_accountant: fix per account_accountant
OCA/l10n-italy pull request #4138
Opened 2024-05-15 14:41 UTC by LorenzoC0

Risolve #4137 , dipende da #4136 

Questo modulo sistema il calcolo dell'importo delle registraioni contabili in caso di ritenuta d'acconto su ambienti in cui è installato il modulo l10n_it_withholding_tax e account_accountant.

2024-05-15 15:47 UTC, eLBati requested changes
Grazie

2024-05-15 15:47 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/readme/DESCRIPTION.md
> +e account_accountant.
@LorenzoC0 puoi descrivere un po' più precisamente il caso d'uso specificando che riguarda la riconciliazione bancaria?

2024-05-15 15:47 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "category": "Hidden",
@LorenzoC0 puoi aggiungere `auto_install`?

2024-05-15 15:47 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "name": "l10n_it_withholding_tax_account_accountant",
Qua ci vuole un nome parlante, vedi altri moduli

2024-05-15 15:47 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "author": "Innovyou, " "Odoo Community Association (OCA)",
Qua ci sono delle virgolette di troppo

2024-05-15 15:47 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/models/bank_rec_widget.py
> +        return super()._lines_widget_prepare_aml_line(aml, **kwargs)
`super` non sovrascrive i campi di `kwargs` che ci interessano?

2024-05-20 12:38 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/models/bank_rec_widget.py
> +        return super()._lines_widget_prepare_aml_line(aml, **kwargs)
No, vedi 
```
    def _lines_widget_prepare_aml_line(self, aml, **kwargs):
        self.ensure_one()
        return {
            'flag': 'aml',
            'source_aml_id': aml,
            **kwargs,
        }```

2024-05-20 12:41 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/readme/DESCRIPTION.md
> +e account_accountant.
Tipo
"Questo modulo sistema il calcolo degli importi da riconciliare durante la riconciliazione bancaria, in caso di
ritenuta d'acconto, su ambienti in cui sono installati i moduli l10n_it_withholding_tax
e account_accountant"

2024-06-14 15:02 UTC, SirAionTech commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "depends": ["base", "l10n_it_withholding_tax", "account_accountant"],
`account_accountant` è enterprise, quindi dubito che si riuscirà a mergiare

2024-06-17 06:32 UTC, eLBati commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "depends": ["base", "l10n_it_withholding_tax", "account_accountant"],
Per l'esecuzione dei test?

2024-06-17 07:53 UTC, SirAionTech commented on l10n_it_withholding_tax_account_accountant/__manifest__.py
> +    "depends": ["base", "l10n_it_withholding_tax", "account_accountant"],
Sì, e rompe anche runboat (non ricordo se è necessario per il merge)

2025-01-26 12:32 UTC, closed without merging

2025-12-10 13:34 UTC, eLBati commented
/ocabot rebase