[FIX][l10n_it_vat_statement_communication] fix encoding file and remo…
OCA/l10n-italy pull request #4148
Opened 2024-05-21 09:15 UTC by matteoopenf

…ve zero value from xml in according the specification of ADE

2024-05-21 10:59 UTC, matteoopenf commented
sistemo il diff e ci siamo

2024-05-21 12:43 UTC, lorenzoallegrucci approved these changes

2024-05-24 09:45 UTC, MaurizioPellegrinet approved these changes
LGTM, grazie Matteo!

2024-05-24 12:01 UTC, matteoopenf commented
> LGTM, grazie Matteo!

Grazie a te

2024-06-19 08:59 UTC, francesco-ooops commented
@SirAionTech riesci a dare un'occhiata? questa è approvata ma è rimasta arenata

2024-07-03 15:20 UTC, SirAionTech requested changes
Grazie della PR!
Puoi modificare il messaggio del commit 
![image](https://github.com/OCA/l10n-italy/assets/143788994/41edacaa-d06f-4c4c-9c78-b5da57aab689)
in modo che segua le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
In particolare
> please check if the commit message is cut with ellipsis

e forse la descrizione del commit potrebbe essere meno ripetitiva :wink: 

Puoi aggiungere un test? Così si evitano regressioni.
Esiste già un test che crea il file, magari puoi semplicemente controllare che abbia l'encoding come te lo aspetti.

Ho cercato in https://www.agenziaentrate.gov.it/portale/web/guest/iva-2024 e non ho trovato parti che obbligano ad includere l'encoding, ma suppongo non faccia male aggiungerlo.
Ho provato a usare il software di controllo su una dichiarazione generata in runboat ma ci sta mettendo un po' tanto ad aprirsi, secondo me non gli piace Ubuntu.

2024-07-09 15:06 UTC, matteoopenf commented
> Grazie della PR! Puoi modificare il messaggio del commit ![image](https://private-user-images.githubusercontent.com/143788994/345465972-41edacaa-d06f-4c4c-9c78-b5da57aab689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mzc4NDQsIm5iZiI6MTcyMDUzNzU0NCwicGF0aCI6Ii8xNDM3ODg5OTQvMzQ1NDY1OTcyLTQxZWRhY2FhLWQwNmYtNGM0Yy05Yzc4LWI1ZGE1N2FhYjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxNTA1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTI4YTdiMzUxOThlODY5ZjhjMDJhZmFiNDUyNDEzMDMwOGFmNTQyNjg1OTg2ZTRkMjllOThjODkzZjE4ZDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IoV8pXr02gAJbS3tS_AZIQUnYjtExW60GgpZ1zEpoHU) in modo che segua le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? In particolare
> 
> > please check if the commit message is cut with ellipsis
> 
> e forse la descrizione del commit potrebbe essere meno ripetitiva 😉
> 
> Puoi aggiungere un test? Così si evitano regressioni. Esiste già un test che crea il file, magari puoi semplicemente controllare che abbia l'encoding come te lo aspetti.
> 
> Ho cercato in https://www.agenziaentrate.gov.it/portale/web/guest/iva-2024 e non ho trovato parti che obbligano ad includere l'encoding, ma suppongo non faccia male aggiungerlo. Ho provato a usare il software di controllo su una dichiarazione generata in runboat ma ci sta mettendo un po' tanto ad aprirsi, secondo me non gli piace Ubuntu.

si i test li ho dovuti fare poi su windows, per il test non sono praticissimo, vedo intanto per sistemare il messaggio di commit che facendo rebase si sono sommati

2024-07-09 17:13 UTC, matteoopenf commented
commit sistemato

2024-07-09 17:16 UTC, matteoopenf commented
> Grazie della PR! Puoi modificare il messaggio del commit ![image](https://private-user-images.githubusercontent.com/143788994/345465972-41edacaa-d06f-4c4c-9c78-b5da57aab689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDU1NjMsIm5iZiI6MTcyMDU0NTI2MywicGF0aCI6Ii8xNDM3ODg5OTQvMzQ1NDY1OTcyLTQxZWRhY2FhLWQwNmYtNGM0Yy05Yzc4LWI1ZGE1N2FhYjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxNzE0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTBlMTM3MDZhOWIzNzc2NmNhMTkzN2Q5ZWM5OGY4MzkzNTNlY2ViZGRhYzBmNGU2OTBmNTNkMGJhMmJhYjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v4V1pB6rc2t7-LbXBuwmkymtxWtWwjselBxLWWcKnzM) in modo che segua le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? In particolare
> 
> > please check if the commit message is cut with ellipsis
> 
> e forse la descrizione del commit potrebbe essere meno ripetitiva 😉
> 
> Puoi aggiungere un test? Così si evitano regressioni. Esiste già un test che crea il file, magari puoi semplicemente controllare che abbia l'encoding come te lo aspetti.
> 
> Ho cercato in https://www.agenziaentrate.gov.it/portale/web/guest/iva-2024 e non ho trovato parti che obbligano ad includere l'encoding, ma suppongo non faccia male aggiungerlo. Ho provato a usare il software di controllo su una dichiarazione generata in runboat ma ci sta mettendo un po' tanto ad aprirsi, secondo me non gli piace Ubuntu.

non trovo il test che crea il file per anche solo ipotizzare la modifica del test, per caso me lo puoi indicare?

2024-07-10 07:12 UTC, SirAionTech commented
> > Puoi aggiungere un test? Così si evitano regressioni.
Esiste già un test che crea il file, magari puoi semplicemente controllare che abbia l'encoding come te lo aspetti.
>
> non trovo il test che crea il file per anche solo ipotizzare la modifica del test, per caso me lo puoi indicare?

Ah hai ragione, stavo guardando in `16.0` dove c'è https://github.com/OCA/l10n-italy/blob/9f773c4fd8a757bf82d93c9a5047e476e005cdde/l10n_it_vat_statement_communication/tests/test_vat_statement_communication.py#L380.
In `14.0` non c'è ancora nulla :scream:

2024-07-10 07:16 UTC, SirAionTech commented
> > Grazie della PR! Puoi modificare il messaggio del commit ![image](https://private-user-images.githubusercontent.com/143788994/345465972-41edacaa-d06f-4c4c-9c78-b5da57aab689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTU1NjksIm5iZiI6MTcyMDU5NTI2OSwicGF0aCI6Ii8xNDM3ODg5OTQvMzQ1NDY1OTcyLTQxZWRhY2FhLWQwNmYtNGM0Yy05Yzc4LWI1ZGE1N2FhYjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNzA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjI0ZTA1NGQ0ZGI5ZDZjYjNmMGZiYjg0Y2JmZDZiMjVmZjI2ZDY4ZWUxMDI4Y2M1M2E2MzA4YmNjZTA3YzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWnGIVNrYKSeEwgcfRi7Gy2hMCrPyurMmyXENv1d-wM) in modo che segua le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
In particolare
> > 
> > > please check if the commit message is cut with ellipsis
>>
> > e forse la descrizione del commit potrebbe essere meno ripetitiva 😉
>
> commit sistemato

Grazie, ora è meno ripetitivo :smile:
![image](https://github.com/OCA/l10n-italy/assets/143788994/cb11c469-0545-4c06-94fe-786de89dfc30)
però ancora non segue le linee guida, per lo stesso motivo che ho scritto sopra

2024-07-10 07:19 UTC, matteoopenf commented
> > > Grazie della PR! Puoi modificare il messaggio del commit ![image](https://private-user-images.githubusercontent.com/143788994/345465972-41edacaa-d06f-4c4c-9c78-b5da57aab689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTU1NjksIm5iZiI6MTcyMDU5NTI2OSwicGF0aCI6Ii8xNDM3ODg5OTQvMzQ1NDY1OTcyLTQxZWRhY2FhLWQwNmYtNGM0Yy05Yzc4LWI1ZGE1N2FhYjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNzA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjI0ZTA1NGQ0ZGI5ZDZjYjNmMGZiYjg0Y2JmZDZiMjVmZjI2ZDY4ZWUxMDI4Y2M1M2E2MzA4YmNjZTA3YzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWnGIVNrYKSeEwgcfRi7Gy2hMCrPyurMmyXENv1d-wM) in modo che segua le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
> > > In particolare
> > > > please check if the commit message is cut with ellipsis
> > > 
> > > 
> > > e forse la descrizione del commit potrebbe essere meno ripetitiva 😉
> > 
> > 
> > commit sistemato
> 
> Grazie, ora è meno ripetitivo 😄 ![image](https://private-user-images.githubusercontent.com/143788994/347296851-cb11c469-0545-4c06-94fe-786de89dfc30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTYyMTIsIm5iZiI6MTcyMDU5NTkxMiwicGF0aCI6Ii8xNDM3ODg5OTQvMzQ3Mjk2ODUxLWNiMTFjNDY5LTA1NDUtNGMwNi05NGZlLTc4NmRlODlkZmMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNzE4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDc3Y2U1MDEwZGIwNDRhNDY1OTdlMTU3ODNlMzA4NDU0ZDBkYjgyODJiYmZiYzVjY2E0YjcxOWRmNTk1ZDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FLHqDAGlX8rPUF-sthdTMEdMvXiXr6wQ7bKmdjyxRsk) però ancora non segue le linee guida, per lo stesso motivo che ho scritto sopra

ora?

2024-07-11 14:48 UTC, SirAionTech approved these changes
Visto che non esiste già nulla di simile nei test e la modifica è minima, _per stavolta_ mergiamo senza test :smile:
/ocabot merge patch

2024-07-11 14:50 UTC, matteoopenf commented
> Visto che non esiste già nulla di simile nei test e la modifica è minima, _per stavolta_ mergiamo senza test :smile:
> 
> /ocabot merge patch

Grazie mille

2024-07-11 15:03 UTC, merged