[16.0][IMP] account_vat_period_end_statement: Updated "Total Statement" label to specify if total is credit or debit
OCA/l10n-italy pull request #4204
Opened 2024-06-12 10:37 UTC by LorenzoC0

#4203

2024-06-12 10:56 UTC, MaurizioPellegrinet approved these changes
Functional test: ok

2024-06-12 12:12 UTC, andreampiovesana approved these changes
LGTM

2024-06-18 10:25 UTC, SirAionTech requested changes
Grazie della PR!
Ho fatto solo revisione del codice, vedi i commenti qui sotto.

Puoi modificare il messaggio del commit per seguire https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
Ad esempio, manca
> please check if the commit message is cut with ellipsis.

2024-06-18 10:25 UTC, SirAionTech commented on account_vat_period_end_statement/views/report_vatperiodendstatement.xml
> -
Questo si può rimuovere?

2024-06-18 10:25 UTC, SirAionTech commented on account_vat_period_end_statement/views/report_vatperiodendstatement.xml
> +                                    t-if="not (total_statement >= 0)"
Giusto per info, esiste anche `t-else` (https://www.odoo.com/documentation/16.0/developer/reference/frontend/qweb.html#conditionals).

2025-04-07 09:32 UTC, eLBati commented
/ocabot merge patch

2025-04-07 14:12 UTC, francesco-ooops commented
/ocabot merge patch

2025-04-07 15:06 UTC, merged