[16.0] [IMP] l10n_it_asset_management: refactoring for compatibility with Odoo Enterprise
OCA/l10n-italy pull request #4212
Opened 2024-06-13 14:07 UTC by eLBati

2024-06-28 07:28 UTC, SirAionTech commented
Risolve #3952 per `16.0`.

2024-06-28 09:23 UTC, SirAionTech requested changes
Grazie della PR!
Puoi modificare il commit in modo che segua le linee guida?
Ad esempio
> please check if the commit message is cut with ellipsis

(da https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message)

Puoi aggiungere gli script di migrazione dei dati?
Altrimenti all'aggiornamento del modulo verranno persi tutti i dati dei cespiti: ho provato e ad esempio le Info contabili spariscono passando da 
![image](https://github.com/OCA/l10n-italy/assets/143788994/739bc9df-166d-404c-a46e-2f8703fa38d2)
a
![image](https://github.com/OCA/l10n-italy/assets/143788994/36d58099-0d51-4773-9812-c6739b2fc8fb)

2024-11-13 11:14 UTC, micheledic commented
@eLBati potresti fixare i problemi segnalati ? questa PR penso sia utile a molti

2024-11-13 11:31 UTC, francesco-ooops commented
/ocabot rebase

2025-02-26 13:29 UTC, micheledic commented
ci sono novità ? servirebbero gli ultimi fix  e le migrations così che si può partire con la mig alla 18.0+

2025-02-27 15:40 UTC, eLBati commented
@micheledic c'è da risolvere i conflitti.
Se volessi farlo, puoi creare un nuovo branch a partire da 16.0 e provare ad applicare il commit

2025-03-07 16:24 UTC, francesco-ooops commented
superseeded by #4635

2025-03-07 16:24 UTC, closed without merging