[FIX][l10n_it_fatturapa_in] fix import with type minimo, and  add che…
OCA/l10n-italy pull request #4229
Opened 2024-06-25 10:08 UTC by matteoopenf

Risolve https://github.com/OCA/l10n-italy/issues/4228

2024-06-25 10:26 UTC, patrickt-oforce approved these changes

2024-06-25 10:26 UTC, lorenzoallegrucci approved these changes

2024-06-25 10:31 UTC, amosdisabatino approved these changes

2024-06-27 15:34 UTC, francesco-ooops commented
@matteoopenf puoi sistemare il nome del commit secondo le guidelines? grazie!

2024-06-28 06:27 UTC, matteoopenf commented
> @matteoopenf puoi sistemare il nome del commit secondo le guidelines? grazie!

Il problema è solo il nome del modulo tra parentesi esatto?
Fammi sapere così provo ad arrivarci entro fine giornata

2024-06-28 07:11 UTC, MaurizioPellegrinet approved these changes
LGTM

2024-07-08 15:13 UTC, matteoopenf commented
@francesco-ooops  fatto merge?

2024-07-08 15:19 UTC, francesco-ooops commented
@matteoopenf so che è una pipponata e non so darti indicazioni pratiche perchè non uso github, ma metterei nel nome commit:

[FIX]l10n_it_fatturapa_in: fix import with type minimo

E nella descrizione commit:

Added check if invoice_line_ids is valorize to check the price_unit, if is not valorize stop the method because is not possibile assume the line is negative

2024-07-08 15:22 UTC, matteoopenf commented
> @matteoopenf so che è una pipponata e non so darti indicazioni pratiche perchè non uso github, ma metterei nel nome commit:
> 
> [FIX]l10n_it_fatturapa_in: fix import with type minimo
> 
> E nella descrizione commit:
> 
> Added check if invoice_line_ids is valorize to check the price_unit, if is not valorize stop the method because is not possibile assume the line is negative

arrivo

2024-07-08 16:03 UTC, francesco-ooops commented
@OCA/local-italy-maintainers mergiamo?

2024-07-09 12:24 UTC, SirAionTech requested changes
Grazie della PR!
Ho provato in runboat e confermo che il problema si verifica in `14.0` con il file https://github.com/OCA/l10n-italy/blob/1c0e8323ec675550e84129bdf9292ccd5962fb6d/l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml:
![image](https://github.com/OCA/l10n-italy/assets/143788994/726f02d3-93d8-4fb0-8a67-9b9549418439)
(da http://oca-l10n-italy-14-0-d2bffbf6a8d1.runboat.odoo-community.org/web#id=15&active_id=1&model=account.move&view_type=form&cids=&menu_id=134).
Il problema viene corretto da questa PR (importando lo stesso file): 
![image](https://github.com/OCA/l10n-italy/assets/143788994/cda772d3-92cd-4e14-ab61-1b8ddda27142)
(da http://oca-l10n-italy-14-0-pr4229-9ecd104a85f3.runboat.odoo-community.org/web#id=15&active_id=1&model=account.move&view_type=form&cids=&menu_id=134)

Puoi aggiungere o modificare un test esistente in modo che fallisca senza questa correzione? Basterebbe anche solo aggiungere un controllo sul tipo di `move` nel test che usa il dettaglio minimo.

2024-07-09 12:27 UTC, matteoopenf commented
> Grazie della PR!
> 
> Ho provato in runboat e confermo che il problema si verifica in `14.0` con il file https://github.com/OCA/l10n-italy/blob/1c0e8323ec675550e84129bdf9292ccd5962fb6d/l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml:
> 
> ![image](https://github.com/OCA/l10n-italy/assets/143788994/726f02d3-93d8-4fb0-8a67-9b9549418439)
> 
> (da http://oca-l10n-italy-14-0-d2bffbf6a8d1.runboat.odoo-community.org/web#id=15&active_id=1&model=account.move&view_type=form&cids=&menu_id=134).
> 
> Il problema viene corretto da questa PR (importando lo stesso file): 
> 
> ![image](https://github.com/OCA/l10n-italy/assets/143788994/cda772d3-92cd-4e14-ab61-1b8ddda27142)
> 
> (da http://oca-l10n-italy-14-0-pr4229-9ecd104a85f3.runboat.odoo-community.org/web#id=15&active_id=1&model=account.move&view_type=form&cids=&menu_id=134)
> 
> 
> 
> Puoi aggiungere o modificare un test esistente in modo che fallisca senza questa correzione? Basterebbe anche solo aggiungere un controllo sul tipo di `move` nel test che usa il dettaglio minimo.

Provo a guardare come torno sul problema per fare la pr anche per 16.0

2024-07-12 12:39 UTC, eLBati requested changes
LGTM

2024-07-12 12:39 UTC, eLBati approved these changes

2024-07-12 16:53 UTC, matteoopenf commented
@SirAionTech scusami sto tentando di fare il test "opposto" al 54, ma non capisco come dire di importare al minimo la fattura anziche' al massimo.
Per caso sai dirmi come fare?

2024-07-12 17:02 UTC, matteoopenf commented
ho provato a creare il test vediamo come va

2024-07-12 17:50 UTC, matteoopenf commented
@SirAionTech  sto ottenendo questo errore tentando di forzare l'import al minimo
![image](https://github.com/user-attachments/assets/fb89186d-5710-4210-a24d-2337f5cbdc90)


Per caso sai darmi un aiuto cosi da concludere la cosa?

2024-07-12 17:52 UTC, matteoopenf commented
oppure come in altri test, prima devo creare il partner e settare il livello di import e poi fare girare il wizard?

2024-07-15 07:27 UTC, SirAionTech commented
Il test `test_16_xml_import` importa con dettaglio minimo:
https://github.com/OCA/l10n-italy/blob/0aa4def826188d5f5ec3eab9bae0839ec8cbee75/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py#L443-L444
lo imposta sul partner prima di importare la fattura, puoi fare allo stesso modo.
Oppure, forse sarebbe più semplice
> aggiungere un controllo sul tipo di `move` nel test che usa il dettaglio minimo.

(da https://github.com/OCA/l10n-italy/pull/4229#pullrequestreview-2166165765)

2024-07-15 07:30 UTC, matteoopenf commented
> Il test `test_16_xml_import` importa con dettaglio minimo:
> 
> https://github.com/OCA/l10n-italy/blob/0aa4def826188d5f5ec3eab9bae0839ec8cbee75/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py#L443-L444
> 
> 
> lo imposta sul partner prima di importare la fattura, puoi fare allo stesso modo.
> Oppure, forse sarebbe più semplice
> > aggiungere un controllo sul tipo di `move` nel test che usa il dettaglio minimo.
> 
> (da [#4229 (review)](https://github.com/OCA/l10n-italy/pull/4229#pullrequestreview-2166165765))

ok provo ad aggiustare li, grazie mille

2024-07-15 08:05 UTC, matteoopenf commented
@SirAionTech ho aggiunto il test e  ci dovremmo essere ora, ho anche fatto il porting sulla pr 16.0

2024-07-15 08:13 UTC, SirAionTech commented
> @SirAionTech ho aggiunto il test e ci dovremmo essere ora, ho anche fatto il porting sulla pr 16.0

Grazie, potresti includere il test nello stesso commit della sua correzione?
Così è chiaro che le due parti di codice sono collegate, senza dover risalire fino a questa PR.

2024-07-15 08:13 UTC, matteoopenf commented
> > @SirAionTech ho aggiunto il test e ci dovremmo essere ora, ho anche fatto il porting sulla pr 16.0
> 
> Grazie, potresti includere il test nello stesso commit della sua correzione? Così è chiaro che le due parti di codice sono collegate, senza dover risalire fino a questa PR.

ok due minuti e li unisco

2024-07-15 08:15 UTC, matteoopenf commented
@SirAionTech  fatto

2024-07-15 08:20 UTC, SirAionTech approved these changes
/ocabot merge patch

2024-07-15 08:35 UTC, merged