[ADD] new module l10n_it_fatturapa_auto_downpayment
OCA/l10n-italy pull request #4230
Opened 2024-06-25 12:43 UTC by TheMule71

Se la fattura è un acconto, setta automaticamente TD02 come tipo documento fiscale.
Tale comportamento è simile a l10n_it_edi

Rimpiazza #4222

Fixes: https://github.com/OCA/l10n-italy/issues/4221

2024-06-25 13:09 UTC, francesco-ooops commented
Non so dare una valutazione su questo caso specifico, ma credo che un obiettivo di oca-italy dovrebbe essere cercare di evitare la proliferazione di nuovi moduli per la contabilità... che ne pensate?

2024-06-25 13:12 UTC, TheMule71 commented
> Non so dare una valutazione su questo caso specifico, ma credo che un obiettivo di oca-italy dovrebbe essere cercare di evitare la proliferazione di nuovi moduli per la contabilità... che ne pensate?

https://github.com/OCA/l10n-italy/pull/4222#issuecomment-2182215610

Ho fatto sia una PR come modifica a modulo esistente e sia una PR come modulo nuovo. Il motivo per avere un nuovo modulo è solo per evitare di introdurre la dipendenza dal modulo `sale` su `l10n_it_fiscal_document_type`.

2024-06-25 18:59 UTC, MaurizioPellegrinet approved these changes
Functional test: OK

2024-06-27 15:23 UTC, SirAionTech requested changes
Grazie della PR!
Potresti mettere **[ADD]** invece di **[IMP]** nel messaggio del commit?
> **[ADD]** for adding new modules

(da https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name)

Grande che hai messo un test :smile: fammi sapere cosa ne pensi delle note qui sotto, le uniche cose bloccanti per me sono nell'override

2024-06-27 15:23 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +        self.ensure_one()
Il metodo in `super` https://github.com/OCA/l10n-italy/blob/0403b98b315ad14f31968495da02f8882bc98428/l10n_it_fiscal_document_type/models/account_move.py#L30 non impone questo vincolo, quindi in teoria può gestire un recordset.
È possibile spostare questo vincolo e il resto del codice che ne ha bisogno dentro un `if len(self) == 1` o qualcosa di analogo?

2024-06-27 15:23 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/readme/CONFIGURE.md
> +- Alla creazione di una fattura di downpayment, viene settato
Perché un elenco?

2024-06-27 15:23 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/readme/USAGE.md
> +The module sets TD02 for downpayment invoices automatically.
Da allineare con l'italiano

2024-06-27 15:23 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +            dt.insert(0, td02.id)
Se **TD02** non viene trovato, si vuole davvero aggiungere `False` come prima scelta per il tipo di documento fiscale?

2024-07-19 08:02 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/readme/USAGE.md
> +The module sets TD02 for downpayment invoices automatically.
A me sembra abbastanza allineato.
"Il modulo funziona automaticamente alla creazione di una fattura di acconto."
"The module sets TD02 for downpayment invoices automatically."

2024-07-19 08:03 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/readme/CONFIGURE.md
> +- Alla creazione di una fattura di downpayment, viene settato
Non so, credo un refuso? In genere copio da un altro modulo e edito.

2024-07-19 08:07 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/readme/USAGE.md
> +The module sets TD02 for downpayment invoices automatically.
Però in pratica "funziona" in inglese viene tradotto con "sets TD02", si può rendere più esplicita la parte in italiano?

2024-07-19 08:20 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +        self.ensure_one()
L'unico punto in cui è chiamata è la `_compute_set_document_fiscal_type()`, all'interno di un loop fattura per fattura.

Piu di quello però, il valore di ritorno è un alista di possibili TDxx _validi per una sola fattura_. La funziona ignora `self` di fatto (potrebbe essere `@api.model`), ma gli vengono passati un solo partner, una sola posizione fiscale, un solo journal, relativi ad una sola fattura.

In pratica la funzione originale è usata come se fosse `self.ensure_one()` e scritta come se fosse `@api.model` . Non credo possa essere chiamata su un recordset, visto che per avere un risultato sensato dovresti assicurarti a priori che sono fatture con lo stesso partner, stessa fpos, stesso journal.

Io ho aggiunto `self.ensure_one()` perché effettivamente uso `self`.

2024-07-19 08:23 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +            dt.insert(0, td02.id)
No, giusto. Diciamo che non so cosa fare se manca però, visto che non dovrebbe mancare la possibilità di generare TD02...

2024-07-19 08:24 UTC, TheMule71 commented
> Grazie della PR! Potresti mettere **[ADD]** invece di **[IMP]** nel messaggio del commit?
> 
> > **[ADD]** for adding new modules

Corretto.

2024-07-19 08:27 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/readme/USAGE.md
> +The module sets TD02 for downpayment invoices automatically.
Sistemato.

2024-08-28 13:23 UTC, sergiocorato commented
@TheMule71 ho aggiunto la PR che avevo proposto in precedenza sulla 14.0, erede di quella proposta sulla 12.0, che hanno un approccio diverso al problema.

2024-09-24 10:16 UTC, matteoopenf commented
ci sono novità in questo modulo?

2024-10-21 14:27 UTC, TheMule71 commented
> ci sono novità in questo modulo?

Dovrebbe essere tutto a posto.

2024-10-21 15:33 UTC, SirAionTech requested changes

2024-10-21 15:33 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +        self.ensure_one()
È vero che il metodo in `super` si comporta come un `api.model` e il risultato dipende solo dai suoi parametri, però credo che questo sia un motivo in più perché l'override aggiunto in questa PR non debba aggiungere vincoli a `self`.

Attualmente potrebbero esserci altri moduli che chiamano `_get_document_fiscal_type` su un recordset e funzionano; dopo l'installazione di questo modulo invece verrebbe sollevato un errore, credo sia meglio evitarlo e rimanere compatibili con il codice esistente.
Non è detto che lo facciano perché si aspettano un risultato in base a `self`, ma semplicemente perché è possibile farlo (come è possibile farlo per i metodi `api.model`).

2024-10-21 15:33 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/README.rst
> +
Puoi eliminare `INSTALL.md`? Altrimenti viene creata questa sezione vuota.

2024-10-21 15:33 UTC, SirAionTech commented on l10n_it_fatturapa_auto_downpayment/readme/CONFIGURE.md
> +TD02 come fiscal document type.
Visto che non c'è nulla da configurare, penso sia meglio rimuovere questo file.

2025-02-24 19:20 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/readme/CONFIGURE.md
> +TD02 come fiscal document type.
Fatto.

2025-02-24 19:20 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/README.rst
> +
Fatto.

2025-02-24 19:53 UTC, TheMule71 commented on l10n_it_fatturapa_auto_downpayment/models/account_move.py
> +        self.ensure_one()
La `_get_document_fiscal_type` viene chiamata da una compute
https://github.com/OCA/l10n-italy/blob/f35ef20e23ada328ce8c73d42488c4a811242b81/l10n_it_fiscal_document_type/models/account_move.py#L8-L28
fattura per fattura.

Per qualche motivo, chi l'ha scritta ha deciso di passare uno ad uno i campi usati per decidere, data _una_
 fattura, l'elenco dei tipi documento disponibili per la scelta.

Si tratta di scelta discutibile, un metodo che li legga da `self` avrebbe avuto molto più senso.  Ma rimane che la logica della funzione - sia per come è definita, sia per come è usata - è quella di fornire i possibili valore del document type di una singola fattura.

La scelta ha fatto si che sia _tecnicamente_ possibile chiamarla su in recordset, ma logicamente non ha senso, visto che comunque o gestisci il fatto che fatture diverse hatto tutte gli stessi valori per i campi in questione, oppure semplicemente la chiami coi valori fattura per fattura, oppure ottieni una risposta che non si puó applicare ad un recordset, ma solo alla fattura di cui hai passato i valori.

In altre parole, il metodo prende comunue i dati specifici singoli e non supporta in ogni caso un recordset, sul quale funziona per caso e non fornisce la risposta giusta. Visto che stiamo parlando di un ipotetico modulo la usasse in quel modo, funzionerebbe solo per caso e non farebbe quello che dovrebbe comunque, visto che non lavora sul recordset ma sui singoli valori. Sarebbe comunque un bug, che non tira eccezione solo grazie a un secondo bug (o scelta di design molto discutibile).

Per altro, non c'è soluzione... se _get_document_fiscal_type() fornisce l'elenco dei possibili valore del document type di una specifica fattura, se la si vuole estendere a criteri che vanno oltre agli argomenti già previsti, bisogna accedere a self. E a quel punto, che ci sia ensure_one in testa o dia errore dopo cambia poco. La posso anche togliere, ma l'eccezione la tirerebbe dopo comunque.

Posso anche riscrivere il metodo per loopare sui record, controllare che siano tutte fatture di downpayment, e restituire un elenco di valori, per poi tirare un'eccezione se le fatture non sono omogenee (o tutte acconti o tutte no). Ma non cambia il fatto che comunque l'ipotetico modulo che chiama il metodo su recordset non omogenei si troverebbe un'eccezione che ieri non c'era.

E poi se parliamo di ipotetici moduli là fuori, ogni volta che si fixa un bug si va a rischio di "rompere" un qualche modulo che implementi una fix o un workaround del bug. La cosa non ci deve impedire di fixare bug, e nel modo migliore.

2025-02-24 20:06 UTC, TheMule71 commented
> @TheMule71 ho aggiunto la PR che avevo proposto in precedenza sulla 14.0, erede di quella proposta sulla 12.0, che hanno un approccio diverso al problema.

Visto, ma passi dalla creazione fattura via sale order. Io per es. ho implementato un modo diverso di creare le fatture di downpayment per un cliente, che vedeva proprio una limitazione nel dover passare dal SO. Gli acconti che preparano sono slegati da un singolo SO e fatture di SO diversi possono andare a scontare dalla stessa fattura di acconto.

È compatibile con il resto di Odoo perche _is_downpayment() fa la cosa giusta e riconosce sia le fatture di acconto standard Odoo sia quelle create direttamente senza passare da SO.

Abbiamo già una funzione che prende:
```
                invoice.move_type,
                invoice.partner_id,
                invoice.fiscal_position_id,
                invoice.journal_id,
```
e propone un elenco di possibili TD* da presentare all'utente. Il che è un po' diverso da impostare un default.

2025-08-17 12:42 UTC, closed without merging