[14.0][IMP] add ability to set intrastat only for in_ or out_ invoices in l10n_it_intrastat
OCA/l10n-italy pull request #4256
Opened 2024-07-09 15:05 UTC by sergiocorato

2024-07-09 16:12 UTC, MaurizioPellegrinet approved these changes
Test funzionale: OK

2024-07-10 07:04 UTC, sergiocorato commented
> Test funzionale: OK

Grazie, ho fatto delle ulteriori modifiche per un discorso funzionale: ho rimosso il campo `Intrastat` generico e lasciato solo i due nuovi campi, così che sia chiaro all'utente di cosa sta impostando.
Ho aggiunto uno script di migrazione che va a settare a `True` i due nuovi campi quando il campo `Intrastat` è impostato.

2024-07-10 07:29 UTC, MaurizioPellegrinet approved these changes
Conferma alle modifiche: OK

2024-11-11 08:50 UTC, SirAionTech requested changes
Grazie della PR!
Ho fatto revisione del codice e provato la migrazione, che però è da modificare perché la versione `14.0.1.4.3` è stata assegnata nel frattempo; quindi
/ocabot rebase

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/models/account.py
> +            or self.move_type.startswith("in_")
Penso sia meglio usare `is_purchase_document` e `is_sale_document`, che ne dici?

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/models/account.py
> +                fiscal_position_id = self.env["account.fiscal.position"].browse(
Potrebbe essere utile
```suggestion
                fiscal_position = self.env["account.fiscal.position"].browse(
```
Per distinguere che le variabili con `_id` sono degli interi, cosa ne pensi?

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/models/account.py
> +                        elif val.get("move_type").startswith("in_"):
Analogamente a quanto suggerito sopra, si potrebbero usare `get_sale_types` e `get_purchase_types`, che ne dici?

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/views/account.xml
> +                        <field name="intrastat_sale" />
Il campo rimosso era citato nella documentazione, potresti aggiornarla?

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/tests/test_intrastat.py
> +    def test_invoice_fiscal_position(self):
Questo ora è diventato il test per verificare che funzioni `intrastat_sale`, penso che andrebbe modificata la firma; faresti il test analogo per verificare `intrastat_purchase`?

2024-11-11 08:50 UTC, SirAionTech commented on l10n_it_intrastat/migrations/14.0.1.4.3/pre-migrate.py
> +        if not openupgrade.column_exists(env.cr, table, column):
`column_exists` esiste solo per retrocompatibilità, si potrebbe usare invece il metodo omonimo di `openupgrade_tools`?
Vedi https://github.com/OCA/openupgradelib/blob/8d04b103b70d6927f805b94ef26ecf53b26e51ed/openupgradelib/openupgrade.py#L411

2024-11-22 15:23 UTC, sergiocorato commented on l10n_it_intrastat/models/account.py
> +            or self.move_type.startswith("in_")
Giusto

2024-11-22 15:24 UTC, sergiocorato commented on l10n_it_intrastat/models/account.py
> +                fiscal_position_id = self.env["account.fiscal.position"].browse(
Vero

2024-11-22 15:26 UTC, sergiocorato commented on l10n_it_intrastat/models/account.py
> +                        elif val.get("move_type").startswith("in_"):
Meglio

2024-11-22 17:04 UTC, sergiocorato commented on l10n_it_intrastat/tests/test_intrastat.py
> +    def test_invoice_fiscal_position(self):
Fatto

2024-11-22 17:10 UTC, sergiocorato commented on l10n_it_intrastat/migrations/14.0.1.4.3/pre-migrate.py
> +        if not openupgrade.column_exists(env.cr, table, column):
Ok grazie

2024-11-22 17:15 UTC, sergiocorato commented on l10n_it_intrastat/views/account.xml
> +                        <field name="intrastat_sale" />
Fatto

2024-12-23 16:21 UTC, SirAionTech approved these changes
Fatta revisione del codice, provata la migrazione e il funzionamento: per me è ok.

Puoi correggere il messaggio del commit? Ti è scappata una **y** all'inizio:
![image](https://github.com/user-attachments/assets/122aa711-82e9-4315-9f10-fdc4eca53856)

Potresti anche seguire il formato `[TAG] module: title` indicato nelle linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message?
> [FIX] website: remove unused alert div

Così la storia dei commit risulta più omogenea

2025-01-17 17:55 UTC, sergiocorato commented
/ocabot merge nobump

2025-01-17 18:28 UTC, merged