[FIX] l10n_it_asset_management: Company and page number out of page
OCA/l10n-italy pull request #4265
Opened 2024-07-11 12:41 UTC by PicchiSeba

Backport of c8179fe9f15e9f5c0a2ef9072da9af41aef7fc7d from https://github.com/OCA/l10n-italy/pull/3776

2024-08-28 07:19 UTC, matteoopenf approved these changes

2024-08-30 09:33 UTC, MaurizioConte commented
Dai test fatti su RUNBOAT l'indirizzo viene esposto mentre il numero di paga è esposto ma su 3 righe ovvero

2024
/
1

2024
/
2

e così via.

Per l'indirizzo se lo si può far stampare sotto la ragione sociale dell'azienda  ?

2024-08-30 14:21 UTC, PicchiSeba commented
@MaurizioConte 
Corrette entrambe le cose

2024-09-02 08:19 UTC, MaurizioPellegrinet approved these changes
Test funzionale: OK

2024-09-02 15:21 UTC, MaurizioConte commented
TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2

2024-09-02 15:42 UTC, SirAionTech commented
> TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2

Grazie, potresti mica aggiungere una revisione?
Se non sai come fare trovi delle istruzioni in https://www.odoo-italia.org/documentazione/14.0/sviluppo/review.html#revisione-funzionale.

2024-09-02 15:51 UTC, MaurizioConte commented
> > TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2
> 
> Grazie, potresti mica aggiungere una revisione? Se non sai come fare trovi delle istruzioni in https://www.odoo-italia.org/documentazione/14.0/sviluppo/review.html#revisione-funzionale.

@SimoRubi Ma la revisione per KO si può mettere ? C'è un errore per questo non ho messo la revisione

2024-09-02 15:59 UTC, francesco-ooops commented
@MaurizioConte sì, è descritto in questa sezione: 

![image](https://github.com/user-attachments/assets/75358a05-7b5c-4985-9e81-7fb29ca079ba)

(se devi rispondere a Simone, usa @SirAionTech ;) )

2024-09-02 16:01 UTC, MaurizioConte reviewed
TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2

2024-09-02 16:03 UTC, SirAionTech commented
> TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2

Già meglio grazie, ma forse hai lasciato **Comment** invece di selezionare **Request changes**?

2024-09-02 16:09 UTC, MaurizioConte requested changes
TEST KO: il numero della prima pagina è errato viene stampato 2024 / 2

2024-10-24 13:25 UTC, PicchiSeba commented
@MaurizioConte non riesco a riprodurre la segnalazione, riusciresti ad indicarmi che dati ha inserito?

2024-11-15 13:46 UTC, tafaRU commented
@MaurizioConte potresti effettuare di nuovo il test?

2025-01-17 14:33 UTC, tafaRU commented
@MaurizioPellegrinet potresti fare review?

2025-01-18 14:20 UTC, sergiocorato approved these changes

2025-01-18 14:21 UTC, sergiocorato commented
/ocabot merge patch

2025-01-18 14:52 UTC, merged