[FIX] 1l10n_it_intrastat_statement: Fixed grouping of intrastat lines of reversed entries
OCA/l10n-italy pull request #4361
Opened 2024-09-06 15:17 UTC by LorenzoC0

Risolve #4360

2024-09-09 07:53 UTC, MaurizioPellegrinet approved these changes
Test funzionale: OK

2024-10-18 08:19 UTC, sergiocorato commented
@LorenzoC0 Puoi cortesemente aggiungere sui test come descritto nella issue?

2024-11-07 13:47 UTC, SirAionTech requested changes
Grazie della PR!
Puoi correggere il titolo del commit? C'è un 1 di troppo:
> [FIX] **1**l10n_it_intrastat_statement: Fixed grouping of intrastat lines if a reversed entry is not in the same period of the line

Potresti anche aggiungere un test? Così si evitano regressioni

2024-11-07 13:47 UTC, SirAionTech commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                            or line.invoice_id.reversed_entry_id.date > period_date_stop
Questi stessi campi vengono usati qualche riga sopra per filtrare il campo `invoice_date`, come mai qui invece viene usato `date`?

2024-11-07 13:47 UTC, SirAionTech commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                        self.refund_line(line, to_refund_model)
Quindi la riga `line` viene segnata come rimborso solo quando la sua fattura ha un rimborso con data inclusa nel periodo, giusto?
Potresti modificarlo come suggerito qui sotto?

```suggestion
                    refund_date = line.invoice_id.reversed_entry_id.date
                    if refund_date and period_date_start <= refund_date <= period_date_stop:
                        self.refund_line(line, to_refund_model)
```
Credo sia un po' più leggibile.

Inoltre, non serve anche che il rimborso sia `intrastat`?
Forse si potrebbe cercare se il rimborso è tra le fatture delle righe che sono già state incluse nella dichiarazione qualche riga sopra, cosa ne dici? Così non serve rifare questi controlli sulle date.

2024-11-07 13:47 UTC, SirAionTech commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +        period_date_stop = fields.Date.to_date(period_date_stop)
`period_date_start/stop` sono già delle `date` perché vengono da https://github.com/OCA/l10n-italy/blob/b59b6770e0520bbd956d81b22fd1c3a7800ed0fe/l10n_it_intrastat_statement/models/intrastat_statement.py#L447-L463
come mai serve questa conversione?

2025-04-22 15:11 UTC, eLBati commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +        period_date_stop = fields.Date.to_date(period_date_stop)
Probabilmente non serve. Rimuovo

2025-04-22 15:13 UTC, eLBati commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                            or line.invoice_id.reversed_entry_id.date > period_date_stop
> Questi stessi campi vengono usati qualche riga sopra per filtrare il campo invoice_date

Dove?

2025-04-22 15:17 UTC, eLBati commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                        self.refund_line(line, to_refund_model)
> Credo sia un po' più leggibile

Modifico

> Inoltre, non serve anche che il rimborso sia intrastat?

se `line.invoice_id` lo è, come può `line.invoice_id.reversed_entry_id` non esserlo?

2025-04-22 15:20 UTC, eLBati commented
Conflitti risolti e correzioni applicate

2025-04-25 08:35 UTC, monen17 requested changes
Grazie della PR!
Sia pre-commit che i test falliscono:
![image](https://github.com/user-attachments/assets/394e0b6e-f1a1-492e-b831-d141adfd2d2a)

puoi correggere?

Inoltre, mancano ancora da correggere le segnalazioni fatte in https://github.com/OCA/l10n-italy/pull/4361#pullrequestreview-2420982561:

> Puoi correggere il titolo del commit? C'è un 1 di troppo:
> 
> > [FIX] **1**l10n_it_intrastat_statement: Fixed grouping of intrastat lines if a reversed entry is not in the same period of the line
> 
> Potresti anche aggiungere un test? Così si evitano regressioni

Nota poi che i messaggi dei commit dovrebbero seguire https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message e questo:
![image](https://github.com/user-attachments/assets/538b24cb-328f-4eaa-9645-560754e1b73f)
(https://github.com/OCA/l10n-italy/pull/4361/commits/e3b08094658d2d715aa68aff2067b7a5f09d90e5) non segue
> please check if the commit message is cut with ellipsis

2025-04-25 08:35 UTC, monen17 commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +
Si può togliere questa nuova riga vuota?

2025-04-25 08:35 UTC, monen17 commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                            or line.invoice_id.reversed_entry_id.date > period_date_stop
In https://github.com/OCA/l10n-italy/blob/0a48656509df896ec599a7a9885a612536110cbd/l10n_it_intrastat_statement/models/intrastat_statement.py#L768-L769

2025-04-25 08:35 UTC, monen17 commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +                        self.refund_line(line, to_refund_model)
> > Inoltre, non serve anche che il rimborso sia intrastat?
> 
> se `line.invoice_id` lo è, come può `line.invoice_id.reversed_entry_id` non esserlo?

È un semplice flag sulla move, potrebbe esserci nella fattura ma non nel rimborso

2025-04-25 08:35 UTC, monen17 commented on l10n_it_intrastat_statement/models/intrastat_statement.py
> +        period_date_stop = fields.Date.to_date(period_date_stop)
:+1:

2025-12-28 12:45 UTC, closed without merging