[14.0][MIG] Migration to 14.0 l10n_it_fatturapa_out_fd
OCA/l10n-italy pull request #4386
Opened 2024-09-27 09:12 UTC by sergiocorato

2024-09-30 08:56 UTC, sergiocorato commented
@TheMule71 pronto per la review!

2024-09-30 09:02 UTC, sergiocorato commented
Ho notato che il numero della fattura, anche se assegnato, viene impostato in automatico ad un numero diverso (con la sequenza 'per mese' di default), cosa che non si nota nei vari test dove non si fa un controllo completo dell'xml.
Questa assegnazione in pratica è ignorata: https://github.com/OCA/l10n-italy/blob/dabbabd7e94647ccb0d724d8f83d62f78e9a1e9d/l10n_it_fatturapa_out/tests/test_fatturapa_out_noteline.py#L212

2024-10-21 15:06 UTC, SirAionTech requested changes
Grazie della PR!

2024-10-21 15:06 UTC, SirAionTech commented on l10n_it_fatturapa_out_fd/tests/data/IT06363391001_00001.xml
> +>
I cambiamenti fatti in automatico da `pre-commit` andrebbero lasciati in un commit a sé precedente la migrazione, come indicato in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0:
```
$ git clone https://github.com/OCA/$REPO -b 14.0
$ git checkout -b 14.0-mig-$MODULE origin/14.0
$ git format-patch --keep-subject --stdout origin/14.0..origin/13.0 -- $MODULE | git am -3 --keep
$ pre-commit run -a  # to run black, isort and prettier (ignore pylint errors at this stage)
$ git add -A
$ git commit -m "[IMP] $MODULE: black, isort, prettier"  --no-verify  # it is important to do all formatting in one commit the first time
```

 riesci a correggere?

2024-10-21 15:06 UTC, SirAionTech commented on l10n_it_fatturapa_out_fd/README.rst
Puoi schiacciare i commit fatti dai bot come indicato in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?
A occhio della storia di `12.0` dovrebbe rimanere solo il commit **ADD** e un commit di traduzione, invece dei 5 che ci sono adesso 
![image](https://github.com/user-attachments/assets/e6458815-1e3d-48bc-8985-aa6ceedc0826)

2024-10-21 15:06 UTC, SirAionTech commented on l10n_it_fatturapa_out_fd/wizards/wizard_export_fatturapa.py
> +        template_values.update({"get_importo": self.get_importo})
Così facendo sovrascrivi la funzione `get_importo`che c'è già in `template_values`: https://github.com/OCA/l10n-italy/blob/919ac3fe12e4288422dfd9a1a3939929fcf93c0f/l10n_it_fatturapa_out/wizard/efattura.py#L234 quindi va a farsi benedire :angel: qualsiasi modifica che altri moduli potrebbero voler fare a questa funzione, così come eventuali modifiche della funzione originale stessa.
Potresti invece mantenere l'ereditarietà? Ad esempio puoi vedere come è stato fatto per `get_importo_totale`: https://github.com/OCA/l10n-italy/blob/919ac3fe12e4288422dfd9a1a3939929fcf93c0f/l10n_it_fatturapa_out/wizard/efattura.py#L186-L189

2024-10-21 15:06 UTC, SirAionTech commented on l10n_it_fatturapa_out_fd/tests/test_xml_generation.py
> +        invoice_form.name = "INV/2020/01/0001"
> Ho notato che il numero della fattura, anche se assegnato, viene impostato in automatico ad un numero diverso (con la sequenza 'per mese' di default), cosa che non si nota nei vari test dove non si fa un controllo completo dell'xml. Questa assegnazione in pratica è ignorata:
> 
> https://github.com/OCA/l10n-italy/blob/dabbabd7e94647ccb0d724d8f83d62f78e9a1e9d/l10n_it_fatturapa_out/tests/test_fatturapa_out_noteline.py#L212

Se come scrivi viene ignorata, si può rimuovere?

2024-10-24 13:31 UTC, sergiocorato commented on l10n_it_fatturapa_out_fd/README.rst
Fatto

2024-10-24 15:04 UTC, sergiocorato commented on l10n_it_fatturapa_out_fd/tests/data/IT06363391001_00001.xml
> +>
dovrei aver fatto

2024-10-24 16:22 UTC, sergiocorato commented on l10n_it_fatturapa_out_fd/tests/test_xml_generation.py
> +        invoice_form.name = "INV/2020/01/0001"
fatto

2024-10-24 16:25 UTC, sergiocorato commented on l10n_it_fatturapa_out_fd/wizards/wizard_export_fatturapa.py
> +        template_values.update({"get_importo": self.get_importo})
dovrei aver fatto

2024-10-24 16:25 UTC, sergiocorato commented
@SirAionTech dovrei aver fatto tutto

2024-11-21 11:58 UTC, SirAionTech commented
/ocabot rebase

2024-11-21 13:08 UTC, SirAionTech commented
/ocabot migration l10n_it_fatturapa_out_fd

2024-11-21 16:29 UTC, SirAionTech reviewed
Grazie, a livello di codice per me è ok.

Potresti però modificare i nuovi commit?
- typo + tipo di commit
  ```diff
  - [IMP] l10n_it_fatturapa_out add wrappaer to get_importo
  + [REF] l10n_it_fatturapa_out: add wrapper to get_importo
  ```

- il nome del modulo deve essere incluso nel titolo del commit (vedi https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message)
  ```diff
  - [IMP] inherit from wizard
  + [IMP] l10n_it_fatturapa_out_fd: inherit from wizard
  ```

Oppure, potrebbe avrebbe senso mettere prima di tutto il commit di refactoring di `l10n_it_fatturapa_out`, e poi i commit della migrazione e tutte le modifiche necessarie dentro il commit di **[MIG]**; che ne dici?

2025-04-27 12:37 UTC, closed without merging