[18.0] [ADD] l10n_it_edi_extension
OCA/l10n-italy pull request #4411
Opened 2024-10-18 08:29 UTC by Borruso

2025-02-17 13:41 UTC, eLBati commented
Non mi è chiaro: quali sono le funzionalità di questo modulo? Non si sovrappongono a quelle di `l10n_it_edi`?

2025-02-17 13:48 UTC, francesco-ooops commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +**Italiano**
Dato che è stata fatta un'analisi approfondita, per qualsiasi nuovo modulo per la 18 ne approfitterei per inserire una documentazione più approfondita, non necessariamente step-by-step ma sicuramente più ampia di così

2025-02-18 11:15 UTC, eLBati commented on l10n_it_edi_extension/models/ir_attachment.py
> +    def remove_xades_sign(self, xml_string):
Non ci sono metodi di `l10n_it_edi` per fare questo? A `l10n_it_edi` non serve farlo?

2025-02-18 11:29 UTC, eLBati commented on l10n_it_edi_extension/views/account_move_view.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Tutti questi dati li vogliamo anche nel form della fattura? Non è sufficiente leggerli eventualmente dall'XML?

2025-02-18 11:35 UTC, eLBati commented on l10n_it_edi_extension/views/l10n_it_view.xml
> +                            groups="account.group_account_invoice"
qua l'obiettivo è cambiare il gruppo di `l10n_it_edi_attachment_id`? In tal caso non è meglio farlo direttamente con `attribute` invece che metterlo invisibile e riaggiungerlo dopo?

2025-02-18 11:42 UTC, eLBati commented on l10n_it_edi_extension/wizards/edi_import_file_wizard.py
> +    _name = "edi.import.file.wizard"
Se è per l'importazione di uno ZIP con tanti XML, lo chiamerei di conseguenza

2025-02-19 11:35 UTC, Borruso commented on l10n_it_edi_extension/views/l10n_it_view.xml
> +                            groups="account.group_account_invoice"
in realtà non è solo per il gruppo a è per aggiungere il pulsante per la preview

2025-02-19 11:36 UTC, Borruso commented on l10n_it_edi_extension/views/account_move_view.xml
> +<?xml version="1.0" encoding="utf-8" ?>
sono gli stessi campi che abbiamo in v16 quando estrapoliamo le info dall'xml

2025-02-19 11:37 UTC, Borruso commented on l10n_it_edi_extension/wizards/edi_import_file_wizard.py
> +    _name = "edi.import.file.wizard"
suggerimenti?

2025-02-19 11:38 UTC, Borruso commented on l10n_it_edi_extension/models/ir_attachment.py
> +    def remove_xades_sign(self, xml_string):
controllo ma forse non l'avevo trovato

2025-02-19 11:39 UTC, Borruso commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +**Italiano**
sicuramente piano piano andremo ad aggiornare più che la descrizione la configurazione/funzionamento (CONFIG.md/USAGE.md)

2025-02-19 13:48 UTC, francesco-ooops commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +**Italiano**
Benissimo, sarebbe una cosa buona da fare prima del merge (magari con l'aiuto di un funzionale), altrimenti resta sempre una di quelle cose da fare dopo 👍

2025-02-19 16:42 UTC, eLBati commented on l10n_it_edi_extension/wizards/edi_import_file_wizard.py
> +    _name = "edi.import.file.wizard"
`edi.import.zip.file.wizard`

2025-02-19 16:43 UTC, eLBati commented on l10n_it_edi_extension/views/account_move_view.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Lo so :-)

2025-03-21 09:20 UTC, eLBati commented
I campi introdotti da questo modulo hanno bisogno di script di upgrade da v16, per recuperare dati che erano in campi gestiti da `l10n_it_fatturapa*`.
Abbiamo però il problema che, durante l'upgrade alla 18, `l10n_it_edi` non è installabile per via dell'`excludes` di `l10n_it_fatturapa`.
Questo vincolo scrive nella tabella `ir_module_module_exclusion`.
Bisognerebbe quindi provare a rimuovere il vincolo in `ir_module_module_exclusion` in uno script di `_pre_init_hook` di `l10n_it_edi_extension`.

Poi possibilmente, una volta che tutti i dati sono stati portati, disinstallare `l10n_it_fatturapa` (teoricamente in `_post_init_hook`)

2025-04-11 11:12 UTC, monen17 requested changes
Grazie della PR!
Oltre a quanto scritto sotto, concordo con le altre revisioni che vada quantomeno esteso il README.

2025-04-11 11:12 UTC, monen17 commented on l10n_it_edi_extension/__init__.py
> +    "l10n_it_vat_payability",
Un gran lavoro! :clap:
Purtroppo non posso provarlo perché OpenUpgrade ancora non ha migrato gran che alla `18.0`.

Se questo però è il modulo che dovrebbe coprire le funzionalità di questi moduli, mi aspetto che ci siano dei test.
Non dico tutti quelli dei moduli elencati, che potrebbero facilmente essere un centinaio, però abbiamo fatto un grande lavoro sui test nella `16.0` e non mi va che vada tutto perso.

2025-04-11 11:21 UTC, Borruso commented on l10n_it_edi_extension/__init__.py
> +    "l10n_it_vat_payability",
per i test in realtà fa tutto `l10n_it_edi` posso fare solo test per preview dell'xml e la popolazione delle tabella di dettaglio della fattura elettronica

2025-04-11 12:21 UTC, monen17 commented on l10n_it_edi_extension/__init__.py
> +    "l10n_it_vat_payability",
Ho preso il primo test di uno dei moduli elencati: https://github.com/OCA/l10n-italy/blob/56621cb667a6d9ed581a55bd452508b28d49e3da/l10n_it_fiscalcode/tests/test_fiscalcode.py#L17-L34

`l10n_it_edi` come fa il calcolo del codice fiscale di un partner?

Per sapere se tutte le funzionalità dei nostri vecchi moduli ci sono in `l10n_it_edi` c'è un modo semplice: eseguire i test automatici.

2025-04-11 14:25 UTC, monen17 commented
Ho proposto https://github.com/Borruso/l10n-italy/pull/23 per creare se mancante durante l'import.

2025-05-02 16:25 UTC, monen17 commented
Ho proposto https://github.com/Borruso/l10n-italy/pull/25 per creare tutte le fatture quando viene importata una fattura elettronica contenente più fatture.

2025-05-16 09:47 UTC, andreampiovesana commented on l10n_it_edi_extension/README.rst
> +   installato e configurato (piano dei conti, tasse, diari contabili,
meglio giornali contabili (non diari)

2025-05-20 13:07 UTC, eLBati requested changes

2025-05-20 13:07 UTC, eLBati commented on l10n_it_edi_extension/wizards/compute_fc.py
> +    _name = "wizard.compute.fc"
Questo non è documentato nel `readme` mi pare

2025-05-20 13:07 UTC, eLBati commented on l10n_it_edi_extension/wizards/l10n_it_edi_import_file_wizard.py
> +    _name = "l10n_it_edi.import_file_wizard"
Questo non è documentato nel `readme` mi pare

2025-05-23 12:25 UTC, eLBati commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +                <Causale t-out="c" />
Anche questo è da documentare nel README

2025-05-23 14:30 UTC, matteonext commented
Ho testato la preview dell'xml e funziona correttamente.

2025-05-25 14:23 UTC, monen17 commented
Ho proposto https://github.com/Borruso/l10n-italy/pull/27 per importare una fattura elettronica senza righe, con una riga per ogni aliquota, oppure con tutte le righe (default).

2025-05-25 15:23 UTC, monen17 commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +                <Causale t-out="c" />
Aggiunto in https://github.com/Borruso/l10n-italy/pull/28.

2025-05-30 06:56 UTC, odooNextev commented on l10n_it_edi_extension/wizards/compute_fc.py
> +    _name = "wizard.compute.fc"
https://github.com/Borruso/l10n-italy/pull/29

2025-05-30 06:56 UTC, odooNextev commented on l10n_it_edi_extension/wizards/l10n_it_edi_import_file_wizard.py
> +    _name = "l10n_it_edi.import_file_wizard"
https://github.com/Borruso/l10n-italy/pull/29

2025-06-09 10:09 UTC, odooNextev commented
@Borruso non capisco perchè falliscono i test: ho provato in locale e non riscontro l'errore della divisione per 0 come qui https://github.com/OCA/l10n-italy/actions/runs/15343445807/job/43174440067?pr=4411#step:8:321
Ne ottengo altri 2 nel file `test_import_zip` che qui non ci sono, ma contabilmente funziona:

- uno per validazione errata di questo CF: MRORSS90E25B111T
- uno perchè `skipping IT05979361218_003.xml.p7m, not an XML/P7M file` e quindi la lunghezza di in_moves non è più 36, ma 35

2025-06-09 10:42 UTC, micheledic commented
> @Borruso non capisco perchè falliscono i test: ho provato in locale e non riscontro l'errore della divisione per 0 come qui https://github.com/OCA/l10n-italy/actions/runs/15343445807/job/43174440067?pr=4411#step:8:321 Ne ottengo altri 2 nel file `test_import_zip` che qui non ci sono, ma contabilmente funziona:
> 
> * uno per validazione errata di questo CF: MRORSS90E25B111T
> * uno perchè `skipping IT05979361218_003.xml.p7m, not an XML/P7M file` e quindi la lunghezza di in_moves non è più 36, ma 35

Probabilmente in locale non hai il core di odoo pullato.
Il problema esce perchè prima c'era una diversa gestione degli sconti maggiorazione che ho introdotto con https://github.com/odoo/odoo/commit/d2b1b140b95f6c60d3a032745ee6880688fa2748 .
Non è questa mia PR a rompere, ma il file presente nello zip di test 

> subdir1/IT01234567890_FPR04.xml

che ha prezzo e sconto a 0 .
```
 <Quantita>1.00</Quantita>
        <UnitaMisura>Nr</UnitaMisura>
        <PrezzoUnitario>0.00</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>0.00</Percentuale>
          <Importo>0.00</Importo>
        </ScontoMaggiorazione>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
```
Imho non ha senso avere lo sconto a 0 e su una riga a 0 
@Borruso @SirAionTech

2025-06-09 12:19 UTC, odooNextev commented
Grazie @micheledic per la spiegazione, effettivamente non avevo il core aggiornato

2025-06-20 08:22 UTC, Borruso commented
@eLBati i test vanno i errore perché prezzo unitario è zero e Odoo non fa il check prima di dividere per prezzo unitario
```
File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1361, in _l10n_it_edi_import_line
    discount = 100 - (100 * current_unit_price) / move_line.price_unit
```

Ho trovato la fattura nei test dello zip IT01234567890_FPR04.xml (non so se è unica)
![FPR04](https://github.com/user-attachments/assets/023986b3-32f1-4f7f-a67f-9fa1fb237264)

2025-07-01 12:47 UTC, tafaRU commented on l10n_it_edi_extension/__init__.py
> +def rename_fields(env, table, field_updates, condition=None):
come mai non usi dappertutto [rename_fields](https://github.com/OCA/openupgradelib/blob/d2d76e772760365988a53af11b65eab648d991d2/openupgradelib/openupgrade.py#L675) di `openupgralib`?

2025-07-01 12:50 UTC, tafaRU commented on l10n_it_edi_extension/__init__.py
> +def rename_fields(env, table, field_updates, condition=None):
@Borruso mi sono accorto che anche [qui](https://github.com/OCA/l10n-italy/blob/2de18b1a726fb4887eda79d8d5fae1e10e50807b/l10n_it_account/migrations/18.0.1.0.0/post-migration.py#L12) non hai usato il metodo messo a disposizione da `openupgradelib`. Attendo tua risposta prima di aprire evntualmente una issue grazie.

2025-07-04 13:07 UTC, eLBati commented
@Borruso @micheledic 

Il file `IT01234567890_FPR04.xml` è valido per SDI 

![image](https://github.com/user-attachments/assets/9109a021-828c-4215-8ce4-fa4461007eee)

quindi odoo lo dovrebbe importare senza errori, ma:

```
2025-07-04 13:05:37,094 1 ERROR test_import_e_bill odoo.addons.account.models.account_move: Errore durante l'importazione dell'allegato 'IT01234567890_FPR04.xml' come fattura (decodificatore=_l10n_it_edi_import_invoice) 
Traceback (most recent call last):
  File "/opt/odoo/addons/account/models/account_move.py", line 4187, in _extend_with_attachments
    success = decoder(invoice, file_data, new)
  File "/opt/odoo/addons/l10n_it_edi_ndd/models/account_move.py", line 91, in _l10n_it_edi_import_invoice
    res = super()._l10n_it_edi_import_invoice(invoice=invoice, data=data, is_new=is_new)
  File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1205, in _l10n_it_edi_import_invoice
    message_to_log += self._l10n_it_edi_import_line(element, move_line, extra_info)
  File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1361, in _l10n_it_edi_import_line
    discount = 100 - (100 * current_unit_price) / move_line.price_unit
ZeroDivisionError: float division by zero
```

Quindi bisogna segnalarlo a odoo, se non già fatto

2025-07-04 13:13 UTC, Borruso commented
> @Borruso @micheledic
> 
> Il file `IT01234567890_FPR04.xml` è valido per SDI
> 
> ![image](https://private-user-images.githubusercontent.com/1033131/462497145-9109a021-828c-4215-8ce4-fa4461007eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE2MzUwNjAsIm5iZiI6MTc1MTYzNDc2MCwicGF0aCI6Ii8xMDMzMTMxLzQ2MjQ5NzE0NS05MTA5YTAyMS04MjhjLTQyMTUtOGNlNC1mYTQ0NjEwMDdlZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDRUMTMxMjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQ5MWQ3NDY0MTkxODQxNjY4OTVhZmM4ZDAxOTczMDNmY2E0MTZiOWMzM2QzMzBmODVkMGNmMDdhMmUzMDI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xbV485jMFK5hh767IysRRyOnKgzw-lyvZ0ftnQbD4Gc)
> 
> quindi odoo lo dovrebbe importare senza errori, ma:
> 
> ```
> 2025-07-04 13:05:37,094 1 ERROR test_import_e_bill odoo.addons.account.models.account_move: Errore durante l'importazione dell'allegato 'IT01234567890_FPR04.xml' come fattura (decodificatore=_l10n_it_edi_import_invoice) 
> Traceback (most recent call last):
>   File "/opt/odoo/addons/account/models/account_move.py", line 4187, in _extend_with_attachments
>     success = decoder(invoice, file_data, new)
>   File "/opt/odoo/addons/l10n_it_edi_ndd/models/account_move.py", line 91, in _l10n_it_edi_import_invoice
>     res = super()._l10n_it_edi_import_invoice(invoice=invoice, data=data, is_new=is_new)
>   File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1205, in _l10n_it_edi_import_invoice
>     message_to_log += self._l10n_it_edi_import_line(element, move_line, extra_info)
>   File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1361, in _l10n_it_edi_import_line
>     discount = 100 - (100 * current_unit_price) / move_line.price_unit
> ZeroDivisionError: float division by zero
> ```
> 
> Quindi bisogna segnalarlo a odoo, se non già fatto

yes

2025-07-07 09:19 UTC, micheledic commented
> > @Borruso @micheledic
> > Il file `IT01234567890_FPR04.xml` è valido per SDI
> > ![image](https://private-user-images.githubusercontent.com/1033131/462497145-9109a021-828c-4215-8ce4-fa4461007eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE2MzUwNjAsIm5iZiI6MTc1MTYzNDc2MCwicGF0aCI6Ii8xMDMzMTMxLzQ2MjQ5NzE0NS05MTA5YTAyMS04MjhjLTQyMTUtOGNlNC1mYTQ0NjEwMDdlZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDRUMTMxMjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQ5MWQ3NDY0MTkxODQxNjY4OTVhZmM4ZDAxOTczMDNmY2E0MTZiOWMzM2QzMzBmODVkMGNmMDdhMmUzMDI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xbV485jMFK5hh767IysRRyOnKgzw-lyvZ0ftnQbD4Gc)
> > quindi odoo lo dovrebbe importare senza errori, ma:
> > ```
> > 2025-07-04 13:05:37,094 1 ERROR test_import_e_bill odoo.addons.account.models.account_move: Errore durante l'importazione dell'allegato 'IT01234567890_FPR04.xml' come fattura (decodificatore=_l10n_it_edi_import_invoice) 
> > Traceback (most recent call last):
> >   File "/opt/odoo/addons/account/models/account_move.py", line 4187, in _extend_with_attachments
> >     success = decoder(invoice, file_data, new)
> >   File "/opt/odoo/addons/l10n_it_edi_ndd/models/account_move.py", line 91, in _l10n_it_edi_import_invoice
> >     res = super()._l10n_it_edi_import_invoice(invoice=invoice, data=data, is_new=is_new)
> >   File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1205, in _l10n_it_edi_import_invoice
> >     message_to_log += self._l10n_it_edi_import_line(element, move_line, extra_info)
> >   File "/opt/odoo/addons/l10n_it_edi/models/account_move.py", line 1361, in _l10n_it_edi_import_line
> >     discount = 100 - (100 * current_unit_price) / move_line.price_unit
> > ZeroDivisionError: float division by zero
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Quindi bisogna segnalarlo a odoo, se non già fatto
> 
> yes

https://github.com/odoo/odoo/pull/217670 attendiamo merge

2025-07-11 08:55 UTC, eLBati commented on l10n_it_edi_extension/__manifest__.py
> +    "development_status": "Production/Stable",
Meglio Beta

2025-07-11 14:37 UTC, matteonext commented
Ho testato la creazione automatica dei partner all'import della fattura, funziona.

2025-07-11 18:39 UTC, monen17 requested changes
Grazie delle modifiche!
Come detto stamattina in chiamata non ho guardato cosa c'è/manca rispetto a `16.0` tranne che per pochi punti, ho solo guardato come funziona cosa c'è nel README e se manca qualcosa.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +  Questo pulsante permette di visualizzare un'anteprima del file XML della fattura elettronica prima dell'invio effettivo.
Come si fa a vedere l'anteprima del file prima dell'invio?
Ho fatto qualche prova e il pulsante per vedere l'anteprima è visibile solo quando la fattura elettronica viene creata, e viene creato all'invio.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Aggiunta della possibilità di visualizzare l'anteprima del file XML anche dal portale.
Come si fa a vedere l'anteprima nel portale? Non ho visto nulla nel codice o nelle viste che lo permetta.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +2. Aggiunge campi nell'export delle fatture XML:
Non credo si capisca molto quello che effettivamente vorrebbe dire, forse qualcosa del genere sarebbe più chiaro?
```suggestion
2. Valorizza i seguenti campi/nodi della fattura elettronica esportata:
```
Sarebbe anche utile scrivere (qui o in CONFIGURE) dove sono i campi in Odoo da valorizzare per avere questi nodi nel XML: alcuni vanno messi nella fattura, altri nella company, altri nelle righe.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<RiferimentoAmministrazione>` (sia sulla riga che nei dati generali): identificativo utilizzato per uso amministrativo/gestionale interno. È un campo libero che può essere utilizzato per inseri
Come si fa ad aggiungere nelle righe? Non trovo il campo nelle viste.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +                </CAP>
Puoi mettere le direttive `t-*` direttamente dentro il nodo? Altrimenti vengono aggiunti spazi prima/dopo il valore: 
```xml
<StabileOrganizzazione>
  <Indirizzo> str </Indirizzo>
  <CAP> 12345 </CAP>
  <Comune>city</Comune>
  <Provincia>RM</Provincia>
  <Nazione>IT</Nazione>
</StabileOrganizzazione>
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +            <Art73 t-if="company.l10n_edi_it_art73">SI</Art73>
Questo è un campo del documento, quindi della fattura, perché è legato invece alla `company`?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - `<TerzoIntermediarioOSoggettoEmittente>`
A quanto vedo questi vengono creati sempre se mancano, quindi la loro creazione non dipende da nessuna opzione.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.l10n_it_edi_intermediary_id = intermediary.id
Tutto questo è duplicato (a parte le stringhe e i nomi delle variabili), puoi estrarlo in un metodo? Si potrebbe chiamare `..search_create..`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                ):
`_l10n_it_edi_search_partner` già farebbe la creazione del partner quando non lo trova, quindi perché:
1. Aggiungere nel contesto `skip_create` così `search_partner` non creerà il partner
2. chiamare `search_partner` che non creerà il partner
3. se il partner non è stato trovato, chiamare `create_partner`

?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                if tax_representative := self._l10n_it_edi_create_partner(
Anche a me piace usare `:=`, ma `_l10n_it_edi_create_partner` creerà sempre un partner, quindi a cosa serve l'`if`?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                )
C'è solo un nodo `FatturaPrincipale`, perché quindi un `for` loop? Tra l'altro se ci fossero più nodi i valori dei campi assegnati verrebbero sovrascritti.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                self.env["l10n_it_edi.summary_data"].create(
Possiamo usare invece la creazione in batch? È fatta apposta per ottimizzare queste situazioni.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                self.env["l10n_it_edi.activity_progress"].create(
Possiamo usare invece la creazione in batch? È fatta apposta per ottimizzare queste situazioni.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    (self.env._(label), self._compose_info_message(body_tree, xpath))
```suggestion
            (".//DatiGenerali/DatiTrasporto", self.env._("Transport informations from XML file:")),
            (".//DatiVeicoli", self.env._("Vehicle informations from XML file:")),
        ]:
            if body_tree.xpath(xpath):
                message = Markup("<br/>").join(
                    label, self._compose_info_message(body_tree, xpath))
```
Altrimenti queste stringhe non vengono esportate come da tradurre perché `_` non è abbastanza furbo per capire cosa c'è dentro `label`

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.article_code"].create(
Possiamo usare invece la creazione in batch? È fatta apposta per ottimizzare queste situazioni.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.discount_rise_price"].create(
Possiamo usare invece la creazione in batch? È fatta apposta per ottimizzare queste situazioni.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.line_other_data"].create(
Possiamo usare invece la creazione in batch? È fatta apposta per ottimizzare queste situazioni.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    company=company,
```suggestion
                    company=company.name,
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - Miglioramento della gestione dello sconto o maggiorazione, nodo `<ScontoMaggiorazione>`
Che tipo di miglioramento? Vedo che crea dei record

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Gestione avanzata dei `<DatiRiepilogo>` con l'importazione di:
```suggestion
   - Importazione dei `<DatiRiepilogo>`:
```
perché mi pare che crei solo dei record all'importazione.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Gestione avanzata dei `<DatiGeneraliDocumento>` con l'importazione di:
```suggestion
   - Importazione dei `<DatiGeneraliDocumento>`:
```
perché mi pare che crei solo dei record all'importazione.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/wizards/compute_fc.py
> +        "codicefiscale library not found. "
È una dipendenza del modulo, perché dovrebbe non esserci?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +4. Aggiunge di un wizard per calcolare i codici fiscali attingendo dai dati dei comuni italiani reperibili dal sito dell'AdE http://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Strumenti/Codici+a
A me questo link dà Access Denied, ma poi davvero viene chiamato nel modulo? Non trovo dove.
E non mi pare lo faccia nemmeno la libreria `codicefiscale` usata.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/wizards/compute_fc.py
> +            "domain": {"birth_province": [("country_id", "=", it)]},
Ritornare un `domain` veniva ammonito con un warning in `16.0`, adesso viene proprio ignorato, vedi https://github.com/odoo/odoo/commit/024fadfd0edf94147a58ffe11c719baafa73dd23.
Si può togliere?

Se serve un dominio dinamico va implementato nel `domain` dei campi.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<Causale>`: in this case there is no specific field, but it transcribes the "Terms and conditions" od the invoice.
```suggestion
   - `<Causale>`: in this case there is no specific field, but it transcribes the "Terms and conditions" of the invoice.
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +5. Importazione di una fattura elettronica senza righe, con una riga per ogni aliquota, oppure con tutte le righe (default).
Questo c'è già più su:
>    - Aggiunge la possibilità di scegliere tra 3 modalità di importazione:
     - senza righe
     - una riga per ogni aliquota
     - tutte le righe (default)

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +6. Il campo "Termini e condizioni" viene scritto nel nodo "Causale" della fattura elettronica.
Questo c'è già più su:
> - `<Causale>`: in questo caso non c'è un campo apposito, ma trascrive i "Termini e condizioni" della fattura

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +his module extends Odoo's standard Italian electronic invoicing functionality, introducing useful tools such as XML preview and fiscal code calculation and improvements in importing and exporting XML
```suggestion
This module extends Odoo's standard Italian electronic invoicing functionality, introducing useful tools such as XML preview and fiscal code calculation and improvements in importing and exporting XML invoices.
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            try:
Ho provato a importare una fattura da interfaccia con il pulsante "Upload" ma non si entra qui dentro, quando dovrebbe essere chiamata questa parte di codice?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
Non si parla dell'aggiornamento dei partner durante l'importazione: è configurabile tramite un flag nel partner stesso.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +    return False
Tutte queste funzioni sono già implementate in https://github.com/odoo/odoo/blob/b7fd61a70a7f41c863529afde493a723a114d5be/addons/l10n_it_edi/models/account_move.py#L22-L50 e mi pare siano identiche, perché non importiamo quelle invece di averne qui una copia?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/res_partner.py
> +        return res
La validazione del codice fiscale in `16.0` è più avanzata di così:
https://github.com/OCA/l10n-italy/blob/11cb1bd550881ea23fa23d830c6dbf00ccb5a0d7/l10n_it_fiscalcode/model/res_partner.py#L13-L40
si può migrare quella?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
Non si parla dei controlli sugli importi che producono inconsistenze e fanno visualizzare i messaggi sulla fattura.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
Come mai questi due campi sono su `account.move.line` mentre tutti gli altri campi della fattura elettronica sono su `l10n_it_edi.line`?
Tra l'altro in `l10n_it_edi.line` ci sono anche campi equivalenti a questi:
```py
    l10n_it_edi_discount_rise_price_ids = fields.One2many(
        "l10n_it_edi.discount_rise_price",
        "l10n_it_edi_line_id",
        string="Discount and Supplement Details",
        readonly=True,
    )
    admin_ref = fields.Char(string="Administration Reference", readonly=True)
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
Esiste già il campo `discount` per lo sconto su `account.move.line`, che rapporto c'è con questi record?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            else:
Ce ne sarà probabilmente solo una, ma perché cercarle tutte per prendere solo la prima?
```suggestion
            country_id = self.env["res.country"].search([("code", "=", country_code)], limit=1).id
            if not country_id:
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            "vat": country_code + vat,
Qui chiederei un parere di @TheMule71 che lo so che gli piace l'argomento :wink:

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Possiamo usare invece `partner_firstname` come in `16.0`?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                vals["state_id"] = fields.first(provinces).id
```suggestion
            if province := self.env["res.country.state"].search(
                [("code", "=", province), ("country_id", "=", partner.country_id.id)], limit=1
            ):
                vals["state_id"] = province.id
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                vals["l10n_edi_it_register_province"] = fields.first(provinces).id
```suggestion
            if province := self.env["res.country.state"].search(
                [
                    ("code", "=", register_province),
                    ("country_id", "=", partner.country_id.id),
                ], limit=1
            ):
                vals["l10n_edi_it_register_province"] = province.id
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/res_partner.py
> +    l10n_edi_it_register_province = fields.Many2one(
```suggestion
    l10n_edi_it_register_province_id = fields.Many2one(
```

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Province ({province}) not present in your system"
Puoi verificare se questo viene tradotto correttamente?
Perché mi sa che la f-string viene valutata prima, andrebbe fatta la sostituzione con i parametri di `_`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Register Province ({register_province}) not present in "
Puoi verificare se questo viene tradotto correttamente?
Perché mi sa che la f-string viene valutata prima, andrebbe fatta la sostituzione con i parametri di `_`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    )
C'è solo un nodo `StabileOrganizzazione`, perché quindi un `for` loop? Tra l'altro se ci fossero più nodi i valori dei campi assegnati verrebbero sovrascritti.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                "admin_ref": get_text(element, ".//RiferimentoAmministrazione"),
Questo è già stato estratto sopra, possiamo usare quello?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Puoi verificare se questo viene tradotto correttamente?
Perché mi sa che la f-string viene valutata prima, andrebbe fatta la sostituzione con i parametri di `_`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Puoi verificare se questo viene tradotto correttamente?
Perché mi sa che la f-string viene valutata prima, andrebbe fatta la sostituzione con i parametri di `_`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Puoi verificare se questo viene tradotto correttamente?
Perché mi sa che la f-string viene valutata prima, andrebbe fatta la sostituzione con i parametri di `_`.

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                f"e-invoice untaxed amount ({self.l10n_it_edi_amount_untaxed})"
Citiamo anche l'arrotondamento visto che viene usato nel confronto?

2025-07-11 18:39 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                abs(self.l10n_it_edi_amount_untaxed),
`l10n_it_edi_rounding` non andrebbe invece sommato a `l10n_it_edi_amount_untaxed` ?

2025-07-16 06:42 UTC, micheledic commented
@Borruso è stato mergiato il mio fix https://github.com/odoo/odoo/pull/217670 rilanciando i test non dovrebbero andare più in errore

2025-07-18 07:24 UTC, odooNextev commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +  Questo pulsante permette di visualizzare un'anteprima del file XML della fattura elettronica prima dell'invio effettivo.
hai ragione, correggo

2025-07-18 07:45 UTC, odooNextev commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Aggiunta della possibilità di visualizzare l'anteprima del file XML anche dal portale.
nel portale effettivamente non c'è l'anteprima, si può solo scaricare il file XML insieme al PDF, ma penso sia di default di `l10n_it_edi`

2025-07-18 09:00 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<RiferimentoAmministrazione>` (sia sulla riga che nei dati generali): identificativo utilizzato per uso amministrativo/gestionale interno. È un campo libero che può essere utilizzato per inseri
C'è da aggiungere il campo (optional) nella vista delle righe fattura

2025-07-18 09:03 UTC, eLBati commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +            <Art73 t-if="company.l10n_edi_it_art73">SI</Art73>
Nella 16 era sull'azienda, lo possiamo lasciare sull'azienda

2025-07-18 09:05 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - `<TerzoIntermediarioOSoggettoEmittente>`
Anche nella 16 vengono creati sempre, quindi lo possiamo tenere così e modificare il README

2025-07-18 09:12 UTC, eLBati commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +            <Art73 t-if="company.l10n_edi_it_art73">SI</Art73>
In realtà @Borruso lo ha già aggiunto anche su account.move

2025-07-18 09:22 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                ):
Nel contesto invece dello skip mettiamo quale nodo dell'XML leggere per eventualmente creare il partner

2025-07-18 09:27 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - Miglioramento della gestione dello sconto o maggiorazione, nodo `<ScontoMaggiorazione>`
Semplicamente registriamo `ScontoMaggiorazione` nelle righe di dettagli della fattura importata. Possiamo modificare il README in questo senso

2025-07-18 09:30 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +4. Aggiunge di un wizard per calcolare i codici fiscali attingendo dai dati dei comuni italiani reperibili dal sito dell'AdE http://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Strumenti/Codici+a
Non funziona più e non sappiamo se c'è un link aggiornato, quindi lo possiamo togliere per ora

2025-07-18 09:34 UTC, eLBati commented on l10n_it_edi_extension/wizards/compute_fc.py
> +            "domain": {"birth_province": [("country_id", "=", it)]},
`domain` da togliere

2025-07-18 09:35 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +5. Importazione di una fattura elettronica senza righe, con una riga per ogni aliquota, oppure con tutte le righe (default).
Togliamo questo e lasciamo quello sopra

2025-07-18 09:36 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +6. Il campo "Termini e condizioni" viene scritto nel nodo "Causale" della fattura elettronica.
da togliere

2025-07-18 09:45 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            try:
Spostiamo l'eventuale creazione dei partner in `_l10n_it_edi_import_invoice` con `_l10n_it_edi_extension_create_partner` , dicendogli quale nodo usare

2025-07-18 09:46 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
da aggiungere

2025-07-18 09:54 UTC, eLBati commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
Visto che lo abbiamo su `l10n_it_edi.line`, possiamo toglierlo da `account.move.line`

2025-07-18 09:56 UTC, eLBati commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
`l10n_it_edi_admin_ref`, visto che lo abbiamo già su `account.move.line` (e il campo ce lo teniamo perchè lo usiamo in esportazione), lo possiamo togliere da `l10n_it_edi.line`

2025-07-18 09:57 UTC, eLBati commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
Vedi sopra

2025-07-18 10:10 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            "vat": country_code + vat,
È possibile salvare nella P.IVA del partner il numero della P.IVA senza il prefisso, quindi possiamo fare sempre così. Quello che troviamo in `IdCodice` sarà scritto in `vat`

2025-07-18 10:19 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            )
In importazione possiamo per ora tenerlo così. Installando `partner_firstname` dovrebbe comunque già fare lo split di `name`

2025-07-18 10:21 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Province ({province}) not present in your system"
andrebbe modificato

2025-07-18 10:23 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                f"e-invoice untaxed amount ({self.l10n_it_edi_amount_untaxed})"
possiamo aggiungere "con un arrotondamento di"

2025-07-18 10:24 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                abs(self.l10n_it_edi_amount_untaxed),
sulla 16 è fatto così quindi ci fidiamo

2025-07-18 10:26 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Province ({province}) not present in your system"
per @monen17

2025-07-18 10:26 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Register Province ({register_province}) not present in "
per @monen17

2025-07-18 10:27 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            )
per @monen17

2025-07-18 10:27 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            )
per @monen17

2025-07-18 10:27 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            )
per @monen17

2025-07-18 10:27 UTC, eLBati commented on l10n_it_edi_extension/models/res_partner.py
> +        return res
per @monen17

2025-07-18 10:28 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            "vat": country_code + vat,
per @monen17

2025-07-18 10:29 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            else:
per @monen17

2025-07-18 10:29 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                vals["state_id"] = fields.first(provinces).id
per @monen17

2025-07-18 10:30 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +                vals["l10n_edi_it_register_province"] = fields.first(provinces).id
per @monen17

2025-07-18 10:32 UTC, eLBati commented on l10n_it_edi_extension/wizards/compute_fc.py
> +            "domain": {"birth_province": [("country_id", "=", it)]},
per @monen17  da qua in giù

2025-07-18 12:28 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            try:
@Borruso di questo abbiamo parlato in chiamata e avevo capito ci stessi già lavorando perché è citato anche sopra, fai tu giusto?

2025-07-18 12:35 UTC, Borruso commented on l10n_it_edi_extension/models/account_move.py
> +            try:
sisi fatto

2025-07-18 12:38 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
@Borruso fammi sapere se questa feature rimarrà dopo lo spostamento della creazione del partner.

@eLBati se non rimane, non è più da aggiungere.

2025-07-18 12:40 UTC, Borruso commented on l10n_it_edi_extension/readme/DESCRIPTION.md
non ho capito a quale ti riferisci

2025-07-18 14:45 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> non ho capito a quale ti riferisci

L'aggiornamento dei partner durante l'importazione che è configurabile tramite un flag nel partner stesso.

2025-07-18 14:45 UTC, Borruso commented on l10n_it_edi_extension/readme/DESCRIPTION.md
è rimasto

2025-07-18 15:17 UTC, monen17 commented
@Borruso per risolvere da https://github.com/OCA/l10n-italy/pull/4411#discussion_r2215703663 in giù della revisione https://github.com/OCA/l10n-italy/pull/4411#pullrequestreview-3010673959 ho proposto https://github.com/Borruso/l10n-italy/pull/33.
Ora ha dei conflitti perché hai appena fatto diversi force-push, e vedo che i test falliscono.
Quando hai finito fammi sapere che faccio rebase di https://github.com/Borruso/l10n-italy/pull/33.
cc @eLBati

2025-07-18 15:47 UTC, Borruso commented
> @Borruso per risolvere i commenti da [#4411 (comment)](https://github.com/OCA/l10n-italy/pull/4411#discussion_r2215703663) in giù della revisione [#4411 (review)](https://github.com/OCA/l10n-italy/pull/4411#pullrequestreview-3010673959) ho proposto [Borruso#33](https://github.com/Borruso/l10n-italy/pull/33). Ora ha dei conflitti perché hai appena fatto diversi force-push, e vedo che i test falliscono. Quando hai finito fammi sapere che faccio rebase di [Borruso#33](https://github.com/Borruso/l10n-italy/pull/33). cc @eLBati

puoi fare rebuild 
potresti controllare l'errore del test su codice fiscale non corretto?

2025-07-19 09:34 UTC, monen17 commented
> > @Borruso per risolvere i commenti da [#4411 (comment)](https://github.com/OCA/l10n-italy/pull/4411#discussion_r2215703663) in giù della revisione [#4411 (review)](https://github.com/OCA/l10n-italy/pull/4411#pullrequestreview-3010673959) ho proposto [Borruso#33](https://github.com/Borruso/l10n-italy/pull/33). Ora ha dei conflitti perché hai appena fatto diversi force-push, e vedo che i test falliscono. Quando hai finito fammi sapere che faccio rebase di [Borruso#33](https://github.com/Borruso/l10n-italy/pull/33). cc @eLBati
> 
> puoi fare rebuild potresti controllare l'errore del test su codice fiscale non corretto?

L'errore è
> Invalid Codice Fiscale 'MRORSS90E25B111T': should be like 'MRTMTT91D08F205J' for physical person and '12345670546' for businesses.

<details><summary>Stack</summary>
<pre>
2025-07-18 15:39:23,847 268 ERROR odoo odoo.addons.l10n_it_edi_extension.tests.test_import_edi_extension_xml: ERROR: TestFatturaPAXMLValidation.test_import_zip
Traceback (most recent call last):
  File "/__w/l10n-italy/l10n-italy/l10n_it_edi_extension/tests/test_import_edi_extension_xml.py", line 155, in test_import_zip
    action = wizard_attachment_import.action_import()
  File "/__w/l10n-italy/l10n-italy/l10n_it_edi_extension/wizards/l10n_it_edi_import_file_wizard.py", line 88, in action_import
    move._l10n_it_edi_import_invoice(move, file_data, True)
  File "/__w/l10n-italy/l10n-italy/l10n_it_edi_extension/models/account_move.py", line 836, in _l10n_it_edi_import_invoice
    intermediary = self._l10n_it_edi_extension_create_partner(
  File "/__w/l10n-italy/l10n-italy/l10n_it_edi_extension/models/account_move.py", line 815, in _l10n_it_edi_extension_create_partner
    return self.env["res.partner"].create(partner_values)
  File "<decorator-gen-192>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 495, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/base_vat/models/res_partner.py", line 768, in create
    res = super().create(vals_list)
  File "<decorator-gen-194>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/account/models/partner.py", line 824, in create
    return super().create(vals_list)
  File "<decorator-gen-97>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/res_partner.py", line 806, in create
    partners = super().create(vals_list)
  File "<decorator-gen-140>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 274, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-31>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 496, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 5017, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 5275, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/odoo/models.py", line 1631, in _validate_fields
    check(self)
  File "/__w/l10n-italy/l10n-italy/l10n_it_edi_extension/models/res_partner.py", line 42, in validate_codice_fiscale
    res = super().validate_codice_fiscale()
  File "/opt/odoo/addons/l10n_it_edi/models/res_partner.py", line 159, in validate_codice_fiscale
    raise UserError(_("Invalid Codice Fiscale '%s': should be like 'MRTMTT91D08F205J' for physical person and '12[345](https://github.com/OCA/l10n-italy/actions/runs/16374490895/job/46270888764?pr=4411#step:8:346)670546' for businesses.", record.l10n_it_codice_fiscale))
odoo.exceptions.UserError: Invalid Codice Fiscale 'MRORSS90E25B111T': should be like 'MRTMTT91D08F205J' for physical person and '12345670546' for businesses.
</pre>
</details> 
(da https://github.com/OCA/l10n-italy/actions/runs/16374490895/job/46270888764?pr=4411#step:8:327)

Ho verificato che il codice fiscale indicato effettivamente non è corretto in https://telematici.agenziaentrate.gov.it/VerificaCF/IVerificaCf.jsp:
<img width="558" height="180" alt="image" src="https://github.com/user-attachments/assets/69f2f280-7829-4792-a343-48954b085635" />

Questo succede perché esiste un terzo intermediario nello zip dei test che ha quel codice fiscale, e fallisce la verifica.
Aggiungo la correzione in https://github.com/Borruso/l10n-italy/pull/33.

2025-07-19 11:57 UTC, monen17 requested changes
Grazie delle modifiche!
Come d'accordo parte delle correzioni le ho fatte in https://github.com/Borruso/l10n-italy/pull/33.

Tra le mie modifiche e le tue credo rimangano aperti solo:
- https://github.com/OCA/l10n-italy/pull/4411#discussion_r2200994569
- https://github.com/OCA/l10n-italy/pull/4411#discussion_r2201406138

Ho notato che in https://github.com/OCA/l10n-italy/pull/4411/commits/45cdc78ba8042b147ba89d9bc840171669d4318f sono finite diverse modifiche che non erano nel commit originale (https://github.com/Borruso/l10n-italy/pull/23/commits/50127b6fdfd6957a63bcb31913e38106dd066f9b), puoi ripristinare il commit originale e mettere le nuove modifiche in un altro commit?
Non posso farlo in una PR perché creerebbe conflitti con https://github.com/OCA/l10n-italy/pull/4411/commits/45cdc78ba8042b147ba89d9bc840171669d4318f e non si può fare dopo il merge.

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +  Questo pulsante permette di visualizzare un'anteprima del file XML della fattura elettronica prima dell'invio effettivo.
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Aggiunta della possibilità di visualizzare l'anteprima del file XML anche dal portale.
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +2. Aggiunge campi nell'export delle fatture XML:
Manca dove andrebbero impostati i campi

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<RiferimentoAmministrazione>` (sia sulla riga che nei dati generali): identificativo utilizzato per uso amministrativo/gestionale interno. È un campo libero che può essere utilizzato per inseri
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +                </CAP>
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/data/invoice_it_template.xml
> +            <Art73 t-if="company.l10n_edi_it_art73">SI</Art73>
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - `<TerzoIntermediarioOSoggettoEmittente>`
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.l10n_it_edi_intermediary_id = intermediary.id
Ho visto il refactoring grazie, ho proposto altre modifiche in https://github.com/Borruso/l10n-italy/pull/33.

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                ):
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                if tax_representative := self._l10n_it_edi_create_partner(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                )
La correzione è in https://github.com/Borruso/l10n-italy/pull/33.

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                self.env["l10n_it_edi.summary_data"].create(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                self.env["l10n_it_edi.activity_progress"].create(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    (self.env._(label), self._compose_info_message(body_tree, xpath))
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.article_code"].create(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.discount_rise_price"].create(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    self.env["l10n_it_edi.line_other_data"].create(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    company=company,
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +     - Miglioramento della gestione dello sconto o maggiorazione, nodo `<ScontoMaggiorazione>`
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Gestione avanzata dei `<DatiRiepilogo>` con l'importazione di:
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - Gestione avanzata dei `<DatiGeneraliDocumento>` con l'importazione di:
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/wizards/compute_fc.py
> +        "codicefiscale library not found. "
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +4. Aggiunge di un wizard per calcolare i codici fiscali attingendo dai dati dei comuni italiani reperibili dal sito dell'AdE http://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Strumenti/Codici+a
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/wizards/compute_fc.py
> +            "domain": {"birth_province": [("country_id", "=", it)]},
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<Causale>`: in this case there is no specific field, but it transcribes the "Terms and conditions" od the invoice.
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +5. Importazione di una fattura elettronica senza righe, con una riga per ogni aliquota, oppure con tutte le righe (default).
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +6. Il campo "Termini e condizioni" viene scritto nel nodo "Causale" della fattura elettronica.
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +his module extends Odoo's standard Italian electronic invoicing functionality, introducing useful tools such as XML preview and fiscal code calculation and improvements in importing and exporting XML
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            try:
Come mai è rimasta questa parte?
Avevo capito che sarebbe stata da spostare, quindi rimuovere da qui e mettere da un'altra parte.

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +    return False
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/res_partner.py
> +        return res
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/readme/DESCRIPTION.md
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move_line.py
> +    l10n_it_edi_discount_rise_price_ids = fields.One2many(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            else:
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            "vat": country_code + vat,
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Era già praticamente fatto in un altro punto, quindi l'ho aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                vals["state_id"] = fields.first(provinces).id
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                vals["l10n_edi_it_register_province"] = fields.first(provinces).id
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/res_partner.py
> +    l10n_edi_it_register_province = fields.Many2one(
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Province ({province}) not present in your system"
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    f"Register Province ({register_province}) not present in "
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                    )
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                "admin_ref": get_text(element, ".//RiferimentoAmministrazione"),
:+1:

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +            )
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                f"e-invoice untaxed amount ({self.l10n_it_edi_amount_untaxed})"
Aggiunto in https://github.com/Borruso/l10n-italy/pull/33

2025-07-19 11:57 UTC, monen17 commented on l10n_it_edi_extension/models/account_move.py
> +                abs(self.l10n_it_edi_amount_untaxed),
:+1:

2025-07-25 08:43 UTC, eLBati requested changes

2025-07-25 08:43 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<StabileOrganizzazione>`: rappresenta i dati della sede operativa stabile del cedente/prestatore in Italia se diversa dalla sede legale
```suggestion
   - `<StabileOrganizzazione>`: rappresenta i dati della sede operativa stabile del cedente/prestatore in Italia se diversa dalla sede legale. Da impostare in odoo nell'azienda, tab "informazioni generali"
```

2025-07-25 08:43 UTC, eLBati commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<Art73>`: indica se il documento è stato emesso secondo modalità e termini stabiliti con decreto ministeriale ai sensi dell'articolo 73 del DPR 633/72
```suggestion
   - `<Art73>`: indica se il documento è stato emesso secondo modalità e termini stabiliti con decreto ministeriale ai sensi dell'articolo 73 del DPR 633/72. Da impostare in odoo nell'azienda o direttamente in fattura.
```

2025-07-25 08:43 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            try:
L'override di `_l10n_it_edi_search_partner` è da togliere.

La parte relativa a stabile organizzazione la mettiamo in `_l10n_it_edi_get_extra_info`

2025-07-25 09:28 UTC, monen17 commented
/ocabot migration l10n_it_fatturapa

2025-07-25 09:29 UTC, monen17 commented
/ocabot migration l10n_it_fatturapa_in

2025-07-25 09:29 UTC, monen17 commented
/ocabot migration l10n_it_fatturapa_out

2025-07-25 09:30 UTC, monen17 commented
/ocabot migration l10n_it_fiscal_payment_term

2025-07-25 09:30 UTC, monen17 commented
/ocabot migration l10n_it_fiscalcode

2025-07-25 09:31 UTC, monen17 commented
/ocabot migration l10n_it_ipa

2025-07-25 09:31 UTC, monen17 commented
/ocabot migration l10n_it_pec

2025-07-25 09:31 UTC, monen17 commented
/ocabot migration l10n_it_rea

2025-07-25 09:32 UTC, monen17 commented
/ocabot migration l10n_it_vat_payability

2025-07-25 09:35 UTC, Borruso commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<StabileOrganizzazione>`: rappresenta i dati della sede operativa stabile del cedente/prestatore in Italia se diversa dalla sede legale
fatto

2025-07-25 09:35 UTC, Borruso commented on l10n_it_edi_extension/readme/DESCRIPTION.md
> +   - `<Art73>`: indica se il documento è stato emesso secondo modalità e termini stabiliti con decreto ministeriale ai sensi dell'articolo 73 del DPR 633/72
fatto

2025-07-25 09:46 UTC, eLBati requested changes

2025-07-25 09:46 UTC, eLBati commented on l10n_it_edi_extension/models/account_move.py
> +            if not partner.l10n_edi_it_electronic_invoice_no_contact_update:
Questo inoltre è da spostare in `_l10n_it_edi_import_invoice`

2025-07-25 10:02 UTC, Borruso commented on l10n_it_edi_extension/models/account_move.py
> +            if not partner.l10n_edi_it_electronic_invoice_no_contact_update:
fatto

2025-07-25 16:25 UTC, monen17 commented
Puoi mergiare https://github.com/Borruso/l10n-italy/pull/33?

2025-07-28 16:37 UTC, monen17 commented
Porto avanti con https://github.com/OCA/l10n-italy/pull/4858.

2025-07-28 16:37 UTC, closed without merging