IMP l10n_it_account removing check_balance_sign_coherence.
OCA/l10n-italy pull request #4431
Opened 2024-10-30 17:26 UTC by eLBati

This check can block chart of accounts configuration and is not mandatory. account_balance_sign is only used by l10n_it_financial_statements_report and, in case of incoherent signs, user can visualize the amounts in financial_statements_report and fix the sign, in case

2024-11-04 11:48 UTC, eLBati commented
pre-commit verde

2024-11-07 10:01 UTC, SirAionTech requested changes
It's worth noting that with this PR, it is possible to have accounts with opposite sign in the same group:
![image](https://github.com/user-attachments/assets/87daf1c4-93cc-40a7-a678-c77b9464bdde)
without this PR, the same setup gives:
![image](https://github.com/user-attachments/assets/bd1e948e-bb6a-4941-89db-42d9657ef621)
I think this is at least unexpected, but I'll rely on functional reviews for its correctness.

Could you please write in the commit the reason of this change instead of just describing it? Right now it is
> [REF] l10n_it_account making making account_balance_sign computed and removing check_balance_sign_coherence

This is also suggested in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message:
> commit messages should be self explanatory (long enough) including the name of the module that has been changed and the reason behind that change.

2024-11-07 10:01 UTC, SirAionTech commented on l10n_it_account/models/account_account.py
> +    def _compute_account_balance_sign(self):
I would add a `@api.depends("account_type")`: I think it might help caching the correct value for an account instead of recomputing it every time.

2024-11-07 10:01 UTC, SirAionTech commented on l10n_it_account/tests/test_l10n_it_account.py
> -        with self.assertRaises(ValidationError):
Please change the test or add a new one to verify the new behavior instead of removing it

2024-11-13 08:22 UTC, eLBati commented on l10n_it_account/models/account_account.py
> +    def _compute_account_balance_sign(self):
Done

2024-11-13 08:23 UTC, eLBati commented
> I think this is at least unexpected

Mi pare il comportamento atteso invece, come mai non dovrebbe?

> Could you please write in the commit the reason of this change instead of just describing it?

Esteso

2024-11-13 08:41 UTC, SirAionTech commented
> > I think this is at least unexpected
> 
> Mi pare il comportamento atteso invece, come mai non dovrebbe?

Nel gruppo di conti c'è un campo segno, nei singoli conti all'interno del gruppo c'è un campo segno; visto che sono oggetti imparentati mi aspetto che ci sia una specie di ereditarietà: se un gruppo ha un segno allora anche tutti i conti nel gruppo hanno lo stesso segno.

Se è il comportamento atteso da questa PR lo puoi chiarire? Sfido qualsiasi funzionale a capire che 
> removing check_balance_sign_coherence

o 
> This check can block chart of accounts configuration and is not mandatory. account_balance_sign is only used by l10n_it_financial_statements_report and, in case of incoherent signs, user can visualize the amounts in financial_statements_report and fix the sign, in case

Vuol dire che i conti all'interno di un gruppo possono avere segno diverso dal gruppo

---
P.S. ma quindi inglese o italiano?

2025-04-04 07:44 UTC, monen17 requested changes

2025-04-04 07:44 UTC, monen17 commented on l10n_it_account/models/account_account.py
> -    def check_balance_sign_coherence_group(self):
Ne abbiamo parlato in chiamata, questo controllo dovrebbe rimanere perché conti all'interno dell stesso gruppo dovrebbero sempre avere lo stesso segno.

Visto che ora il segno dipende in modo più diretto dal tipo, si potrebbe aggiungere ai constrain `account_type` oppure `account_balance_sign`.

2025-04-04 08:58 UTC, eLBati commented on l10n_it_account/models/account_account.py
> -    def check_balance_sign_coherence_group(self):
Ho provato a riapplicare il controllo ma non è applicabile perchè già nel PDC di base ci sono delle eccezioni:

![image](https://github.com/user-attachments/assets/9136b380-e50f-4f78-9378-26e3bce67937)

Faccio notare che queste eccezioni sono uno dei motivi per cui è nata questa PR, senza la quale la modifica del PDC diventa praticamente impossibile perchè l'utente viene continuamente bloccato per il controllo dei segni

2025-04-04 10:06 UTC, odooNextev commented on l10n_it_account/models/account_account.py
> -    def check_balance_sign_coherence_group(self):
I conti fuori bilancio, non finiscono nel bilancio, non ha senso un controllo su quel tipo di conti
Può essere che il gruppo passività vada consideri il prefisso da 20 a 28?

2025-04-10 10:21 UTC, eLBati commented
Non si può togliere `account_balance_sign`da `account.group` senza modificare `l10n_it_financial_statements_report` , vedi `def get_balance_sign`

2025-04-10 10:48 UTC, gdemarco2esseti approved these changes
Functional review: OK coerenza sul segno conto

Non posso testare la visualizzazione dei gruppi conto perchè non sono disponibili nel runbot.

2025-04-10 12:20 UTC, Wvven approved these changes
LGTM

2025-04-10 12:56 UTC, odooNextev commented
> Non posso testare la visualizzazione dei gruppi conto perchè non sono disponibili nel runbot.

anche noi non troviamo il menu neanche con debuggaste e funzionalità contabili complete: sai perchè @eLBati ?

2025-04-10 13:04 UTC, eLBati commented
> 
> anche noi non troviamo il menu neanche con debuggaste e funzionalità contabili complete: sai perchè @eLBati ?

Su CE serve https://github.com/OCA/account-financial-tools/tree/16.0/account_usability

2025-04-10 13:20 UTC, eLBati commented
/ocabot merge minor

2025-04-10 17:09 UTC, merged