[16.0] [FIX] l10n_it_fatturapa_in_rc: flag RC in importazione e-fattura con raggruppamento per Aliquota
OCA/l10n-italy pull request #4434
Opened 2024-11-04 11:57 UTC by TennyMkt

risolve https://github.com/OCA/l10n-italy/issues/3768 per la 16.0

Estende funzione `_prepareInvoiceLineAliquota` per mettere a `True` la flag `RC` nelle linee della fattura se viene importata una fattura con Reverse Charge per Aliquota IVA

2024-11-07 10:08 UTC, SirAionTech requested changes
Grazie della PR!
Potresti aggiungere un test o modificarne uno esistente per verificare il nuovo comportamento? Così si evitano regressioni.
Visto che esiste già un test in questo modulo, magari ti basta aggiungere un `self.assert...` nel test esistente.

Potresti modificare il messaggio del commit in modo che segua le linee guida in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? In particolare
> Commit messages are in English

2024-11-12 09:55 UTC, TennyMkt commented
> Grazie della PR! Potresti aggiungere un test o modificarne uno esistente per verificare il nuovo comportamento? Così si evitano regressioni. Visto che esiste già un test in questo modulo, magari ti basta aggiungere un `self.assert...` nel test esistente.
> 
> Potresti modificare il messaggio del commit in modo che segua le linee guida in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? In particolare
> 
> > Commit messages are in English

Ho modificato il messaggio di commit.

Ho provato ad aggiungere un test perchè per testare serve un'importazione per Aliquota e il test già esistente non lo faceva.
Però il test va in errore ma non capisco perchè, sapreste aiutarmi a come sistemarlo?

2024-11-12 10:12 UTC, SirAionTech commented
> Ho provato ad aggiungere un test perchè per testare serve un'importazione per Aliquota e il test già esistente non lo faceva. Però il test va in errore ma non capisco perchè, sapreste aiutarmi a come sistemarlo?

Grazie dell'aggiunta! Lo stack dell'errore preso da https://github.com/OCA/l10n-italy/actions/runs/11794311853/job/32851644723?pr=4434#step:8:893 è
<details><summary>Stack</summary>
<pre>

2024-11-12 09:30:21,508 528 ERROR odoo odoo.addons.l10n_it_fatturapa_in_rc.tests.test_fatturapa_in_rc: ERROR: TestInvoiceRC.test_01_xml_import
Traceback (most recent call last):
  File "/__w/l10n-italy/l10n-italy/l10n_it_fatturapa_in_rc/tests/test_fatturapa_in_rc.py", line 13, in setUp
    self._create_account()
  File "/__w/l10n-italy/l10n-italy/l10n_it_fatturapa_in_rc/tests/test_fatturapa_in_rc.py", line 22, in _create_account
    self.account_selfinvoice = account_model.create(
  File "<decorator-gen-745>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/__w/l10n-italy/l10n-italy/l10n_it_account/models/account_account.py", line 34, in create
    return super().create(vals_list)
  File "<decorator-gen-136>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 258, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-68>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-15>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 3984, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 4165, in _create
    cr.execute(
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "account_account_code_company_uniq"
DETAIL:  Key (code, company_id)=(295000, 10) already exists.

</pre>
</details>

Da qui si vede che durante il `setUp` cerca di creare un conto avente codice **295000**, ma fallisce perché esiste già.

Questo succede perché la classe dei test è `SingleTransactionCase`: https://github.com/OCA/l10n-italy/blob/2da29dd2a42fd82958c3b5465f1e848eb278a147/l10n_it_fatturapa_in/tests/fatturapa_common.py#L18 quindi ogni test (`setUp` + test + `tearDown`) viene eseguito in un'unica transazione: finché c'è solo un test no problemo; però ora che hai aggiunto un altro test esegue di nuovo il `setUp`, cerca di creare di nuovo lo stesso conto e giustamente fallisce.

Per risolvere puoi trasformare l'attuale `setUp` in `setUpClass`, se possibile andrebbe fatto in un commit di refactoring precedente alla fix che stai proponendo.

2024-11-12 11:48 UTC, TennyMkt commented
> > Ho provato ad aggiungere un test perchè per testare serve un'importazione per Aliquota e il test già esistente non lo faceva. Però il test va in errore ma non capisco perchè, sapreste aiutarmi a come sistemarlo?
> 
> Grazie dell'aggiunta! Lo stack dell'errore preso da https://github.com/OCA/l10n-italy/actions/runs/11794311853/job/32851644723?pr=4434#step:8:893 è
> 
> Stack
> Da qui si vede che durante il `setUp` cerca di creare un conto avente codice **295000**, ma fallisce perché esiste già.
> 
> Questo succede perché la classe dei test è `SingleTransactionCase`:
> 
> https://github.com/OCA/l10n-italy/blob/2da29dd2a42fd82958c3b5465f1e848eb278a147/l10n_it_fatturapa_in/tests/fatturapa_common.py#L18
> 
> quindi ogni test (`setUp` + test + `tearDown`) viene eseguito in un'unica transazione: finché c'è solo un test no problemo; però ora che hai aggiunto un altro test esegue di nuovo il `setUp`, cerca di creare di nuovo lo stesso conto e giustamente fallisce.
> Per risolvere puoi trasformare l'attuale `setUp` in `setUpClass`, se possibile andrebbe fatto in un commit di refactoring precedente alla fix che stai proponendo.

Grazie dell'aiuto, ho fatto quanto richiesto

2024-11-13 10:16 UTC, SirAionTech approved these changes
> Grazie dell'aiuto, ho fatto quanto richiesto

Grazie a te, bel lavoro :medal_sports:

/ocabot merge patch

2024-11-13 10:43 UTC, merged