[14.0][REF] l10n_it_fatturapa_import_zip: Clarify active invoices flow
OCA/l10n-italy pull request #4454
Opened 2024-11-25 08:04 UTC by sergiocorato

2024-11-25 10:04 UTC, andreampiovesana approved these changes
LGTM

2024-11-26 09:15 UTC, SirAionTech requested changes
Grazie della PR!
Vedi i commenti qui sotto

2024-11-26 09:15 UTC, SirAionTech commented on l10n_it_fatturapa_import_zip/readme/CONFIGURE.md
In `14.0` viene usato il formato `.rst` (vedi i formati degli altri file in questa cartella), puoi creare anche questo file in quel formato?

Nella PR la CI di `pre-commit` non solleva errore perché nelle PR non vengono rigenerati i README, vedi l'esecuzione di questa PR: https://github.com/OCA/l10n-italy/actions/runs/12005701551/job/33462795664?pr=4454#step:7:14:
> Generate addons README files from fragments.............................Skipped

Infatti, eseguendo `pre-commit` in locale viene sollevato l'errore
> Generate addons README files from fragments..............................Failed
>- hook id: oca-gen-addon-readme
>- exit code: 1
>
>Both .md and .rst fragments found in ./l10n_it_fatturapa_import_zip/readme. Please ensure the same format is used for all fragments.

2024-11-26 09:15 UTC, SirAionTech commented on l10n_it_fatturapa_import_zip/README.rst
Potresti includere anche le modifiche a `USAGE`? In https://github.com/OCA/l10n-italy/pull/3774 ci sono:
![image](https://github.com/user-attachments/assets/546f1583-95b8-4422-ac22-11bde627c533)

2024-12-18 18:24 UTC, sergiocorato commented on l10n_it_fatturapa_import_zip/readme/CONFIGURE.md
Fatto

2024-12-18 18:24 UTC, sergiocorato commented on l10n_it_fatturapa_import_zip/README.rst
Fatto, grazie!

2025-01-10 13:21 UTC, SirAionTech requested changes

2025-01-10 13:21 UTC, SirAionTech commented on l10n_it_fatturapa_import_zip/README.rst
Grazie, ma non sarebbe meglio aggiungere direttamente il file corretto invece di creare il file `.md` e poi rinominarlo?

Puoi modificare il messaggio del nuovo commit
![image](https://github.com/user-attachments/assets/04bbc453-2c77-4049-8e5a-27670d47f15f)
per seguire le linee guida https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message? In particolare manca il nome del modulo:
> Always put meaningful commit messages: commit messages should be self explanatory (long enough) including the name of the module that has been changed and the reason behind that change.

Potresti fare cherry-pick del commit analogo di `16.0` https://github.com/OCA/l10n-italy/pull/3774/commits/d9ec2d5b24d55140096ce8efc7f463a236bfa133 così oltre al messaggio corretto verrebbe anche mantenuto l'autore originale?

2025-07-13 12:42 UTC, closed without merging