[FIX] l10n_it_riba: remove account and journal domain
OCA/l10n-italy pull request #4455
Opened 2024-11-25 09:26 UTC by sergiocorato

2024-11-26 10:25 UTC, odooNextev approved these changes
Review tecnica e funzionale OK per il porting.

PS. Cambierei solo il titolo della PR perchè ero partito con l'idea di togliere le restrizioni del dominio anche per il registro di banca, ma poi non l'ho fatto e non ricordo di preciso il motivo.
Allora non l'ho cambiato, ma visto che questa è ancora aperta si può fare.

Funzionalmente invece lasciando la forzatura di un conto di tipo banca, la PR va bene se l’insoluto viene accreditato e poi stornato dalla banca altrimenti anche il registro dovrebbe essere libero.

2024-11-27 20:36 UTC, andreampiovesana approved these changes
LGTM

2024-11-28 08:15 UTC, SirAionTech approved these changes
Grazie della PR!
Ho fatto solo revisione del codice e per me è ok; i commenti qui sotto non sono bloccanti.

2024-11-28 08:15 UTC, SirAionTech commented on l10n_it_ricevute_bancarie/models/riba_config.py
> +        domain="[('company_id', '=', company_id)]",
Questo si può togliere: quando il dominio è solo _per multicompany_, l'attributo `check_company` inietta già il dominio corretto (vedi https://github.com/odoo/odoo/blob/d7f13b50148d0a3ec764dc37b0ca3631c9a35483/odoo/fields.py#L2541).

2024-11-28 08:15 UTC, SirAionTech commented on l10n_it_ricevute_bancarie/models/riba_config.py
> +        domain="[('company_id', '=', company_id)]",
Anche questo si può togliere, vedi l'altro commento sul codice simile.

2024-11-28 09:01 UTC, primes2h commented
Dato che si tratta della v.14.0 sarebbe meglio modificare la descrizione del commit e della PR come già indicato [qui](https://github.com/OCA/l10n-italy/pull/4457#issuecomment-2501267793).

2024-12-18 12:02 UTC, SirAionTech commented
> Dato che si tratta della v.14.0 sarebbe meglio modificare la descrizione del commit e della PR come già indicato [qui](https://github.com/OCA/l10n-italy/pull/4457#issuecomment-2501267793).

Non l'avevo notato, puoi chiarire con una review se per te è una modifica da fare necessaria per il merge o meno?

2024-12-18 14:44 UTC, primes2h commented
> > Dato che si tratta della v.14.0 sarebbe meglio modificare la descrizione del commit e della PR come già indicato [qui](https://github.com/OCA/l10n-italy/pull/4457#issuecomment-2501267793).
> 
> Non l'avevo notato, puoi chiarire con una review se per te è una modifica da fare necessaria per il merge o meno?

Direi di si, è lo stessa situazione indicata [qui](https://github.com/OCA/l10n-italy/pull/4457#issuecomment-2501066873) e poi corretta. Nella v. 14.0 il modulo si chiama `l10n_it_ricevute_bancarie`.

2024-12-18 14:45 UTC, primes2h requested changes
https://github.com/OCA/l10n-italy/pull/4455#issuecomment-2505589373

2025-01-17 13:32 UTC, tafaRU commented
@sergiocorato puoi risolvere i commenti in pending così poi riusciamo a chiudere la issue grazie.

2025-01-17 13:50 UTC, sergiocorato commented on l10n_it_ricevute_bancarie/models/riba_config.py
> +        domain="[('company_id', '=', company_id)]",
fatto

2025-01-17 13:50 UTC, sergiocorato commented on l10n_it_ricevute_bancarie/models/riba_config.py
> +        domain="[('company_id', '=', company_id)]",
fatto, grazie

2025-01-17 13:53 UTC, sergiocorato commented
> [#4455 (comment)](https://github.com/OCA/l10n-italy/pull/4455#issuecomment-2505589373)

Ho rinominato il commit, se non c'era altro.

2025-01-18 09:30 UTC, primes2h commented
> > [#4455 (comment)](https://github.com/OCA/l10n-italy/pull/4455#issuecomment-2505589373)
> 
> Ho rinominato il commit, se non c'era altro.

:+1: 
La descrizione l'ho modificata io.

2025-01-18 09:31 UTC, primes2h approved these changes

2025-01-18 09:32 UTC, primes2h commented
/ocabot merge patch

2025-01-18 09:48 UTC, merged