[14.0][ADD] l10n_it_sdd_cbi: adding module for CBI SDD Italy
OCA/l10n-italy pull request #4480
Opened 2024-12-03 16:00 UTC by Borruso

2024-12-03 16:17 UTC, francesco-ooops commented
@Borruso non potrebbe essere integrato in https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_sct_cbi ?

2024-12-04 07:52 UTC, Borruso commented
> @Borruso non potrebbe essere integrato in https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_sct_cbi ?

poterbbe ma come nel repo https://github.com/OCA/bank-payment [account_banking_sepa_credit_transfer](https://github.com/OCA/bank-payment/tree/16.0/account_banking_sepa_credit_transfer) e [account_banking_sepa_direct_debit](https://github.com/OCA/bank-payment/tree/16.0/account_banking_sepa_direct_debit) sono separati

2024-12-04 16:49 UTC, primes2h commented
> > @Borruso non potrebbe essere integrato in https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_sct_cbi ?
> 
> poterbbe ma come nel repo https://github.com/OCA/bank-payment [account_banking_sepa_credit_transfer](https://github.com/OCA/bank-payment/tree/16.0/account_banking_sepa_credit_transfer) e [account_banking_sepa_direct_debit](https://github.com/OCA/bank-payment/tree/16.0/account_banking_sepa_direct_debit) sono separati

Anche per me ha senso tenerli separati, però sarebbe meglio uniformare il nome a quello del modulo già presente nel repo.
`l10n_it_sct_cbi`
`l10n_it_sdd_cbi`

2024-12-09 10:43 UTC, francesco-ooops commented
@Borruso puoi rinominare come suggerito?

2025-01-09 10:49 UTC, francesco-ooops commented
Ciao @Borruso ti risulta che ci sia un nuovo standard CBIBdySDDReq.00.01.01 - in vigore dal 20/03/2023 ?

Ho [verificato](https://www.cbiservice.com/correttoresepa.php) un file generato con questo modulo e rispetta lo standard CBIBdySDDReq.00.01.00 ma non quello successivo, pertanto la banca non lo accetta. Riscontri lo stesso problema?

2025-01-10 08:28 UTC, Borruso commented
> Ciao @Borruso ti risulta che ci sia un nuovo standard CBIBdySDDReq.00.01.01 - in vigore dal 20/03/2023 ?
> 
> Ho [verificato](https://www.cbiservice.com/correttoresepa.php) un file generato con questo modulo e rispetta lo standard CBIBdySDDReq.00.01.00 ma non quello successivo, pertanto la banca non lo accetta. Riscontri lo stesso problema?

non lo conoscevo devo darci un'occhiata

2025-01-10 10:23 UTC, francesco-ooops commented
@Borruso non ho accesso alla documentazione CBI, ho solo trovato questo [commit](https://github.com/f4b10/X4GA/commit/b75c902589d443075334e053df3a4bb7db13a455) dove semplicemente vengono aggiornati i numeri di versione

Test "pecoreccio" fatto sostituendo il numero di versione nell'XML (sostituisci .00.01.00 con .00.01.01), il file viene accettato dalla banca

Se hai accesso alla documentazione puoi verificare il changelog tra versioni?

2025-01-13 10:23 UTC, patrickt-oforce commented
> Ciao @Borruso ti risulta che ci sia un nuovo standard CBIBdySDDReq.00.01.01 - in vigore dal 20/03/2023 ?
> 
> Ho [verificato](https://www.cbiservice.com/correttoresepa.php) un file generato con questo modulo e rispetta lo standard CBIBdySDDReq.00.01.00 ma non quello successivo, pertanto la banca non lo accetta. Riscontri lo stesso problema?

Si esiste un nuovo standard da marzo 2023 e termina con lo .01; i documenti si possono trovare su cbi-org.eu dopo essersi registrati e accedendo al menu servizi documentazione tecnica

2025-01-13 10:24 UTC, patrickt-oforce commented
> @Borruso non ho accesso alla documentazione CBI, ho solo trovato questo [commit](https://github.com/f4b10/X4GA/commit/b75c902589d443075334e053df3a4bb7db13a455) dove semplicemente vengono aggiornati i numeri di versione
> 
> Test "pecoreccio" fatto sostituendo il numero di versione nell'XML (sostituisci .00.01.00 con .00.01.01), il file viene accettato dalla banca
> 
> Se hai accesso alla documentazione puoi verificare il changelog tra versioni?

Piccolo consiglio, conviene mantenere entrambe le versioni dello standard perché non tutti supportano l'ultima versione

2025-01-13 10:27 UTC, francesco-ooops commented
> > Ciao @Borruso ti risulta che ci sia un nuovo standard CBIBdySDDReq.00.01.01 - in vigore dal 20/03/2023 ?
> > Ho [verificato](https://www.cbiservice.com/correttoresepa.php) un file generato con questo modulo e rispetta lo standard CBIBdySDDReq.00.01.00 ma non quello successivo, pertanto la banca non lo accetta. Riscontri lo stesso problema?
> 
> Si esiste un nuovo standard da marzo 2023 e termina con lo .01; i documenti si possono trovare su https://cbi-org.eu dopo essersi registrati e accedendo al menu servizi documentazione tecnica

Grazie @patrickt-oforce, il link corretto è [questo](https://www.cbi-org.eu/My-Menu/Servizio-CBI-Documentazione/Servizio-CBI-Documentazione-Documentazione-tecnica)? Se sì, in quale file è contenuta la documentazione

2025-01-13 10:29 UTC, patrickt-oforce commented
> @Borruso non ho accesso alla documentazione CBI, ho solo trovato questo [commit](https://github.com/f4b10/X4GA/commit/b75c902589d443075334e053df3a4bb7db13a455) dove semplicemente vengono aggiornati i numeri di versione
> 
> Test "pecoreccio" fatto sostituendo il numero di versione nell'XML (sostituisci .00.01.00 con .00.01.01), il file viene accettato dalla banca
> 
> Se hai accesso alla documentazione puoi verificare il changelog tra versioni?

Purtroppo cbi non fornisce un changelog ma solo l'archivio con i nuovi standard, sono comunque mantenute le versioni precedenti, ma non specificano cosa hanno cambiato. Nell'archivio che forniscono sono presenti gli xsd, la struttura del file in formato excel e il pdf di spiegazione

2025-01-13 10:34 UTC, patrickt-oforce commented
> > > Ciao @Borruso ti risulta che ci sia un nuovo standard CBIBdySDDReq.00.01.01 - in vigore dal 20/03/2023 ?
> > > Ho [verificato](https://www.cbiservice.com/correttoresepa.php) un file generato con questo modulo e rispetta lo standard CBIBdySDDReq.00.01.00 ma non quello successivo, pertanto la banca non lo accetta. Riscontri lo stesso problema?
> > 
> > 
> > Si esiste un nuovo standard da marzo 2023 e termina con lo .01; i documenti si possono trovare su https://cbi-org.eu dopo essersi registrati e accedendo al menu servizi documentazione tecnica
> 
> Grazie @patrickt-oforce, il link corretto è [questo](https://www.cbi-org.eu/My-Menu/Servizio-CBI-Documentazione/Servizio-CBI-Documentazione-Documentazione-tecnica)? Se sì, in quale file è contenuta la documentazione?

Il link è [Standard CBI](https://www.cbi-org.eu/My-Menu/Servizio-CBI-Documentazione/Servizio-CBI-Documentazione-Standard) gli SDD sono nel blocco Area Incassi; se quando importate gli XSD vengono segnalati errori per i file Hdr e Sign sono nel gruppo area generale e come manuale di riferimento STPG-MO-001

2025-01-28 07:57 UTC, Borruso commented
@patrickt-oforce @francesco-ooops ping

2025-02-06 09:40 UTC, francesco-ooops approved these changes
Funzionale ok!

2025-02-06 09:41 UTC, francesco-ooops commented
@patrickt-oforce posso chiederti una review di codice dato che conosci la materia? Grazie!

2025-02-07 09:44 UTC, francesco-ooops requested changes
@Borruso ti risulta questo errore? https://www.loom.com/share/3ff99727f1a14a7fac66f96b76c09650

C'è qualcosa di sbagliato a livello di concetto / configurazione?

2025-02-11 11:46 UTC, francesco-ooops commented
@Borruso ping :)

2025-02-11 12:08 UTC, Borruso commented
> @Borruso ti risulta questo errore? https://www.loom.com/share/3ff99727f1a14a7fac66f96b76c09650
> 
> C'è qualcosa di sbagliato a livello di concetto / configurazione?

devi controllare che il conto bancario dell'azienda e del partner siano di tipo iban
infatti se ci fai caso il pagamento non è contrassegnato come SEPA

2025-02-11 14:03 UTC, francesco-ooops commented
ok grazie, possiamo comunque aggiungere un errore più umano?

2025-02-11 16:45 UTC, Borruso commented
> ok grazie, possiamo comunque aggiungere un errore più umano?

okok sorry

2025-02-12 09:43 UTC, francesco-ooops commented
> > @Borruso ti risulta questo errore? https://www.loom.com/share/3ff99727f1a14a7fac66f96b76c09650
> > C'è qualcosa di sbagliato a livello di concetto / configurazione?
> 
> devi controllare che il conto bancario dell'azienda e del partner siano di tipo iban infatti se ci fai caso il pagamento non è contrassegnato come SEPA

@Borruso mi segnalano lo stesso errore con la configurazione che hai suggerito: https://www.loom.com/share/20eda0a04c6345a28a4af849b703939d

Vedi qualcosa di strano?

2025-02-12 14:31 UTC, Borruso commented
> @Borruso mi segnalano lo stesso errore con la configurazione che hai suggerito: https://www.loom.com/share/20eda0a04c6345a28a4af849b703939d
> 
> Vedi qualcosa di strano?

è proprio quel boolean pagamento SEPA l'errore

2025-02-13 09:15 UTC, francesco-ooops commented
@Borruso scusa non mi è chiaro, c'è qualcosa di sbagliato nel modulo o nella configurazione? 

Se è nella configurazione, cosa nello specifico?

2025-02-14 08:00 UTC, Borruso commented
> @Borruso scusa non mi è chiaro, c'è qualcosa di sbagliato nel modulo o nella configurazione?
> 
> Se è nella configurazione, cosa nello specifico?

la configurazione è corretta in questo caso non funziona perché hai usato i dollari

per far contrassegnare il flag SEPA deve essere in queste regole:
`sepa_list = [
    "BE",  "BG", "ES", "HR",  "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GI", "GR", "GB", "HU", "IS", "IE", "IT", "LV", "LI", "LT", "LU", "PT", "MT", "MC", "NL", "NO", "PL", "RO", "SM", "SK", "SI", "SE", "CH", "VA"]`
- Il conto bancario dell'azienda deve essere un IBAN e le prime due lettere devono corrispondere a uno dei paesi presenti nella lista sepa_list
- L'importo delle righe deve essere espresso in euro
- Il conto bancario del partner indicato nelle righe deve essere anch'esso un IBAN e deve iniziare con due lettere appartenenti alla sepa_list

2025-02-19 14:15 UTC, francesco-ooops approved these changes
Ok mi dicono funzionale tutto ok

2025-02-19 17:44 UTC, GSLabIt approved these changes

2025-02-19 18:02 UTC, francesco-ooops commented
/ocabot merge nobump

2025-02-19 18:02 UTC, francesco-ooops commented
Mergio in quanto in uso in più aziende, eventuali miglioramenti possono essere aggiunti in seguito

2025-02-19 18:37 UTC, merged